BitBoxSwiss/bitbox-wallet-app

- backend/coins/btc/electrum/electrum.go
In the current setup, the cert is usually self signed, with a missing
CommonName (many public electrum servers work like that). When
connecting a full node, the cert is downloaded and checked manually.
> electrum: skip cert hostname verification

- frontends/web/src/components/balance/balance.css
- frontends/web/src/components/balance/balance.jsx
- frontends/web/src/components/forms/button.css
- frontends/web/src/style/layout.css
> Frontend header adjustments

- frontends/web/src/i18n/en.json
This section is available while on the device settings screen.
Took the text from https://shiftcrypto.ch/start and made minor adjustments.
This is missing German translation at the moment..
R: @thisconnect
> frontend: add guide section about 2FA

- frontends/web/src/i18n/en.json
- frontends/web/src/routes/settings/electrum.jsx
Also reflect on the role of the node, if the default nodes are left in. Not sure, if all of this is actually true. @benma please review, and explain if it is not :P
> Add step in full node connection, to restart the wallet

- Makefile
- env.mk.inc
- frontends/qt/BitBox.pro
- frontends/qt/Makefile
- frontends/qt/server/Makefile
- frontends/qt/server/Makefile.linux
- frontends/qt/server/Makefile.macosx
- frontends/qt/server/Makefile.windows
- hardening.mk.inc
- scripts/docker_install.sh
This is a minimally invasive set of targets that should document the libserver build process for our three major supported platforms.
> libserver Makefile changes

- util/config/appdir.go
I underestimated quirks of CGO where an init func may be called
only after a package var is being accessed.
This does not currently apply to the BB app because appFolder
is accessed only from a Go function, i.e. no direct access from
C/C++ code via CGO.
Yet I didn't feel comfortable enough to let it be.
So, the proposed change serializes initialization of the appFolder
using sync.Once, the first time AppDir is called.
R: @benma
> util/config: wrap appFolder init in sync.Once

- BUILD.md
- README.md
- scripts/docker_install.sh
Per #19, I've collected the responses and documented it.
> basic supported build documentation

- frontends/web/src/i18n/en.json
- frontends/web/src/routes/device/settings/components/upgradefirmware.jsx
Same content, but numbered and spelled out better. Based on user
feedback.
> frontend/bitbox: improve upgrade instructions

- frontends/web/src/components/guide/guide.tsx
- frontends/web/src/components/update/update.tsx
- frontends/web/src/decorators/load.tsx
- frontends/web/src/decorators/share.tsx
- frontends/web/src/decorators/subscribe.tsx
- frontends/web/src/utils/component.ts
https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging
> Decorators

- backend/handlers/handlers.go
- backend/update.go
It is also triggered when the user is offline.
> backend: suppress the error in the update handler

- backend/coins/btc/account.go
- backend/coins/btc/addresses/address.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/coin/address.go
- frontends/web/src/routes/account/receive/receive.jsx
Another step towards a coin agnostic interface.
> btc/account: use address interface

- backend/devices/bitbox/device.go
- backend/devices/bitbox/device_test.go
- backend/devices/bitbox/handlers/handlers.go
- backend/devices/bitbox/keystore.go
> bitbox: also return `recid`

- backend/coins/btc/account.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/btc/transaction.go
- backend/coins/coin/amount.go
- backend/coins/coin/error.go
Move out of the btc package, make available for all coins.
> coins: move SendAmount, TxValidationError out btc

- backend/coins/btc/account.go
- backend/coins/btc/handlers/handlers.go
- backend/devices/bitbox/device.go
- backend/devices/bitbox/keystore.go
- backend/keystore/keystore.go
- backend/keystore/keystores.go
> btc/handlers: uncouple from bitbox

- frontends/web/src/routes/account/receive/receive.jsx
Could not verify/convert the first address anymore.
> frontend/receive: null validation bug

- frontends/web/src/routes/device/manage-backups/manage-backups.jsx
Needs to take `t` from props, otherwise the labels won't be updated when the language is changed.
> frontend/i18n: fix backups

- frontends/web/src/i18n/en.json
- frontends/web/src/routes/device/settings/components/hiddenwallet.jsx
Was cryptic coming from backend.
> frontend: hidden wallet error messages

- frontends/web/src/components/backups/backup.jsx
- frontends/web/src/components/transactions/transaction.jsx
- frontends/web/src/i18n/de.json
- frontends/web/src/i18n/en.json
> frontend: use built-in to format date

- backend/handlers/handlers.go
- frontends/web/src/components/rates/rates.tsx
> backend: rates endpoint typo

- frontends/web/src/components/backups/restore.jsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/settings/components/changepin.jsx
- frontends/web/src/routes/device/settings/components/hiddenwallet.jsx
- frontends/web/src/routes/device/settings/components/reset.jsx
- frontends/web/src/routes/device/setup/initialize.jsx
- frontends/web/src/routes/device/setup/seed-create-new.jsx
- frontends/web/src/routes/device/setup/seed-restore.jsx
- frontends/web/src/routes/device/unlock.jsx
If an object has only numeric keys, flattening and then
unflattening (which locize does) generates an array :(
> frontend/i18n: no numeric keys

- frontends/web/src/components/guide/entry.tsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/account.jsx
- frontends/web/src/routes/device/waiting.jsx
> frontend/i18n: string instead of []string for entry.text

- frontends/web/src/routes/account/send/send.jsx
> frontend/send: translate invalid amount err msg

- frontends/web/src/app.jsx
- frontends/web/src/routes/device/device.jsx
- frontends/web/src/routes/device/waiting.jsx
Also remove unused deviceIDs prop in settings.
> frontend: fetch state in waiting instead of parent

- backend/coins/btc/account.go
- backend/coins/btc/coin.go
- backend/coins/coin/coin.go
- backend/coins/eth/account.go
- backend/coins/eth/coin.go
Same as https://github.com/digitalbitbox/bitbox-wallet-app/pull/155, which confused CI because I first pushed the branch mistakenly to upstream.
> backend: rename init in coin

- frontends/web/jest.config.js
see https://github.com/kulshekhar/ts-jest/issues/377
> frontend: exlude .d.ts files in coverage

- backend/coins/eth/account.go
So the pending outgoing tx is listed without delay.
> backend/coins/eth: after sending a tx, immediately refresh

- backend/coins/eth/account.go
- backend/coins/eth/coin.go
Set account to offline, reconnect automatically in next poll
iteration.
> backend/eth: handle connection error

- backend/coins/btc/transaction.go
- backend/coins/coin/amount.go
- backend/coins/coin/amount_test.go
- backend/coins/eth/account.go
> backend/coins: allowZero for amount parsing

- backend/coins/btc/handlers/handlers.go
- backend/coins/eth/etherscan/etherscan.go
- backend/coins/eth/transaction.go
- backend/coins/eth/types/types.go
- frontends/web/src/components/transactions/transaction.jsx
- frontends/web/src/locales/en/app.json
Gas used for confirmed tx. Gas limit for pending tx.
> eth: show gas in tx list

- frontends/web/src/app.jsx
- frontends/web/src/routes/device/manage-backups/manage-backups.jsx
When the device is removed, we staid in the manage backup
screen. Should route to /.
> frontend: fix route in manage backups

- backend/backend.go
- backend/coins/btc/coin.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/coin/coin.go
- backend/coins/eth/coin.go
Otherwise, the fee has no conversion in the send screen.
All fiat conversions in the confirmation dialog also depended on it.
> backend and frontend: add conversions into the formatted amount again

- backend/handlers/handlers.go
- frontends/web/src/routes/account/add/addaccount.tsx
The routing does not work yet, unfortunately.
> account/add: route to new account after adding it

- backend/backend.go
- backend/handlers/handlers.go
- frontends/web/src/app.jsx
- frontends/web/src/routes/account/add/addaccount.tsx
Attention: This might be one of those pull requests that break random other stuff.
>  backend: change when the accounts status changed event is triggered

- frontends/web/src/routes/settings/settings.jsx
Shown only in devmode for now.
> frontend/settings: add Ethereum

- backend/coins/btc/handlers/handlers.go
- util/system/system.go
Quick fix. Proper fix should do handle the error nicely.
> util/system: fix url/file opening on windows

- frontends/web/src/components/rates/rates.css
> frontend: add styling to indicate that fiatunit can change

- frontends/web/src/components/backups/backups.jsx
- frontends/web/src/components/backups/restore.jsx
- frontends/web/src/components/backups/restore.tsx
Should be updated when the password changes.
> restore: fix submit button

- backend/devices/usb/manager.go
Easier to debug if something goes wrong.
> backend/devices/usb/manager: log all deviceInfo fields

- backend/coins/eth/account.go
nil instead of an invalid empty struct.
> backend/coins/eth: don't return account info

- scripts/ci.sh
Did not actually exit with 1, it just printed the message.
> ci: fix locize-format check

- backend/backend.go
> backend: don't load mainnet accounts in testnet mode

- .gitignore
- cmd/servewallet/main.go
/cache, /config.json is appfolder data, now moved into a dedicated
subfolder to catch them all.
Other entries out of date.
> .gitignore: clean up

- backend/coins/eth/etherscan/etherscan.go
to can be empty, e.g. in a contract creation tx.
> eth: handle to vs. contractAddress

- Dockerfile
https://github.com/enkessler/childprocess/issues/143
Dependency of fpm: https://rubygems.org/gems/fpm
> Dockerfile/ci: fix broken ruby build

- Dockerfile
Fixed upstream.
https://github.com/jordansissel/fpm/issues/1592#issuecomment-459056612
This reverts commit ec27c09d99b2f7aacc6eb2f6909c3496ffbb4d96.
> Revert "Dockerfile/ci: fix broken ruby build"

- frontends/web/package.json
- frontends/web/src/app.tsx
- frontends/web/src/components/sidebar/sidebar.css
- frontends/web/src/decorators/translate.ts
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/account/send/utxos.css
- frontends/web/src/routes/account/send/utxos.tsx
- frontends/web/src/routes/device/deviceswitch.tsx
- frontends/web/yarn.lock
Will need to add a guide entry separately if we want to elaborate on how to use coin control.
> Frontend coincontrol feedback

- frontends/web/src/components/layout/version.tsx
This was just a TypeScript and decorator example for @Tomasvrba.
> frontend/version: move the version to a separate component and use a HOC

- backend/coins/eth/account.go
- backend/coins/eth/coin.go
> backend/eth: close account

- frontends/web/src/routes/account/summary/initializeall.tsx
TODO: design a better way to update account summary without reloading
> summary: fix componentDidUpdate loop

- frontends/qt/resources/MacOS/Info.plist
- frontends/qt/resources/MacOS/Testnet.app/Contents/Info.plist
Solved the camera access problem with the own build.
> Info.plist improvements for macOS

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/send/send.tsx
E.g. error when pasting a http/https url.
> frontend/send: qr code error on invalid protocol

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/receive/receive.jsx
The force verify button should stay visible after verifying once, in
case one once to repeat it.
> frontend/receive: missing i18n and always show button

- frontends/web/src/components/devices/bitbox02/deviceinfo.css
- frontends/web/src/components/devices/bitbox02/deviceinfo.jsx
- frontends/web/src/components/devices/bitbox02/setdevicename.jsx
- frontends/web/src/components/devices/bitbox02/settings.tsx
settings screen for v2 has same layout as v1
> Frontend v2 buttons layout

- README.md
> README: change ltc faucet

- frontends/web/src/components/devices/bitbox02/checkbackup.tsx
Send two check-backup requests, one silent and one not to receive
backup data from device and wait for user confirmation on device
screen.
Also fixes an issue when a successful backup was found and ID
returned, but could not be matched to a backup name in frontend
> check-backup: make blocking, wait for user confirmation on device

- backend/backend.go
To be right after err is assigned.
> backend: move error handling

- backend/coins/btc/electrum/electrum.go
- util/jsonrpc/jsonrpc.go
Checking the electrum connection previously could crash if the server
responded with something unexpected, for example if there is a proxy
in the middle that sends back something other than the real electrum
responses if misconfigured.
> backend/electrum: handle unexpected errors

- frontends/web/src/components/balance/balance.css
- frontends/web/src/components/devices/bitbox02/settings.tsx
- frontends/web/src/components/fiat/fiat.tsx
- frontends/web/src/components/forms/input.css
- frontends/web/src/components/layout/header.css
- frontends/web/src/components/layout/header.tsx
- frontends/web/src/components/rates/rates.css
- frontends/web/src/components/sidebar/sidebar.css
- frontends/web/src/components/sidebar/sidebar.tsx
- frontends/web/src/components/transactions/transaction.css
- frontends/web/src/components/transactions/transaction.jsx
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/account/send/utxos.css
- frontends/web/src/routes/account/send/utxos.tsx
- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/account/summary/balancestable.tsx
- frontends/web/src/routes/account/summary/summary.css
- frontends/web/src/style/layout.css
- frontends/web/src/style/variables.css
main changes:
- sidebar to look the same in desktop and mobile
- swiping right from the edge toggles the sidebar
- sidebar now has headers (account and settings)
> Mobile sidebar

- Makefile
- docs/i18n.md
- frontends/qt/BitBox.pro
- frontends/qt/main.cpp
- frontends/web/src/i18n/i18n.js
Makes it easier to build the app with the editor inside.
> qt: streamline i18n locize editor build

- backend/devices/bitbox02/device.go
> backend/bitbox02: protocol compatibility with firmware v4.0.0

- frontends/qt/Makefile
- frontends/qt/resources/linux/usr/share/applications/bitbox.desktop
> qt/linux: update .desktop app name

- frontends/web/src/components/backups/backups.tsx
- frontends/web/src/components/backups/check.jsx
- frontends/web/src/components/backups/create.jsx
- frontends/web/src/routes/device/manage-backups/manage-backups.jsx
- frontends/web/src/routes/device/settings/settings.jsx
please merge after https://github.com/digitalbitbox/bitbox-wallet-app/pull/527
> Manage backups bb01

- frontends/web/src/components/alert/Alert.tsx
- frontends/web/src/components/wait-dialog/wait-dialog.jsx
please merge after https://github.com/digitalbitbox/bitbox-wallet-app/pull/529
> Color updates

- frontends/web/src/routes/account/receive/receive.jsx
> frontend/receive: don't require a device

- frontends/web/src/locales/en/app.json
> frontend: make locize-pull

- backend/backend.go
- backend/handlers/handlers.go
- frontends/web/src/routes/settings/settings.jsx
Get rid of the 'please replug your device' message.
> backend,frontend: reinit accounts when accounts config changes

- frontends/web/src/components/devices/bitbox02/bitbox02.tsx
insert sd card needs to be blocking.
> frontend/bitbox02/wizard: better sd card handling

- frontends/web/src/components/appupgraderequired.tsx
- frontends/web/src/components/forms/button.css
- frontends/web/src/components/settingsButton/settingsButton.css
- frontends/web/src/components/settingsButton/settingsButton.tsx
- frontends/web/src/routes/device/settings/components/device-lock.jsx
- frontends/web/src/routes/device/settings/components/mobile-pairing.tsx
- frontends/web/src/routes/device/settings/components/upgradefirmware.jsx
- frontends/web/src/routes/device/upgrade/bootloader.jsx
- frontends/web/src/routes/device/upgrade/require_upgrade.jsx
- frontends/web/src/style/layout.css
- remove button focus override
- fix dialog content of mobile pairing
- bb01 upgrade steps to be contained in white boxes
- fix layout of 2fa dialog
- upgrade firmware screen for bb01 centered on screen
> Bb01 fixes

- frontends/web/src/components/transactions/transaction.css
- frontends/web/src/components/transactions/transaction.jsx
- frontends/web/src/style/layout.css
display entire tx id in details dialog
> frontend: show entire transaction id in tx details

- frontends/web/src/routes/account/send/send.tsx
Need to better research the various url standards/conventions for
eth/token transfers.
> frontend/send: temporarily disable QR code scanning for eth/erc20

- backend/devices/bitbox/device_test.go
- backend/devices/bitbox/pairing_test.go
- backend/devices/bitbox/relay/configuration.go
Otherwise log can be nil, which will panic.
> util/socksproxy: correctly initialize everywhere

- backend/bitboxbase/bitboxbase.go
- backend/bitboxbase/handlers/handlers.go
- backend/bitboxbase/rpcclient/rpcclient.go
- backend/bitboxbase/rpcclient/websocket.go
- backend/bitboxbase/rpcmessages/rpcmessages.go
Together with https://github.com/digitalbitbox/bitbox-base/pull/176 this adds the RPCs and their handlers needed for the Base setup in the App.
> Base setup RPCs and handlers  

- frontends/web/src/components/alert/Alert.tsx
- frontends/web/src/components/backups/check.jsx
- frontends/web/src/components/backups/create.jsx
- frontends/web/src/components/backups/erase.jsx
- frontends/web/src/components/backups/restore.tsx
- frontends/web/src/components/devices/bitbox02/reset.tsx
- frontends/web/src/components/devices/bitbox02/setdevicename.jsx
- frontends/web/src/components/dialog/dialog.css
- frontends/web/src/components/dialog/dialog.tsx
- frontends/web/src/components/wait-dialog/wait-dialog.jsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/settings/components/changepin.jsx
- frontends/web/src/routes/device/settings/components/hiddenwallet.jsx
- frontends/web/src/routes/device/settings/components/reset.jsx
- frontends/web/src/style/animate.css
- frontends/web/src/style/base.css
- frontends/web/src/style/variables.css
- frontends/web/src/utils/animation.ts
- remove redundant key handlers from components where the dialog component already handles keydown events.
- update animation for revealing/hiding dialogs for smoother experience
- update hover colors for primary and secondary buttons to distinguish between hover / disabled state
- display scrollbars for scrollable content
> frontend: ui issues

- .golangci.yml
- backend/bitboxbase/bitboxbase.go
- backend/bitboxbase/handlers/handlers.go
- backend/bitboxbase/rpcclient/rpcclient.go
- backend/bitboxbase/rpcmessages/rpcmessages.go
This PR is based on so far unmerged https://github.com/digitalbitbox/bitbox-wallet-app/pull/506
As it undoes some things that PR since the middleware has changed since then, we might want to fixup some of these commits before merging.
Such as removing GetHostname() and Mount/UnmountFlashdrive()
> Backend rpcs

- frontends/qt/main.cpp
BB02 setup wizard looks better this way.
> qt: increase default window height to 785px

- Gopkg.lock
- Gopkg.toml
> dep: remove karalabe/hid constraint and run dep update

- backend/bitboxbase/bitboxbase.go
- backend/bitboxbase/handlers/handlers.go
- backend/bitboxbase/rpcclient/rpcclient.go
- backend/bitboxbase/rpcclient/websocket.go
- backend/bitboxbase/rpcmessages/errorcodes.go
- backend/bitboxbase/rpcmessages/rpcmessages.go
This adds backend rpc call to the app to get base info implemented on the base here: https://github.com/digitalbitbox/bitbox-base/pull/218
I did this pretty quickly to test the middleware functionality so it might need some tweaks
> Get base info

- frontends/web/src/app.tsx
- frontends/web/src/components/devices/bitbox02/bitbox02.tsx
- frontends/web/src/components/layout/header.css
- frontends/web/src/components/spinner/Spinner.css
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/receive/receive.jsx
- frontends/web/src/routes/settings/settings.jsx
- frontends/web/src/style/base.css
- frontends/web/src/style/layout.css
changes:
- remove keypress events before an instance of `alertUser` in receive
- update spinner color to primary
- move bb02 wizard texts to translation keys
- unplugging device in settings redirects to home screen / add link to home in settings when no device
> Ui updates 2

- frontends/web/src/routes/settings/settings.jsx
Mention tor in the main settings page.
> frontend/settings: rename tor settings entry

- frontends/web/yarn.lock
just `rm yarn.lock && rm -rf node_modules && yarn install`
> frontend: updates yarn.lock

- frontends/web/src/locales/en/app.json
Make locize-pull after updating locize entries which had been reverted with out of date locize-push
> frontend: revert locize change with locize-pull upstream update

- frontends/android/BitBox/app/src/main/java/com/shiftcryptosecurity/bitbox/MainActivity.java
See comment in the code in the commit.
> android: recognize device when already plugged in

- backend/coins/btc/blockchain/blockchain.go
- backend/coins/btc/blockchain/mocks/Interface.go
- backend/coins/btc/blockchain/mocks/mock.go
- backend/coins/btc/db/headersdb/headersdb.go
- backend/coins/btc/electrum/client/client.go
- backend/coins/btc/headers/db.go
- backend/coins/btc/headers/db_test.go
- backend/coins/btc/headers/headers.go
- backend/coins/btc/headers/headers_test.go
Shutdown goroutine and close db.
> backend/coins/btc/headers: add Close()

- docs/BUILD.md
small type-o fix. Removed 'is'
> Update Build.md - small type-o fix

- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
This change makes the app show an exit prompt and brutally kill itself, taking down all goroutines with it. The slower startup is very slightly noticeable but I've seen much worse tbh. Not too bad for an alpha quality version.
I didn't touch shutdown/close functions. Would prefer to deal with them separately.
> android: prompt and force app exit on back button tap

- frontends/android/BitBoxApp/app/build.gradle
versionCode is 2, because we uploaded and discarded versionCode 1
earlier.
> android: update versionCode and versionName for release

- backend/backend.go
Might want to link to the shop from a banner.
> backend/SystemOpen: whitelist ^https://shop.shiftcrypto.ch/

- frontends/web/package.json
- frontends/web/src/components/bitboxbase/bitboxbase.css
- frontends/web/src/components/bitboxbase/detectedbase.tsx
- frontends/web/src/routes/bitboxbase/bitboxbaseconnect.tsx
- frontends/web/src/style/forms.css
- frontends/web/src/style/layout.css
- frontends/web/yarn.lock
- bigger items on larger screens
- sortable items feature
- layout for mobile screens
> ui updates to connectbase component

- backend/backend.go
Can link to this from the in-app guide.
> backend/whitelist: https://guides.shiftcrypto.ch/

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/receive/receive.jsx
other changes include:
- flexible height for copyable input
- scrollable container for mobile views
- remove legacy ltc address conversion button & related in receive component
> frontend: fix button alignment in receive / minor style updates

- backend/accounts/account.go
- backend/coins/btc/account.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/eth/account.go
The newer M... format is now supported widely enough.
> backend/ltc: remove Litecoin legacy 3... address converter

- go.mod
- go.sum
- vendor/github.com/digitalbitbox/bitbox02-api-go/api/firmware/device.go
- vendor/github.com/digitalbitbox/bitbox02-api-go/api/firmware/system.go
- vendor/modules.txt
- Bump bitbox02 version.
- Reset api cmd fix.
> vendor: update bitbox02-api-go

- frontends/web/src/app.tsx
- frontends/web/src/routes/account/buy/buy.tsx
> frontend/app: deviceIDs shouldn't be a state variable

- backend/accounts/transaction.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/btc/transactions/transactions.go
- backend/coins/eth/etherscan/etherscan.go
- backend/coins/eth/types/types.go
So the frontend can indicate when the tx is considered complete.
> backend/acccounts: add NumConfirmationsComplete()

- backend/bitboxbase/mdns/manager.go
Connection attempts can take a lot of time. Start() should not block,
as this delays the launch of the BitBoxApp GUI and everything else.
This patch makes it run in the background. The newly introduced mutex
should also be applied to detectedbases probably, but this needs some
more care.
> backend/bitboxbase: do not block Start()

- backend/bitboxbase/rpcmessages/rpcmessages.go
- frontends/web/src/routes/bitboxbase/basesettings.tsx
- frontends/web/src/routes/bitboxbase/bitboxbase.tsx
Comes together with: https://github.com/digitalbitbox/bitbox-base/pull/316 on the Base side
> base-rpcmessages: harmonize fields and json format with middleware

- frontends/web/src/components/bitboxbase/enablesshlogin.tsx
- frontends/web/src/components/settingsButton/settingsButton.css
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/bitboxbase/basesettings.tsx
- frontends/web/src/utils/verificationprogress.ts
@benma please take a look at the third commit: https://github.com/digitalbitbox/bitbox-wallet-app/commit/cdfd9ba80d51ab1f515eafa9f8b8be6e5bc8e5d9 
if it addresses your i18n issues mentioned in Issue #942
> Base settings ui

- frontends/web/src/components/bitboxbase/confirmbaserpc.tsx
- frontends/web/src/components/bitboxbase/enablesshlogin.tsx
- frontends/web/src/components/confirm/Confirm.tsx
- frontends/web/src/components/settingsButton/settingsButton.css
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/bitboxbase/basesettings.tsx
- frontends/web/src/utils/verificationprogress.ts
This PR builds on top of: https://github.com/digitalbitbox/bitbox-wallet-app/pull/758 which should be merged first. 
Only this commit is relevant: https://github.com/digitalbitbox/bitbox-wallet-app/commit/695732a012b0f109ddf8550a4b8d73ee0526f118
I already made the text changes for both PRs in locize
> Base settings dialogs

- frontends/web/src/components/progressRing/progressRing.css
- frontends/web/src/components/progressRing/progressRing.tsx
- frontends/web/src/components/transactions/transaction.css
- frontends/web/src/components/transactions/transaction.jsx
- frontends/web/src/components/transactions/transactions.css
- frontends/web/src/components/transactions/transactions.jsx
- frontends/web/src/locales/en/app.json
- circular progress bar component
- transactions (including details dialog) to use circular progress bar instead of indicator dots
- remove unused css from transactions
> frontend: circular progress bar / tx status to use progress bar

- backend/backend.go
For details see: https://github.com/ethereumbook/ethereumbook/blob/develop/05wallets.asciidoc
> eth-keypath: change keypath to the standard depth 4: m/44'/60'/0'/0

- backend/devices/bitbox02/keystore.go
Those can now return the user abort error.
> backend/bitbox02: make address/xpub display compatible with v6.0.0

- frontends/qt/server/server.go
This is a blind attempt to fix the issue that the app does not start
on macOS the first time, somtimes.
The args are logged so we can inspect if the weird arg was really
passed or not.
> qt/server: ignore -psn_xxxx flags on macOS

- backend/coins/btc/exchange.go
- frontends/qt/main.cpp
- frontends/web/src/routes/settings/settings.tsx
They suspended services outside of Sweden :@
> disable safello

- backend/backend.go
- backend/bitboxbase/bitboxbase.go
- backend/coins/btc/electrum/electrum.go
- backend/handlers/handlers.go
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/settings/electrum.jsx
Especially useful when connecting to a tor hidden service, where tls
would be redundant.
> allow adding a tcp server (no tls)

- go.mod
- go.sum
- vendor/github.com/digitalbitbox/bitbox02-api-go/api/firmware/query.go
- vendor/modules.txt
go get -u github.com/digitalbitbox/bitbox02-api-go@741357f
go mod tidy
make go-vendor
> vendor: update bitbox02-api-go:

- backend/backend.go
- backend/devices/bitbox/device.go
- backend/devices/bitbox02/device.go
- backend/devices/bitbox02bootloader/device.go
- backend/devices/device/device.go
- frontends/web/src/components/devices/bitbox02/backups.tsx
> Backup refresh

- frontends/web/src/components/status/status.css
- frontends/web/src/components/status/status.jsx
- frontends/web/src/style/variables.css
Increases readability of the status component
- larger font size
- more spacing
- highlight dismiss button in darker 
(see also screenshots at the bottom)
Drawback
- uses more room, i.e. large amount of text can be unreadable
Test
This component is used 8 times
> Frontend status visibility

- backend/backend.go
- backend/bridgecommon/bridgecommon.go
- backend/handlers/handlers.go
- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
- frontends/android/goserver/goserver.go
- frontends/web/src/app.tsx
- frontends/web/src/components/mobiledatawarning.tsx
- frontends/web/src/locales/en/app.json
Includes UI changes based off #815
> Mobile (UI)

- frontends/web/src/components/sidebar/sidebar.tsx
Replaces https://github.com/digitalbitbox/bitbox-wallet-app/pull/770
Closes #770
> frontend: making BitBoxApp logo link to '/'

- frontends/web/package.json
- frontends/web/src/manifest.json
Found the old name quite irritating as the tab name ;)
> Update App name

- backend/backend.go
- backend/coins/btc/account.go
- backend/coins/btc/account_test.go
- backend/coins/btc/coin.go
- backend/coins/btc/coin_test.go
- backend/coins/btc/maketx/maketx_test.go
- backend/coins/coin/codes.go
- backend/coins/coin/coin.go
- backend/coins/eth/coin.go
- backend/config/accounts.go
- backend/devices/bitbox/relay/channel.go
- backend/devices/bitbox02/keystore.go
- backend/devices/bitbox02/protobuf.go
- backend/erc20.go
- backend/handlers/handlers.go
> backend: unstringlify coin codes

- backend/rates/rates.go
- frontends/web/src/components/rates/rates.tsx
Based on feedback from the telegram group.
> rates: add AUD

- backend/coins/btc/account.go
- backend/coins/eth/account.go
- Explicit `initialized` flag instead of implicit
`account.signingConfiguration != nil`.
- Remove inline func that returns `alreadyInitialized`, easier to read
code.
> backend/coins: more straight forward initialization

- backend/coins/btc/account.go
Directly pass the address chain, skip indirection via the
`addresses()` method.
> backend/coins/btc: simplify code

- Makefile
- backend/arguments/arguments.go
- backend/backend.go
- backend/bridgecommon/bridgecommon.go
- backend/handlers/handlers_test.go
- cmd/servewallet/main.go
It was not functional anyway since we disabled multisig in the bb01 in
the app, and would need some love to re-enable for bb02, but that is
not necessary now.
> backend: remove multisig from default account init

- backend/coins/btc/account.go
Before:
- Legacy gap limits higher than regular gap limits by default
- User can increase the limits with the `-gapLimitReceive` and
`-gapLimitChange` cli args. They apply to all accounts equally.
After:
The same applies to the subaccounts in a unified account.
> unified-accounts: resolve TODO related to gap limits

- backend/coins/btc/account.go
Sync all subaccount addresses.
> unified-accounts: resolve TODO, syncing addresses

- backend/accounts/account.go
- backend/backend.go
- backend/coins/btc/account.go
- backend/coins/btc/account_test.go
- backend/coins/btc/exchange.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/btc/maketx/maketx.go
- backend/coins/btc/maketx/maketx_test.go
- backend/coins/btc/sign.go
- backend/coins/btc/transaction.go
- backend/coins/eth/account.go
- backend/config/config.go
- backend/devices/bitbox/keystore.go
- backend/devices/bitbox02/keystore.go
- backend/handlers/handlers.go
- backend/keystore/keystore.go
- backend/keystore/software/software.go
- backend/signing/configuration.go
- backend/signing/configuration_test.go
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/info/info.jsx
- frontends/web/src/routes/account/info/signingconfiguration.tsx
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/settings/settings.tsx
This is a rebase of https://github.com/digitalbitbox/bitbox-wallet-app/tree/staging-unified-accounts on master. The invasive work is done and seems to be working well, the rest are only small fixes that can be done on master.
> Staging unified accounts -> master

- backend/coins/btc/maketx/maketx.go
- backend/coins/btc/maketx/maketx_test.go
Litecoin does not have RBF.
We opt-in to RBF to mitigate transactions that might get stuck in
periods of high fees (bull market), or if the user enters a fee that
is too low (when we add the feature to manually choose fees).
The app does not support fee bumping yet, but in emergencies, users
can use Electrum+BitBox02 and bump the fee there.
> backend/coins/btc: enable RBF for BTC transactions

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/info/info.css
- frontends/web/src/routes/account/info/info.jsx
- frontends/web/src/routes/account/info/signingconfiguration.tsx
- frontends/web/src/routes/account/receive/receive.css
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/settings/settings.tsx
- Support toggling between bech32 and Segwit in recieve screen
- Rearrange account info view
- Rearrange settings view
- Rephrase split accounts label
- Increase space for expert settings
- Remove badges for Bitcoin and Litecoin as they are more confusing than helpful
> Unified UI

- frontends/web/src/components/dialog/dialog.css
- frontends/web/src/routes/settings/electrum.jsx
- frontends/web/src/routes/settings/settings.css
- break long words in alert dialog
- improves server list in electrum settings
> frontend: long words (hashes, addresses) should break to new line

- frontends/android/BitBoxApp/.gitignore
Seems to be generated by gomobile.
> android/git: ignore goserver/build

- backend/update.go
- frontends/android/BitBoxApp/app/build.gradle
- frontends/qt/Makefile
- frontends/qt/resources/MacOS/Info.plist
- frontends/qt/setup.nsi
This is a patch release which includes UI display language detection.
Need this mostly for Android, to lift the "early release" label.
There will be no builds for other platforms.
> release: bump to v4.20.1

- Makefile
- backend/coins/btc/handlers/handlers.go
- frontends/web/src/components/dialog/dialog.css
- frontends/web/src/components/dialog/dialog.tsx
- frontends/web/src/components/forms/input.css
- frontends/web/src/components/forms/input.tsx
- frontends/web/src/components/forms/select.css
- frontends/web/src/components/transactions/components/icons.css
- frontends/web/src/components/transactions/components/icons.tsx
- frontends/web/src/components/transactions/transaction.css
- frontends/web/src/components/transactions/transaction.tsx
- frontends/web/src/components/transactions/transactions.css
- frontends/web/src/components/transactions/transactions.tsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/send/feetargets.css
- frontends/web/src/routes/account/send/feetargets.tsx
- frontends/web/src/routes/account/send/send.css
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/test/routes/account/send/__snapshots__/feetargets.test.tsx.snap
- frontends/web/test/routes/account/send/feetargets.test.tsx
Not sure why GH closed https://github.com/digitalbitbox/bitbox-wallet-app/pull/939
> Frontend labels

- frontends/web/src/components/forms/input.tsx
- frontends/web/src/components/transactions/transaction.css
- frontends/web/src/components/transactions/transaction.tsx
- frontends/web/src/components/transactions/transactions.css
- support long multiline notes in tx overview
- better focus for editing long notes
- limit note to 256 chars
> Frontend long notes

- backend/accounts/baseaccount_test.go
> backend/accounts: add BaseAccount tests

- backend/accounts/errors/errors.go
- backend/coins/btc/account.go
- backend/coins/btc/transaction.go
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/send/feetargets.tsx
- frontends/web/src/routes/account/send/send.tsx
Builds on https://github.com/digitalbitbox/bitbox-wallet-app/pull/978/ - will rebase once the other one is done.
> backend/btc: too low fee error handling 

- frontends/web/package.json
- frontends/web/yarn.lock
We do not make use of it anywhere.
> frontend: remove unused babel-plugin-module-resolver

- backend/rates/rates.go
- frontends/web/src/components/rates/rates.tsx
- frontends/web/test/routes/account/send/feetargets.test.tsx
> backend/rates: add ILS

- frontends/web/.eslintrc.js
using `yarn fix` / `eslint --fix`
> Frontend: eslint set quote-props to warn as needed, fix with eslint

- Makefile
- frontends/web/Makefile
- frontends/web/src/routes/bitboxbase/bitboxbase.tsx
Also fix a mergeconflict introduced introduced with eslint changes.
> frontend: support eslint fix via make webfix

- backend/handlers/handlers.go
- frontends/web/src/routes/account/summary/balancerow.tsx
- frontends/web/src/routes/account/summary/balancestable.tsx
The two structs were too similar. Makes typing in the frontend easier.
> backend/handlers: use same account json

- backend/rates/rates.go
tiny bugfix from staging to master for the release
> backend/rates: add the missing SAI token to CryptoCompare

- backend/handlers/handlers.go
- frontends/web/src/routes/account/summary/accountssummary.tsx
Daily: all time
Hourly: only last week
> backend/handlers: split chart data into daily and hourly data sets

- frontends/web/src/components/sidebar/sidebar.css
- frontends/web/src/components/sidebar/sidebar.tsx
- Fix displaying `0` in the sidebar when there are no accounts
- Fix animating the sidebar on desktop (should only animate with the hamburger)
> Frontend fix sidebar

- backend/backend.go
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/summary/accountssummary.tsx
Added
- What is this page about
- How is the total amount calculated
> frontend/accountsummary: add guide entry

- backend/rates/history.go
There are many scenarios where the upstream API may return non-zero
results and yet incomplete data. Picking just one, namely "... unless
the start/end range is suspiciously arbitrary close to current time"
improves nothing. So, there's no point in making the logic more
complicated.
This commit also computes correctly when to request hourly vs daily
rates from the upstream in the case where the difference between
the oldest point and current time is less than 90 days.
> backend/rates: better backfill stop condition and daily/hourly logic

- backend/rates/history.go
- util/ratelimit/ratelimit.go
A Call fn could be blocked for too long and had no way to cancel.
For example, this happens when a RateUpdater has many active coin/fiat
pairs and the app settings are changed. The RateUpdater needs to then
quickly reconfigure and shutdown its goroutines but they would be
dangling inside a LimitedCall.Call.
The new context arg in Call allows to get rid of those dangling
goroutines.
> util/ratelimit: make LimitedCall.Call cancellable by a context

- frontends/web/src/routes/account/summary/chart.tsx
When creating a chart without any data, the chart displays
nothing, but creates a big empty space.
This checks if there is chart data and only creates the chart
and displays the filters with data."
> Frontend: initialize chart only when there is data to show

- frontends/web/src/routes/account/summary/accountssummary.css
- frontends/web/src/routes/account/summary/accountssummary.tsx
Added the total balance in the summary table footer when available.
> frontend: show total balance in summary table footer

- backend/rates/db.go
- backend/rates/history.go
For what concerns the app and the UI, the result is identical.
The bbolt cache though executes fewer "put" operations per
dumpHistoryBucket call.
The difference is probably negligible but this feels like a correct way
of doing it.
> backend/rates: append instead of replacing a bbolt cache bucket

- backend/rates/history.go
- backend/rates/rates.go
It's running in production and ready for public consumption.
> backend/rates: switch to our coingecko mirror

- backend/coins/eth/etherscan/etherscan.go
Still running into rate limiting errors occasionally.
> backend/etherscan: increase rate limit

- frontends/web/src/routes/account/summary/accountssummary.tsx
This is the main event to listen to and is fired when an account is
updated.
> frontend/accountsummary: update data on syncdone event

- backend/chart.go
- backend/handlers/handlers.go
This is still not enough to pass the complexity linter :see_no_evil: But it the function is shorter and the code a bit more organized so I opened this PR.
> Chart refactor

- backend/backend.go
We had an accountsLock, but it not held for the whole duration of
initAccounts(), which means that in concurrent calls, the accounts
could be uninitialized twice, then all accounts would be added twice,
or other such race conditions.
This commit only acquires lock in exported functions to make it work
with all combinations of account-changing function calls.
> backend: make changes to accounts atomic

- backend/backend.go
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/buy/guide.tsx
- frontends/web/src/routes/buy/info.css
- frontends/web/src/routes/buy/info.tsx
- frontends/web/src/routes/buy/moonpay.tsx
Added disclaimer payment, fees and security info.
> add moonpay disclaimer

- frontends/android/BitBoxApp/app/src/main/AndroidManifest.xml
https://promon.co/security-news/strandhogg-critical-severity-vulnerability/
> android: mitigate strandhogg issue

- frontends/web/src/components/spinner/Spinner.css
- frontends/web/src/routes/buy/moonpay.css
Fixed sidebar overlay not covering MoonPay's iframe (small + medium screen)
> Frontend moonpay CSS

- backend/exchanges/moonpay.go
This concludes tweaking Moonpay API parameters for now.
For docs, see the following link but note that it's behind an
authentication, unfortunately:
https://www.moonpay.com/dashboard/getting_started/
The widget now looks like this:
> backend/moonpay: enable bank transfer payment method

- frontends/web/src/routes/buy/info.tsx
Updated the Fees for credit & debit cards and Apple/Google/Samsung.
> frontend: better moonpay fees

- frontends/web/src/components/backups/backup.tsx
- frontends/web/src/components/backups/backups.css
- frontends/web/src/components/backups/backups.tsx
- frontends/web/src/components/devices/bitbox02/backups.tsx
- frontends/web/src/components/devices/bitbox02/bitbox02.tsx
- frontends/web/src/components/forms/radio.css
- cleanup
- fix scrolling/jumping of long backup lists
- fix radio form element focus
> Frontend backup update

- CHANGELOG.md
- backend/accounts/transaction.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/eth/etherscan/etherscan.go
- backend/coins/eth/types/types.go
- frontends/web/src/api/account.ts
- frontends/web/src/components/transactions/transaction.tsx
Good advanced info, can help with understanding stuck tx problems
should they appear.
> frontend/transactions: show ETH nonce in details

- frontends/web/src/api/account.ts
- frontends/web/src/api/accountsync.ts
- frontends/web/src/api/subscribe-legacy.ts
- frontends/web/src/api/subscribe.ts
- frontends/web/src/app.tsx
- frontends/web/src/components/sidebar/sidebar.tsx
- frontends/web/src/connected.tsx
- frontends/web/src/index.js
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/buy/info.tsx
- frontends/web/src/routes/buy/moonpay.tsx
- frontends/web/src/utils/event-legacy.ts
- frontends/web/src/utils/subscriptions.ts
- util/observable/action/action.go
supersedes https://github.com/digitalbitbox/bitbox-wallet-app/pull/1172
> Frontend refactor account sync

- frontends/web/src/api/devices.ts
- frontends/web/src/api/devicessync.ts
- frontends/web/src/app.tsx
- frontends/web/src/components/devices/bitbox02/bitbox02.tsx
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/buy/info.tsx
- frontends/web/src/routes/buy/moonpay.tsx
- frontends/web/src/routes/device/deviceswitch.tsx
- frontends/web/src/routes/device/setup/success.jsx
- frontends/web/src/routes/device/unlock.jsx
- adds api/devices and api/devicessync
- rewrite app.tsx to use api/devices*
- change get started and unlock routing to directly go to account-summary
- updated app / device routing
> Frontend api devices

- backend/devices/device/device.go
They have been commented long enough.
> backend/device: remove commented/unused interace methods

- util/socksproxy/socksproxy_test.go
I said I added tests in https://github.com/digitalbitbox/bitbox-wallet-app/pull/1231#discussion_r614841012, but I actually didn't commit the file ...
> util/socksproxy: add validation tests

- frontends/web/src/components/devices/bitbox02/bitbox02.tsx
- frontends/web/src/components/dialog/dialog.tsx
- frontends/web/src/components/language/language.tsx
- frontends/web/src/components/layout/footer.tsx
- frontends/web/src/components/mobiledatawarning.tsx
- frontends/web/src/components/password.jsx
- frontends/web/src/components/status/status.css
- frontends/web/src/components/status/status.tsx
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/device/device.jsx
- frontends/web/src/routes/device/setup/goal.jsx
- frontends/web/src/routes/device/setup/initialize.tsx
- frontends/web/src/routes/device/setup/security-information.tsx
- frontends/web/src/routes/device/setup/seed-create-new.jsx
- frontends/web/src/routes/device/setup/seed-restore.jsx
- frontends/web/src/routes/device/setup/success.jsx
- frontends/web/test/components/language/language.test.tsx
In Preact X branch there were a few issues, i.e. setState asynchronously updating `this.state` and subsequent code relying on an update `this.state` breaking. This PR has some of the changes in frontend-preact-x as a single PR:
- rewrite language component to typescript
- rewrite status component with hidden prop
- frontend: ensure dialog refs are present
- frontend: ensure state is up to date before continuing
See also old Preact X PR https://github.com/digitalbitbox/bitbox-wallet-app/pull/1228
> Frontend improvements from issues with Preact X 

- frontends/web/src/components/devices/bitbox02/settings.tsx
- frontends/web/src/locales/en/app.json
> frontend/bitbox02: display securechip model

- backend/accounts.go
- backend/backend.go
- backend/config/accounts.go
- backend/config/accounts_test.go
- backend/handlers/handlers.go
- frontends/web/src/api/account.ts
- frontends/web/src/api/backend.ts
- frontends/web/src/app.tsx
- frontends/web/src/components/icon/assets/paxg-color.svg
- frontends/web/src/components/icon/logo.tsx
- frontends/web/src/routes/settings/manage-accounts.css
- frontends/web/src/routes/settings/manage-accounts.tsx
Rebased and extended https://github.com/digitalbitbox/bitbox-wallet-app/pull/1274
> Multi-accounts manage tokens prototype - rebased & extended

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/add/add.tsx
- frontends/web/src/routes/settings/manage-accounts.tsx
- frontends/web/src/routes/settings/settings.tsx
- removed old unused translations
- TODO: remove from locize as well
- moved translations for adding to addAccount, same for manageAccounts
- added missing translations (also on settings view)
> frontend: cleanup translations for add and manage accounts

- frontends/web/src/routes/account/add/add.css
- frontends/web/src/routes/account/add/add.tsx
- frontends/web/src/style/layout.css
- frontends/web/src/style/variables.css
> frontend: visual update for add-account

- frontends/web/src/app.tsx
- frontends/web/src/components/sidebar/sidebar.tsx
- frontends/web/src/routes/account/summary/chart.tsx
- route add-account and manage-account on unplug
- hide add-account in sidebar header 
- fix error when routing away from chart
> Multiaccount routing

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/buy/info.tsx
> Frontend fix translations

- frontends/android/BitBoxApp/app/build.gradle
Submitted the previous code for review, but a regression was found, so
we have to make a new release.
> android: bump versionCode

- backend/accounts.go
If no accounts exist, the first account of each supported coin is
added with a default name. Making a default name was accidentally
removed in 4ab179273826c59137bc7c592a6ca1c0484a11f1, leading to an
error when adding the initial accounts.
> backend: fix regression with naming the default initial accounts

- frontends/web/src/routes/account/add/add.tsx
The suggested name should be entered as a value into the input field,
not a placeholder, so it is more intuitive that one can simply proceed
with the suggested name.
> frontend/account/add: make placeholder a value instead

- backend/accounts.go
- backend/accounts_test.go
- backend/backend.go
- backend/backend_test.go
- backend/handlers/handlers.go
- backend/rates/rates.go
- frontends/web/src/routes/settings/manage-accounts.tsx
Builds on https://github.com/digitalbitbox/bitbox-wallet-app/pull/1320 and https://github.com/digitalbitbox/bitbox-wallet-app/pull/1319
> More unit tests

- backend/accounts.go
- backend/accounts/baseaccount.go
- backend/accounts_test.go
- backend/backend_test.go
- backend/chart.go
- backend/config/accounts.go
- backend/handlers/handlers.go
- frontends/web/src/api/account.ts
- frontends/web/src/app.tsx
- frontends/web/src/routes/settings/settings.tsx
Enables activation and deactivation of accounts.
> backend: add SetAccountActive

- frontends/qt/setup.nsi
It seems there can only be one app for one protocol. We set it if no
other app is registered, or otherwise ask the user for permission.
> aopp: register URI scheme on Windows

- CHANGELOG.md
Forgot to add in https://github.com/digitalbitbox/bitbox-wallet-app/issues/1193
> CHANGELOG: mention update to Qt 5.15

- frontends/android/BitBoxApp/app/src/main/AndroidManifest.xml
- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
https://developer.android.com/training/app-links/deep-linking
> aopp: register URI scheme on Android

- backend/devices/bitbox/keystore.go
- backend/devices/bitbox02/keystore.go
- backend/keystore/keystore.go
- backend/keystore/mocks/keystore.go
- backend/keystore/software/software.go
> backend/keystore: add BTCSignMessage

- frontends/web/src/components/devices/bitbox02/settings.tsx
- frontends/web/src/routes/account/utils.ts
- frontends/web/src/routes/buy/info.tsx
- frontends/web/src/routes/buy/moonpay.tsx
- added missing divider on the device setting view
- bitcoin crypto naming changes due to multi acccount
> Frontend cleanup multiaccounts

- frontends/web/src/api/aopp.ts
- frontends/web/src/components/aopp/aopp.tsx
- frontends/web/src/components/aopp/verifyaddress.tsx
Builds on https://github.com/digitalbitbox/bitbox-wallet-app/pull/1392 because of a conflict, otherwise independent.
> frontend/aopp: improve Aopp type 

- frontends/web/src/components/aopp/aopp.tsx
- frontends/web/src/locales/en/app.json
Locize will need to be updated accordingly.
> frontend/aopp: changed wording

- backend/aopp.go
- backend/aopp_test.go
No need for the user to select the account in a dropdown with only one choice.
> backend/aopp: skip choosingAccount step if there is only one account

- frontends/android/BitBoxApp/app/build.gradle
Missed to update the versionName in e01b7b4acf2a245f5d3895fd9d370cafa2856a50.
> android: fix versionName

- README.md
The note is outdated, the issues were fixed.
> README: ElectrumX is supported

- frontends/web/src/components/confirm/Confirm.tsx
- frontends/web/src/components/dialog/dialog.css
- frontends/web/src/components/dialog/dialog.tsx
- frontends/web/src/routes/device/bitbox01/components/upgradefirmware.jsx
- frontends/web/src/routes/device/bitbox01/restore.tsx
- frontends/web/src/routes/device/bitbox01/settings/components/changepin.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/hiddenwallet.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/mobile-pairing.tsx
- frontends/web/src/routes/device/bitbox01/settings/components/randomnumber.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/reset.jsx
- frontends/web/src/routes/device/bitbox02/checkbackup.tsx
- frontends/web/src/routes/device/bitbox02/reset.tsx
- frontends/web/src/routes/device/bitbox02/sdcardcheck.tsx
- frontends/web/src/routes/device/bitbox02/setdevicename.jsx
- frontends/web/src/routes/settings/manage-accounts.tsx
- frontends/web/src/routes/settings/settings.tsx
let me know if cACK then I'll check all components that use dialogs
> Frontend dialog buttons

- CHANGELOG.md
Was added in 4ca933f7d64d31fa5e6d1717a1014548c27820ed
> changelog: support copy address from tx detail

- CONTRIBUTING.md
- README.md
Should probably link to this from the readme but not sure where exactly yet.
Closes #96
> docs: add contribution guidelines

- frontends/web/src/routes/account/account.tsx
With the new routing normal anchors cause a page reload which
messes up the routing.
Changed to use  compoent for send button.
> frontend: use link component for send button

- frontends/web/src/components/devices/bitbox02bootloader/toggleshowfirmwarehash.tsx
- frontends/web/src/components/toggle/toggle.tsx
The toggle was not being reflected since the React merge.
> Frontend: fix `ToggleFWHash` visual bug

- frontends/web/src/api/version.ts
- refactored version component
- fixed warning about state update on unmounted component
> Frontend refactor version component

- README.md
- frontends/qt/server/server.go
Mention how to use the environment variable to debug the BitBoxApp
with devtools.
Also removed old outdated section about base.
> readme: add section about qt webengine debugging

- frontends/web/src/components/layout/header.tsx
> Frontend: fix header not showing childrens

- frontends/web/src/components/message/__snapshots__/message.test.tsx.snap
- frontends/web/src/components/message/message.test.tsx
- frontends/web/src/components/message/message.tsx
> Frontend: remove unused `style` prop on `Message`

- frontends/web/src/index.tsx
> frontend: remove loading text on app start

- CHANGELOG.md
And add the migration to react.
> CHANGELOG: fix entries in wrong release

- backend/accounts/account.go
- backend/accounts/errors/errors.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/eth/account.go
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/send/send.tsx
> fontend/eth: remove dead code

- Makefile
- scripts/travis-ci.sh
I'm trying to generate a native build using Apple Silicon and the first roadblock I hit was this library, for some reason and updating it seems to make the process go further.
I hope this helps :)
> Update Go CI Lint

- frontends/web/src/components/spinner/Spinner.tsx
- Migrate `ClassComponent` to `FunctionComponent`
- Migrate HOCs to hooks
> Frontend: refactor `Spinner` component

- frontends/web/src/components/badge/badge.tsx
- Migrate `ClassComponent` to `FunctionComponent`
- Migrate HOCs tos hooks
> Frontend: refactor `Badge` component

- frontends/web/src/components/balance/balance.tsx
- Migrate `ClassComponent` to `FunctionComponent`
- Migrate HOCs tos hooks
> Frontend: refactor `Balance` component

- frontends/web/src/components/confirm/Confirm.tsx
Updated https://github.com/digitalbitbox/bitbox-wallet-app/pull/1608
Last commit moved callback to state hook, but the callback does
not impact rendering, changed to useRef hook.
This component is used in:
- BitBox01 mobile pairing
- create backup
- show mnemonic
- connect node: remove and reset to default
Deprecate Confirm component, exporting a function and updating
the state of the global confirm instance is a bit an antipattern.
> Frontend confirmation refactor II

- frontends/web/src/components/icon/assets/icons/close-x-white.svg
- frontends/web/src/components/icon/icon.tsx
- frontends/web/src/components/status/status.module.css
- frontends/web/src/components/status/status.tsx
- frontends/web/src/routes/settings/electrum.jsx
- frontends/web/src/routes/settings/electrum.module.css
- frontends/web/src/style/variables.css
- removes custom font size for small screen that was only used in electrum and status (came up during https://github.com/digitalbitbox/bitbox-wallet-app/pull/1601 design review)
- moves close button icon out of JSX into a SVG file
- fixes close button sometimes overlapping text
> Frontend update status component

- frontends/web/src/api/backend.ts
- frontends/web/src/components/mobiledatawarning.tsx
- Migrate `ClassComponent` to `FunctionComponent`
- Migrate HOCs to hooks
> Frontend: refactor `MobileDataWarning` component

- frontends/web/src/routes/account/send/send.tsx
Typechecker should have caught that :O
> frontend/send: fix send to self

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/info/signingconfiguration.tsx
> frontend/accountinfo: translate script type

- backend/coins/btc/transactions/transactions.go
If an account has many transactions, SpendableOutputs() was very
slow. The reason for this is that the outputs set that it iterates
over can be very large, and for output we loaded the corresponding
transaction from the database.
We only need to load the transaction if the output is still unspent
though. The number of unspent outputs is usually much smaller than the
number of total outputs.
> backend/btc: speed up SpendableOutputs()

- backend/devices/bitbox02/keystore.go
Fix regression from b3775ed28a7b85b7ebf1a708f26e3b6a72020272.
We forgot to add the change output account config to the available
account configs in the above commit, which would lead to an error if
there was a change output whose type was different from the first input.
> backend/bitbox02: properly handle change account config

- CHANGELOG.md
Forgot to do that before tagging :shrug:
> CHANGELOG: mark v4.32.0

- frontends/web/src/hooks/keyboard.ts
- frontends/web/src/routes/account/info/info.tsx
- frontends/web/src/routes/account/receive/receive.tsx
Added hook to take care about ESC keydown event and fire a callback.
Based on PR https://github.com/digitalbitbox/bitbox-wallet-app/pull/1679
> Frontend esc hook

- frontends/web/src/routes/account/receive/receive.tsx
Introduced in a3f5ff9d33050ff0f84981d5204f0b1bf184dc8a
> frontend: fix regression to change to previous address

- backend/coins/eth/account.go
- backend/coins/eth/account_test.go
- backend/coins/eth/etherscan/etherscan.go
- backend/coins/eth/rpcclient/mocks/rpcclient.go
- backend/coins/eth/rpcclient/rpcclient.go
> Small ETH RPC client refactor

- frontends/web/src/routes/account/add/add.tsx
- frontends/web/src/routes/account/info/guide.tsx
- frontends/web/src/routes/account/info/info.tsx
- frontends/web/src/routes/buy/guide.tsx
- frontends/web/src/routes/buy/info.tsx
- frontends/web/src/routes/buy/moonpay.tsx
- frontends/web/src/routes/settings/manage-account-guide.tsx
- frontends/web/src/routes/settings/manage-accounts.tsx
Changed to useTranslation hook instead of passing the 't' function
to function components.
> frontend: use translation hook

- frontends/web/src/routes/account/receive/components/guide.tsx
- frontends/web/src/routes/account/receive/index.tsx
- frontends/web/src/routes/account/receive/receive-bb01.tsx
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/router.tsx
This has some duplicated code, but it will allow to completely revamp the receive view for BitBox02 and keep the legacy BitBox01 receive flow as it is.
> Frontend split receive component into bitbox02 and legacy (bitbox01)

- backend/coins/btc/maketx/txsize_internal_test.go
We want to update the btcd dep, but it heavily refactored the btcec
package - it now does not use big.Int anymore and there seems to be no
way to get the R and S values as big.Int anymore.
This test is changed to not use the btcec dep at all, circumventing
that problem.
I manually converted the DER signature from before to the
types.Signature that is needed in the test.
> backend/btc/maketx: don't use btcec in test

- frontends/web/.eslintrc.json
- frontends/web/src/components/headerssync/headerssync.tsx
- frontends/web/src/components/rates/rates.tsx
- frontends/web/src/decorators/load.tsx
- frontends/web/src/hooks/utils.ts
- frontends/web/src/routes/account/add/add.tsx
- frontends/web/src/routes/account/add/components/steps.tsx
- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/account/summary/chart.tsx
- frontends/web/src/routes/device/bitbox01/backups.tsx
- frontends/web/src/routes/device/bitbox01/check.jsx
- frontends/web/src/routes/device/bitbox01/create.jsx
- frontends/web/src/routes/device/bitbox01/restore.tsx
- frontends/web/src/routes/device/bitbox01/settings/components/changepin.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/hiddenwallet.jsx
- frontends/web/src/routes/device/bitbox02/components/password-entry/password-entry.tsx
- frontends/web/src/routes/settings/electrum.jsx
- frontends/web/src/utils/equal.js
- frontends/web/src/utils/qttransport.js
Always use consitent braces with newlines for better readability.
> frontend: eslint rule for curly braces

- backend/keystore/software/software.go
We added P2TR support for the BitBox02 but couldn't do the same for
the software (debug) keystore as BTCD didn't have Taproot support
yet. Now it does, and since we upgraded the dep in
c44d766c87303821855b4bcdee045b619317b5bf, we can use Taproot also in
the software keystore.
`keystore.sign()` is inlined into the main signing function, as the
signatures now need to be distinguished between Schnorr/BIP86 and
ECDSA.
The private key is tweaked accoriding to BIP-86 to match the public
key that backs the BIP-86 P2TR address created by address.go.
> backend/keystore/software: add Taproot (P2TR) support

- frontends/web/src/globals.d.ts
- frontends/web/src/utils/env.ts
also added global.d.ts to define qt and android globals.
> frontend: migrate env to typescript

- CHANGELOG.md
- frontends/web/src/components/settingsButton/settingsButton.module.css
- frontends/web/src/components/settingsButton/settingsItem.tsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/bitbox02/settings.tsx
With this, the user can verify at any moment the authenticity of his device by checking the device view.
> frontend: add attestation check on device setting.

- frontends/web/src/components/toggle/toggle.module.css
- frontends/web/src/components/toggle/toggle.tsx
- frontends/web/src/routes/settings/components/fiat/fiat.tsx
- changed from class based to function component
- removed '[key: string]: any;' type and added className type
- changed from interface to type
- cleaned up CSS, alphabetically sorted CSS properties and removed prefixed styles
> frontend: refactor toggle component

- docs/BUILD.md
Updated BUILD.md with up to date instructions for Android build and deploy.
> docs/BUILD.md: update instructions for Android build and deploy

- frontends/web/src/routes/device/bitbox02/sdcardcheck.tsx
As a part of the refactoring process and to follow the latest conventions in the frontend, class components need to be converted into functional components whenever possible.
> frontend: converted SDCardCheck to a functional component

- CHANGELOG.md
- frontends/web/src/api/version.ts
- frontends/web/src/components/icon/assets/icons/red-dot.svg
- frontends/web/src/components/icon/icon.tsx
- frontends/web/src/components/settingsButton/settingsButton.module.css
- frontends/web/src/components/settingsButton/settingsButton.tsx
- frontends/web/src/components/update/update.tsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/settings/settings.tsx
This adds a new `Info` section in settings, which states the current version of the App and, in case of available updates, offers a download link.
> frontend: add available updates check in settings

- frontends/web/.eslintrc.json
- frontends/web/src/i18n/__mocks__/i18n.js
- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/account/summary/chart.tsx
- frontends/web/src/routes/device/bitbox01/setup/security-information.tsx
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
- frontends/web/src/routes/device/manage-backups/manage-backups.jsx
Updated frontend codebase with 'make webfix'.
> frontend: add no-multi-spaces eslint rule

- frontends/web/.eslintrc.json
- frontends/web/src/app.tsx
- frontends/web/src/components/sidebar/sidebar.tsx
- frontends/web/src/hooks/sdcard.ts
- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/account/summary/chart.tsx
- frontends/web/src/routes/settings/manage-accounts.tsx
Added space-in-parens rule and fixed with "make webfix", see
- https://eslint.org/docs/latest/rules/space-in-parens
> frontend: eslint consistent space in parentheses

- frontends/web/src/components/layout/header.module.css
Looks like the change header design branch and refactor CSS variables canceled each others header background out.
Fixed and removed header color as it is supposed to be in:
- f30df4f4a64f50789541fe153a24389b5fc1954d
> frontend: fix header background

- frontends/web/.eslintrc.json
See https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-equals-spacing.md
> frontend: eslint consistent space in jsx props

- frontends/web/src/components/aopp/aopp.module.css
- frontends/web/src/components/dialog/dialog.module.css
- frontends/web/src/components/forms/button.module.css
- frontends/web/src/components/forms/checkbox.module.css
- frontends/web/src/components/forms/input.module.css
- frontends/web/src/components/forms/select.module.css
- frontends/web/src/components/message/message.module.css
- frontends/web/src/routes/account/add/components/steps.module.css
- frontends/web/src/routes/account/send/feetargets.module.css
- frontends/web/src/routes/account/send/send.module.css
- frontends/web/src/routes/account/summary/accountssummary.module.css
- frontends/web/src/routes/account/summary/chart.module.css
- frontends/web/src/routes/settings/electrum.module.css
- frontends/web/src/style/base.css
- frontends/web/src/style/forms.css
Assigned correct color variables to components that still use the wrong ones or hard coded ones.
In addition, border color variables are changed so they use background color variables instead.
> frontends: refactoring color variables

- frontends/web/src/components/badge/badge.test.tsx
- frontends/web/src/components/balance/balance.test.tsx
- frontends/web/src/components/balance/balance.tsx
- frontends/web/src/components/forms/button.test.tsx
- frontends/web/src/components/forms/checkbox.test.tsx
- frontends/web/src/components/forms/radio.test.tsx
- frontends/web/src/components/forms/select.test.tsx
- frontends/web/src/components/forms/select.tsx
- frontends/web/src/components/guide/entry.test.tsx
- frontends/web/src/components/guide/entry.tsx
- frontends/web/src/components/headerssync/headerssync.test.tsx
- frontends/web/src/components/headerssync/headerssync.tsx
- frontends/web/src/components/language/language.test.tsx
- frontends/web/src/i18n/forTests/i18nfortests.js
- frontends/web/src/i18n/forTests/i18nwrapper.tsx
as a part of our refactoring efforts  in the FE, we'd like to increase the test coverage of our react components.
**Created unit tests for functional component ones**. This PR did not cover all functional components yet though - so the rest can be done in another PR to hopefully avoid a huge, longstanding PR. 🙂  thanks.
> frontend: added unit tests for several components

- backend/exchanges/exchanges.go
- backend/exchanges/moonpay.go
- backend/exchanges/pocket.go
- backend/handlers/handlers.go
- frontends/web/src/api/exchanges.ts
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/actionButtons.tsx
- frontends/web/src/routes/buy/exchange.tsx
- frontends/web/src/routes/buy/info.tsx
- frontends/web/src/routes/buy/pocket.tsx
Exchange endpoints number has been reduced and the data structures passed to the frontend has been refactored to increase usability.
Context: this PR is meant to be merged to allow a rebase of https://github.com/digitalbitbox/bitbox-wallet-app/pull/1881# which should become a bit more simple thanks to the new endpoint results format.
> backend: refactor exchange endpoints

- frontends/web/src/components/alert/Alert.test.tsx
- frontends/web/src/components/alert/Alert.tsx
to improve our code in the FE, we'd like to convert following component into a functional one and added tests for it.
> frontend: convert alert into functional and added tests

- backend/accounts/baseaccount.go
- backend/coins/btc/account.go
- frontends/web/src/api/account.ts
- frontends/web/src/routes/account/receive/components/guide.tsx
- frontends/web/src/routes/account/receive/receive-bb01.tsx
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/account/send/send.tsx
This fixes some potential race conditions. More to come.
> Fix race conditions pt1

- frontends/web/src/api/exchanges.ts
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/buy/components/exchangeselectionradio.module.css
- frontends/web/src/routes/buy/components/exchangeselectionradio.tsx
- frontends/web/src/routes/buy/exchange.module.css
- frontends/web/src/routes/buy/exchange.tsx
- frontends/web/src/routes/buy/types.ts
- frontends/web/src/routes/buy/utils.ts
- frontends/web/src/style/variables.css
as a part of the development of the exchange page, other than re-styling, some data (from the BE) also got re-structured to follow best practices in the FE.
[Preview] Video
https://user-images.githubusercontent.com/28676406/207245268-a5193140-c171-43a5-88a8-4afa865ef1d1.mov
This PR is a part of the development process and will be followed by one or several more PRs.
**What's still missing?**
1. Custom Select Component (Select Region) with Flags and Globe Icon
2. Payment Method Logo / Icon
3. The "Fast" and "Best Deal"  Badge
4. The "i" (information) button
**What's been done in this PR?**
1. Exchange Deals data re-structuring in the FE. This is done for several reasons, such as cleaning up the code, increasing modularity / re-usability of the components (decreasing "hardcoded-ness"), and …
> frontend: partly re-style the exchange page

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/buy/components/buyTags.module.css
- frontends/web/src/routes/buy/components/buyTags.tsx
- frontends/web/src/routes/buy/components/exchangeselectionradio.tsx
- frontends/web/src/style/variables.css
as a part of development of the UI for the account selection page
Preview:
> frontend: created buy tags

- frontends/web/src/api/bitbox02.ts
- frontends/web/src/routes/device/bitbox02/settings.tsx
- frontends/web/src/routes/device/bitbox02/showmnemonic.tsx
- frontends/web/src/utils/markup.test.tsx
- frontends/web/src/utils/markup.tsx
- move and type showMnemonic to api/bitbox02
- refactored ShowMnemonic class to functional component
> frontend: refactor showmnemonic.tsx to functional component

- frontends/web/src/components/copy/Copy.module.css
- frontends/web/src/components/dialog/dialog.module.css
- frontends/web/src/components/dialog/dialog.tsx
- frontends/web/src/components/icon/assets/icons/menu-light.svg
- frontends/web/src/components/icon/icon.tsx
- frontends/web/src/components/spinner/Spinner.module.css
- frontends/web/src/components/transactions/transaction.module.css
- frontends/web/src/routes/account/add/components/steps.module.css
- frontends/web/src/routes/account/summary/accountssummary.module.css
- frontends/web/src/routes/account/summary/chart.module.css
- frontends/web/src/routes/account/summary/chart.tsx
- frontends/web/src/routes/buy/info.module.css
- frontends/web/src/routes/device/components/backups.module.css
- frontends/web/src/routes/exchanges/exchanges.module.css
- frontends/web/src/style/forms.css
- frontends/web/src/style/layout.css
- frontends/web/src/style/variables.css
Changed existing CSS and assets to hardcoded dark mode, the related JavaScript will be done in a later commit. Some assets have not yet been updated as they require some additional logic to change to dark mode.
superseds https://github.com/digitalbitbox/bitbox-wallet-app/pull/1883
> frontends: added css changes for dark mode

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/buy/components/infocontent.tsx
- frontends/web/src/routes/buy/exchange.tsx
To support multiple languages for "buy / exchange" info content, we'd need to localise them.
> frontend: localise info content

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/buy/guide.tsx
- frontends/web/src/routes/buy/moonpay.tsx
- frontends/web/src/routes/buy/pocket-terms.tsx
- frontends/web/src/routes/buy/pocket.tsx
The guide content for the buy section is updated to cover the integration of Pocket.
> frontend/guide: update buy guide content

- backend/coins/btc/account.go
In Litecoin, the default `minrelaytxfee` is 0.00001 LTC/kB. However, the fee estimation sometimes returns fee rates smaller than that:
```
estimatesmartfee 2
{
"feerate": 0.00000999,
"blocks": 2
}
```
If the estimated fee is used for a tx, it can't be relayed and sending a tx results in an error.
We simply use the minrelayfee if it is larger than the estimated fee rate.
> backend/btc: use minrelayfee if the fee estimation is smaller

- frontends/web/src/routes/buy/exchange.tsx
A bug in the locale detection caused the exchange selection flow to break if an empty native locale values was retrieved. This fixes the bug exploiting `i18n.language` instead of detecting (again) the language in the page.
> frontend/exchange: fix locale detection

- frontends/web/src/api/bitbox02.ts
- frontends/web/src/routes/device/bitbox02/backups.tsx
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
- frontends/web/src/routes/device/bitbox02/createbackup.tsx
I rebased https://github.com/digitalbitbox/bitbox-wallet-app/pull/1925
and tested as described here https://github.com/digitalbitbox/bitbox-wallet-app/pull/1925#issuecomment-1405058713
looking at the changes they are mostly just typescript related, I will highlight the place where it is a bit different in JavaScript, due to TS complaining.
> Frontend type bitbox02 api

- frontends/web/src/components/alert/Alert.tsx
- frontends/web/src/components/aopp/aopp.tsx
- frontends/web/src/components/view/view.module.css
- frontends/web/src/components/view/view.tsx
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
- frontends/web/src/routes/device/bitbox02/passphrase.tsx
- frontends/web/src/routes/device/bitbox02/settings.tsx
To fulfil our UI requirements, View needs to be able to centre its content vertically when NOT on full screen (`!fullscreen`).
> frontend: added prop verticallyCentered for View component

- frontends/web/package-lock.json
- frontends/web/package.json
- frontends/web/src/routes/buy/components/countryselect.module.css
- frontends/web/src/routes/buy/components/countryselect.tsx
- frontends/web/src/routes/buy/exchange.module.css
- frontends/web/src/routes/buy/exchange.tsx
To improve our UI & UX, we'd like to have a custom dropdown / select implemented for the Country Selector. This enables search and displays the flag of each region in the option list.
The custom dropdown was implemented using `react-select` pkg.
[Preview]:
https://user-images.githubusercontent.com/28676406/218675245-7375c58b-a74f-4bb6-aadf-0792ca1650ce.mov
> frontend: created custom dropdown for Country selector

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
Remove custom back button text in favor of generic back button.
> frontend: use generic back button

- frontends/web/src/routes/device/bitbox02/checkbackup.tsx
- frontends/web/src/routes/device/components/backup.tsx
2 small ui improvements
- show check backup title
- confirm check-backup-success and close with enter key
also refactored backkupitem to functional component
> Frontend checkbackup fix

- frontends/web/src/routes/device/bitbox02/checkbackup.tsx
Here, we're converting `checkbackup.tsx` into a functional component.
> frontend: convert `checkbackup` into a functional component.

- frontends/web/src/routes/device/bitbox02/createbackup.tsx
supersedes https://github.com/digitalbitbox/bitbox-wallet-app/pull/1981
Here, we're converting `createbackup.tsx` into a functional component.
This also fixes the hidden error dialog covered by blocking dialog.
Steps to reproduce:
1) inser microSD
2) manage backups / create backup
3) cancel on device
(also test with empty sdCard)
> frontend: convert `createbackup` into a functional component

- frontends/android/BitBoxApp/app/src/main/res/values/colors.xml
Change the navigation bar color to match the removal of the white top bar
> Update navigation bar color

- frontends/web/src/components/copy/Copy.tsx
Here, we're converting `copy.tsx` into a functional component.
> frontend: convert `CopyableInput` (`Copy.tsx`) into a functional component

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/buy/components/infocontent.tsx
Added info about which currencies, transfer methods, reccuring payments and identity verification.
> frontend: update pocket info content

- frontends/web/src/api/account.ts
- frontends/web/src/routes/account/info/signingconfiguration.tsx
Here, we're converting `signingconfiguration.tsx` into a functional component.
> frontend: convert `signingconfiguration` into a functional component

- frontends/web/src/app.tsx
- frontends/web/src/components/darkmode/darkmode.tsx
- frontends/web/src/components/darkmode/darkmodetoggle.tsx
- frontends/web/src/hooks/mediaquery.ts
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/summary/chart.tsx
- frontends/web/src/routes/settings/settings.tsx
- frontends/web/src/style/variables.css
adding draft as the JS part is not React like. It "works" but doesn't update once the mediaquery changes (if system settings is changed).
Lets discuss in dm.
> draft: frontend darkmode toggle

- frontends/web/src/routes/buy/terms.module.css
Text was not readable, removed hardcoded white background color.
> frontend: fix terms background color in darkmode

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/settings/settings.tsx
> Frontend updating settings

- frontends/web/src/api/account.ts
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/add/add.tsx
Here, we're converting `add.tsx` into a functional component.
> frontend: convert AddAccount to functional

- frontends/web/src/components/rates/rates.tsx
And associated backend handler.
> frontend: remove unused reinitializeAccounts() backend API function

- frontends/web/src/api/account.ts
- frontends/web/src/routes/device/components/skipfortesting.tsx
- frontends/web/src/routes/device/waiting.tsx
Converting SkipForTesting to functional component.
> frontend: convert `SkipForTesting` to functional

- frontends/web/src/routes/buy/moonpay.tsx
So that is displays correct light and dark mode.
> frontend: pass theme to moonpay widget

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/new-settings/about.tsx
- frontends/web/src/routes/new-settings/appearance.tsx
- frontends/web/src/routes/new-settings/components/about/app-version-setting.module.css
- frontends/web/src/routes/new-settings/components/about/app-version-setting.tsx
- frontends/web/src/routes/new-settings/components/settingsItem/settingsItem.tsx
- frontends/web/src/routes/new-settings/components/tabs.tsx
- frontends/web/src/routes/router.tsx
Preview (Desktop):
Preview (Mobile):
> frontend: created About page for the new settings page

- frontends/web/src/components/update/update.tsx
To test this change `semver.NewSemVer` in `backend/update.go` to a lower semver number and restart servewallet.
> frontend: refactored update component without load hoc

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
- frontends/web/src/routes/device/bitbox02/setup/name.tsx
- frontends/web/src/routes/device/bitbox02/setup/password.tsx
- frontends/web/src/routes/device/bitbox02/setup/sdcard.tsx
- frontends/web/src/routes/device/bitbox02/setup/wait.tsx
- frontends/web/src/routes/device/bitbox02/setup/wallet-create.tsx
- frontends/web/src/routes/device/bitbox02/setup/wallet-restore.tsx
This includes fixed up https://github.com/digitalbitbox/bitbox-wallet-app/pull/2120
> frontend: refactor create wallet and restore backup

- frontends/web/src/locales/en/app.json
I did a locize pull before a locize push in 8dbaab3ac, accidentally removing keys.
> frontend: re-add deleted locize keys

- frontends/web/src/api/bitbox02.ts
- frontends/web/src/components/devices/bitbox02bootloader/toggleshowfirmwarehash.tsx
- use typed api
- removed unnecessary div
> frontend: refactor show-firmware-hash component

- frontends/web/src/routes/new-settings/advanced-settings.tsx
- frontends/web/src/routes/new-settings/components/advanced-settings/enable-coin-control-setting.tsx
> Frontend: coin control setting item in new settings

- CHANGELOG.md
- frontends/web/src/components/layout/grid.module.css
- frontends/web/src/components/layout/grid.tsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
- frontends/web/src/routes/device/bitbox02/setup/checklist.tsx
- frontends/web/src/routes/device/bitbox02/setup/choose.module.css
- frontends/web/src/routes/device/bitbox02/setup/choose.tsx
- frontends/web/src/routes/device/bitbox02/setup/name.tsx
- frontends/web/src/routes/device/bitbox02/setup/wait.tsx
- frontends/web/src/routes/device/bitbox02/setup/wallet-create.tsx
- frontends/web/src/style/base.css
- frontends/web/src/style/forms.css
and added support for skip microSD card and 12 words config.
> Frontend: create wallet with advanced backup options

- CHANGELOG.md
- backend/update.go
- frontends/android/BitBoxApp/app/build.gradle
- frontends/qt/Makefile
- frontends/qt/resources/MacOS/Info.plist
- frontends/qt/setup.nsi
Fixed changelog typo and also added Czech translation (Added in
b162aadcc).
> backend: update to version 4.38.0

- frontends/web/src/routes/settings/manage-accounts.tsx
was removed accidentally in [`d34225120743648...`](https://github.com/digitalbitbox/bitbox-wallet-app/commit/d34225120743648f5ae25d943e52c12f5a6fef67)
[Preview]:
> frontend: added missing guide in manage account

- CHANGELOG.md
Was introduced in bc0c448593df9d1b8c455d62bd41c0cc8c6ed9f4
> CHANGELOG: mention notes in coin control feature

- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/account/summary/balancerow.tsx
- frontends/web/src/routes/account/summary/subtotalrow.tsx
- frontends/web/src/routes/account/summary/summarybalance.tsx
- frontends/web/src/routes/router.tsx
* Refactor AccountsSummary into functional component
* move the rendering part into a dedicated component to increase readability and modularity
* add sd-card check that was previously missing
I had to change a bit the functions declaration order in the file because of hook dependencies, sorry for that making the review a bit more complicated :pray:
> frontend/accountsummary.tsx: refactor into functional component and add sd-card check

- frontends/web/src/components/forms/input.module.css
- frontends/web/src/routes/account/send/components/dialogs/confirm-wait-dialog.tsx
- frontends/web/src/routes/account/send/feetargets.module.css
- frontends/web/src/routes/account/send/send-guide.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/account/send/types.ts
An effort to modularise `send.tsx`. This PR consists of:
1. created ConfirmWaitDialog component
2. using GuidedContent and View for send screen
3. created separate guide component for send screen
> frontend: modularise `send` screen (pt 1)

- frontends/web/src/routes/account/send/components/dialogs/message-wait-dialog.tsx
- frontends/web/src/routes/account/send/send-guide.tsx
- frontends/web/src/routes/account/send/send.tsx
Created and used MessageWaitDialog for send screen as a part of the `send.tsx` refactoring effort (#2190).
> frontend: created and used MessageWaitDialog for send screen

- frontends/web/src/api/banners.ts
- frontends/web/src/components/banner/banner.tsx
This probably could use useSync hook, but keeping it simple first.
The banner is shown but there is a subscription which I am not sure how to test.
> Frontend refactor banner

- frontends/web/src/routes/account/send/components/dialogs/scan-qr-dialog.tsx
- frontends/web/src/routes/account/send/components/inputs/receiver-address-input.tsx
- frontends/web/src/routes/account/send/send.tsx
as a part of the refactoring effort of `send.tsx`, we're creating a new component ReceiverAddressInput as its own component to be used in the send screen.
> created ReceiverAddressInput component for `send`

- frontends/web/src/hooks/qrcodescanner.test.ts
- frontends/web/src/hooks/qrcodescanner.ts
- frontends/web/src/routes/account/send/components/inputs/receiver-address-input.tsx
To make lazy loaded QR code scanner more reusable, we can create a hook for it.
> frontend: created and used lazy loaded qrcode scanner hook

- frontends/web/src/routes/account/send/components/inputs/coin-input.tsx
- frontends/web/src/routes/account/send/components/inputs/receiver-address-input.tsx
- frontends/web/src/routes/account/send/send.tsx
as a part of the refactoring effort of `send.tsx`, we're creating a new component CoinInput as its own component to be used in the send screen.
> frontend: created CoinInput for send screen

- frontends/web/src/api/system.ts
- frontends/web/src/app.tsx
Converting api post call to trigger native os notification.
> frontend: type notify user

- frontends/web/src/routes/account/info/info.module.css
- frontends/web/src/routes/account/info/signingconfiguration.tsx
- frontends/web/src/style/forms.css
In HTML nesting DIV in P elements is actually invalid and prints
the following warnign:
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
Fixed by using DIV element for entries.
also removed unused CSS styles
> Frontend fix nesting error

- frontends/web/src/api/backend.ts
- frontends/web/src/api/transactions.ts
- frontends/web/src/app.tsx
This types the subscription to listen for incoming transactions.
It is used to trigger native OS notification, test with Qt app.
> frontend: type newtxs subscription api

- frontends/web/src/hooks/qrcodescanner.ts
The useQRScanner will execute its useEffect multiple times. This caused the await this.$video.play(); from the qr-scanner library to be interrupted (unresolved). This refactor synchronizes the cleanup to execute only when the promise is resolved.
The QR-Scanner was broken for me on Linux, it would only work the first time after granting camera access but not after that when trying to open it again. It seems like there were multiple calls to the `scanner.start()` function before the promise was resolved, the cleanup also did not wait for the promise to resolve.
I'm not sure if this fix makes sense since the `scanner.start()` function can still be called multiple times, I think forcing the cleanup function of the hook to wait until it is resolved synchronizes it which achieves the desired …
> frontend: refactor qrcodescanner to sync. cleanup

- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
Commit 3b62772 introduced a base url to be used in external requests to comply with Moonpay frame-ancestors content security policy. It somehow broke the update of the android webview location and made impossible to block external requests on the base of the page that originated them.
This commit implements a workaround that updates the location after navigation related events and blocks unexpected requests as already done in Qt.
Please note:
- I'm opening this PR towards staging-walletconnect since it will probably be soon merged into master. This way we avoid being forced to merge master into that branch before and then adding the rules to allow the external requests for dapps.
- Reverting commit 3b62772 solves the navigation issue in a cleaner way, but I could not find a solution to …
> frontend/android: block unexpected external requests

- frontends/web/src/api/system.ts
- frontends/web/src/components/anchor/anchor.tsx
- frontends/web/src/routes/settings/components/about/app-version-setting.tsx
> frontend: type system open api

- CHANGELOG.md
> CHANGELOG: add Android screen lock feature

- frontends/web/package-lock.json
ran:
rm package-lock.json
rm -rf node_modules
npm i --ignore-scripts
> frontend: update npm deps

- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/account/summary/chart.module.css
- refactored to using View component
- removed fullscreen chart hack and added simpler scrolling prevention
> frontend: improve account-summary

- frontends/web/src/routes/settings/components/manage-accounts/watchonlySettings.module.css
- frontends/web/src/routes/settings/manage-accounts.module.css
- frontends/web/src/routes/settings/manage-accounts.tsx
So the user can see which wallet is connected.
> frontend: show which wallet is connected on manage-accounts

- frontends/web/src/routes/bitsurance/bitsurance.tsx
- frontends/web/src/routes/bitsurance/dashboard.tsx
Fixes a glitch on bitsurance landing page during redirect towards dashboard and improves dashboard lazy loading.
> frontend/bitsurance: fix loading glitches on landing page and dashboard

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/settings/manage-accounts.tsx
Fixes label text of enable/disable account toggle.
> frontend: fix enable account toggle label text

- frontends/web/package-lock.json
- frontends/web/package.json
- frontends/web/src/routes/account/summary/chart.tsx
See https://tradingview.github.io/lightweight-charts/docs/migrations/from-v3-to-v4
> frontend: upgrade lightweight-charts to 4.x

- backend/devices/bitbox02/handlers/handlers.go
- frontends/web/src/api/bitbox02.ts
To invoke the BIP-85 workflow on the device (only available from v9.16.0).
> backend/bitbox02: add /invoke-bip85 handler

- backend/coins/btc/account.go
Bitsurance contract only covers funds on native segwit addresses. We already hide non-segwit addresses from the receive screen, and now we also hide non-segwit xpubs from the account info page.
> backend/account: hide non-segwit xpubs for insured accounts

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/bitsurance/dashboard.tsx
- frontends/web/src/routes/bitsurance/guide.tsx
This should answer the most common questions about Bitsurance.
> frontend: add bitsurance guide

- frontends/web/src/routes/account/account.tsx
Just small fix, as we already use /redirects/ on the website
> frontend: update the bitsurance guide links

- frontends/web/src/components/groupedaccountselector/groupedaccountselector.tsx
[Preview]:
https://github.com/digitalbitbox/bitbox-wallet-app/assets/28676406/4eee56f5-09e8-4eed-ba87-f2b72150a419
> frontend: fix preselcted account on buy page's account dropdown

- .github/workflows/ci.yml
- .golangci.yml
- Makefile
- README.md
- appveyor.yml
- backend/aopp_test.go
- backend/coins/btc/db/headersdb/headersdb_test.go
- docs/BUILD.md
- scripts/docker_install.sh
- scripts/github-ci.sh
- scripts/osx-brew.sh
Disable some useless/annoying linters.
> ci: update golangci to 1.55.2

- frontends/web/src/components/transactions/transaction.tsx
builds on https://github.com/digitalbitbox/bitbox-wallet-app/pull/2546
> Frontend refactor transaction

- frontends/web/src/app.tsx
- frontends/web/src/contexts/providers.tsx
Grouping all providers in a single component so that app component does need to be updated everytime a new provider gets added.
> frontend: group all providers in a dedicated component

- frontends/web/src/app.tsx
- frontends/web/src/components/language/language.test.tsx
- frontends/web/src/components/transactions/transaction.tsx
- frontends/web/src/contexts/providers.tsx
- frontends/web/src/utils/language.ts
There was a small conflict in `frontends/web/src/app.tsx`
> master > staging (merged)

- backend/backend.go
- backend/lightning/lightning.go
- backend/util/util.go
Based on #2566
@benma with this solution we'll fetch the credentials each time the app starts. Should we cache them for better privacy?
> Fetch breez and greenlight credentials 

- frontends/web/src/components/copy/Copy.tsx
- frontends/web/src/components/qrcode/qrcode.tsx
- frontends/web/src/routes/lightning/receive/receive.module.css
- frontends/web/src/routes/lightning/receive/receive.tsx
LN invoice copy button wasn't working on Qt, this fixes it.
co-authored: thisconnect
> frontend/lightning: fix invoice copy button

- frontends/web/src/locales/en/app.json
Manually ran:
npx locize-cli format ./frontends/web/src/locales --format json
> frontend: fixed weblint by sorting locales 

- .github/workflows/ci.yml
- CHANGELOG.md
- backend/exchanges/moonpay.go
- frontends/android/BitBoxApp/app/build.gradle
- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
- frontends/android/BitBoxApp/build.gradle
- frontends/android/BitBoxApp/gradle/wrapper/gradle-wrapper.properties
- scripts/docker_install.sh
- scripts/github-ci.sh
The link to upload KYC documents on moonpay wasn't working for Android.
The modification required a new `androidx.activity` dependency and to bump gradle, CompileSdk and some related stuff (details in the commit msgs)
> fix uploading KYC docs for moonpay 

- frontends/web/src/routes/account/summary/chart.tsx
Sometimes the chart did not resize properly, leaving half of the
area empty.
Removed setTimeout hack and just call chart.timeScale().fitContent()
seem to fix this.
> frontend: fix resizing chart

- backend/mobileserver/Makefile
I just tried building with gomobile using modules+vendoring and it still didn't work. Added a relevant issue.
> backend/mobileserver: add another GH issue in comment

- backend/lightning/dto.go
- backend/lightning/handlers.go
- backend/lightning/request.go
- backend/lightning/response.go
- backend/lightning/util.go
- frontends/web/src/api/lightning.ts
- frontends/web/src/routes/lightning/receive/receive.tsx
- go.mod
- go.sum
- vendor/github.com/breez/breez-sdk-go/breez_sdk/breez_sdk.go
- vendor/modules.txt
**SDK v0.3.6:** This update fixes various VLS signer issues updating to v0.11, mitigates connectivity issues to Greenlight at startup and improves GRPC connection performance to chain and breez services
**SDK v0.3.8:** This update bypasses the Greenlight signer loop initialization and lowers the TCP keepalive
> Update Breez SDK to v0.3.8

- frontends/web/src/i18n/config.ts
The api calls used in i18n/config.ts are already available.
> frontend: use typed apis

- backend/accounts.go
- backend/accounts_test.go
- backend/chart.go
- backend/config/lightning.go
This commit fixes calculation of totals in my portfolio when the lightning wallet is active.
> backend: add lightning balance to total balance

- frontends/web/src/assets/icons/wallet-light.svg
- frontends/web/src/components/sidebar/sidebar.module.css
- frontends/web/src/components/sidebar/sidebar.tsx
- frontends/web/src/routes/device/components/skipfortesting.tsx
Before the unlock button was an unstyles button.
With this the button is styled like other sidebar items.
Had to include parent stylesheet from sidebar.
> frontend: style unlock software keystore for testing

- frontends/web/src/routes/device/bitbox02/passphrase.tsx
~~The first commit is only concerned with refactoring from class to function based component and not improving the code. The second commit refactors the whole file to be better/cleaner.~~
~~We can either squash them, or if you think the second commit is too much, we can drop the second and improve the first.~~
Refactor the `Passphrase` component from a react class component to a functional one. The refactor does not try to improve the code much, only to _convert_ class to functional component.
I will open a second PR after this with improvements.
> Refactor functional passphrase

- frontends/web/src/routes/device/bitbox02/passphrase.tsx
This is a followup on #2713 that refactors the component to be more concise, and easier to understand/maintain.
- Set passphraseEnabled to decide whether to display the disable or the enable wizard.
- When one wizard is rendered it knows the status of the passphraseEnabled. Also the disable wizard does not need to know about the steps. The enable wizard knows where to start end stop and can manage that state on its own.
- SetPassphrase is more explicit and less error prone than toggling it.
- Remove unnecessary API request after receiving a successful response after setting the passphrase on the device.
- Remove some code duplication when rendering steps
> frontend: refactor passphrase.tsx

- .github/workflows/ci.yml
Updated all GitHub Actions. Solved all workflow deprecation warnings.
> chore: update github-actions

- .github/dependabot.yml
Hi, 
I've added [dependabot](https://github.com/dependabot). I recommend to activate it, so automated (security) updates are performed. I started with updates for `github-actions` and `gomod`. You can add more components ([package-ecosystems](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem)). You can activate dependabot in the [Code security and analysis section](https://github.com/BitBoxSwiss/bitbox-wallet-app/settings/security_analysis).
For more information see the [Dependabot quickstart guide](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide).
> feat: added dependabot

- CHANGELOG.md
- backend/update.go
- frontends/android/BitBoxApp/app/build.gradle
- frontends/qt/Makefile
- frontends/qt/resources/MacOS/Info.plist
- frontends/qt/setup.nsi
I rebased the release branch onto master and cleaned up the commits.
> Merge back 4.42.1 changes to master

- backend/handlers/handlers.go
- frontends/web/src/api/account.ts
- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/account/summary/coinbalance.tsx
The backend now returns a slice of coin balances including coin names and correct sorting, removing the need to fetch account data on the frontend.
> backend/coin balance: refactor total coin balance calculation

- frontends/web/src/components/sidebar/sidebar.tsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/info/buyReceiveCTA.tsx
- frontends/web/src/routes/accounts/select-receive.tsx
- frontends/web/src/routes/buy/exchange.tsx
Same as https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/2783 but to release branch
cc @benma
> frontend: improve bitcoin or crypto in translations

- CHANGELOG.md
> CHANGELOG: add BitBox02 v9.19.0 firmware

- frontends/web/src/components/terms/moonpay-terms.tsx
- frontends/web/src/locales/en/app.json
as https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/2792
> Frontend translation update iii 4release

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/lightning/activate.tsx
- frontends/web/src/routes/lightning/deactivate.tsx
- frontends/web/src/routes/lightning/receive/receive.tsx
This fixes a bug that sometimes showed a qr placeholder instead of
a real code. This happened if the user edited an invoice and changed
amount to invalid amount for example empty amount.
Also added new invoice button on invoice created and success step
and slightly changed the layout to better fit on mobile screen.
> frontend: improve lighting receive workflow

- frontends/web/.eslintrc.json
- frontends/web/vite.config.mjs
This should error if some deps are missing when using useEffect.
> frontend: error on react hook exhaustive deps

- frontends/web/src/components/backbutton/backbutton.tsx
- frontends/web/src/components/forms/button.tsx
- frontends/web/src/components/transactions/components/details.tsx
- frontends/web/src/routes/account/add/add.tsx
- frontends/web/src/routes/account/info/info.tsx
- frontends/web/src/routes/account/receive/receive-bb01.tsx
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/account/send/services.test.ts
- frontends/web/src/routes/account/send/services.ts
- frontends/web/src/routes/account/walletconnect/components/connect-form/connect-form.tsx
- frontends/web/src/routes/account/walletconnect/connect.tsx
- frontends/web/src/routes/buy/exchange.tsx
- frontends/web/src/routes/device/bitbox02/sdcardcheck.tsx
- frontends/web/src/routes/device/manage-backups/manage-backups.tsx
- frontends/web/src/routes/settings/components/mobile-header.module.css
- frontends/web/src/routes/settings/components/mobile-header.tsx
- frontends/web/src/routes/settings/electrum.tsx
Back buttons should not add new history entries and behave same
as native back buttons by going one step back in history.
also: added functional back button component for send view class component
> frontend: use navigate -1 for back buttons

- frontends/android/BitBoxApp/app/build.gradle
Required by Google Play by end of August 2024.
> frontend/android: update targetSdkVersion to 34

- frontends/web/src/components/keystoreconnectprompt.tsx
- frontends/web/src/routes/account/receive/receive.tsx
- cancel keystore prompt on back
- block back button while verifying receive address
> frontend: back behavior

- frontends/ios/BitBoxApp/BitBoxApp/BitBoxAppApp.swift
> ios: fix build

- backend/devices/bitbox02/handlers/handlers.go
It was never used. We will also remove the functionality from the BitBox firmware.
> backend/bitbo02: remove unused remove sdcard code

- frontends/ios/BitBoxApp/BitBoxApp.xcodeproj/project.pbxproj
- frontends/ios/BitBoxApp/Config.xcconfig
See https://developer.apple.com/documentation/xcode/adding-a-build-configuration-file-to-your-project.
> ios: centralize and set version data

- frontends/ios/BitBoxApp/BitBoxApp/Info.plist
- frontends/ios/BitBoxApp/BitBoxApp/WebView.swift
> ios: allow app to access camera

- frontends/web/src/api/account.ts
- frontends/web/src/components/transactions/components/arrow.tsx
- frontends/web/src/components/transactions/components/details.tsx
- frontends/web/src/components/transactions/components/status.tsx
cherry picked some commits from https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/2936
> Frontend fix types

- frontends/web/src/components/balance/balance.module.css
- frontends/web/src/components/balance/balance.tsx
- frontends/web/src/routes/account/account.module.css
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/style/layout.css
cherry picked some commits from https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/2936
> Frontend update account header

- docs/i18n.md
Clarify that **only** `en` keys should be added, removed or changed.
ref: https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/2910#issuecomment-2349689642
> docs/i18n: add more details on add/remove keys

- frontends/web/src/components/title/subtitle.module.css
- frontends/web/src/routes/account/account.module.css
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/info/buyReceiveCTA.tsx
- fixes a regression when no transaction message shown
- improves layout of empty transaction message
- fixes action buttons spacing on mobile
> Forntend account improvements

- frontends/web/src/components/balance/balance.module.css
- frontends/web/src/components/rates/rates.module.css
- frontends/web/src/routes/account/account.module.css
- frontends/web/src/routes/account/account.tsx
With this the font-size of the total coin and currency unit slightly increases. Proportional to the larger total amount font-size.
> frontend: move total balance into viewheader

- frontends/web/src/routes/account/send/components/inputs/note-input.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/account/send/services.ts
cherry-picked from https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/2966
> Frontend cleanup send

- frontends/android/BitBoxApp/build.gradle
- frontends/android/BitBoxApp/gradle/wrapper/gradle-wrapper.properties
Done using Android Studio upgrade assistant.
> frontend/android: upgrade gradle to 8.8.0

- frontends/web/src/routes/exchange/btcdirect.tsx
This fixes the broken copy button in the bank transfer page.
> frontend/btcdirect: enable write clipboard for iframe integration

- frontends/web/src/app.tsx
- frontends/web/src/components/sidebar/sidebar.tsx
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
- frontends/web/src/routes/device/deviceswitch.tsx
- frontends/web/src/routes/router.tsx
- frontends/web/src/routes/settings/about.tsx
- frontends/web/src/routes/settings/advanced-settings.tsx
- frontends/web/src/routes/settings/bb02-settings.tsx
- frontends/web/src/routes/settings/components/tabs.tsx
- frontends/web/src/routes/settings/general.tsx
- frontends/web/src/routes/settings/manage-accounts.tsx
- frontends/web/src/routes/settings/mobile-settings.tsx
- frontends/web/src/routes/settings/types.ts
Before, it was also called on BitBox01 resulting in an error. It will
also might work with future BitBoxes just like that.
> frontend/settings: check version only for BitBox02

- frontends/web/src/components/actionable-item/actionable-item.module.css
- frontends/web/src/components/actionable-item/actionable-item.tsx
- frontends/web/src/routes/exchange/components/exchange-provider.module.css
Actionable item component should set correct color even if it is internally a button and allow for text only children.
> frontend: update actionable-item styling

- frontends/web/src/components/amount/amount.module.css
- frontends/web/src/components/amount/amount.tsx
- frontends/web/src/components/amount/conversion-amount.module.css
- frontends/web/src/components/transactions/transaction.module.css
- frontends/web/src/components/transactions/transaction.tsx
- fixes breaking unit (U S D) onto multiple newlines on small screen 
- unit should be gray and smaller regression
- hide plus minus sign if amount is not yet known
- fix long amounts on small screens
> frontend fix transactions

- frontends/web/src/routes/account/account.tsx
Before the status is loaded, we returned null, causing a flicker when changing accounts, even for static elements.
We can simply proceed with rendering and handle all elements that depend on `status` conditionally to avoid the flicker.
> frontend/account: remove flicker

- backend/coins/btc/headers/headers.go
Use the built-in max/min from the standard library in Go 1.21 to simplify the code.  https://pkg.go.dev/builtin@go1.21.0#max
> refactor: use the built-in max/min to simplify the code

- frontends/web/src/routes/account/send/components/inputs/receiver-address-input.tsx
> frontend: fix send to self for non-BTC accounts.

- backend/coins/btc/transaction.go
- backend/coins/btc/transaction_test.go
> tests: add tests for account.pickChangeAddress

- frontends/web/public/btcdirect/coin-to-fiat.html
- frontends/web/src/api/exchanges.ts
- frontends/web/src/routes/exchange/btcdirect.tsx
- frontends/web/src/routes/exchange/components/buysell.tsx
- frontends/web/src/routes/router.tsx
This adds an initial BTC Direct sell workflow proof of concept.
> frontend: btcdirect sell workflow poc

- backend/coins/btc/maketx/txsize_internal_test.go
remove duplicate package imports
> chore: remove duplicate package imports

- backend/accounts/account.go
- backend/accounts/mocks/account.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/btc/transaction.go
- backend/coins/eth/account.go
- frontends/web/src/api/account.ts
> backend: return transaction's ID from SendTx API.

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/bitbox01/bitbox01.module.css
- frontends/web/src/routes/device/waiting.module.css
- frontends/web/src/routes/device/waiting.tsx
The reason for the generic first line is because we had the BB01 when
this text was made. Now that the BB01 has been EOL for a long time,
we don't need to consider it and just focus on current products.
> Frontend update welcome message

- frontends/web/public/btcdirect/coin-to-fiat.html
- frontends/web/src/routes/exchange/btcdirect.tsx
- update btcdirect sell order with transaction-id
- cancel btcdirect sell order
> Frontend update sell order

- backend/devices/bitbox02/keystore_simulator_test.go
> backend/test: fix soft merge conflict

- frontends/ios/BitBoxApp/BitBoxApp/Bluetooth.swift
This lowers the time to flash to 1m45s
~~Needs a new ble firmware that handles up to 320 bytes per ble write and also a new `bitbox02-api-go` that attempts to write more packets simultaneously.~~
edit: the required firmware is in the staging/ble branch. This PR has been rebased with new `bitbox02-api-go`.
> ble: Add support for larger ble packets

- CHANGELOG.md
- backend/exchanges/btcdirect.go
- frontends/web/src/components/terms/btcdirect-terms.tsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/exchange/components/buysell.tsx
- frontends/web/src/routes/exchange/components/infocontent.tsx
- frontends/web/src/routes/exchange/exchange.tsx
update btcdirect terms for selling
> update BTC Direct terms for selling

- frontends/ios/BitBoxApp/BitBoxApp/BitBoxAppApp.swift
- frontends/ios/BitBoxApp/BitBoxApp/Info.plist
Note: this has been tested only on XCode simulator: testing on an actual device would be much appreciated!
> ios: add support for AOPP links

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/waiting.tsx
BitBo01 has been EOL for 5+ years
> frontend: remove bb01 not recognized guide in waiting view

- frontends/web/src/routes/exchange/btcdirect.tsx
- frontends/web/src/routes/exchange/iframe.module.css
Block the UI when there is a signing request so that the user cannot navigate when there is a signing request on the device.
> frontend: block ui during address verification

- backend/exchanges/btcdirect.go
- backend/handlers/handlers.go
- frontends/web/src/api/exchanges.ts
Btcdirect info for sell action was mocked up in the fronted. this implements it in the backend.
> backend/btcdirect: implement info endpoint for sell action

- backend/devices/bitbox02/keystore_simulator_test.go
- backend/devices/bitbox02/testdata/simulators.json
The test didn't check again for the hashes after downloading the file, so we add a further check.
> tests: fix hash mismatch check in simulator tests.

- .github/workflows/ci.yml
- frontends/qt/Makefile
- scripts/github-ci.sh
> chore: switch from GHCR to Docker for CI.

- backend/accounts.go
- backend/accounts_test.go
- backend/backend.go
- backend/coins/coin/amount.go
- backend/coins/coin/conversions.go
- backend/handlers/handlers.go
- frontends/web/src/api/account.ts
- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/account/summary/chart.tsx
- frontends/web/src/routes/account/summary/coinbalance.tsx
- frontends/web/src/routes/account/summary/keystorebalance.tsx
The code needed to load the accounts summary table was complicated and fragmented. This refactors some parts of the code, unifying some endpoints and adding unit tests.
> backend/accounts: refactor accounts summary endpoint and functions

- backend/backend.go
- backend/coins/eth/blockbook/blockbook.go
Note that this is targeting a staging branch; there are a few TODOs left that will be fixed before opening a PR against master.
This first implementation adds a wrapper and the call to `Balance` in blockbook. Tested by comparing the returned balance on `master` and here (and added a log line to make sure that the balance is indeed returned by Blockbook.
> backend: add blockbook/etherscan wrapper.

- CHANGELOG.md
- backend/devices/usb/hid.go
- go.mod
- go.sum
- vendor/github.com/BitBoxSwiss/bitbox02-api-go/communication/u2fhid/hiddevice.go
- vendor/modules.txt
> backend/usb: fix potential macOS communication issue with BitBox02

- .github/workflows/ci.yml
> ci: Add shortlog with every artifact message

- frontends/web/eslint.config.mjs
- frontends/web/src/utils/walletconnect.ts
Disallow reassigning function parameters
- https://eslint.org/docs/latest/rules/no-param-reassign
> frontend: enable no-param-reassign eslint rule

- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/BitBoxWebChromeClient.java
- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/BitBoxWebViewClient.java
- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/GoViewModel.java
- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
Refactor GoViewModel and a first refactor of MainActivity. See commit messages for details :innocent:
> Android refactor

- backend/accounts/baseaccount.go
This fixes a test failure (data race) that might have escaped before: I'm not able to repro it if running `make ci` inside the `dockerdev`, nor it happens in github CI. However, it happens 100% of the times if ran locally on my machine:
```
WARNING: DATA RACE
Write at 0x00c0003cf2e0 by goroutine 50:
github.com/BitBoxSwiss/bitbox-wallet-app/backend/accounts.(*BaseAccount).SetOffline()
/Users/bznein/Documents/bznein/bitbox-wallet-app/backend/accounts/baseaccount.go:143 +0x1ac7
github.com/BitBoxSwiss/bitbox-wallet-app/backend/coins/eth.(*Updater).UpdateBalances()
/Users/bznein/Documents/bznein/bitbox-wallet-app/backend/coins/eth/updater.go:182 +0x1a9d
github.com/BitBoxSwiss/bitbox-wallet-app/backend.(*Backend).updateETHAccounts()
/Users/bznein/Documents/bznein/bitbox-wallet-app/backend/backen …
```
> backend: fix data race.

- CHANGELOG.md
- frontends/web/src/components/dropdown/dropdown.module.css
- frontends/web/src/routes/account/send/feetargets.module.css
- frontends/web/src/routes/account/send/feetargets.test.tsx
- frontends/web/src/routes/account/send/feetargets.tsx
The native select dropdown sometimes renders with buggy visual effect on windows.
Fixed by changing to dropdown component which is a wrapper around react-select lib and doesn't ues native select element.
> frontend: use dropdown component in feetargets

- backend/market/bitrefill.go
- backend/market/market.go
Updated the list of regions where Bitrefill offers their products.
> backend: update bitrefill regions

- backend/exchanges/btcdirect.go
- backend/handlers/handlers.go
- frontends/web/public/btcdirect/coin-to-fiat.html
- frontends/web/src/api/exchanges.ts
- frontends/web/src/routes/exchange/btcdirect.tsx
> Fetch BTC Direct sell addresses from the widget instead of hardcoding in the backend

- CHANGELOG.md
- backend/backend.go
- backend/coins/btc/maketx/maketx_test.go
- backend/devices/bitbox02/keystore_simulator_test.go
- frontends/web/src/routes/account/utils.test.ts
mempool.space is considered one of the best Bitcoin explorers and the preferred choice of many. The app already uses mempool.space for fee estimations.
> backend: change block explorer to mempool.space
