frontends/web/src/locales/en/app.json
frontends/web/src/routes/buy/exchange.tsx

Region selection in exchange page was mandatory in order to proceed with the buy workflow. This allows the user to explicitly avoid specifying the region.

frontend/exchange: make exchange region selection optional

---

backend/accounts/errors/errors.go
backend/coins/eth/account.go
backend/coins/eth/account_test.go

A race condition between the `Initialize()` and `TxProposal()` methods was causing a deadlock where they were blocking each other in accessing `account.Synchronizer` and `account.updateLock`. This recently caused CI tests to timeout and fail from time to time.
This changes the behavior of `newTx()`, which is called by `TxProposal()`, making it returning an errror instead of waiting when the account is not yet synced. This should fix the race condition.

backend/eth/account: fix race condition on tx-proposal

---

frontends/web/src/routes/buy/exchange.module.css

To match our app's styling and to maintain uniformity throughout our app's UI, we should remove the additional/custom css applied to the "back" and "next" button in the exchange page.
Also altered the buttons' container margin to match the previous page's  button (the "next"  button) spacing, for the same reason as the above.
Before:
After:

frontend: remove additional styling on buttons in exchange page

---

frontends/web/src/routes/device/bitbox02/bitbox02.tsx

Navigating to device settings triggered the sidebar to close, this was the reason that it looked like the whole app window flickered.
Forcing the sidebar to close on will mount is not necessary as it will open/close later depending on the device state.
Test on medium screen (when hamburger is visible)
- reset device
- navigate through app
- open app with unlocked BB
- plugin uninitialized BB on waiting screen or app settings
- other tests?

frontend: fix flickering sidebar when navigating to device settings

---

frontends/web/src/routes/device/bitbox02/bitbox02.tsx

In e34ddc8450fbb6596375ed5655bbbc4f84f1fa93 the attestation error was changed for debuggin purpose and accidentally commited. Changed back to show the warning if attestation fails

frontend: revert attestation warning regression

---

.github/workflows/ci.yml
.golangci.yml
Makefile
backend/accounts/account.go
backend/accounts/notifier.go
backend/accounts/transaction.go
backend/aopp.go
backend/coins/btc/account.go
backend/coins/btc/addresses/addresschain.go
backend/coins/btc/coin.go
backend/coins/coin/amount.go
backend/coins/coin/coin.go
backend/coins/eth/account.go
backend/coins/eth/coin.go
backend/coins/eth/rpcclient/rpcclient.go
backend/devices/bitbox/device.go
backend/handlers/handlers_test.go
backend/keystore/keystore.go
backend/rates/history.go
backend/rates/rates.go
backend/signing/configuration.go
scripts/travis-ci.sh
util/jsonp/jsonp.go
util/test/tcp.go

Upgrading `golanci-lint` to v1.50 showed several nits in the code. With this I updated the code where possible and skipped three new tests.

backend: comply with new golangci tests

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/device/bitbox02/bitbox02.tsx

The pairing code prompt does not give any information about why that
the user should confirm and has no visual feedback after confirming
on the device.
There are also unused and inconsistent pairing translations.
Changed:
- added new device detected sentence to unpaired message.
- change to previously unused pairing.unpaired translation to be
consistent with the other keys
- show a paired message after confirming on the device using unused
pairing.paired translation
- move attestation error before the pairing messages (this should
be the first information the user reads if it ever happens)

frontend: reword pairing code verification

---

docs/BUILD.md

We long moved to Ubuntu 18.04. Newer versions are of course also supported for Ubuntu and the other OSes.

docs/BUILD: update system requirements

---

backend/exchanges/exchanges.go
backend/exchanges/pocket.go
backend/exchanges/util.go

This fixes some lines developed on the staging-pocket branch, to comply with golangci-lint, that has been updated in the meantime.

backend/exchanges: fix to comply updated golangci-lint

---

frontends/web/src/components/spinner/Spinner.tsx
frontends/web/src/routes/account/account.tsx
frontends/web/src/routes/account/send/send.tsx
frontends/web/src/routes/buy/exchange.tsx
frontends/web/src/routes/buy/info.tsx
frontends/web/src/routes/device/bitbox01/restore.tsx
frontends/web/src/routes/device/bitbox01/settings/settings.jsx
frontends/web/src/routes/device/bitbox01/setup/initialize.tsx
frontends/web/src/routes/device/bitbox01/setup/seed-create-new.jsx
frontends/web/src/routes/device/bitbox01/setup/seed-restore.jsx
frontends/web/src/routes/device/bitbox01/unlock.jsx

To reduce ambiguity, we would like to manually pass `guideExists` prop to `<Spinner />` instead of relying totally on the `SharedProps` coming from the store (the `share` decorator).
The `guideExists` prop in the `<Spinner />` controls the render of the guide button when the `<Spinner />` component / view appears.

frontend: remove store decorator from `<Spinner/>`.

---

backend/devices/usb/hid.go

For unknown reasons, on macOS, there are intermittent errors during hid.Device.Write():
`IOHIDLibUserClient:0x100002065 setReport failed: 0xe00002bc` In the BitBoxApp, the issue appears most frequently in the loop polling the device for a API call status in query.go/rawQueryV7.
Running all calls in the same OS thread seems to resolve the issue, even though it is not clear why that is. Maybe something in the macOS SDK relies on thread-local variables, or there is a memory-bug that does not get triggered this way.
After a long time debugging this, I am still not sure what causes it, especially because it also happens in a test program without any goroutines of this sort:
`main() { for { C.hid_write(...); C.hid_read(...) }`.
The issue disappears however if there is a `runtime.Gosched()` in …

backend/usb: run all hidapi API calls in a dedicated OS thread

---

frontends/web/src/components/language/language.tsx

The language button didn't work in some views that have a form around the view.
regression introduced in 77fd86e40491d0af98578b2015f0fe194d609390
test:
1) create new wallet
2) on enter-name click on langauge button
3) invalid input
reason was that buttons by default are type submit, so if there is a form wrapping the whole view, clicking the button fires the onsubmit event that propagates all up the the form wrapping the view.

frontend: fix language button regression

---

frontends/web/src/components/view/view.module.css

Success icon is sometimes rendered too big, this seems to be a regression from View component refactoring.
Changed to limit the max size of large icons in the view component.

frontend: limit success icon min and max size

---

.golangci.yml

Some golanci-lint default tests are deprecated because unmantained. This update disables them:
- `varcheck`
- `structcheck`
- `deadcode`
Ref: https://github.com/golangci/golangci-lint/issues/1841

golanci-lint: disable deprecated tests

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/device/bitbox02/bitbox02.tsx

There was no exlpanation of why the microSD card should be inserted when creating a new wallet during the set wallet name step.
Moved step description next to the title followed by the warning and added minimal information about what the SD Card will be used for, i.e.  to create a backup of the wallet.

frontend: rephrase sd card warning when creating a new wallet

---

frontends/web/src/components/dialog/dialog.tsx

Currently dialog only checks on component did change if the prop is open, but ignores if the open prop is already set to true when the component mounts.
This was the reason why sdcard warning did not show when microSD card was missing on the manage-backups view.
Added on component did mount method that checks if the open prop is already set to true and if so calls this activate.
Changed the existing on props did update and removed setState, as this.activate will do setState anyway.

frontend: fix dialog open on mount

---

frontends/web/src/routes/buy/exchange.tsx

Back button in the country selector (`/buy/exchange/`) page doesn't work as expected when there's only one account. 
This is due to the back button is trying to go back to `/buy/info`, but that page redirects the user back to the `/buy/exchange/` page again. Therefore no "going back" action is actually happening for the user.
We fix this by going back 2 pages when there's only one account, and only going back once when there's more than one account. `useNavigate()` is utilised for this approach.

frontend: fix "back btn" behaviour on country selector (buy page).

---

frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java

Iframes integrated in the app have some external links that the user could click to open in an external browser. Before this, the view url were used to allow the links clicked in views inside the '/buy/ route. For unknown reasons this recently stopped working (the retrieved url was "about:blank"). Since it was not possible to retrive the view url in other ways, this just creates a list of allowed domains that can be pointed to.

android: fix unwanted blocking of iframe links

---

frontends/web/src/routes/device/bitbox02/gotostartupsettings.tsx
frontends/web/src/routes/device/bitbox02/settings.tsx

Here, we're converting `gotostartupsettings.tsx` into a functional component.

frontend: convert gotostartupsettings.tsx into a functional component

---

CHANGELOG.md
frontends/qt/main.cpp

Autoscaling was only enabled for windows, because with Qt < v5.14 it didn't look nice on Linux and Mac OS. Now that we are compiling with Qt v5.15 we can enable it on all OSs.

frontend/Qt: enable autoscaling for high density screens

---

frontends/web/src/components/aopp/verifyaddress.tsx

Here, we're converting `verifyaddress.tsx` into a functional component.

frontend: convert verifyaddress.tsx into a functional component

---

frontends/web/src/components/accountselector/accountselector.tsx
frontends/web/src/routes/account/info/buyReceiveCTA.tsx

1. Buy CTA for an empty account in the `/account/${code}` page redirects user straight into the country selector (`/buy/exchange/${code}`). We'd like it to redirect to the account selector first (`/buy/info/${code}`) so user will be able to see the account they selected. The selected account is displayed in a dropdown.
2. The said dropdown is also supposed to  display the selected account's  balance which gets fetched asyncly. The balance was fetched asyncly, but it's not yet displayed. This PR also fixes this bug; to actually display the fetched balance in the dropdown.
Preview for an empty account:
https://user-images.githubusercontent.com/28676406/223382842-aae6e8f5-e91d-4f19-95dd-5b8aa3b596ca.mov
Preview for a non-empty account: …

frontend: fix buy CTA redirect & balance loading (account dropdown)

---

frontends/web/src/components/settingsButton/settingsItem.tsx

Here, we're converting `settingsitem.tsx` into a functional component.

frontend: convert `settingsitem` into functional component

---

frontends/web/src/components/accountselector/accountselector.module.css

Hardcoded CSS values to display the account dropdown in dark mode. We added some new selectors in the css file, where previously weren't needed.
This is because most of react-select's default styles suit our light mode. However, it's not the case for dark mode. Thus, we need to grab ahold of more selectors to be customised for them to work with our dark mode (hence adding more selectors in the css).
Preview:

frontend: set dark mode colour scheme for account dropdown/selector

---

frontends/web/src/routes/buy/components/countryselect.module.css

The dropdown text previously has a dark colour. This is now changed to a light colour so it's visible (in the darkmode).
Preview (before):
Preview (after):

frontend: fix country dropdown search text colour

---

scripts/dockerdev.sh

`$container_name` was wrongly uppercase in the script, causing an error when running `make dockerdev` for the first time.

script/dockerdev: fix a bug in dockerdev script

---

frontends/web/src/components/dialog/dialog-legacy.module.css

As legacy dialog is still used in some parts of the app, we need
to use proper CSS variables for the component so its styling
will be appropriate for both dark and light mode.
(`<Confirm/>`) before:
after:

frontend: use CSS var for legacy dialog's background

---

frontends/web/src/components/accountselector/accountselector.module.css
frontends/web/src/style/variables.css

We need to use proper CSS variables for the component so its styling will be appropriate for both dark and light mode.
Before:
After:

frontend: use CSS variables for account selector

---

frontends/web/src/style/variables.css

`--color-disabled` should have different values depending on the theme (dark or light).
Previews
1. disabled toggle bgcolor:
2. buttons in the "connect your own full node" screen:

frontend: differ `--color-disabled` for lightmode and darkmode

---

frontends/web/src/routes/buy/components/countryselect.module.css

we need to use proper CSS variables for the component so its styling will be appropriate for both dark and light mode.
Before:
After:

frontend: use CSS variables country selector

---

CHANGELOG.md
backend/coins/btc/account.go
frontends/web/src/components/message/__snapshots__/message.test.tsx.snap
frontends/web/src/components/message/message.module.css
frontends/web/src/components/message/message.tsx
frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/send/feetargets.tsx

In case the fee estimations were missing for any reason (e.g. download too slow or some error), the send screen was unusable, as the transaction proposal could not be made due to missing fee. The error was not propagated to the user, and a transaction could not be made.
This patch enables custom fees as a fallback in that case, even if custom fees are otherwise disabled in the settings. It is not great (probably confusing for most users), but better than not being able to transact at all. Luckily this should not happen often - the only instance we know of so far has been with a user that used a custom Electrs node on a slow connection, going into the send screen immediately after sync.
Alternatives considered:
- try downloading the fee rates on the fly if they are missing. Didn't do this …

btc: enable custom fees w/ info text if fee targets are missing

---

frontends/qt/main.cpp

Darkmode did not work on linux/Windows/macOS as the `@media (prefers-color-scheme: light/dark)` seemed to be ignored. Defining this env var seems to fix it. I did not investigate further about why that is.

qt: fix @media prefers-color-scheme rule in Qt 5.15.2

---

CHANGELOG.md
backend/devices/usb/hid.go
backend/update.go
frontends/qt/setup.nsi

In a35e009b we forced all USB communication to happen in a single thread because macOS otherwise fails with obscure errors (see commit msg).
For simplicity we applied this to all platforms. At least on Windows, users ar experiencing issues where the BitBox02 would timeout during password entry. It is not clear why, but since this was the only change related to USB communication, we revert it for all platforms except macOS.

backend/usb: only force single thread on macOS

---

backend/coins/btc/electrum/client.go
backend/coins/btc/handlers/handlers.go

If there was any error, the user would see 'Response is unexpected (expected TX hash)' instead of the real error, which could be something different.

backend/btc: fix error propagation in TransactionBroadcast

---

frontends/web/src/routes/account/summary/chart.module.css

The chart filter buttons have custom CSS styling which didnt look correct on a new empty account summary view.
Kept lightmode as is and added custom darkmode styling for those buttons in disable state.

frontend: fix disabled filter buttons on empty summary

---

backend/accounts_test.go
backend/backend.go
backend/bridgecommon/bridgecommon.go
backend/bridgecommon/bridgecommon_test.go
backend/handlers/handlers.go
backend/handlers/handlers_test.go
cmd/servewallet/main.go
frontends/android/BitBoxApp/app/src/main/AndroidManifest.xml
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/GoViewModel.java
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
frontends/android/BitBoxApp/app/src/main/res/values-v23/styles.xml
frontends/android/BitBoxApp/app/src/main/res/values/colors.xml
frontends/android/BitBoxApp/app/src/main/res/values/styles.xml
frontends/android/goserver/goserver.go
frontends/qt/server/server.go
frontends/web/src/api/darktheme.ts
frontends/web/src/components/darkmode/darkmode.tsx

App style parent is changed to `Theme.AppCompat.DayNight.DarkActionBar` as this allows to automatically enable dark mode following system setting (e.g. when on power saving).

frontend/android: change App style to autoswitch darkmode

---

frontends/web/src/routes/buy/components/exchangeselectionradio.module.css

Our current implementation causing the outline of the `ExchangeSelectionRadio` to be overlapping with another radio component.
To fix this, we're modifying the radio when `:focus` to have `z-index: 2` and `position: relative`.

frontend: fix `ExchangeSelectionRadio`'s outline-overlap issue

---

.github/workflows/ci.yml

This is only for the CI base image. Our actual CI runs in a docker image that has an independent base image, which is stil 18.04.
This change is needed as GitHub deprecated ubuntu-18.04:
>  The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04 or ubuntu-22.04 (ubuntu-latest). For more details, see https://github.com/actions/runner-images/issues/6002

.github/workflows/ci.yml: update to ubuntu-22.04

---

frontends/web/src/app.tsx
frontends/web/src/components/darkmode/darkmode.tsx
frontends/web/src/components/darkmode/darkmodetoggle.tsx
frontends/web/src/components/icon/combined.tsx
frontends/web/src/components/view/view.tsx
frontends/web/src/contexts/DarkmodeContext.ts
frontends/web/src/contexts/DarkmodeProvider.tsx
frontends/web/src/routes/buy/components/exchangeselectionradio.tsx
frontends/web/src/routes/device/waiting.tsx

Using context for Darkmode allows us to get and set the darkmode state easier across component (globally). We used our own `useDarkmode` hook to wrap the dark mode context.
Keeping `getDarkmode()` as it's still required by class components.

frontend: use Context for Darkmode

---

frontends/web/src/routes/buy/components/countryselect.tsx

in 393344428732250e7066456a04b8d4a4cec82848 the useDarkmode hook changed, it now returns an object with isDarkMode and a function to toggle. This object was always truthy and so the globe always used light icon.

frontend: fix globe icon in lightmode

---

backend/handlers/handlers.go
frontends/web/src/api/coins.ts
frontends/web/src/routes/account/send/send.tsx

Parsing external BTC values (e.g. amount scanned through QR scanning feature) did not properly convert BTC values to sats in case sats mode was enabled. This fixes adding a backend endpoint that allows to parse an external BTC value, converting to sats if needed.

backend: fix external BTC value parsing when sats mode is enabled

---

frontends/web/src/routes/buy/components/exchangeselectionradio.module.css

Background should be white and border lightgray, was using wrong CSS variables.

frontend: fix exchange selection color in lightmode

---

frontends/web/src/components/layout/grid.module.css

The send and back button had no more spacing. CSS regression introduced in:
- 7e49d89fb8ed97184a756b11701c21c83128abe1
Reason: on older chrome versions (before 84) gap did not work with flexbox, gap only works with dislpay: grid. See also:
- https://developer.mozilla.org/en-US/docs/Web/CSS/gap

frontend: send button spacing css regression

---

backend/chart.go
frontends/web/src/api/account.ts
frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/summary/chart.module.css
frontends/web/src/routes/account/summary/chart.tsx

If one of the coin/rates pairs is older than 2hs the backend set the `chartIsUpToDate` flag to false inside the `account-summary` return struct. This adds a map to the struct that list the latest update timestamp for each coin. This will allow the frontend to show a meaningful message in the future instead of just keep loading the chart.

backend/chart: add latest rates timestamps in chart data

---

frontends/qt/server/detectdarktheme_darwin.go
frontends/qt/server/detectdarktheme_linux.go
frontends/qt/server/detectdarktheme_windows.go
frontends/qt/server/server.go

When starting the app and when toggling darkmode, a CMD window would pop up on Windows very quickly during the execution of `reg query ...`.

qt/windows: hide CMD window when queriyng for darkmode

---

frontends/web/src/api/bitbox02.ts
frontends/web/src/routes/device/bitbox02/reset.tsx
frontends/web/src/routes/device/bitbox02/settings.tsx

To follow the latest conventions and best practices of React, 
we'd like to convert our class components into functional ones.
Here, we're converting `reset.tsx` into a functional component.

frontend: convert `reset.tsx` into a functional component

---

frontends/web/src/components/view/view.tsx

Modified the App logo in the view component to dynamically switch between light and dark mode versions based on the current theme.

frontend: update bitboxapp logo to support darkmode

---

frontends/web/src/routes/buy/components/exchangeselectionradio.module.css
frontends/web/src/routes/buy/components/exchangeselectionradio.tsx

Long label after the bank/card icon broke weirdly to a new line in some languages. This change is not perfect but improves that the word break nicer when needed and not rightaway after the icon.

frontend: improve spacing of exchange radio

---

frontends/web/src/api/bitbox02.ts
frontends/web/src/locales/en/app.json
frontends/web/src/routes/device/bitbox02/bitbox02.tsx
frontends/web/src/routes/device/bitbox02/checkbackup.tsx
frontends/web/src/routes/device/bitbox02/createbackup.tsx
frontends/web/src/routes/device/bitbox02/passphrase.tsx
frontends/web/src/routes/device/bitbox02/setdevicename.tsx
frontends/web/src/routes/device/bitbox02/settings.tsx

api calls that throw if success is false, have few disadvantages:
- rejecting the promise on failed success mixes failed response with real errors, so catch gets either an error or a failed response
- data passed to promise reject cannot be typed
- throwing error in the api call must be caught, either try/catch or .catch else the whole script just stops with uncaught promise error
Refcatored api calls and removed the success handling, always resolving the promise now with response data.

frontend: refactor api calls should not throw on failed result

---

backend/accountcodes.go
backend/accounts.go
backend/accounts/baseaccount.go
backend/accounts/baseaccount_test.go
backend/accounts/types/code.go
backend/accounts/types/event.go
backend/accounts_test.go
backend/aopp.go
backend/aopp_test.go
backend/backend.go
backend/backend_test.go
backend/chart.go
backend/coins/btc/account.go
backend/coins/btc/account_test.go
backend/coins/btc/handlers/handlers.go
backend/coins/eth/account.go
backend/coins/eth/account_test.go
backend/config/accounts.go
backend/exchanges/pocket.go
backend/handlers/handlers.go
backend/notifier.go

accounts.AccountConfig and config.Account have lots of duplicate
fields. Code can be simplifed by reusing the latter in the former.

backend/accounts: de-duplicate account config fields

---

backend/coins/btc/account.go
backend/coins/btc/handlers/handlers.go
frontends/web/src/api/account.ts
frontends/web/src/components/transactions/transactions.tsx
frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/account.tsx
frontends/web/src/routes/buy/pocket.tsx

Fixes one panic TODO. All call sites deal with the error now. An error here is usually a database access for a database that was already closed (e.g. transactions endpoint called at the same time as a bitbox02 is unplugged or the account is closed for some other reason).

backend/btc: do not panic when retrieving transactions

---

backend/devices/bitbox02/handlers/handlers.go
frontends/web/src/api/bitbox02.ts
frontends/web/src/routes/device/bitbox02/bitbox02.tsx
frontends/web/src/routes/device/bitbox02/createbackup.tsx

This adds a parameter to the createBackup endpoint to choose the sdcard backup or the recovery words backup. This can be then used later to allow skipping the sdcard backup in favor of the recovery words backup in the BitBox02 setup wizard.
Since this feature is only possible since firmware v9.13.0, one must first check if `versionInfo.canBackupWithRecoveryWords` is true before using the recovery words method.

api/bitbox02: allow backups using recovery words, skipping sdcard

---

backend/accounts.go
backend/accounts_test.go
backend/backend.go
backend/backend_test.go

We have persisted accounts in accounts.json and load them into live
accounts.
We want the accounts sorted by coin, account number for the
frontend (sidebar, manage accounts). Until now we sorted the accounts
while loading them from accounts.json.
It is preferable to sort the accounts only when serving them to the
frontend - then we could easily modify the backend.accounts list on
the fly and add accounts without having to call `Reinitialize()`,
which closes all accounts and reloads all of them, just so that the
sorting is correct. When we add automatic accounts discovery, we don't
want to Reinitialize() repeatedly for every account that is found, but
just add it to the list.
The sorting function is now a bit more complicated because it needs to
also sort ETH with their ERC20 tokens …

backend: sort accounts in Accounts()

---

backend/accounts.go
backend/backend.go

Closing and rescanning all accounts is overkill.

backend: rename account without reinitializing all accounts

---

backend/accounts_test.go

Unit test broke as a result of a semantic merge conflict when merging 27a5da070f791c79ba67e8e170f0fe7f842c97d4 (conflict with ca8fa91dfd3c436b141804d8582d7a4f23277865).

backend: fix unit test

---

frontends/web/src/components/amount/amount.test.tsx
frontends/web/src/components/amount/amount.tsx

Current proposal: using spacing for BTC/LTC fractional part everywhere except for balance and chart, since the trailing zeroes are removed there (see pics).

Btc amount spacing

---

frontends/web/src/components/rates/rates.tsx
frontends/web/src/routes/new-settings/appearance.tsx
frontends/web/src/routes/new-settings/components/appearance/activeCurrenciesDropdownSetting.tsx
frontends/web/src/routes/new-settings/components/appearance/defaultCurrencyDropdownSetting.tsx

Previously, in the newly created appearance (`new-settings/appearance`) we could:
1. set a default currency that's not even in our active currencies list.
2. remove our default currency from our active currencies list. So our default currency
won't be among the active currencies, which doesn't make sense.
**These are bugs and aren't the intended behaviours.** This could be verified by the fact that in the old settings, these aren't allowed.
The root cause is because we needed to add the checks. After adding the checks though, it's still not fixed because we can't get the updated values of the store once these values change, except by refreshing it (which isn't what we want).
**To fix this, we unfortunately still need to use our "old" `share` decorator. It's because these values are …

frontend: fix default & active currencies selection

---

frontends/web/src/components/icon/assets/icons/chevron-left-dark.svg
frontends/web/src/components/icon/assets/icons/chevron-right-dark.svg
frontends/web/src/components/icon/icon.tsx
frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/routes/new-settings/appearance.tsx
frontends/web/src/routes/new-settings/components/appearance/activeCurrenciesDropdownSetting.tsx
frontends/web/src/routes/new-settings/components/appearance/darkmodeToggleSetting.tsx
frontends/web/src/routes/new-settings/components/appearance/defaultCurrencyDropdownSetting.tsx
frontends/web/src/routes/new-settings/components/appearance/displaySatsToggleSetting.tsx
frontends/web/src/routes/new-settings/components/appearance/languageDropdownSetting.tsx
frontends/web/src/routes/new-settings/components/mobile-header.module.css
frontends/web/src/routes/new-settings/components/mobile-header.tsx
frontends/web/src/routes/new-settings/components/settingsItem/settingsItem.module.css
frontends/web/src/routes/new-settings/components/settingsItem/settingsItem.tsx
frontends/web/src/routes/new-settings/components/tabs.module.css
frontends/web/src/routes/new-settings/components/tabs.tsx
frontends/web/src/routes/new-settings/mobile-settings.tsx
frontends/web/src/routes/router.tsx

This PR is mainly to set-up the Tabs view that we have on Desktop, as well as the "Back" button when on mobile.
For each changes, please see the commits history.
Preview (desktop):
Preview (mobile) _(still missing the "arrow left" / "chevron left" icon to be put on the left of the "Back" button):_

Frontend revamp settings tabs

---

frontends/web/src/api/account.ts
frontends/web/src/routes/settings/manage-accounts.tsx

In the manage-accounts view all coin names are followed by the ticker symbol of the coin, but the ERC20 tokens were only showing the token name. This adds it for consistency.

frontend/manage-accounts: Add ticker symbol to erc20 tokens

---

.github/workflows/ci.yml
frontends/android/BitBoxApp/app/build.gradle
scripts/docker_install.sh
scripts/github-ci.sh

We need to update target SDK version because of this:
```
Starting August 31, 2023:
New apps and app updates must target API level 33 to be submitted to Google Play (Wear OS must target API 30).
Existing apps must target API level 31 or above to remain discoverable by all users on Google Play. Apps that target API level 30 or below (target API level 29 or below for Wear OS), will only be discoverable on devices running Android OS same or lower than your apps’ target API level.
```

frontend/android: update targetSdkVersion to 33

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/device/bitbox02/bitbox02.tsx

createBackup was still using catch in case of success false, this should have been part of 374bd5377b0021ab23f452657e1ddaf721524f63
This also fixes an issue when continuing the workflow after the user aborted is-date-correct on the device. After canceling the app showed confirm date on device but the device did not continue.

frontend: fix regression api create-backup

---

frontends/web/src/routes/new-settings/about.tsx
frontends/web/src/routes/new-settings/appearance.tsx
frontends/web/src/routes/new-settings/components/tabs.tsx
frontends/web/src/routes/new-settings/mobile-settings.tsx
frontends/web/src/routes/new-settings/type.ts
frontends/web/src/routes/router.tsx

We pass a condition `hasAccounts` (bool) to each page that uses tabs, and based on this condition the settings tab render "Manage Accounts" tab (if `true`) and vice versa (when `false`).
When user has no account (Manage Account tab isn't visible):
When user has at least 1 account (Manage Account tab visible):

frontend: make manage account tab functional for the new settings

---

backend/coins/btc/handlers/handlers.go
frontends/web/src/api/account.ts
frontends/web/src/routes/account/send/utxos.module.css
frontends/web/src/routes/account/send/utxos.tsx

This adds notes to utxo struct, to be displayed when using coin control feature.

backend/handlers: add notes to utxo

---

frontends/web/src/routes/new-settings/components/appearance/defaultCurrencyDropdownSetting.tsx
frontends/web/src/routes/new-settings/components/appearance/defaultCurrencySetting.module.css
frontends/web/src/routes/new-settings/components/appearance/languageDropdownSetting.tsx
frontends/web/src/routes/new-settings/components/singledropdown/singledropdown.module.css
frontends/web/src/routes/new-settings/components/singledropdown/singledropdown.tsx
frontends/web/src/style/variables.css

Refactored and re-styled the **single dropdown** component for the newly redesigned / revamped settings. This is so that we can re-use and already are re-using the this **single dropdown** component in this PR. 
We'll do the same for multi dropdown component (which is used for selecting active currencies) **in another PR.**
For detailed changes, please refer to the commit history.
Preview (light):
Preview (dark):

frontend: single dropdown styling and refactoring

---

frontends/web/src/components/settingsButton/settingsButton.module.css
frontends/web/src/routes/device/bitbox01/settings/settings.jsx

Added BitBox01 serial number for customer support purposes.

frontend: display bitbox01 serial number for customer support

---

CHANGELOG.md
Dockerfile
docs/BUILD.md
frontends/qt/docker-qt5base/Dockerfile
scripts/docker_install.sh

We would like to update nodejs to v18.16.0, which requires libc6 with a higher version than that available on ubuntu 18.04 (which reached end of life on 30/04/2023). This commit updates shiftcrypto/qt5 and shiftcripto/bitbox-wallet-app docker images to be based upon ubuntu 20.04 and allows updating nodejs.

docker: update ubuntu base image to 20.04

---

frontends/web/src/components/layout/header.module.css

Hamber should not be shown on large screen as the sidebar is always visible, for example on waiting view.
CSS regression introduced in b169a1439

frontend: hide hamburger on large screen

---

backend/devices/bitbox02/handlers/handlers.go
backend/handlers/handlers.go
frontends/web/src/api/backend.ts
frontends/web/src/components/qrcode/qrcode.tsx

The error returned by handlers is not propagated to the frontend in production. For errors that should be displayed to the user, we currently use the `{ success: false }` pattern, sometimes with an error message and/or error code.
It has been a frequent confusion that one can simply return an error from the handler. This commit adds a non-error version of the handler function, with the goal that all handlers eventually use this one, so errors are properly handled in all cases.

backend/handlers: use handlers that can't return an error

---

README.md
appveyor.yml
docs/BUILD.md
frontends/web/package-lock.json
scripts/docker_install.sh
scripts/github-ci.sh

Tested on macOS:
- `make buildweb` (will update & install frontend/web/node_modules)
- `make webtest`
- `make webdev`
- `make weblint`

nodejs: update node to latest lts version 18.16.0

---

frontends/web/src/routes/new-settings/components/appearance/activeCurrenciesDropdownSetting.tsx
frontends/web/src/routes/new-settings/components/appearance/defaultCurrencyDropdownSetting.tsx

To improve intuitiveness of our default & currencies settings, we are changing its behaviour.
The default currencies dropdown now shows all the currencies, and when selecting a currency from the dropdown, that currency will be the active currency.
(also removed unused / empty style file)
Preview: 
https://github.com/digitalbitbox/bitbox-wallet-app/assets/28676406/06a04a46-75cd-4944-9111-3ec03352775c

frontend: change behaviour of active & default currencies

---

frontends/web/src/routes/new-settings/bb02-settings.tsx
frontends/web/src/routes/new-settings/components/about/app-version-setting.tsx
frontends/web/src/routes/new-settings/components/appearance/activeCurrenciesDropdownSetting.tsx
frontends/web/src/routes/new-settings/components/appearance/defaultCurrencyDropdownSetting.tsx
frontends/web/src/routes/new-settings/components/appearance/languageDropdownSetting.tsx
frontends/web/src/routes/new-settings/components/device-settings/attestation-check-setting.tsx
frontends/web/src/routes/new-settings/components/settingsItem/settingsItem.module.css
frontends/web/src/routes/new-settings/components/settingsItem/settingsItem.tsx
frontends/web/src/routes/new-settings/components/singledropdown/singledropdown.module.css
frontends/web/src/routes/new-settings/components/tabs.tsx

To have optimal UI & UX we slightly change the styling of the new settings SettingItem  on mobile by hiding the secondary text and optionally collapsing elements & hiding displayed value.
With this PR, the new settings now should be fully responsive. 
Preview:
https://github.com/digitalbitbox/bitbox-wallet-app/assets/28676406/7e38eb99-54ec-4ed2-8ff3-5d12a615e678

frontend: added new settings styling for mobile and small bugfix

---

backend/backend.go

Not used anywhere in the app or in the banner notifications.

backend: remove ext.shiftcrypto.ch and guids.shiftcrypot.ch

---

scripts/dockerdev.sh

Fixes a small nit that caused `make dockerdev` to fail if there is a space in the repo path.

scripts/dockerdev: handle spaces in repo path

---

backend/devices/bitbox02/handlers/handlers.go
frontends/web/src/api/bitbox02.ts
frontends/web/src/routes/device/bitbox02/bitbox02.tsx
go.mod
go.sum
vendor/github.com/digitalbitbox/bitbox02-api-go/api/firmware/system.go
vendor/modules.txt

This is supported since firmware v9.6.0.
api-go is updated to the latest version which exposes this functionality.
```
go get github.com/digitalbitbox/bitbox02-api-go@9cc89fd
go mod vendor
go mod tidy
```

backend/bitbox02: allow creation of 16 byte seeds (12 words)

---

frontends/web/src/routes/new-settings/components/settingsItem/settingsItem.module.css
frontends/web/src/routes/new-settings/components/singledropdown/singledropdown.module.css
frontends/web/src/routes/new-settings/components/tabs.module.css

small spacing/aligning improvement, will paste screenshots in comments.
- decrease space between active tab and underline
- decrease space between setting config label and description
- align tabs on the left with content/main-title
- center setting toggle vertically on mobile
cc @jadzeidan

frontend: small settings styling/spacing improvement

---

frontends/web/src/contexts/DarkmodeProvider.tsx

When user changes darkmode settings to the same setting that the OS prefers the config should be just removed, so it uses same as OS.
This broke in:
- e91c84a517cfe81fbdaac228ed58ef1cef8ae687
setConfig now merged with current config and ensures nothing gets lost, but this broke removing the config by omitting.

frontend: fix removing darkmode from config

---

backend/coins/eth/account.go

ETH accounts update fetches the balance from etherscan. This amount does not consider possible pending outgoing transactions and this means that after sending a txs the balance is not correctly updated, until the txs gets confirmed.
With this, the balance fetched from etherscan is decresed considering the amounts and fees of pending outgoing transactions.
NOTES: The fees are only considered when computing the balance for ETH accounts, since for ERC20-tokens they should be subtracted from the related ETH account. This is not implemented yet, as it would require a link between the ETH main account and the ERC20 derived account. It could be possibly solved with a future migration to blockbook chain explorer, that could allow to list the ERC20 pending transactions within the main ETH account …

backend: fix ETH balance update including pending txs

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/new-settings/components/about/app-version-setting.tsx
frontends/web/src/routes/new-settings/components/advanced-settings/enable-coin-control-setting.tsx
frontends/web/src/routes/new-settings/components/advanced-settings/enable-custom-fees-toggle-setting.tsx
frontends/web/src/routes/new-settings/components/advanced-settings/enable-tor-proxy-setting.tsx
frontends/web/src/routes/new-settings/components/appearance/activeCurrenciesDropdownSetting.tsx
frontends/web/src/routes/new-settings/components/appearance/darkmodeToggleSetting.tsx
frontends/web/src/routes/new-settings/components/appearance/defaultCurrencyDropdownSetting.tsx
frontends/web/src/routes/new-settings/components/appearance/displaySatsToggleSetting.tsx
frontends/web/src/routes/new-settings/components/appearance/languageDropdownSetting.tsx
frontends/web/src/routes/settings/manage-accounts.tsx

To be able to provide translated texts to the users, we must use locize keys.
In this commit, when the exact word we want to use is already available in locize, we're using them. Otherwise, we created new entries.
Edited & deleted some keys in-place as well as they're not yet "live" on locize.

frontend: using locize keys for texts in the new settings

---

frontends/web/src/components/rates/rates.tsx
frontends/web/src/routes/new-settings/components/appearance/defaultCurrencyDropdownSetting.tsx

When using the `store.state.active` directly from `rates` file, it won't give us the correct value. In our case, this causes invalid value for default currency after refreshing (after loading the component).
We need to use the string that contains `store.active.state` in the component, instead of inside the `rates` file.
[Preview (picking a default value and refreshing)]:
https://github.com/digitalbitbox/bitbox-wallet-app/assets/28676406/b2d94802-5530-4051-9d4c-7b693b67edfc

frontend: use store.state.active in DefaultCurrencyDropdownSetting (bugfix)

---

frontends/web/src/components/layout/header.module.css
frontends/web/src/components/layout/header.tsx
frontends/web/src/routes/new-settings/about.tsx
frontends/web/src/routes/new-settings/advanced-settings.tsx
frontends/web/src/routes/new-settings/appearance.tsx
frontends/web/src/routes/new-settings/bb02-settings.tsx
frontends/web/src/routes/new-settings/components/mobile-header.module.css
frontends/web/src/routes/new-settings/components/mobile-header.tsx
frontends/web/src/routes/new-settings/components/tabs.tsx
frontends/web/src/routes/new-settings/mobile-settings.tsx
frontends/web/src/routes/settings/manage-accounts.tsx

There were several changes to make the guide works with our tabbed settings.
1. We now use the `Header` component's prop `title` for showing both setting page name for both desktop & mobile.
e.g "Settings" on Desktop and "Appearance" on mobile (when on `/new-settings/appearance`). Previously, to display the page name on mobile we use `WithSettingsTabs`
2. Modified `WithSettingsTab` to not receive the page title anymore due to the point above.
3. Modified `Header` to be able to hide sidebarToggler also due to point 1.
We need to be able to hide `sidebarToggler` because on an individual setting page on mobile (for example `Appearance`), we already have a back button which is inside `MobileHeader`.
So we don't need the `sidebarToggler` anymore.
Preview:

frontend: added guides for relevant settings pages & modified header

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/device/bitbox02/setup/choose.tsx

Locize recognized keys ending with _1 and _2 as plural, this was not intended, fixed by renaming the keys.
https://www.i18next.com/translation-function/plurals

frontend: fix translation keys

---

CHANGELOG.md
backend/accounts/transaction.go
backend/coins/btc/handlers/handlers.go
backend/coins/btc/transactions/transactions.go
backend/coins/eth/etherscan/etherscan.go
backend/coins/eth/types/types.go

Address Poisoning attack consists of an attacker creating empty (0 amount) txs to/from vanity addresses, hoping that the possible victim will copy/paste the wrong address from the transaction history when sending/receiving coins. This can happen in some ERC20 tokens, depending on the implementation of the `transfer` function inside the token contract (see
https://mirror.xyz/x-explore.eth/cL3d_CyNujXq8XY7ueP4omNXx_IY1EG5Dz0FD0vJ90M for details).
This hide 0 amount erc20 txs from the `transactions` endpoint, to mitigate the effects of this attack.

backend/handlers: skip 0txs to mitigate address poisoning

---

backend/accounts.go

If there is a testnet account stored (from a testnet run) and the app is then run in mainnet, the accounts scan would also scan testnet accounts. This commit fixes it to only look at the right coins depending on testnet or mainnet.

backend/accounts: make distinction between testnet and mainnet

---

backend/coins/btc/account.go

When the account and db closes, DB operations subsequently fail. The panics should be handled better anyway, but in the case that the account was closed, we can just abort there and prevent a crash.

backend/btc: avoid some panics

---

frontends/web/src/routes/settings/bb02-settings.tsx

Without skeleton, there will be a slight jump in the layout of "Manage Device" settings, (under Device Information) due to `null` being rendered when `deviceinfo` is still undefined.
Before:
https://github.com/digitalbitbox/bitbox-wallet-app/assets/28676406/3d454c93-e355-40e9-a583-4673706d0a47
After:
https://github.com/digitalbitbox/bitbox-wallet-app/assets/28676406/0fd0a8a6-c187-407a-98f6-6ce29106ef99

frontend: use skeleton when rendering DeviceNameSetting

---

backend/backend.go
backend/banners/banners.go
frontends/web/src/app.tsx
frontends/web/src/components/banner/banner.tsx
frontends/web/src/components/status/status.tsx

Banner messages are available for bitbox01 trough a dedicated backend endpoint that allows to fetch a banner json exposed on a specific url.
This adds banner support also for bitbox02, which allows e.g. to advertise offers to the users or communicate important messages inside the app.

frontend/banner: add banner support for bitbox02

---

frontends/web/src/components/language/language.tsx
frontends/web/src/components/language/types.ts
frontends/web/src/routes/settings/components/appearance/languageDropdownSetting.tsx

The new settings dropdown is missing Čeština (CZ lang), but it is shown in the language menu during setup or in the waiting view.
Changed so that both use the same list of languages and rearranged all languages types in alphabetical order.

frontend: add missing cz lang in settings

---

frontends/web/src/components/amount/amount.module.css

The sats separator should improve reading Bitcoin sats values, but the space is unnecessary big and almost hard to read.
Reduced sats separator spacing so the number looks more natural.

frontend: decrease sats separator spacing

---

backend/handlers/handlers.go
frontends/web/src/api/account.ts
frontends/web/src/routes/account/summary/accountssummary.tsx

Export functionality for account summary was unused and not working properly. This removes the feature from the frontend and the related callback from the backend.

frontend: delete unused account summary export

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/device/bitbox02/bitbox02.tsx
frontends/web/src/routes/device/bitbox02/setup/success.tsx

The create wallet success step had a message specific to microSD card (remove the microSD card), added a message if wallet was created with mnemonic words instead.

frontend: add success recommendation for created with mnemonic

---

frontends/web/src/routes/device/bitbox02/setup/name.tsx
frontends/web/src/routes/device/bitbox02/setup/wallet-create.tsx

The please insert your microSD card warning should not show when the user setups with skip sdcard.

frontend: remove sdcard warning in create mnemonic wallet

---

frontends/web/src/routes/device/bitbox02/setup/success.tsx

The restore from mnemonic success view the last point mentioned sdcard changed to security notice about recovery words.

frontend: fix restore from mnemonic success message

---

frontends/web/src/routes/settings/components/tabs.module.css

There is a global style to break text in long words, this is a precausion to always show long addresses and break the address in the worst case.
But this rule breaks the tab text of the new settings view on some breakpoints (medium-ish screeen size).

frontend: fix breaking word in tabs navigation

---

frontends/web/src/routes/settings/manage-accounts.tsx

With the 'encrypt seed in RAM' firmware it can now take slightly longer to enable an account. Clicking the toggle quickly can deactivate the account again.
https://github.com/digitalbitbox/bitbox02-firmware/pull/1056
This change sets the toggle to disabled until the enabling is complete. To keep it simple this doesn't keep the disabled state of each toggle, but just fire and forgets.
Setting the toggle to disabled quickly changes the color. In a future commit this could be changed a loading indicator  instead of chaning it to disabled color.

frontend: block toggle account until coin is enabled

---

CHANGELOG.md
frontends/android/BitBoxApp/app/build.gradle

v4.37.1 was a hotfix based on v4.37.0 with its own changelog entry and Android version code. For v4.38.0 we need to bump the version code to avoid a collision.

releases: bump version code, add 4.37.1 changelog entry

---

frontends/web/src/components/guide/guide.tsx
frontends/web/src/components/layout/header.tsx
frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/routes/account/guide.tsx

As we're looking into migrating our class-based HoC pattern store into React's Context API, we'd first need the components that use these store directly to be converted into functional components.

frontend: convert guide and sidebar into functional components

---

frontends/web/src/routes/account/account.tsx
frontends/web/src/routes/account/info/buyReceiveCTA.tsx
frontends/web/src/routes/account/summary/accountssummary.tsx

We're now showing BuyReceiveCTA properly to avoid blank screen on account screen on testnet.
Now, BuyReceiveCTA on the account screen will always show when account is empty (instead of two conditions: empty account and supported buy).
Only when the exchange supports the buy of that certain coin, the BuyReceiveCTA will render the Buy button along with a Receive button. When it's not supported, only Receive button (and the default CTA message) will be rendered. 🙂 
Before (testnet, empty acc):
After (testnet, empty acc):
On mainnet, there should be no difference. For reference:
After (mainnet, empty acc):

frontend: change conditions to show BuyReceiveCTA

---

scripts/github-ci.sh

This should fix macos ci '404 Not Found'
/Users/runner/.nvm/.cache/bin/node-v18.16.0-darwin-x64/node-v18.16.0-darwin-x64.tar.xz
Changelog:
- https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.16.1

ci: update nodejs to latest lts version 18.16.1

---

frontends/web/src/components/forms/button.module.css
frontends/web/src/components/forms/button.test.tsx
frontends/web/src/components/forms/button.tsx
frontends/web/src/routes/device/bitbox01/restore.tsx
frontends/web/src/style/variables.css

The background color of unchecked toggles were hard to see in dark
mode, background tertiary is also used for secondary buttons.
Changed background tertiary in darkmode to fix the toggle color,
this also changes button secondary color.
Another issue is that button secondary and button transparent are
visually very similar, but the transparent style is not a text only
transparent button as the name implies. This can be improved in a
subsequent change.
Also added stricter types for button and a cleanup commit that removes
duplicate CSS properties.

Frontend button and toggle styling

---

frontends/web/src/app.tsx
frontends/web/src/components/anchor/anchor.tsx
frontends/web/src/components/guide/guide.tsx
frontends/web/src/components/layout/header.tsx
frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/components/spinner/Spinner.tsx
frontends/web/src/contexts/AppContext.tsx
frontends/web/src/contexts/AppProvider.tsx
frontends/web/src/routes/settings/mobile-settings.tsx

As a part of the refactoring effort, we want to move away from class based components and HoC. In this PR, we're removing the guide store (and the HoC related to it). We're using context API to fulfil the same goal.

frontend: using context to replace guide store

---

frontends/web/src/components/confirm/Confirm.tsx
frontends/web/src/components/devices/bitbox02bootloader/bitbox02bootloader.tsx
frontends/web/src/routes/account/add/add.tsx
frontends/web/src/routes/account/info/info.tsx
frontends/web/src/routes/account/receive/receive-bb01.tsx
frontends/web/src/routes/account/receive/receive.tsx
frontends/web/src/routes/account/send/send.tsx
frontends/web/src/routes/device/bitbox01/check.jsx
frontends/web/src/routes/device/bitbox01/components/upgradefirmware.jsx
frontends/web/src/routes/device/bitbox01/create.jsx
frontends/web/src/routes/device/bitbox01/restore.tsx
frontends/web/src/routes/device/bitbox01/settings/components/changepin.jsx
frontends/web/src/routes/device/bitbox01/settings/components/device-lock.jsx
frontends/web/src/routes/device/bitbox01/settings/components/hiddenwallet.jsx
frontends/web/src/routes/device/bitbox01/settings/components/mobile-pairing.tsx
frontends/web/src/routes/device/bitbox01/settings/components/reset.jsx
frontends/web/src/routes/device/bitbox01/setup/initialize.tsx
frontends/web/src/routes/device/bitbox01/setup/security-information.tsx
frontends/web/src/routes/device/bitbox01/setup/seed-create-new.jsx
frontends/web/src/routes/device/bitbox01/setup/seed-restore.jsx
frontends/web/src/routes/device/bitbox02/passphrase.tsx
frontends/web/src/routes/device/bitbox02/sdcardcheck.tsx
frontends/web/src/routes/device/bitbox02/setup/choose.tsx
frontends/web/src/routes/device/bitbox02/setup/name.tsx
frontends/web/src/routes/device/bitbox02/setup/restore.tsx
frontends/web/src/routes/device/manage-backups/manage-backups.jsx
frontends/web/src/routes/settings/components/device-settings/firmware-setting.tsx

Our transparent buttons are not transparent and look similar to
the secondary button.
Changed most transparent buttons to secondary so they are more
consistent and we can use real transparent buttons in the future.
The only 2 buttons that remain using transparent and should be
visually transparent (no button styling) are in choose component
the advanced setup options and on manage accounts toggle tokens
(only visible in mainnet).
After this commit is merged, button transparent style can be
updated (remove button border) and used everywhere were we should
use button component without border.

Frontend button secondary

---

frontends/web/src/components/devices/bitbox02bootloader/toggleshowfirmwarehash.tsx
frontends/web/src/components/toggle/toggle.tsx
frontends/web/src/routes/settings/manage-accounts.module.css
frontends/web/src/routes/settings/manage-accounts.tsx

Tokens did not break correctly to their own section.
Regression introduced in https://github.com/digitalbitbox/bitbox-wallet-app/commit/87b820d99dedf36050e89d7740987b03f405e2b7
This is only visible with make servewallet-mainnet as tokens are
only shown in mainnet.
also fixed className support on toggles see 2nd commit

Frontend fix manage account

---

backend/accounts.go
backend/accounts_test.go
backend/backend.go

The step to look for more accounts was only invoked when the previous account was used. If one had e.g. account 4 unused, but account 5 used, this could prevent discovery of account 5.
It worked anyway in some cases due to a race condition, as maybeAddHiddenUnusedAccounts could be invoked after account 4 was scanned (e.g. a different coin's account being added after acount 4 was scanned).

backend/accounts: fix scanning of first 5 accounts

---

frontends/web/src/routes/settings/manage-accounts.tsx

added missing `withGuide` prop in MobileHeader (manage accounts page).
without this prop, the positioning of the MobileHeader text won't be centred.
Before:
After:

frontend: added missing withGuide prop in MobileHeader (manage acc)

---

frontends/web/src/components/appdownloadlink/appdownloadlink.tsx
frontends/web/src/components/appupgraderequired.tsx

Changed AppUpgradeRequired component to use View component, also changed download link to use Button and added ViewFooter to display language menu.
Another noticeable change is that the view is now fullscreen without
showing the sidebar that contains settings.
Test by lowering semver number for lowestSupportedFirmwareVersion and lowestNonSupportedFirmwareVersion in:
- bitbox02-api-go/api/firmware/device.go

frontend: refactored appupgraderequired view

---

frontends/web/src/routes/device/bitbox02/bitbox02.tsx
frontends/web/src/routes/device/upgrade-firmware-required.tsx
frontends/web/src/routes/settings/components/device-settings/firmware-setting.module.css
frontends/web/src/routes/settings/components/device-settings/firmware-setting.tsx

Changed FirmwareUpgradeRequired to use View component, also with this BitBox02.tsx does not need to use translation decorator anymore and types can be simplified.
Test by increasing lowestSupportedFirmwareVersion in:
- bitbox02-api-go/api/firmware/device.go

frontend: refactor firmware-upgrade-required to functional component

---

frontends/web/src/routes/account/send/feetargets.module.css

to fix the spacing between "Note" & Fee Target components on mobile.
Before fix:
After fix (various states):
After fix (various states, on desktop):

frontend: fix margin issue for feetargets

---

backend/backend.go
backend/banners/banners.go

This avoids showing a device related banner (e.g. warning about bb01 being at end of life) also after the device has been removed.

backend/banner: deactivate banner when device is removed

---

frontends/web/src/components/sidebar/sidebar.module.css

To break word (account name) appropriately, we need to use the `break-word` value for `word-break` css property for `.sidebarLabel`.
Previously, the sidebarLabel is able to break world "appropriately" when account name is either short or long **with** spaces. **Long names without spaces will cause the coin logo to shift to the left, which isn't ideal.**
Before:
After:

frontend: using `word-break: break-word` for sidebarLabel

---

docs/BUILD.md

Since 732c0ef3d815f7673ba7b7c824e54fb76fa5d06a we build on Ubuntu 20.0. Ubuntu 20 comes with glibc 2.31. Debian 9 (Stretch) and 10 (Buster) have glibc's older than that. Debian 11 (bullseye) is also at 2.31. Fedora 37 is at
2.36 (https://packages.fedoraproject.org/pkgs/glibc/glibc/). Fedora 36 has been EOL since 2023‑05‑16.

docs/BUILD: bump min. required version for Debian and Fedora

---

backend/aopp_test.go
backend/keystore/mocks/keystore.go

Regenerating the keystore mock using an updated moq newly adds locks to the struct, so the linter complained with:
```
ackend/aopp_test.go:386:10: copylocks: assignment copies lock value to ks2: github.com/digitalbitbox/bitbox-wallet-app/backend/keystore/mocks.KeystoreMock contains sync.RWMutex (govet)
ks2 := ks
^
backend/aopp_test.go:422:10: copylocks: assignment copies lock value to ks2: github.com/digitalbitbox/bitbox-wallet-app/backend/keystore/mocks.KeystoreMock contains sync.RWMutex (govet)
ks2 := ks
^
```
This commit updates the mock file and fixes the test to avoid the linting error.

backend: fix aopp test after updating moq

---

backend/accounts.go

Serves little purpose and can harm privacy.

backend: don't log account name upon creation

---

frontends/web/src/components/anchor/anchor.module.css
frontends/web/src/components/anchor/anchor.tsx
frontends/web/src/components/appdownloadlink/appdownloadlink.tsx
frontends/web/src/components/banner/banner.module.css
frontends/web/src/components/banner/banner.tsx
frontends/web/src/components/forms/button.module.css
frontends/web/src/components/guide/entry.tsx
frontends/web/src/components/guide/guide.module.css
frontends/web/src/components/guide/guide.tsx
frontends/web/src/components/transactions/transaction.module.css
frontends/web/src/components/transactions/transaction.tsx
frontends/web/src/components/transactions/transactions.tsx
frontends/web/src/components/update/update.module.css
frontends/web/src/components/update/update.tsx
frontends/web/src/routes/account/send/send.tsx
frontends/web/src/routes/account/send/utxos.module.css
frontends/web/src/routes/account/send/utxos.tsx
frontends/web/src/routes/buy/components/infocontent.tsx
frontends/web/src/routes/buy/moonpay-terms.tsx
frontends/web/src/routes/buy/pocket-terms.tsx
frontends/web/src/routes/buy/terms.module.css
frontends/web/src/routes/settings/electrum-servers.tsx
frontends/web/src/routes/settings/electrum.module.css
frontends/web/src/style/layout.css

The anchor component initially only supported links to external urls which opened in the native browser.
With exchange recommendations linking to internal routes got added in c595e1d8a741bb75af190e54d0ae692854c91fe2
This was linked from the guide, so there is some logic to close the guide after clicking an internal link. Since we removed exchanges recommendation support for internal urls is not needed and could probably be removed completely.
Anchor component should be used for outgoing links, but was also used as buttons.
Changed anchors that used onClick to Button component.
Most anchors should look like a link (blue + underlines), changed
default styling of A component.
Other changes are:
- className should be added together with internal anchor className
- added tabindex so anchors …

frontend: refactor anchor component

---

frontends/web/src/routes/settings/components/settingsItem/settingsItem.module.css

to prevent displayedValue text and the setting description text collapsing with one another, we adjusted the left padding of displayedValue text.
Before:
After:

frontend: increase displayedValue setting item left padding

---

.golangci.yml
backend/banners/banners.go
backend/bridgecommon/bridgecommon.go
backend/coins/eth/account.go
backend/keystore/software/software.go

This used to be included in golint or go vet, but was moved to the `revive` linter.
https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#exported
It is good practice to document all exported items.

golangci-lint: enable check that exported items have comments

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/receive/receive.tsx

Bitsurance service only covers funds received on native segwit addresses. This limits the receiving options dialog to this script type for insured accounts, in order to avoid users to accidently receiving on uncovered addresses.

frontend/receive: limit receiving to p2wpkh for insured accounts

---

frontends/web/src/api/account.ts
frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/actionButtons.tsx
frontends/web/src/routes/account/info/buyReceiveCTA.tsx
frontends/web/src/routes/account/walletconnect/components/connect-form/connect-form.tsx
frontends/web/src/routes/account/walletconnect/components/header/header.tsx
frontends/web/src/routes/account/walletconnect/components/incoming-pairing/incoming-pairing.tsx
frontends/web/src/routes/account/walletconnect/components/session-card/session-card.module.css
frontends/web/src/routes/account/walletconnect/components/session-card/session-card.tsx
frontends/web/src/routes/account/walletconnect/components/success-pairing/success-pairing.tsx
frontends/web/src/routes/account/walletconnect/dashboard.module.css
frontends/web/src/routes/account/walletconnect/dashboard.tsx
frontends/web/src/routes/account/walletconnect/utils.ts
frontends/web/src/routes/router.tsx
frontends/web/src/style/variables.css

The dashboard screen contains all connected WC sessions of all accounts in the bitbox (to dApps), as well as a button to go to the connect screen.
It also contains some general information of the currently opened account such as the account name and its receive/wallet address.
Preview:

frontend: created Dashboard screen for wallet connect

---

frontends/web/src/components/scanqrdialog/scan-qr-dialog.module.css
frontends/web/src/components/scanqrdialog/scan-qr-dialog.tsx
frontends/web/src/hooks/qrcodescanner.test.ts
frontends/web/src/hooks/qrcodescanner.ts
frontends/web/src/routes/account/send/components/inputs/receiver-address-input.tsx
frontends/web/src/routes/account/send/send.module.css
frontends/web/src/routes/account/walletconnect/components/connect-form/connect-form.module.css
frontends/web/src/routes/account/walletconnect/components/connect-form/connect-form.tsx

To improve WC user experience especially on mobile, we allow users to connect to dApps using  QR code provided by WC.
We use our existing qr code reader hook to read the QR codes.
Also fixed / adjusted some CSS, as well as moved `scan-qr-dialog` component from `send` to `components` directory as it's now technically a shared component (it's used here in WC qr code scanning desktop view, and still used in the send screen).
Previews:

frontend: created WC QR code reading functionality

---

backend/coins/btc/maketx/maketx.go
backend/coins/btc/sign.go
backend/coins/btc/transaction.go
backend/devices/bitbox/keystore.go
backend/devices/bitbox02/keystore.go
backend/keystore/software/software.go

Refactor the TxProposal to contain PreviousOutputs which are all Outputs selected in coin selection as Inputs for the transaction.
I noticed we pass all spendable outputs as `previousOutputs` [here](https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/backend/coins/btc/transaction.go#L240-L244) this is not a performance problem since it is a map but I felt like it would make more sense that it is available in the TxProposal since it knows which Outputs it used for its Transaction Inputs.
**motivation**: drafting CPFP I refactored the `SpendableOutputs` to also return unconfirmed outputs and it made me wonder if it is correct to pass all outputs to the `signTransaction` function.
**note**: maybe its not good that `maketx` depends on `transactions` now..but we need the methods …

backend: add PreviousOutputs to TxProposal

---

scripts/github-ci.sh

This uses latest nodejs LTS 18.x version used in macOS GitHub ci.
Linux ci does not have specific nodejs version set but installs
nodejs in scripts/docker_install.sh
Changelog:
- https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.17.0
- https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.17.1

ci: use latest nodejs 18.x lts version for macos

---

backend/aopp_test.go
backend/keystore/mocks/keystore.go

The updadated moq tool adds locks to the struct.
```
backend/aopp_test.go:392:10: copylocks: assignment copies lock value to ks2: github.com/digitalbitbox/bitbox-wallet-app/backend/keystore/mocks.KeystoreMock contains sync.RWMutex (govet)
ks2 := ks
```

backend: regenerate keystore mock file and fix CI

---

frontends/web/src/components/guide/entry.tsx

Multiple empty lines in an entry result in a duplicate key. We use the index instead. This is not a problem as the order of the lines in the entry never change.

frontend/guide/entry: fix repeated key=''

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/settings/components/device-settings/show-recovery-words-setting.tsx

Show a warning in the app before showing the recovery words (mnemonic) on the device:
_Never share your recovery words with anyone. Your recovery words give full access to your wallet. If someone is asking you for your recovery words, it's a scammer, do not share them!_
~~Requires: #2262 to be merged-~~
~~Please point me in the right direction on how to style this, if I understood correctly it should not be part of the `description` in the `app.json` but another key (`warning`) this means it could also use a strong tag anywhere but we would need to use `SimpleMarkup` instead of `Message`.~~
~~note: **don't look at the 'files changed' diff as it contains commits from the confrim dialog refactor, select the last commit to see the relevant changes**~~

Show recovery words warning

---

backend/coins/eth/account.go
scripts/ci.sh

Add the -race flag for go test in the ci.sh script to detect race conditions.
Fix failing test by closing the channel and document the `quitChan` in the `Account` struct.
**note for reviewers:**
In case there are tests that we know have races but it does not matter or it's intentional we can use the [build tag](https://pkg.go.dev/go/build#hdr-Build_Constraints) `!race` to exclude that test. In this case we would need to add a script to build/run these tests without the `-race` flag.
I can drop the documentation commit if you want as it's a bit unnecessary.
Feel free to close this if you think adding this will be to annoying/slowing dev. down.

testing: run tests with -race flag

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/account.tsx

Bitsurance service only covers p2wpkh utxos. This adds a check in the account page that warns the user in case the account is insured but there are uncovered utxos that need to be moved.

frontend/account: add alert if insured account has uncovered utxos

---

frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/routes/device/bitbox01/bitbox01.module.css
frontends/web/src/routes/device/components/skipfortesting.tsx
frontends/web/src/routes/device/waiting.tsx

In watch-only, accounts can be loaded even if no keystore is connected. The debug "skip for testing" software keystore unlock would not be shown, as the app would always route to the portfolio.
We simply move it to the sidebar where it is always accessible.

frontend: move SkipForTesting to sidebar

---

frontends/web/src/index.tsx

ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it’s running React 17.
https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis

frontend: fix react 18 render warning

---

frontends/web/src/hooks/permissions.ts

Recent commit 48eebe9 introduced a new hook to check for camera permissions and inform the user about that, that was causing a frontend exception on Android. This fixes the bug.

frontend/hooks: fix permissions hook android bug

---

frontends/web/src/routes/settings/manage-accounts.module.css

The expand icon was not aligned properly with the toggle button text, this probably is a regression from recent button refactor.
or expanded:

frontend: fix css regression toggle tokens in manage accounts

---

frontends/web/src/hooks/mount.ts

Regression introduced in https://github.com/thisconnect/bitbox-wallet-app/commit/d120245f2346ead89c37b4c51147f0cfb74d9979
In webdev, this caused useLoad hook to always return undefined
which broke various components.
Issues appeared with syncheaders on account summary (never ended),
some settings did not load (that depend on useLoad) or the skip for
testing was missing on the waiting view.
> React 18 introduces a new development-only check to Strict Mode.
> This new check will automatically unmount and remount every
> component, whenever a component mounts for the first time,
> restoring the previous state on the second mount.
https://react.dev/blog/2022/03/29/react-v18#new-strict-mode-behaviors
This explains why useLoad broke, as it cleaned up after first
unmount and after that the …

frontend: fix usemounted hook in react 18 mode

---

frontends/web/src/routes/account/send/components/inputs/scan-qr-video.tsx

In the scan-qr-video component, we use a html video tag which has an unappealing placeholder image. Adding a poster attribute changes that placeholder image, we use an empty svg in this case.

frontend: add poster attribute video tag

---

frontends/web/src/locales/en/app.json

This commit added a message when chart data is missing: 2f8805c4764793648b53cc1f6b0547eda538afd7
The translation was lost in fe114752ccff387be72f65467ff42da3e34b5556
Added the translation again.

frontend: bring back lost translation

---

frontends/web/src/routes/account/account.tsx
frontends/web/src/routes/account/info/buyReceiveCTA.tsx
frontends/web/src/routes/account/summary/accountssummary.tsx

After chaning account settings and navigating back to account summary, sometimes no chart and no empty-wallet message show.
Reason seems to be that in this moment the frontend has all balances and wrong condition on when to render the message.
Changed and simplified the logic a bit. It should now show the message unless there is either a balance or one of the accounts once had coins.

frontend: fix empty accounts message

---

frontends/qt/main.cpp

To proceed with the Walletconnect workflow, we need to allow some external requests originated by the frontend WC library.

frontend/qt: whitelist frontend requests for wallet-connect

---

backend/config/accounts.go
backend/handlers/handlers.go
backend/signing/configuration.go
frontends/web/src/api/account.ts
frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/routes/account/utils.ts
frontends/web/src/routes/settings/manage-accounts.tsx

Group shows the keystore name.
The BitBox02 keystore name for now is simply the device name. For passphrase users that means that multiple keystores will have the same name. We will not give this any special consideration for now. The user can label the individual accounts, which is enough to disambiguate.

frontend: group accounts by keystore in sidebar and account settings

---

scripts/dockerdev.sh

With the current `dockerdev.sh` I was not able to get the `amd64` docker image started on my M2 arm based Mac. By adding the `--platform "linux/amd64"` parameter I was able to enforce virtualization with docker and get it running. So I recommed to add it for future developers using a Mac arm based laptop.
On other machines this additional parameter should not change anything - but I was not able to test it.

Specify 'platform' parameter to run docker build on Apple Silicon

---

.github/workflows/ci.yml

CI currently always fails on macOS, seems due to homebrew not supporting macOS 11 anymore.

ci: use macos 12

---

backend/accounts.go
backend/accounts_test.go
backend/backend.go
backend/backend_test.go
backend/config/accounts.go
backend/handlers/handlers.go
frontends/web/src/api/account.ts
frontends/web/src/api/backend.ts
frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/routes/settings/manage-accounts.tsx

Enabling the watchonly setting on an account leaves the account loaded when the keystore is removed, and the account is loaded at app launch too.
Watch-only is opt-in per account for now - in the future we might switch to enabling watch-only by default.
**Not done in this PR:** handling the case when the user performs an action on a watchonly account that requires the keystore, like verifying an address or transaction. This will follow in another PR.

Add watchonly setting to accounts & handle watchonly account loading/unloading

---

appveyor.yml
backend/accounts.go
backend/accounts/baseaccount.go
backend/accounts/baseaccount_test.go
backend/backend.go
backend/coins/btc/account.go
backend/coins/btc/account_test.go
backend/coins/btc/handlers/handlers.go
backend/coins/btc/sign.go
backend/coins/eth/account.go
backend/coins/eth/account_test.go
backend/connectkeystore.go
backend/connectkeystore_test.go
backend/exchanges/pocket.go
backend/handlers/handlers.go
frontends/web/src/api/account.ts
frontends/web/src/api/backend.ts
frontends/web/src/app.tsx
frontends/web/src/components/accountselector/accountselector.tsx
frontends/web/src/components/keystoreconnectprompt.tsx
frontends/web/src/hooks/api.ts
frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/receive/index.tsx
frontends/web/src/routes/account/receive/receive.tsx
frontends/web/src/routes/account/send/send.tsx
frontends/web/src/routes/buy/info.tsx
go.mod

Whenever the keystore is needed to perform an action on an account (verify address, send tx, ...), the user is prompted to connect the device/keystore. 
- If it is already connected, it proceeds automatically.
- If the user cancels, whatever action the user is doing aborts
- If the user connects the wrong device (or right device but wrong passphrase), the action aborts with a relevant error message
This is invoked automatically in the backend whenever the keystore is needed. In addition, an API call `connectKeystore()` is added that manually invokes this prompt. This is useful to prompt the user to connect before upfront, e.g. in the first step of the "Buy crypto" workflow instead of in the middle of it.

Watchonly: prompt user to connect device/keystore when needed 

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/bitsurance/widget.tsx

On the `requestAddress` message that is send from the Bitsurance-iFrame-App to the BitBoxApp was already the `withExtendedPublicKey` parameter available, but it was not implemented yet on the Bitsurance Widget page of the BitBox App that processes that message.
This PR adds checking this parameter and sends the xpub of the previous selected account as part of the answere with the `sendAddressWithXPub`.

Bitsurance Widget: Adding `sendAddressWithXPub`

---

frontends/web/src/routes/bitsurance/widget.tsx

The widget integration and the dashboard redirect at the end of the workflow can be tested by adding a `mockup=1` param at the widget URL: https://github.com/Beerosagos/bitbox-wallet-app/blob/bitsurance-widget-route/backend/bitsurance/bitsurance.go#L35
`widgetTestURL = "https://test.bitsurance.eu/?wallet=bitbox&version=" + widgetVersion + "&mockup=1&lang="`
Notes: 
- Bitsurance is not available on testnet, please use `make servewallet-mainnet`
- This branch doesn't include the dashboard page yet (PR in review #2334), so the redirect will bring to an empty page, this is ok.

cleanup bitsurance widget and redirect to dashboard after contract confirmation

---

frontends/web/src/routes/account/send/send.tsx

Calling `validateAndDisplayFee` without waiting for `setState` to complete was causing the actual transaction proposal amount possibly not to be updated to the last inserted digit.

frontend/send: fix bug in send form

---

frontends/qt/BitBox.pro
frontends/qt/Makefile

There is a official Qt installer, with which the macOS build works
fine.
When installing Qt from homebrew, as done in the CI and in the build
docs of this repo, the resulting build has invalid library references
in the QtWebEngineProcess. The QtWebEngine executable resides in
BitBox.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/Current/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
Instead of referencing the Qt library (frameworks) by path relative to
the BitBox.app folder to point to the local frameworks in
BitBox.app/Contents/Frameworks (using `@rpath` or `@loader_path`), it uses
absolute paths like
/usr/local/Cellar/qt@5/5.15.10_1/lib/QtGui.framework/...
The reason for this difference is unclear, most likely the macdeployqt
has a different version or a …

qt: fix macOS build when using Qt from homebrew

---

backend/accounts.go
backend/accounts_test.go
backend/backend.go
backend/backend_test.go
backend/config/accounts.go
backend/config/config.go
backend/handlers/handlers.go
frontends/web/src/api/backend.ts
frontends/web/src/locales/en/app.json
frontends/web/src/routes/settings/appearance.tsx
frontends/web/src/routes/settings/components/appearance/watchonlySetting.tsx
frontends/web/src/routes/settings/manage-accounts.tsx

With option to exempt individual accounts.
- When global watchonly is enabled, all currently loaded accounts and
accounts loaded in the future will be set to watchonly. Accounts that
had been persisted beforehand are not automatically set to watch-only.
- When global watchonly is disabled, all persisted accounts' watchonly
status is reset. This way, when one enables watchonly again, accounts
that are already persisted don't immediately appear - one has to first
load them with a keystore.
**Test cases**:
With a deleted/fresh accounts.json before every test
- Unlock BB02, remove BB02 - accounts will be loaded and unloaded, no accounts after app restart
- Enable watchonly, insert BB02, remove BB02: accounts remain, also after app restart
- Unlock BB02, enable watchonly, remove BB02: accounts …

watchonly: add global watchonly setting

---

backend/accounts_test.go
backend/backend.go
backend/bridgecommon/bridgecommon.go
backend/bridgecommon/bridgecommon_test.go
backend/config/config.go
backend/handlers/handlers.go
backend/handlers/handlers_test.go
cmd/servewallet/main.go
frontends/android/BitBoxApp/app/build.gradle
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/BiometricAuthHelper.java
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/GoViewModel.java
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
frontends/android/goserver/goserver.go
frontends/qt/libserver.h
frontends/qt/server/server.go
frontends/web/src/api/backend.ts
frontends/web/src/app.tsx
frontends/web/src/components/auth/authrequired.module.css
frontends/web/src/components/auth/authrequired.tsx
frontends/web/src/locales/en/app.json
frontends/web/src/routes/settings/advanced-settings.tsx
frontends/web/src/routes/settings/components/advanced-settings/enable-auth-setting.tsx

Watch-only can benefit from a feature that allows the user to authenticate when opening the bitboxapp, to protect the privacy. This commit creates an Auth component in the frontend that can trigger an environment-based authentication.
On Qt and Webdev the authentication succeds automatically, while on Android it requires the user to complete the system biometric authentication every time the app is resumed (.i.e. at startup and when the app comes to foreground after being put in the background).
The authentication check can be requested by the frontend using the `auth` endpoint.
Authentication messages from backend to frontend are sent via three new notifications:
- 'auth-required': which triggers a new `authenticate` call from the frontend Auth component
- 'auth-ok': which means …

Android system auth

---

frontends/web/src/routes/device/bitbox02/wizard.tsx

Unlocking a device renders an empty main element. This is only visible in some views (i.e. settings) as a large empty space on top of the view.
Reason is that the setup wizard is now always mounted since watch-only as the device can be unlocked at any time.

frontend: fix empty element

---

frontends/web/src/api/keystores.ts
frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/routes/account/info/buyReceiveCTA.tsx

superseds https://github.com/digitalbitbox/bitbox-wallet-app/pull/2307

Frontend type keystores

---

frontends/web/src/routes/account/add/add.tsx

Since watchonly, one can enter this screen without a keystore connected. If so, we ask the user to connect to proceed.

frontend/add-account: ask user to connect BitBox02 to continue

---

frontends/web/src/components/appdownloadlink/appdownloadlink.tsx
frontends/web/src/components/banner/banner.tsx
frontends/web/src/routes/device/bitbox02/settings-guide.tsx
frontends/web/src/routes/device/waiting.tsx
frontends/web/src/routes/settings/electrum.tsx
frontends/web/src/utils/url_constants.ts

A locale may contain region and other sub tags, in which case it would fallback to English.
I.e. if i18n.language is 'de-ch' instead of 'de' download link would point to english page.
i18next added resolvedLanguage in v21, see:
- https://www.i18next.com/overview/api#resolvedlanguage
The app should keep using i18n.language (with region information) if used for: Date formatting, country display names or internationalized number formatting.
In 2nd commit:
Link to pages that are available in Spanish, i.e the downloads page or the BitBox02 security page.

Frontend fix langauge

---

frontends/web/src/components/sidebar/sidebar.module.css

The sidebar header used to display ACCOUNTS (uppercase) but with watch-only this now includes the wallet name (user input).
Removed uppercase styling so that the BitBoxApp shows the exact name that the user has choosen. The user can decide to use a name that is all uppercase. The app should just display the name as choosen and not transform to uppercase.

frontend: show actual account name in sidebar

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/settings/manage-accounts.tsx

The BitBoxApp already has an enable option in the manage-accounts view. Adding a similar 'hide' option in the edit-account dialog is confusing.
This commit changes the wording and flips the toggle, from hide account to watch account. The verb 'watch' is more naturally associable with the feature watch-only.

frontend: invert watch account option

---

.github/workflows/ci.yml

Recently, half of the PRs fail CI because macOS cache downloading gets
stuck at 99.9%.
We simply remove it, it does not seem to have a performance
downside. Downloading from brew seems to take more or less the same
amount of time as downloading the cache. It may even be faster - CI
with this commit ran in 6min while a previous one with the cache ran
in 7min.

ci: remove macOS caching

---

backend/backend.go

backend.AccountSetWatch holds the accounts config lock while it is modifying the config, and while it holds the config lock it tries to acquire the accountsAndKeystoreLock in the filter function. This can deadlock if the accountsAndKeystoreLock is held already.

backend: avoid deadlock

---

frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/routes/account/utils.ts

If multiple keystores have the same name (commonly when you add keystores from one seed using multiple different passphrases), we append the fingerprint to disambiguate the groups.

frontend/sidebar: add fingerprint to accounts group to disambiguate

---

frontends/web/src/routes/settings/manage-accounts.module.css

Whenever possible always use regular font-size. In the edit account dialog there is a small description about watch-only this can just use normal font-size.

frontend: use normal font-size in account edit dialog

---

frontends/web/src/routes/device/components/skipfortesting.tsx

Small spelling change from `kestore` to `keystore`.

frontend: fix a typo in 'Unlock software keystore'

---

CHANGELOG.md
Makefile
scripts/osx-brew.sh

Apple machines with M processor have an arm64 architecture with a compatiblity layer for x86_64 software. Brew packages are installed with an arm64 architecture by default on these machines.
BitBoxApp is compiled for x86_64 arch, and the arm64 Qt was causing errors in the build process.
This commit introduces an osx-brew.sh script that forces the installation of x86_64 deps even on arm64 machines, fixing the error.
**NOTE: this is untested on Intel machines!**

build/os-x: fix build errors for M-based Apple machines

---

backend/handlers/handlers.go
frontends/web/src/components/icon/assets/icons/edit-active.svg
frontends/web/src/components/icon/icon.tsx
frontends/web/src/locales/en/app.json
frontends/web/src/routes/settings/components/manage-accounts/watchonlySetting.tsx
frontends/web/src/routes/settings/components/manage-accounts/watchonlySettings.module.css
frontends/web/src/routes/settings/manage-accounts.module.css
frontends/web/src/routes/settings/manage-accounts.tsx

- chanage from watch wallet to remember wallet
- removed outdated translations and replaced with rememberWallet
- moved enable/disable account to edit dialog
- comment code that allowed to enable watching one account, if many users request this we might bring it back
- changed manage-accounts ui to use Grid/Column component

frontend: update manage-accounts ui with remember account

---

frontends/web/src/app.tsx
frontends/web/src/routes/router.tsx
frontends/web/src/routes/settings/components/device-settings/passphrase-setting.tsx

After enabling the passphrase option (watch-only enabled) the app says "Please replug the BitBox02 now", but the app just keeps showing that view.
Without watch-only the unlock device view shows as expected.
Reason was that the /passphrase route was not under /settings and had some special condition which including testing accounts. But with watch-only there might be always accounts, so this failed.
Moved the /passphrase router under /settings/device-settings, so that it is covered by another condition in app.tsx routing logic. With this there is no need to check for /passphrase directly, as it is now under /settings.
Alternative would have been to explicitly test for /passphrase.

frontend: fix route after passphrase device settings changed

---

frontends/web/src/routes/account/account.tsx

Bitsurance badge was not correctly removed navigating from an insured account to an uninsured one. This fixes the issue.

frontend/account: fix bitsurance badge on uninsured accounts

---

backend/accounts.go
backend/accounts_test.go
backend/backend.go

It was supposed to only be applied to the accounts that belong to the current keystore, but 52bf446c7e1d09ac95c7c4d61e9f784fe028e1c1 added a regression and it was applied to all persisted accounts.
The `setWatch()` thing can be removed - it was there before when the watchonly setting was global and accounts would need to be marked as `Watch` when the keystore is connected. After we moved it to be a keystore setting, it can only be enabled after connecting the keystore anyway in 'Manage accounts'.

backend: fix regression related to updating persisted accounts

---

frontends/web/src/components/badge/badge.module.css
frontends/web/src/components/sidebar/sidebar.module.css
frontends/web/src/components/sidebar/sidebar.tsx

The connected icon is slightly bigger than the small text fontsize.
This caused a tiny jump, when the device is disconnected.
Fixed by having the icon always in place and just turn on and off
the visibility.
The icon in the badge was not perfectly centered. Reason is
that the icon has an uneven width (9px) so it rounds the
position to be 1px off.
Changed so that the icon is now a max of 10px wide. Ideally
all icons in the future that are used in badges should have
an even width.

Frontend fix sidebar connected icon

---

frontends/web/src/app.tsx

If you are inside one account that is removed when the device/keystore is disconnected, it always routes to `/`, even if there are other watchonly accounts. This commit fixes it to route to the portfolio if there is at least one account.

frontend: fix routing when removing account

---

frontends/web/src/routes/settings/components/manage-accounts/watchonlySetting.tsx
frontends/web/src/routes/settings/components/manage-accounts/watchonlySettings.module.css
frontends/web/src/routes/settings/manage-accounts.module.css
frontends/web/src/routes/settings/manage-accounts.tsx

amend CSS to fix manage accounts UI on smaller screens.
The "Edit" button collapses on smaller screens. This PR aims to fix that.
Before:
After:

frontend: amend CSS to fix manage accounts UI on smaller screens

---

backend/devices/bitbox02/handlers/handlers.go

If one inserts a BitBox02 while in the account summary or account, `useSDCard(devices);` returns true even if there is no sdcard, because:
1. It is called before the BitBox02 has established the communication (paired channel)
2. The checkSDCard endpoints returns an error
3. The `useSDCard()` assumes the result is `boolean` always, so it interprets the non-zero error as `true`, which leads to the warning banner being shown even if the sdcard is not inserted.
This is a quick fix to not show the banner in this case by returning `false` instead of an error.
The proper fix is postponed, and involes rewriting `useSDCard` to listen on the `statusChanged` event of the BitBox02 to only chekc the sdcard once the device is paired (or do something similar in the backend and make an `sdcard` event).

frontend/summary,account: sdcard check false positive

---

frontends/web/src/routes/account/utils.ts

The input accounts list seems to be possibly ordered differently in different places in the code (e.g. sidebar vs manage account page). This ensures that the list of accounts grouped by keystore always has a consistent order, and also keeps keystores with same name (e.g. create using different passphrases) to be close to each other in the list.

frontend/utils: sort getAccountsByKeystore map

---

frontends/web/src/routes/settings/manage-accounts.module.css

fix: use flex-wrap to wrap "Show tokens" button on manage accs

---

frontends/web/src/components/terms/bitsurance-terms.tsx
frontends/web/src/routes/bitsurance/bitsurance.tsx

Bitsurance terms and conditions page contains an external link towards the bitsurance website. This commit introduces different links for german and non german languages.

frontend/bitsurance: localize bitsurance terms privacy link

---

backend/coins/btc/transaction.go
backend/devices/bitbox02/keystore.go

This will make the BitBox02 show 'This BitBox02' before the address verification when making a self-send transaction.
There is a annoying edge case that is fixed by moving the `firmware.BTCSignNeedsPrevTxs()` check below processing the outputs:
- Previous transactions are not needed if all inputs are Taproot.
- The firmware determines this by checking if all provided script configs are Taproot - if it is, it does not require the previous transcations, otherwise it does.
- Unfortunately, change outputs and now also recpient outputs can add a script config for its own type. For changes it didn't change anything as we only added Taproot changes if all inputs were Taproot.
- This means that if you send-to-self using only Taproot inputs but send to a non-taproot (native segwit) recipient …

backend/bitbox02: mark recipient address as ours if they are ours

---

frontends/web/src/routes/settings/components/settingsItem/settingsItem.tsx

Unuseful space was added due to always having `.displayedValue` class regardless when there's displayed value or not for `SettingsItem` (visible on mobile). We should only add it if there's a displayed value.
Before:
After:
After for stuff with "displayed value" (no change):

frontend: apply `displayedValue` class conditionally to rm space

---

frontends/web/src/app.tsx
frontends/web/src/components/balance/balance.test.tsx
frontends/web/src/components/rates/rates.tsx
frontends/web/src/contexts/RatesContext.tsx
frontends/web/src/contexts/RatesProvider.tsx
frontends/web/src/routes/account/send/send-wrapper.tsx
frontends/web/src/routes/account/send/send.tsx
frontends/web/src/routes/router.tsx
frontends/web/src/routes/settings/appearance.tsx
frontends/web/src/routes/settings/components/appearance/activeCurrenciesDropdownSetting.tsx
frontends/web/src/routes/settings/components/appearance/defaultCurrencyDropdownSetting.tsx
frontends/web/src/routes/settings/components/appearance/displaySatsToggleSetting.tsx
frontends/web/src/routes/settings/components/dropdowns/activecurrenciesdropdown.tsx

We'd like to move away from our self-made `store` HoC & decorator
and use React's Context API instead.
This commit migrates rates store to context API. We created RatesProvider to provide "global" rates data/state & methods for the whole app and we can get them from anywhere within the app using RatesContext.
Also renamed these method & states/variables from the store for
better consistency & clarity:
1. `setActiveFiat()` -> `updateDefaultFiat()`
2. `active` -> `defaultCurrency`
3. `selected` -> `activeCurrencies`

frontend: migrate rates store to context API

---

backend/coins/btc/account.go
backend/coins/btc/account_test.go
frontends/web/src/routes/account/receive/receive.tsx

Insured accounts should only receive to native segwit addresses as they are the only addresses supported by Bitsurance. This limitation was already in the code, but in the frontend part. This commit moves the limitation code to the backend, as this is where the logic should be.

Limit receive

---

backend/accounts.go
backend/accounts_test.go
backend/backend.go

The `go backend.maybeAddHiddenunusedAccounts()` call in `registerKeystore()` could execute before or after the first `CreateAndPersistAccountConfig()` in that Watchonly unit test. If it happened after, then there would already be two accounts and we would fail at
require.Nil(t, b.Config().AccountsConfig().Lookup(expectedNewAccountCode2))

backend/accounts_test: fix race condition

---

frontends/web/src/routes/account/send/send.tsx
frontends/web/src/routes/account/send/services.test.ts
frontends/web/src/routes/account/send/services.ts

To reduce the amount of logic and as a part of the refactoring of `send.tsx`, we create a new service file to place more logic-heavy codes outside of the `send` component.
This commit moves a lengthy switch case into the service and called it `txProposalErrorHandling`.

frontend: extracted txProposal error handling into a function

---

frontends/web/src/components/status/status.tsx

defaulting `show` to `true` may cause flickering if the status
is `dismissible` and has previously been dismissed.
This is due to the status getting rendered (since `show` is true) by
default, several seconds/ms before `checkConfig` finishes.
In other words, the status gets rendered for a very short time
before it disappears after `checkConfig` finishes, giving the
appearance of a flicker.
Before:
https://github.com/digitalbitbox/bitbox-wallet-app/assets/28676406/62f0cb88-d211-422d-84e3-36d454fb1021
After:
https://github.com/digitalbitbox/bitbox-wallet-app/assets/28676406/6553aabb-dbb2-4588-a010-9b0d098a7d48

frontend: default `show` as `false` for status component

---

frontends/web/src/routes/account/account.tsx
frontends/web/src/routes/account/actionButtons.tsx

BitBox02 fw <9.15.0 can only sign legacy ETH
transactions (EIP155). After 9.15.0, it can also sign EIP1559 transactions. The app decides which one to create in the send screen depending on which keystore is used, so we need to already have it connected when entering the send screen.
We do this only for Ethereum, as for Bitcoin/Litecoin, this is not needed.
Alternaties dismissed:
- Prompt keystore on first send form modification - bad UX
- Force fw upgrade when sending ETH and only do EIP1559 - bad UX

frontend/account: prompt keystore for ETH before going to send screen

---

frontends/web/src/api/accountsync.ts
frontends/web/src/api/exchanges.ts
frontends/web/src/components/aopp/verifyaddress.tsx
frontends/web/src/components/transactions/transaction.tsx
frontends/web/src/components/transactions/transactions.tsx
frontends/web/src/routes/account/account.tsx
frontends/web/src/routes/account/info/info.tsx
frontends/web/src/routes/account/info/signingconfiguration.tsx
frontends/web/src/routes/account/receive/index.tsx
frontends/web/src/routes/account/receive/receive-bb01.tsx
frontends/web/src/routes/account/receive/receive.tsx
frontends/web/src/routes/account/send/send-wrapper.tsx
frontends/web/src/routes/account/send/send.tsx
frontends/web/src/routes/account/send/utxos.tsx
frontends/web/src/routes/account/summary/accountssummary.tsx
frontends/web/src/routes/account/utils.ts
frontends/web/src/routes/account/walletconnect/components/connect-form/connect-form.tsx
frontends/web/src/routes/account/walletconnect/components/success-pairing/success-pairing.tsx
frontends/web/src/routes/account/walletconnect/connect.tsx
frontends/web/src/routes/account/walletconnect/dashboard.tsx
frontends/web/src/routes/buy/exchange.tsx
frontends/web/src/routes/buy/info.tsx
frontends/web/src/routes/buy/moonpay.tsx
frontends/web/src/routes/buy/pocket.tsx
frontends/web/src/routes/settings/manage-accounts.tsx

For clarity, we should use the named type instead of `string`.

frontend: use AccountCode everywhere

---

backend/devices/bitbox02bootloader/device.go
frontends/web/src/api/bitbox02bootloader.ts
frontends/web/src/components/devices/bitbox02bootloader/bitbox02bootloader.tsx

And also load the status when the component loads, otherwise the view is wrong if the user exists and re-enters the view (until a new push notification arrives).

frontend/bootloader: use replace instead of reload in getStatus

---

frontends/web/src/api/devicessync.ts
frontends/web/src/routes/device/bitbox02/bitbox02.tsx

The status does not need to be synced, as the status does not change from or to `initialized` while the user is in the Manage Device screen.

frontend: convert bitbox02.tsx to a functional component

---

frontends/web/package-lock.json
frontends/web/package.json

In the following commit qr-scanner was added, but @zxing/library was not removed: 35cf802331e6e285361cb3fa06c3d85cfe1e3977

frontend: remove old scanner zxing/library

---

frontends/web/src/components/transactions/transactions.module.css
frontends/web/src/routes/account/account.module.css

frontend: fix actions btns spacing when collapsed

---

frontends/web/src/api/devicessync.ts
frontends/web/src/routes/device/bitbox02/setup/pairing.tsx
frontends/web/src/routes/device/bitbox02/unlock.tsx
frontends/web/src/routes/device/bitbox02/wizard.tsx

The waitDialog state was unused so I removed it.
Instead of resetting `status` to `''`, instead I reset `showWizard`, which should work the same way to hide the dialog. The reason is that there is no easy way to set the `status` state manually, and it also seems cleaner.

frontend: convert BB02 wizard.tsx to a functional component

---

breeztest/breeztest_disabled.go
breeztest/breeztest_enabled.go
frontends/qt/make_windows.sh
frontends/qt/server/Makefile.windows

In Windows, DLLs in the same folderas the binary referencing are
automatically found, so we just need to copy the DLL to the same
folder as libserver.dll (which references libbreez).
Builds on https://github.com/digitalbitbox/bitbox-wallet-app/pull/2373/

frontend/qt: link breez to the Windows build

---

breeztest/breeztest_disabled.go
breeztest/breeztest_enabled.go
frontends/qt/Makefile

Similar to the commit that links the breez lib in linux, libserver.so
ends up having an absolute path to libbreez_sdk_bindings becaus of the
rpath linker flag set here:
```
cgo darwin,amd64 LDFLAGS: -Wl,-rpath,${SRCDIR}/lib/darwin-amd64 -L${SRCDIR}/lib/darwin-amd64
```
(https://github.com/breez/breez-sdk-go/blob/7b566724daae0fa539f622b301fe840a3e5cbd59/breez_sdk/cgo.go)
`SRCDIR` is an absolute path and it ends up in the libserver.so
binary (check with `otool -l libserver.so`).
By adding libserver.so to the executables to rewire by macdepoyqt, we
fix its rpath and path to libbreez.
Builds on #2377

frontend/qt: deploy and link breez to the macOS build

---

frontends/web/src/components/accountselector/accountselector.module.css
frontends/web/src/components/accountselector/accountselector.tsx
frontends/web/src/routes/account/components/insuredtag.module.css
frontends/web/src/routes/account/components/insuredtag.tsx
frontends/web/src/routes/buy/info.tsx

This is how it looks 
This is how it goes with very long account names

frontend/accountselector: add insured badge icon

---

frontends/web/src/contexts/AppContext.tsx
frontends/web/src/contexts/AppProvider.tsx
frontends/web/src/routes/settings/components/appearance/hideAmountsSetting.tsx

previously, we deactivate hide amounts only via the "hide/show amounts" button (shown on the top of some pages).
Due to this, amounts will still be hidden even if we disable the settings as a whole - given we didn't disable the feature via the "hide/show amounts" btn.
This commit fixes it by always setting `setHideAmounts(false)`
as well as the config value `hideAmounts: false` if we disable
the feature via settings.

frontend: deactivate hide amounts if disabled from settings page

---

frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/routes/buy/info.tsx

also fixed the active state / class  of the sidebar when user is in specific account's buy page (`/buy/exchange/accountCode`).
Preview:
Shows "Buy Bitcoin" as title when only BTC accounts are loaded:
:Shows Sidebar active when on specific account's buy page:

fix: buy page title shows "Buy Bitcoin" if only has btc account

---

frontends/web/src/components/hideamountsbutton/hideamountsbutton.module.css

frontend: remove width css property for hideamount button text

---

frontends/web/src/api/devicessync.ts
frontends/web/src/routes/account/send/components/dialogs/confirm-wait-dialog.tsx
frontends/web/src/routes/account/send/send.tsx
frontends/web/src/routes/account/send/types.ts

type 2 subscription fns `signProgresss` and `signConfirm`
On top of that did a small refactor creating a reusable `updateBalance` fn.

frontend: type 2 subscription fns signProgresss and signConfirm 

---

frontends/web/src/components/layout/header.module.css
frontends/web/src/routes/settings/components/mobile-header.module.css
frontends/web/src/routes/settings/components/mobile-header.tsx

and adjusted the position of the title to centre better on the screen as well as hiding the "Back" button text on exceptionally small screen devices (width <330px).
Preview on super small screen (280px width):
Preview on small screen (360px width):

frontend: adjust 'Back' & title font size on MobileHeader

---

backend/bitsurance/bitsurance.go

In preperation for the GoLive I did a last API key rotation. The new key also works with test & production server and should now stay constant after release. Its a public published key anyway, but now its prepared for GoLive. 
Not part of this PR but as a reminder ... the `backend.DevServers()` can now give back `false` to signal to work against the production API for next release.

Rotated Bitsurance API key

---

frontends/web/src/api/account.ts
frontends/web/src/app.tsx
frontends/web/src/routes/account/utils.test.ts
frontends/web/src/routes/account/utils.ts

- removed sort from getAccountsByKeystore (this was not really necessary anymore after share decorator was removed from sidebar in a8be91a1d3d007cbb17ab2ca29e554e2335532d9)
- moved the sort to the parent component to after the accounts subscription (so we don't sort on every render)
- added unit test for getAccountsByKeystore
- added separate sortAccounts function + tests
- added missing 'lastConnected' key in TKeystore

frontend: refactor get keystore by accounts

---

frontends/web/src/routes/account/account.tsx

The link to the guide explaining how to move funds of an insured account to native segwit addresses was still missing. This commit fixes that.

frontend/account: add bitsurance guide link

---

frontends/web/src/components/groupedaccountselector/groupedaccountselector.module.css
frontends/web/src/components/groupedaccountselector/groupedaccountselector.tsx
frontends/web/src/components/groupedaccountselector/services.ts
frontends/web/src/routes/accounts/select-receive.tsx
frontends/web/src/routes/bitsurance/account.tsx
frontends/web/src/routes/buy/info.tsx

to improve our UX when multiple keystore is connected, we'd like to add a grouping on the account selector.
This account selector is used on the info buy page (`/buy/info`) as well as the receive page (`/accounts/select-receive`) and bitsurance.

frontend: created and used GroupedAccountSelector

---

backend/accounts.go
backend/backend.go
backend/coins/btc/handlers/handlers.go
backend/connectkeystore.go
backend/connectkeystore_test.go
frontends/web/src/api/backend.ts
frontends/web/src/components/keystoreconnectprompt.tsx
frontends/web/src/locales/en/app.json
util/errp/errp.go

With the current implementation, when the wrong keystore is connected after a keystore request, the app is not able to automatically detect the connection of the correct keystore. The only option for the user is to cancel the 'connect keystore' popup and repeat the action to create a new keystore connection request. This is counterintuitive and inefficient.
This adds a `connectkeystore.retryCallback` that allows waiting for a new keystore to be connected and checking if that is the expected one.
This PR is a better solution than #2487, as it solves the same issue while being easier and completely transparent to the frontend. It also makes #2489 unnecessary.

backend/keystore: detect new keystores after a wrong one

---

frontends/web/src/routes/bitsurance/dashboard.tsx

Account's balance was fetched without checking if the account was active. This caused unexpected errors during the component reload after disconnecting a wallet.

frontend/bitsurance: fix bug in dashboard

---

frontends/web/src/routes/bitsurance/account.tsx

When there is only one insurable account, the Bitsurance workflow skips the account selection step. Doing it, it was missing to request the keystore connection in case it was disconnected. This fixes the issue.

frontend/bitsurance: check keystore when skipping account selection

---

frontends/web/src/contexts/RatesProvider.tsx

`rotateFiat` function of the RatesProvider was missing to update the app config with the new default fiat selected. This fixes the issue.

frontend/rates: fix bug in rotate fiat

---

frontends/web/src/app.tsx

Only the active accounts were sorted before, but manage-accounts has a list of all account including inactive accounts which had different order.
Changed so that all accounts are sorted the same way.

frontend: sort accounts in manage-accounts

---

backend/handlers/handlers.go
frontends/web/src/api/backend.ts
frontends/web/src/routes/settings/manage-accounts.tsx

In previous commit 4fb2f72 we commented out the code to enable/disable watch-only at an account level. Since we didn't receive any request about that now we are completely removing it from the code base.

frontend/settings: remove dead code form manage account

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/device/bitbox02/setup/name.module.css
frontends/web/src/routes/device/bitbox02/setup/name.tsx

We already have a backend validation, but that only shows an invalid input message after the user clicked continue.
Better experience is to give live feedback and information about what is wrong.
It should only allow: printable ascii chars, with max length of 30 including spaces, but not starting or ending with (that is just trimmed, without showing an error to the user).

frontend: validate devicename input field in setup

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/device/bitbox02/setup/wallet-restore.tsx

On top of https://github.com/digitalbitbox/bitbox-wallet-app/pull/2509
Restoring from mnemonic did not allow to set a device name so it
was always 'My BitBox'.
Added set device name step before continuing with restoreMnemonic.
This also fixes a bug in webdev that was caused by calling
restoreMnemonic on mount, ending up with multiple api calls and
a fail message after the workflow was done.

Frontend restore mnemonic with name

---

frontends/web/src/routes/settings/manage-accounts.module.css
frontends/web/src/routes/settings/manage-accounts.tsx

Now that the "disable account" toggle is in the "edit" dialog, it is hard to see which accounts are disabled.
We'll grey out disabled accounts and add "disabled" text next to the edit button to make it clearer that the account is disabled
Previews:

frontend: show if account is disabled on manage accounts

---

frontends/android/Makefile

In commit 225705be7 we changed the app log identifier to fix an Android warning. This commit updates the `make logcat` command consequently.

frontend/android: update make logcat command

---

frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java

Bitsurance iframe unblocking rule was missing from the android frontend.

frontend/android: allow loading bitsurance iframe

---

frontends/web/src/routes/account/summary/accountssummary.tsx

Recent commit d8c6ba0 refactored the account summary section to group accounts by keystore. The commit also introduced a small regression, hiding the account rendering until the balance of each account is ready, while the previous behavior was to show the accounts displaying the scanned addresses.
This fixes the regression.

frontend/account-summary: fix regression during address scanning

---

frontends/web/src/components/sidebar/sidebar.tsx

With watch-only items in the sidebar are now groupped by keystore, but there is a rare issue that React gets confused and renders one account at the top of the sidebar.
This change explicitly sets keys for all items in the sidebar, and wrapps keystores and the associated  account in a separate container. This should theoretically fix the rare rendering bug.

frontend: use unique keys for sidebar items

---

backend/coins/btc/handlers/handlers.go

ETH sign related endpoints were incorrectly handling user abort error generated in case the user aborted the connect keystore popup. This commit fixes the issue.

backend/handlers: fix user abor error handling

---

frontends/web/src/routes/bitsurance/bitsurance.module.css

In German the button text was much longer and broke onto 2 lines.
Also the button icon was not positioned nicely anymore.
Changed to let buttons grow to 100% before they break to 2 lines, also changed the spacing a bit so that even if there are 2 lines the icon is positioned nicely.

frontend: fix bitsurance button in german

---

backend/aopp.go
backend/aopp_test.go

Since watch-only feature introduction, AOPP doesn't correctly handle the available accounts list, making it possible to request signing a message for an account, while having a different wallet connected. In that case there is a mismatch between the addresses displayed by the bbapp and the wallet. This also causes the signing flow to fail because of the mismatch between the address and the signature.
This commit gives a poor man's fix to the issue, filtering the available accounts and including only those belonging to the currently connected keystore.

backend/aopp: fix bug in aopp signing flow

---

frontends/web/src/app.tsx
frontends/web/src/routes/account/utils.test.ts
frontends/web/src/routes/account/utils.ts

The backend has a fairly involved accounts sorting function already in `backend/accounts.go:sortAccounts`. The current frontend sorting function sorts lexicographically by fingerprint and account code, which is a different ordering than before, but has two more problems:
- account number 10 comes before account number 2, which is wrong
- account codes cannot be relied upon to have the current structure, they could be random IDs, in which case the accounts would be ordered randomly
The original sorting in the frontend was added in
937a023bfa16e9de69ce52da4b1b7df5c10333a1 to work around a React bug where accounts were ordered differently in the sidebar vs manage accounts, but since moving to React functional components in both places, this is not needed anymore.

frontend: do not sort accounts

---

CHANGELOG.md
backend/accounts/transaction.go
backend/accounts/transaction_test.go

In ETH, there can be failed transactions that are mined (gas limit too low). The fee is deducted, but the amount is not transfered.
We need to take this into account, otherwise the chart can go out of whack.

backend: fix balance time series computation with failed txs

---

backend/banners/banners.go
backend/update.go

The desktop.json/banners.json files are moved from the bitbox.swiss website to a dedicated domain to serve files to the BitBoxApp.
The old URLs will do a 301 redirect to the new ones - old BitBoxApp versions will automatically follow the redirects.

backend: use new URLs for update/banners

---

frontends/web/src/routes/account/account.tsx

The spinner in account.tsx is rendered in many different scenarios and is quite hard to read.
This simply moves the spinner rendering to the top, one per condition, for clarity. While the spinner is rendering, nothing else is rendered.

frontend/account: detangle Spinner rendering

---

backend/coins/btc/handlers/handlers.go
backend/handlers/handlers.go

Some had the Handler suffix, some didn't. in btc/handlers, none have that suffix. This commit makes it consistent.
Same for the `_ *http.Request` change, where some have the `_` and some don't.

handlers: drop "Handler" suffix in method names and `_` var name

---

frontends/web/src/routes/account/summary/chart.tsx
frontends/web/src/routes/account/summary/filters.tsx
frontends/web/src/routes/account/summary/types.ts

This commit addresses the problem of disabled chart filters in the portfolio view when users empty their wallet. They were unable to change the chart view once they emptied their wallet.

frontend: fix disabled chart filters after user empty wallet

---

frontends/web/src/components/transactions/transaction.module.css
frontends/web/src/components/transactions/transaction.tsx

ETH transactions can sometimes fail, in that case the entry in the transaction list should be styled differently to clearly distinguish it from other completed transactions.
This commit changes the transaction icon to warning symbol and removes the color on the failed amount to be just gray instead of green or red.

frontend: style failed transactions

---

backend/chart.go

This commit modifies the chart display after the initial transaction. Previously, the chart would begin at the first fiat value of the transaction,  resulting in only one data point visible in the middle of the chart. With this update, the chart now starts at zero, providing a better view of the data.

backend: adjust chart display to start from zero after first tx

---

frontends/web/src/routes/lightning/send/send.tsx

Having one big component with multiple conditional variable child components is convenient but can also lead to more spaghetti code.
Split Send into separate components, similar as we did in setup.

frontend: split lightning send workflow into smaller components

---

frontends/web/src/routes/lightning/lightning.tsx

In mainnet we have a this-account-is-empty message that contains send, buy and receive buttons, therefore the normal buttons were hidden if the account is empty.
In lightning we have no message (yet) and should just always show the buttons.

frontend: always show send and receive buttons in lightning

---

frontends/web/src/app.tsx
frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/contexts/LightningContext.tsx
frontends/web/src/contexts/LightningProvider.tsx
frontends/web/src/hooks/lightning.ts
frontends/web/src/routes/router.tsx
frontends/web/src/routes/settings/advanced-settings.tsx

Moved Lightning config loader and subscription to a new lightning context/provider and hook, with this every component can now use the useLightning hook to get the current config.
This context could also be used to subscribe to NodeState changes.

frontend: move lightning config to context

---

backend/config/config_test.go
backend/config/lightning.go
backend/lightning/lightning.go
frontends/web/src/api/lightning.ts
frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/contexts/LightningContext.tsx
frontends/web/src/contexts/LightningProvider.tsx
frontends/web/src/routes/settings/advanced-settings.tsx

To ensure future compatibility in case we'll support multiple lightning accounts, we need to refactor the breez cache folder name and the lightning config struct, which is persisted as a json config file.

backend/lightning: refactor lightning configuration

---

frontends/web/src/components/sidebar/sidebar.tsx

This commit moves Lightning item in the sidebar to be the first item of each wallet (keystore).
Alternative would be before the wallets, after the 'My portfolio' item, this would be suitable if only one lightning wallet should be supported.

frontend: move lightning as first keystore item in the sidebar

---

backend/backend.go
backend/lightning/lightning.go

The previous asynchronous connection made difficult to properly handle errors during the activation and also caused the redirect to the lightning account to happen before the sdk completed connecting. This was causing an error being shown for a few seconds right after the activation.
The activation flow may now take a few seconds to complete, but the frontend shows a nice loader so that should not be a big issue.

backend/lightning: make ligthning SDK connection synchronous

---

frontends/web/src/routes/lightning/lightning.tsx

As this is an alpha release intended for preview and testing, this commit adds a warning to only use lightning with a small amount of funds.

frontend: add alpha release warning banner on lightning account

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/lightning/send/send.tsx

Added a new step edit-invoice to allow specifying a custom amount if no amount was given or amount is 0.
Other change:
- back button on confirm screen goes now back to the lighting view was going back to the QR scanner

frontend: handle zero amount invoices when sending with lightning

---

backend/accounts/balance.go
backend/backend.go
backend/coins/btc/handlers/handlers.go
backend/coins/coin/amount.go
backend/handlers/handlers.go
backend/lightning/handlers.go
backend/lightning/lightning.go
frontends/web/src/api/lightning.ts
frontends/web/src/routes/account/summary/accountssummary.tsx
frontends/web/src/routes/account/summary/summarybalance.tsx
frontends/web/src/routes/lightning/lightning.tsx

This is a first PR to start adding Fiat conversion support for lightning. 
Fiat conversions for LN send/receive will be addressed in a separate PR.

Lightning fiat

---

backend/lightning/handlers.go

This adds a backend check on the available balance, to avoid sending a LN payment wihtout sufficient funds.

backend/lightning: check available balance before sending LN payment

---

backend/handlers/handlers.go
frontends/web/src/api/coins.ts
frontends/web/src/routes/lightning/receive/receive.tsx
frontends/web/src/routes/lightning/send/send.tsx

This also adds a getBTCSatsAmount backend endpoint that allows to convert a sat amount into an Amount object (FE: IAmount, BE: FormattedAmount) with the fiat conversions. This is not the best solution, as it would be much better to heavily refactor the invoices parsing, removing all the FE types that depends on breez and making the enpoints return a simpler struct containing only the used data (including the fiat conversions).
This is a workaround that allows to show fiat conversions in the frontend while we take our time to decide how to refactor this part.

frontend/lightning: add fiat conversions to send/receive flows

---

frontends/android/BitBoxApp/app/build.gradle

So an alpha release of the BitBoxApp for Android does not interfere with existing installations of the BitBoxApp.

android: add lnalpha build target

---

frontends/web/src/routes/lightning/receive/receive.tsx

Creating a LN invoice with an amount lower than the open channel fee hangs indefinitely with Breez. This implements a frontend check to disable the 'create invoice' button if the amount is lower than the fee.

frontend/lightning: check receive amount for channel fee

---

frontends/web/src/routes/account/summary/accountssummary.tsx

Small regression introduced in 40976c936c7e388bd4a361a04b674d94ae1b3c83
Fixes the error:
accountssummary.tsx:180 Warning: Each child in a list should have a unique "key" prop.
Check the render method of `AccountsSummary`.

frontend: add missing key prop

---

frontends/qt/main.cpp

If a user manually has to set this, it would be helpul to see this msg
to know that the right var was set.

qt: log rendering mode

---

backend/devices/bitbox02bootloader/device.go

Sometimes users get 'invalid firmware' and go into the bootloader screen without the button to install/upgrade `CanUpgrade=false`. This should never happen if the user is using the latest app release. This may help debug the problem should it appear again.

bitbox02/bootloader: log monotonic version

---

frontends/qt/BitBox.pro
frontends/qt/Makefile

7d3ab0abab500a319f138991012edb19b19ac2dd rebased incorrectly on top of
https://github.com/digitalbitbox/bitbox-wallet-app/pull/2378 https://github.com/digitalbitbox/bitbox-wallet-app/pull/2377 https://github.com/digitalbitbox/bitbox-wallet-app/pull/2373
These PRs fixed linking on Win/macOS/Linux, and the changes in the above commit are therefore not needed.

frontend/qt: remove rebase errors related to linking Breez SDK

---

frontends/web/src/routes/lightning/receive/receive.tsx

The LN receive workflow was failing to show errors returned by the backend because the loading screen wasn't hidden in case of errors.

frontend/lightning: fix bug in handling receive invoice error

---

frontends/web/src/components/view/view.module.css

View content and button was not always centered on small screen before, especially in combination with fitContnet.
Affected views:
- create wallet success
- aopp success

frontend: optimize center view

---

frontends/web/src/routes/lightning/receive/receive.tsx

Before the success view changed autmatically after 5 seconds.
Changed so that the success view stays and needs to be manually dismissed. Also added an option to directly start a new invoice.

frontend: keep lightning receive success view

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/add/add-account-guide.tsx
frontends/web/src/routes/account/add/add.tsx
frontends/web/src/routes/router.tsx
frontends/web/src/routes/settings/manage-account-guide.tsx
frontends/web/src/routes/settings/manage-accounts.tsx

Added a "Which coins are supported?" guide entry in settings/manage-accounts and add-account, which links back to the [coins overview](https://bitbox.swiss/coins/) on the BitBox homepage. If users struggle to add a Cardano or ERC20 token account, they can now find information on this directly in the BitBoxApp.
It also makes sense to hide this new and the existing "How can I add additional tokens" entry for Bitcoin-only edition users, since they are irrelevant.
**Preview in add-acount:**

frontend: add guide entry for supported coins

---

frontends/web/src/components/view/view.module.css

With this ViewBottons are nicely positioned on mobile.
One change affects large screen that fixes a small misalingment of
aopp success buttons.
Buttons container on large screen should have no padding if inside
a View component with fitContent prop, else they are misaligned
with the content.
Button padding is only needed for small screen and defined later
in this change.
I tested the following views:
- send scan qr code dialog
- AOPP
- AppUpgradeRequired
- AuthRequired
- walletconnect (tested only without active pairing)
- ReceiveAccountsSelector accounts/select-receive
- party tested bitsurance
- pairing
- passphrase

frontend: reduce container spacing on mobile

---

CHANGELOG.md
backend/coins/btc/maketx/maketx.go
backend/coins/btc/maketx/maketx_internal_test.go
backend/coins/btc/sign.go

This commit refactors the sorting mechanism for transaction inputs and outputs. It replaces the existing BIP69 lexicographical sorting with a randomized sorting approach.
BIP69, or "Lexicographic Order of Transaction Inputs and Outputs," was initially proposed to enhance privacy and mitigate blockchain fingerprinting. However, due to its limited adoption and effectiveness, it has been replaced by random shuffling of inputs and outputs, offering improved privacy benefits.

backend: replace BIP69 with random sorting for tx inputs/outputs

---

frontends/web/src/components/appupgraderequired.tsx

App-upgrade-required component looks better if fully centered, as it is just a message and a download button.

frontend: center appupgraderequired view

---

backend/devices/bitbox02/handlers/handlers.go

Expected to be released in that version.

backend/bitbox02: require fw v9.18.0 for BIP-85

---

frontends/web/src/components/rates/rates.module.css
frontends/web/src/components/rates/rates.tsx
frontends/web/src/contexts/RatesContext.tsx
frontends/web/src/contexts/RatesProvider.tsx
frontends/web/src/routes/account/summary/accountssummary.tsx
frontends/web/src/routes/account/summary/chart.module.css
frontends/web/src/routes/account/summary/chart.tsx
frontends/web/src/routes/settings/components/appearance/defaultCurrencyDropdownSetting.tsx
frontends/web/src/routes/settings/components/dropdowns/activecurrenciesdropdown.tsx

to improve UX, we'd like to enable rotating default currency on account summary. This is done by:
- creating DefaultCurrencyRotator component
- reused that component in rates.tsx and chart.tsx
- onClick, fires `rotateFiat` (`RatesContext`).
- reinitialize chart on change `defaultCurrency` (`RatesContext`)

frontend: rotate default currency on account summary

---

backend/devices/usb/hid.go

Whith this update the device identifier changes when the bitbox reboots into bootloader and forces the app to detect the reboot, that was sometime missed.

backend/usb: update hid identifier

---

backend/accounts.go
backend/backend.go
backend/chart.go
backend/coins/coin/coin.go
backend/handlers/handlers.go

Addressing most of the observations done in #2513, in particular:
- Use hex keystore fingerprint as key for KeystoresAccountsListMap 
- Move some functions from backend.go to accounts.go
- Create backend.accountFiatBalance to reduce code duplication between `AccountsTotalBalanceByKeystore` and `ChartData`
Unit tests will come in a separate PR, together with a small refactoring of backend tests.

backend/backend: refactor backend accounts keystores

---

frontends/web/src/routes/account/summary/chart.tsx

Sometimes the chart was only half filled or not everything was
displayed. This can happen if there is at least one rememebered
wallet in combination with an unlocked wallet with different age,
so that the length of the chart data changes.
calling fitContent after setting the new data fixes this
https://tradingview.github.io/lightweight-charts/docs/api/interfaces/ITimeScaleApi#fitcontent

frontend: update chart when chart data length changed

---

backend/handlers/handlers.go
frontends/web/src/api/account.ts
frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/summary/accountssummary.tsx
frontends/web/src/routes/account/summary/coinbalance.tsx
frontends/web/src/routes/account/summary/subtotalrow.tsx

Before this update, the account summary didn't show total coin balances, especially when managing multiple wallets with the watch-only feature. This commit addresses that by adding a new coin balances table below the chart. It appears only when there are multiple wallets in the portfolio.
Restored backend code previously removed in commit https://github.com/digitalbitbox/bitbox-wallet-app/commit/d8c6ba030767703128865978ab711ddc4092d133.

frontend/account-summary: add coins total balance

---

frontends/web/vite.config.mjs

By default vitejs uses the following build targets: es2020, edge88, firefox78, chrome87, safari14. But this is not very useful as it contains targets the BitBoxApp never runs on (edge, firefox) and does not target the chrome version that is currently used in Qt webview, which is chrome83.
https://vitejs.dev/config/build-options#build-target
Explicitly setting the build target to chrome83 has the following effect:
- un-minified bundle is smaller 3,271.26 kB -> 3,266.49 kB
- changes traditional class constructor pattern to modern class field declarations https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields

frontend: vite build target to chrome83

---

CHANGELOG.md
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/GoService.java
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/Util.java

On various Android versions, when closing the app through the app manager (i.e. swiping out the app from the list you get by pressing the squared button on the device) the backend service was still running. This was causing a crash the next time the app was opened, as an already running backend was detected.
The nice fix for this would be to call Mobileserver.shutdown() when destroying the GoService, but this is not easy, as the server shutdown is only drafted, at the moment.
This commit explicitly kills the app (the same way as it happens when clicking the back button) to fix the issue.

frontend/android: fix app close and re-open crash

---

backend/coins/btc/account.go
backend/coins/btc/account_test.go
backend/coins/btc/handlers/handlers.go
frontends/web/src/api/account.ts
frontends/web/src/routes/bitsurance/widget.tsx
frontends/web/src/routes/buy/pocket.tsx
frontends/web/src/utils/request-addess.ts

Removes an unnecessary check in the function and adds a unit test function.
This was suggested in the review of #2485

backend/btc: update SignBTCAddress and add tests

---

backend/accounts_test.go
backend/aopp_test.go
backend/backend_test.go
backend/rates/mock.go

Refactor backend tests, add some utils to make it easier to create new tests and add tests for `backend.AccountsByKeystore` and `backend.AccountsTotalBalanceByKeystore`.
In particular:
- Moved several util functions from accounts_test.go to backend_test.go (accounts_test was really long and difficult to read, and now backend_tests.go gathers all the main related utils together, while account_test.go has mainly actual tests inside)
- Added new util functions, to reduce code duplication and make it easier to create new tests
- Added tests for `backend.AccountsByKeystore` and `backend.AccountsTotalBalanceByKeystore`
- Added a RatesUpdater mock function

backend/tests: refactor backend tests and add new tests 

---

backend/lightning/lightning.go

The breez cache folder is no longer needed after disabling the lightning wallet and may consume unnecessary disk space.

backend: add deletion of breez cache folder

---

backend/lightning/lightning.go

If an error occurs during the lightning connection process, it is returned, but the lightning configuration is not cleared. This leads to the appearance of a lightning wallet in the app when, in reality, it doesn't exist. This commit addresses this issue by deactivating the lightning configuration if any error occurs during this step.

backend: handle connection error during lightning activation

---

CHANGELOG.md
backend/backend.go
backend/handlers/handlers.go
frontends/web/src/api/backend.ts
frontends/web/src/locales/en/app.json
frontends/web/src/routes/settings/advanced-settings.tsx
frontends/web/src/routes/settings/components/advanced-settings/export-log-setting.tsx

This commit introduces a new feature to the Settings section, enabling users to easily export log files for troubleshooting purposes. With this addition, users can access log files without the need to navigate through the application's files manually, simplifying the process of sharing logs with support team.
When 'Export Logs' is selected from the Settings menu, the save dialog opens, allowing the user to specify the destination folder. Upon confirmation, the log file, including the current date and time in the filename, is then copied to the selected folder.
This update works only on Qt and is not available in debug mode.

frontend/settings: add 'Export logs' feature

---

frontends/web/src/routes/settings/components/device-settings/bip85-setting.tsx

This change fixes the graphic about BIP-85 child keys that did not use the whole available width in the Qt app.

frontend: fix bip-85 graphic too small

---

CHANGELOG.md
backend/backend.go
backend/coins/btc/handlers/handlers.go
backend/mobileserver/mobileserver.go
frontends/android/BitBoxApp/app/src/main/AndroidManifest.xml
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/GoViewModel.java
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/Util.java
frontends/android/BitBoxApp/app/src/main/res/xml/provider_paths.xml
frontends/web/src/components/transactions/transactions.tsx
util/config/appdir.go

Transactions export feature was disabled for Android environment, this implements it.
Android app storage space is sandboxed: the transactions csv is persisted inside the app dedicated storage and can be shared by any third-party app available on the system.

frontends/android: implement transactions export

---

frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/hooks/backend.ts
frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/account.tsx
frontends/web/src/routes/device/waiting.tsx

After unlock, especially the first time, it can take many seconds for the initial set of accounts to be loaded. Until then, the app shows nothing in the sidebar and 'Please connect your device to get started'.
The user is easily confused, it seems as something went wrong.
We can probably speed up this loading with firmware and app changes, but this is a quick improvement that shows a spinner until the accounts become available.
[Preview]:

frontend: show spinner after unlock, before accounts are loaded

---

CHANGELOG.md
frontends/android/BitBoxApp/app/build.gradle
frontends/android/BitBoxApp/app/src/main/AndroidManifest.xml

Edited PR #2646 
A user reported a crash when accessing the camera for QR code scanning. The crash report said that this tag was required.
I could not find much info about why accessing the camera would require Google Play Services. It seems however that simply adding the tag should not prevent the app to be installed on devices without Google Play Services.
Edit: the app did not build because the resource `@integer/google_play_services_version` was not defined/did not exist which indicates that google play services was not properly integrated/recognized by the build system.
Adding google play services to the dependencies in `build.gradle` fixes the problem and the app builds. Two GrapheneOS users confirmed that this build fixes the issue for them.

android: add com.google.android.gms.version to AndroidManifest.xml

---

CHANGELOG.md
frontends/web/src/components/forms/index.tsx
frontends/web/src/components/forms/input-number.test.tsx
frontends/web/src/components/forms/input-number.tsx
frontends/web/src/components/forms/input.test.tsx
frontends/web/src/components/forms/input.tsx
frontends/web/src/routes/account/send/components/inputs/fiat-input.tsx
frontends/web/src/routes/account/send/send.tsx

Amounts on invoices can use localized formatting for thousand and
decimal separators.
The BitBoxApp uses an input[type="number"] element as input field
which converts strings to numbers. Pasting amounts with localized
formatting can mess up the actual amount.
i.e. 100,50 becomes 10050, which is 100x off.
This change supports some additional formats by listening on the
onPaste event and conditionally patching some formats.
With this change, formats such as the following are now properly
converted.
- 100,50
- ,99
- 0,0000000000000000001
- 1'000'000,50
- 1'000'000.50
- 1 000 000.50
- 1.000.000,50
- 1.000,50
- 1,000.50
- 1,000,000.50
This change introduces a new NumberInput component that allows
pasting more formats. It is still just an input field for numbers
and not specifically aware or …

frontend: properly paste localized amounts

---

frontends/web/src/routes/device/bitbox02/backups.tsx
frontends/web/src/routes/device/components/backups.module.css

Preview before:
Preview after:
Preview after (with backups):

frontend: align center "no backups" text and padding on container

---

frontends/web/src/routes/device/waiting.tsx
frontends/web/src/routes/settings/electrum.tsx

Replacing external links to our knowledge base with redirects on the website enables easy and swift maintenance if the knowledge base URL ever changes in the future, e.g. because of a domain change or entirely new knowledge base system.
This will avoid broken links in old BitBoxApp versions in the future. The new redirect links are already implemented on the website.
* https://bitbox.swiss/redirects/restore-wallet-without-bitbox-en
* https://bitbox.swiss/redirects/restore-wallet-without-bitbox-de
* https://bitbox.swiss/redirects/connect-your-own-full-node-en
* https://bitbox.swiss/redirects/connect-your-own-full-node-de

frontend: change support links to redirects

---

frontends/web/src/routes/account/account.tsx

Somehow the text Welcome is shown directly after 'available balance'
regression introduced in ee2d529a1a26187e9cf2cfafd4c0fa284939d687

frontend: fix available balancewelcome

---

frontends/web/src/routes/account/summary/chart.module.css

- on some smaller breakpoints but before it centeres the total balance was touching the left screen, added some padding
- filter buttons was not centered correctly

frontend: fix account summary spacing on small screen

---

frontends/web/src/app.tsx
frontends/web/src/contexts/LightningProvider.tsx

When the lightning wallet is enabled and the device disconnects (with no watch-only accounts present), the application should redirect to My Portfolio and not to "Please connect your device" as the lightning wallet is active.
This PR also updates the initial state of lightningConfig within the LightningProvider component to use an empty array for the `accounts` property.

frontend: update redirects when lightning wallet active

---

frontends/web/src/api/account.ts
frontends/web/src/api/coins.ts
frontends/web/src/routes/account/send/send.tsx

Part of typing all api calls.
Note: in the future we should call Fiat just currencies as it can contain Fiat as well as Bitcoin.

frontend: type convert coin from and to currency

---

frontends/web/src/routes/account/summary/chart.tsx

Previously, the chart would reset to 'All' whenever the currency was changed. This commit ensures that the selected timeframe remains consistent when rotating currencies.

frontend: Maintain chart timeframe when rotating currencies

---

frontends/web/src/connected.tsx

Convert the class component in frontends/web/src/connected.tsx into a functional component.
Tested on `webdev` (normal operation and when killing the backend) and on AppImage (only normal operation, I don't know how to kill the backend when using the AppImage).

frontend: convert connected.tsx component

---

backend/lightning/dto.go
backend/lightning/response.go

Fixes an issue raised by @thisconnect about the naming of the `FeeParams` in the type OpenChannelFeeResponse. It was renamed in the Breez SDK from `UsedFeeParams` to `FeeParams`. PR #2636 updated it's use to `FeeParams` in the frontend but not in the backend.

Fix FeeParam naming issue

---

backend/coins/btc/account.go

Currently, the list of all UTXOs in the coin control selection is ordered by amount. Users sometimes re-use addresses and are not aware that there might be other UTXOs they didn't want or want to use on the same address as their selected output. Grouping the UTXOs by address helps the user to detect if there are other UTXOs.
This commit updates the sorting of outputs in the coin control dialog and is now grouped by address from the biggest to the lowest amount.

backend: update coin control outputs sorting

---

frontends/web/src/components/forms/checkbox.test.tsx
frontends/web/src/components/forms/checkbox.tsx
frontends/web/src/components/forms/index.tsx
frontends/web/src/components/groupedaccountselector/groupedaccountselector.tsx
frontends/web/src/components/headerssync/headerssync.tsx
frontends/web/src/components/icon/logo.tsx
frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/components/spinner/ascii.tsx
frontends/web/src/contexts/DarkmodeContext.ts
frontends/web/src/contexts/DarkmodeProvider.tsx
frontends/web/src/hooks/darkmode.ts
frontends/web/src/routes/account/send/components/inputs/receiver-address-input.tsx
frontends/web/src/routes/account/summary/balancerow.tsx
frontends/web/src/routes/account/summary/chart.tsx
frontends/web/src/routes/account/summary/filters.tsx
frontends/web/src/routes/account/summary/subtotalrow.tsx
frontends/web/src/routes/buy/exchange.tsx
frontends/web/src/routes/buy/guide.tsx
frontends/web/src/routes/buy/info.tsx
frontends/web/src/routes/buy/moonpay.tsx
frontends/web/src/routes/buy/pocket.tsx
frontends/web/src/routes/settings/manage-accounts.tsx

Refactored TypeScript files to use named exports instead of default exports to improve code readability and facilitate better auto-completion in IDEs. This change also enhances the consistency and maintainability of the codebase by explicitly defining exported members.

frontend: prefer named exports

---

frontends/web/src/contexts/AppContext.tsx
frontends/web/src/contexts/AppProvider.tsx
frontends/web/src/routes/account/summary/chart.tsx
frontends/web/src/routes/account/summary/types.ts

Persisting chart's timeframe using the AppContext so the timeframe doesn't reset when we navigate through the app.

frontend: persist chart timeframe

---

frontends/web/src/routes/account/send/send.tsx

When Strict Mode is on, React will also run one extra setup+cleanup cycle in development. This helps reveal subtle bugs that are hard to catch manually. This also makes the deprecated UNSAFE componentWillMount only run first time.
Send view used UNSAFE_componentWillMount to listen to keydown events that handles ESC button. In webdev pressing ESC button did therefore not go back to the account overview.
Changed to register events on componentDidMount.
Also changed deprecated KeyBoardEvent.keyCode to KeyBoardEvent.key.
See:
- https://react.dev/reference/react/StrictMode
- https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

frontend: remove unsafe componnetwillmount fix esc in webdev

---

frontends/web/src/routes/account/send/feetargets.test.tsx
frontends/web/src/routes/account/send/feetargets.tsx

Due to the useEffect fetching the fee targets depending on config, it was executed many times when going to the send screen, while it should only be called once. This commit fixes this.
While not strictly necessary, I also moved the fee target fetching its own `useLoad()`, which should decrease the chance that we will accidentally increase the number of requests again.

frontend/feetargets: load fee targets only once

---

backend/accounts_test.go

testAccountsByKeystore test was occasionally failing the check on the number of loaded accounts for each keystore
(see https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/2716#issuecomment-2114690746)
This fix excludes the `HiddenBecauseUnused` accounts from the check and should fix the issue.

backend/accounts_test: fix testAccountsByKeystore occasional error

---

CHANGELOG.md
frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/walletconnect/components/incoming-pairing/incoming-pairing.tsx
frontends/web/src/routes/account/walletconnect/components/session-card/session-card.tsx
frontends/web/src/routes/account/walletconnect/dashboard.tsx

Closes https://github.com/BitBoxSwiss/bitbox-wallet-app/issues/2689

wallet-connect: fix ui crash when account unspecified by dapp

---

backend/accounts/baseaccount.go
backend/accounts/baseaccount_test.go
backend/accounts/notes/notes.go
backend/accounts/notes/notes_test.go

In the past we had different account IDs, and the notes where stored in different files. To deal with this, we used a list of notes objects per account to be able to fetch notes from all files.
This commit changes this to migrate/merge legacy note files so we only have one notes file per account. This is conceptually easier and simplifies the upcoming notes export feature.
This also fixes a bug where the rates updater event is not propagated for accounts with account number > 0 - Initialize() returned early with `return nil` in that case.

backend/account: migrate legacy notes upfront

---

frontends/web/src/routes/account/summary/chart.tsx

Our chart uses `daily` as its `source` default state value, which isn't always useful. Instead, we need to make sure to set this `source` state to the appropriate value according to the stored `chartDisplay` in the context, since the `source` state is used to populate chart data,etc.
Other than as a best practice, this fixes an edge case bug. Such as wrong data & percentage difference displayed when user does the following:
1. picks USD as default currency,
2. navigate to a different page,
3.  and going back to account summary.
The above only happens when "USD" is picked because of the following line:
```js
if (this.props.data.chartFiat !== prev.data.chartFiat) {
this.reinitializeChart();
}
```
This means, if other `chartFiat` is picked, it'll reinitializeChart() very quickly (thus …

frontend: set data source to hourly on mount if display is week

---

backend/devices/bitbox02bootloader/device.go
backend/devices/bitbox02bootloader/firmware.go
backend/devices/bitbox02bootloader/firmware_test.go

Problem: a new device ships with the latest firmware monotonic version. User
sees 'Install' because the device is erased (no firmware on it), but during
first install of firmware, unplugs. Upon replug, the device will show 'Invalid
firmware' and boot into bootloader again. Since the monotonic version of the
firmware to be installed is the same as the version stored on the device, and
the device is not erased (half of the firmware is on it), the user sees no
button to upgrade/instll anymore.
This commit fixes this by still showing the upgrade button if the versions are
the same, but the device firmware hash does not match the expected firmware
hash.
Replaces https://github.com/digitalbitbox/bitbox-wallet-app/pull/2700 - @thisconnect suggested to use the firmware hash instead, which is a …

backend/bitbox02bootloader: allow fixing broken install

---

frontends/web/src/routes/account/send/send.tsx

Bug: enter send screen, modify note, exit send screen, re-enter send screen. Now the note field is empty but the previously proposed tx note will be used to label the new transaction.
Fix: wipe the proposed tx note when leaving the send screen.

frontend/send: wipe proposed tx note

---

CHANGELOG.md
backend/coins/btc/handlers/handlers.go
frontends/web/src/api/account.ts
frontends/web/src/components/badge/badge.module.css
frontends/web/src/components/badge/badge.tsx
frontends/web/src/components/forms/radio.module.css
frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/send/utxos.module.css
frontends/web/src/routes/account/send/utxos.tsx
frontends/web/src/routes/account/summary/accountssummary.module.css
frontends/web/src/routes/buy/components/exchangeselectionradio.module.css
frontends/web/src/routes/buy/exchange.module.css

Add a warning to the coin control modal when a user selects one or more UTXOs from reused addresses. The warning: "One or more UTXOs have a reused address. Be aware  the receiver will see all UTXOs associated with those addresses."
The UTXOs now have red badge when their address was re-used.

frontend/coin-control: add address reuse warning

---

frontends/web/src/components/pillbuttongroup/pillbuttongroup.module.css
frontends/web/src/components/pillbuttongroup/pillbuttongroup.tsx
frontends/web/src/routes/account/summary/chart.module.css
frontends/web/src/routes/account/summary/filters.tsx

Right now, we're only using such components in `filters.tsx`. However, this will change in the future as other components may incorporate these pill buttons for filtering / tabbing-like functionality.
I didn't make a new variant in the button component because we wanna keep the styling on the parent container of the buttons (`PillButtonGroup`) as we want them to look & behave the same (size-wise, etc) on every components we want to have them in. So instead, I made a `PillButtonGroup` and `PillButton` components to be used together.

frontend: make reusable pill button & pill button group

---

CHANGELOG.md
frontends/qt/main.cpp
frontends/qt/webclass.h

qt/windows: fix utf8 encoding of notes etc.

---

frontends/web/package-lock.json
frontends/web/package.json

Bump lightweight-charts dependency to latest version 4.1.4.
No breaking changes, see [release notes.](https://github.com/tradingview/lightweight-charts/blob/0f7343e7934a063238c61a67ca9926248f7f1fbd/website/docs/release-notes.md)
tested on `webdev` chrome.

frontend: bump lightweight-charts dep. to latest

---

frontends/web/package-lock.json
frontends/web/package.json

no breaking changes, see [release notes.](https://github.com/JedWatson/react-select/releases)
tested on `webdev` chrome.

frontend: bump react-select dep. to latest 5.8.0

---

frontends/web/package-lock.json
frontends/web/package.json

no breaking changes, simple update.
flag-icons [CHANGELOG.md](https://github.com/lipis/flag-icons/blob/main/CHANGELOG.md)

frontend: bump flag-icons dep. to latest 7.2.3

---

.github/workflows/ci.yml

Accidentally renamed in 0dd9660def9896eca922895285d432651924d2ab, but the docker hub org name is shiftcrypto and not bitboxswiss.

.github/workflows/ci.yml: fix typo in docs

---

.github/workflows/ci.yml

Hi,
I've added a Trivy action scanner (in repository mode), to scan for security vulnerabilities. The results would be sent to the security tab (can be changed). I'm using it for all my repositories and recommend it.
If you like the idea, You can ask me anything. A example run can be seen on my fork [here](https://github.com/baizon/bitbox-wallet-app/actions/runs/9444306412/job/26009589307).
For more information see: https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#usage

feat: added trivy repository mode scan

---

frontends/web/package-lock.json
frontends/web/package.json

Bump all @walletconnect dependencies to the newest versions:
@walletconnect/jsonrpc-types@1.0.4
@walletconnect/types@2.13.1
@walletconnect/web3wallet@1.12.1
Since the dependencies are transitive they should be updated together. There is no easy way to check for any breaking changes because there is not really something like a changelog (?).
- tested with `webdev` real BB02M keystore and Wallet Connect to Uniswap, connection was established without any issues.

frontend: bump @walletconnect versions to latest

---

Makefile

I just found that updating golangci there is a manual change needed in the Makefile to also bump the version.

chore(deps): update golangci to 1.59.0

---

frontends/web/package-lock.json
frontends/web/package.json

Bump the version of the @testing-library/jest-dom to the latest version 6.4.6.
There should be no breaking changes (since only minor version was updated), see the CHANGELOG:
https://github.com/testing-library/jest-dom/releases
Tested by running `act` locally since this is for testing this should be sufficient.

frontend: bump @testing-library/jest-dom version

---

frontends/web/src/components/spinner/Spinner.tsx

The Spinner component has some logic that aggressively suppresses
keydown events, it prevents the default bubbling of the event and
removes focus from the active element.
This was done to prevent the user from accidentally navigating or
changing a form that was covered by the Spinner.
The logic was introduced to Spinner and WaitDialog in:
- d7a9fec80254740dc905974374206b100e896ecc
- a0077119ccc607b728dff95f023f2c337bd751a9
Listening to global document and preventing the event is a bit a
hack and at some point this broke on macOS. It still works on
Linux and is the reason for a regression. The bug is that users
can not enter a device name during setup and the input element
looses focus when typing.
Regression was introduced in a change that conditionally shows
the Spinner in the Waiting …

frontend: remove keydown blocking in spinner component

---

CHANGELOG.md
frontends/web/src/app.tsx
frontends/web/src/components/sidebar/sidebar.module.css
frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/routes/settings/components/tabs.module.css
frontends/web/src/routes/settings/components/tabs.tsx

Users miss that the firmware can update or are just not aware.
Added red dot in the sidebar (or on device tab) indicating that there is something important.
In the sidebar this only checks for the first connected device.

frontend: add red dot in sidebar and settings when fw can update

---

backend/accounts/transaction.go
backend/accounts/transaction_test.go

This commit updates the transaction history sorting to handle multiple unconfirmed transactions. These transactions are now sorted by their created time.

backend: sort unconfirmed transactions by created time

---

.github/workflows/ci.yml
.github/workflows/trivy.yml

I've moved trivy to a seperate yml, because of the added rule `on:push:branches: - main`

refactor: moved trivy to seperate yml

---

frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/info/buyReceiveCTA.tsx
frontends/web/src/routes/accounts/select-receive.tsx
frontends/web/src/routes/buy/exchange.tsx

In some languages Bitcoin or crypto can have special ending depending
on the context, so translating crypto does not work in all cases.
This is the first step changing keys using bitcoin or crypto
context so that terms like Bitcoin or crypto can be translated
differently.
Added generic buy and receive keys with context, without context
this keys still use a coinCode placeholder. i.e.
- Buy Bitcoin
- Buy crypto
- Buy LTC / Buy {{coinCode}}
Reason to not offer different keys for each token/coin is that it
would required a different key for each coin/token.

frontend: improve bitcoin or crypto in translations

---

frontends/web/src/routes/settings/components/tabs.module.css
frontends/web/src/routes/settings/components/tabs.tsx

The position of the red dot in settings on mobile looked visually a bit off.
Placed the dot in the settings item on the right so it has same look and style as when we use the red dot in other places in the settings item.

frontend: improve firmware update indicator on small screen

---

frontends/web/src/components/terms/moonpay-terms.tsx
frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/info/buyReceiveCTA.tsx
frontends/web/src/routes/account/utils.ts
frontends/web/src/routes/buy/exchange.tsx
frontends/web/src/routes/buy/guide.tsx
frontends/web/src/routes/buy/info.tsx
frontends/web/src/routes/buy/moonpay.tsx
frontends/web/src/routes/buy/pocket.tsx

In some languages Bitcoin or crypto can have special ending depending
on the context, so translating crypto does not work in all cases.
Added Bitcoin and crypto context with option to show coinCode,
if needed.
The buy title will now use coin code instead of coinname, this is
so that we do not need a different translation key for each altcoin.
With that the buy workflow can show 'Buy Bitcoin' or 'Buy crypto',
and once an account is selected it will show the coin code of the
altcoin (unless it is Bitcoin), i.e. 'Buy LTC'.
For simplicity the guide is just using crypto or bitcoin.
Also buy.info.disclaimer keys need to be updated with coinCode.
Related https://github.com/BitBoxSwiss/bitbox-wallet-app/commit/b617b15427ffac7e0c0e9e1b7c2a8d01b59cefd0

frontend: improve translations with crypto, bitcoin or coincode

---

frontends/web/src/components/terms/moonpay-terms.tsx
frontends/web/src/locales/en/app.json

Removed Moonpay specific terms in favor of general disclaimer text.
And fixed small regression with LTC as it was detected as Bitcoin

frontend: simplify terms and condition 

---

frontends/web/package-lock.json
frontends/web/package.json

Bump @testing-library/react to latest version 16.0.0. Also installs @testing-library/dom as a peer dependency, see:
https://github.com/testing-library/react-testing-library/releases/tag/v16.0.0
There are breaking changes from 15.0.0 to 16.0.0 (none from 14 to 15) but they do not cause any problems, see link above. Tested with CI and `webdev` (just opened a software keystore and clicked on some stuff / `webdev` not really relevant to test this)

frontend: bump @testing-library/react version

---

backend/handlers/handlers.go

If getExchangeBuySupported was called after an account was closed it was returning a generic error, causing the frontend to display the generic error popup when disconnecting the bitbox every now and then.
This makes the endpoint to return an empty list of supported exchanges if the account is not available.

backend/handlers: fix err handling in getExchangeBuySupported

---

frontends/web/src/components/transactions/components/address-or-txid.tsx
frontends/web/src/components/transactions/components/arrow.tsx
frontends/web/src/components/transactions/components/date.tsx
frontends/web/src/components/transactions/components/detail.tsx
frontends/web/src/components/transactions/components/details.tsx
frontends/web/src/components/transactions/components/show-details-button.tsx
frontends/web/src/components/transactions/components/status.tsx
frontends/web/src/components/transactions/transaction.tsx

Refactor the transaction.tsx component to be more concise and easier to understand, also fix some minor nits like using template literals for element class names.
The PR implements all suggestions from #2549 and does not do anything else. **The commits can be reviewed own their own.** But the [first](https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/2776/commits/3621dcde23cb5579d8e35e2c4feca70eff3349f9) and the [third](https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/2776/commits/388c932dc78feee5eee0bbc92843427f08472fd7) could be skipped because the changed code is moved in other commits.
The last commit moves, and changes the transaction dialog to its own component which is why everything editing something in `Dialog` prior to that commit can also be reviewed later in the last …

frontend: refactor transaction.tsx

---

backend/accounts/account.go
backend/coins/btc/handlers/handlers.go
backend/coins/btc/maketx/maketx.go
backend/coins/btc/transaction.go
backend/coins/coin/conversions.go
backend/devices/bitbox02/keystore.go
frontends/web/package-lock.json
frontends/web/package.json
frontends/web/src/api/account.ts
frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/send/send.tsx
frontends/web/src/routes/exchange/pocket.tsx

Payment requests have been supported by bitbox02 firmware since v9.19.0. This integrates the feature in the app, mocking a payment request in the Pocket widget section. Once the Pocket sell widget integration is completed the mock function will be removed.
Note: to test this it is necessary to flash a dev device with a FW having the test merchant enabled.

backend/btc: add support for payment request transactions

---

frontends/web/src/components/dialog/dialog.tsx
frontends/web/src/routes/settings/components/device-settings/factory-reset-setting.tsx

Only used in the factory reset dialog during isConfirming, but when isConfirming is true, the FactoryResetWaitDialog is shown and the original dialog is hidden anyway.

frontend/dialog: remove disableClose param

---

.github/workflows/trivy.yml

I've refactor the trivy scan from using the GitHub Security tab to table format. Now within the `Run Trivy` step a table is shown with the vulnerabilities. Also `exit-code: '1'` is triggered then. No more interaction with the GitHub Security tab.

refactor: trivy scan to table format

---

frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
frontends/web/src/components/alert/Alert.tsx
frontends/web/src/components/dialog/dialog.tsx
frontends/web/src/components/wait-dialog/wait-dialog.tsx
frontends/web/src/contexts/BackButtonContext.tsx
frontends/web/src/contexts/providers.tsx
frontends/web/src/globals.d.ts
frontends/web/src/hooks/backbutton.ts
frontends/web/src/routes/device/bitbox02/passphrase.tsx
frontends/web/src/routes/device/bitbox02/setup/wait.tsx

**Behavior**
Before it would always prompt to quit the app. Now, the back button behavior is:
- if a frontend component is using `useBackButton(handler)`, then handler is executed. If the handler returns false, stop. This is useful for dialog components to inhibit the Android back button or make it close the dialog.
- If there is no active frontend back button handler, or a handler was executed and returns true, then the default behavior kicks in:
- if we can go back in browser history, we go back
- if we can't we prompt exiting the app
This commit contains this with a few frontend components modified to use the useBackButton hook:
- wait dialogs make the back button do nothing, so user can't exit blocking dialogs when e.g. input on the BitBox02 is required
- close normal dialogs if they …

android: make back button actually go back

---

frontends/web/src/components/dialog/dialog.tsx
frontends/web/src/routes/account/receive/receive-bb01.tsx
frontends/web/src/routes/account/receive/receive.tsx
frontends/web/src/routes/buy/pocket.tsx

If onClose is undefined, there is on close button, and ESC should then also not work, and vice versa.
This also fixes some dialogs that could be escaped via ESC that shouldn't have, like the BB02 backup check dialog.

frontend/dialog: remove disableEscape param, use onClose instead

---

frontends/web/src/app.tsx
frontends/web/src/routes/bitsurance/account.tsx
frontends/web/src/routes/bitsurance/bitsurance.tsx
frontends/web/src/routes/buy/info.tsx
frontends/web/src/routes/device/manage-backups/manage-backups.tsx
frontends/web/src/routes/settings/mobile-settings.tsx

When automatic navigation occurs (redirects) the history entry should be replaced so that the user can go back.
This fixes issues when the user tries to go back but lands on the same page again due to previous step redirecting.
This also removes some routing logic from manage-backups which can be handled centrally by app.tsx routing.

frontend: replace history entry when redirecting

---

frontends/web/src/routes/settings/components/mobile-header.tsx

We removed it as it's not necessarry to have the text especially since it overlaps with other components in certain ocassions.
Preview:

frontend: remove "Back" text from back button in mobile header

---

frontends/web/src/routes/settings/manage-accounts.tsx

Navigating to add-account should add a history entry so that back goes back to manage-accounts.

frontend: add history entry navigating to add-account

---

backend/coins/btc/handlers/handlers.go
backend/devices/bitbox/keystore.go
backend/devices/bitbox02/keystore.go
backend/keystore/keystore.go
backend/keystore/mocks/keystore.go
backend/keystore/software/software.go
frontends/web/src/api/account.ts
frontends/web/src/locales/en/app.json
frontends/web/src/routes/exchange/components/buysell.tsx

This inserts a new `SupportsPaymentRequests` method in the device interface and creates a new related endpoint to check if the connected device supports sell action in the exchange section.

backend/devices: implement the has-payment-request endpoint

---

backend/handlers/handlers.go
frontends/web/src/api/lightning.ts

This commit ensures the mnemonic words created
for lightning wallet are not exposed to frontend.

backend/lightning: don't expose mnemonic words for lightning

---

backend/coins/btc/account.go
backend/coins/btc/feetarget.go
backend/coins/btc/feetarget_test.go
backend/coins/btc/transaction.go
frontends/web/src/routes/exchange/pocket.tsx

There was a bug in the payment request implementation that didn't correctly support mempool.space fees and resulted in a fee error during the tx proposal on production environment.
This commit moves the fee target selection for payment requests in the BE and fixes the bug.

backend/transaction: auto select highest fee for payment requests

---

frontends/android/BitBoxApp/app/src/main/AndroidManifest.xml
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java

A recent upgrade to targetSdkVersion 34 (ffc030aa6) caused a crash when starting the app. This fixes the crash adding permission requests in the manifest and updating the `registerReceiver` call in `MainActivity` to v34 requirements.

frontend/android: fix startup crash

---

frontends/web/src/contexts/AppContext.tsx
frontends/web/src/contexts/AppProvider.tsx
frontends/web/src/contexts/BackButtonContext.tsx

After closing the guide by going back, the guide opens on next app
restart.
Reason was BackButtonProvider closed the guide by calling:
setGuideShown but this function doesn't update the config and
should probably be internal to AppProvider.

frontend: fix guide open on app restart

---

frontends/web/src/routes/bitsurance/widget.tsx
frontends/web/src/routes/buy/moonpay.tsx
frontends/web/src/routes/buy/pocket.tsx

The app should disable native back when the user is in an iframe so that they do not accidentally leave its workflow.

frontend: disable native back when showing iframes

---

backend/devices/bitbox02/keystore.go

Updated dep in 6a75faeb3, we can use a new function added there: `NewBTCPrevTxFromBtcd()`.

backend/bitbox02/keystore: use bitbox02-api-go util function

---

frontends/web/src/components/terms/pocket-terms.tsx
frontends/web/src/locales/en/app.json
frontends/web/src/routes/exchange/components/infocontent.tsx
frontends/web/src/routes/exchange/guide.tsx

moved & update content of pocket T&C. Removed the old / out-of-date (thus unused) pocket T&C translation keys.
T&C: 
Info box:

frontend: update pocket T&C and info box content, remove unused translation keys

---

frontends/web/src/api/banners.ts
frontends/web/src/app.module.css
frontends/web/src/app.tsx
frontends/web/src/components/banner/banner.tsx
frontends/web/src/components/contentwrapper/contentwrapper.module.css
frontends/web/src/components/contentwrapper/contentwrapper.tsx
frontends/web/src/components/globalbanners/globalbanners.tsx
frontends/web/src/components/message/message.module.css
frontends/web/src/components/message/message.tsx
frontends/web/src/components/status/status.module.css
frontends/web/src/components/status/status.tsx
frontends/web/src/routes/account/account.tsx
frontends/web/src/routes/account/send/send.tsx
frontends/web/src/routes/account/summary/accountssummary.tsx
frontends/web/src/routes/account/walletconnect/dashboard.tsx
frontends/web/src/routes/device/bitbox02/passphrase.tsx
frontends/web/src/routes/device/bitbox02/setup/password.tsx
frontends/web/src/routes/settings/about.tsx
frontends/web/src/routes/settings/advanced-settings.tsx
frontends/web/src/routes/settings/bb02-settings.tsx
frontends/web/src/routes/settings/general.tsx
frontends/web/src/routes/settings/manage-accounts.tsx
frontends/web/src/routes/settings/mobile-settings.tsx
frontends/web/src/style/layout.css
frontends/web/src/utils/types.ts

to improve consistency & aesthetics, we'd like to use our revamped Message component for our Status component.
Please note that our Banner component uses Status. Therefore, with this change, Banner will also use Message component.

frontend: use Message component for Status

---

scripts/run_regtest.sh

By default electrs serves Prometheus metrics on 127.0.0.1:24224 for regtest. Because we run two electrs containers one always panic because the port is alrady in use. This commit configures one of the two electrs servers to serve metrics on 24225 instead to avoid the crash.
```
[2024-08-05T19:54:21.513Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:24224
[2024-08-05T19:54:21.513Z INFO  electrs::server] serving Electrum RPC on 127.0.0.1:52001
thread 'metrics' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', src/metrics.rs:30:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

scripts: fix run_regtest.sh electrs panic

---

frontends/web/src/api/account.ts
frontends/web/src/components/rates/rates.tsx
frontends/web/src/hooks/localized.test.ts
frontends/web/src/hooks/localized.ts
frontends/web/src/routes/settings/components/appearance/activeCurrenciesDropdownSetting.tsx
frontends/web/src/routes/settings/components/appearance/defaultCurrencyDropdownSetting.tsx
frontends/web/src/routes/settings/components/dropdowns/activecurrenciesdropdown.module.css
frontends/web/src/routes/settings/components/dropdowns/activecurrenciesdropdown.tsx
frontends/web/src/routes/settings/components/dropdowns/dropdowns.module.css

also minor CSS fix on the active currencies dropdown. These are done to improve the UX. The standardised Intl is being used to follow best practices.

frontend: use Intl.DisplayNames to localise currency names

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/info/info.tsx

Using Taproot extended public keys in raw xpub format is not widely supported and can lead to dangerous misuse. This hides the Taproot extended public key and displays an info message instead.
Most wallets will default to P2PKH when scanning a raw P2TR xpub, resulting in a non-standard combination of script type and derivation path. Recovering funds sent to addresses like this is difficult and potentially unsafe for users, as the BitBox02 does not support spending from P2PKH outputs.
As long as the BitBoxApp does not support output descriptors, expert users should instead connect their device to other wallet software to view detailed account information.

frontend: hide taproot account info

---

frontends/web/src/routes/account/send/send-wrapper.tsx
frontends/web/src/routes/account/send/send.tsx

The Send component interacts with one account per transaction which is why it makes sense to refactor the component to only take one account instead of a list of all accounts and the code of the relevant account.
This has several benefits:
- reduce code size
- remove non-null assertions that should not be used (`getAccount()!.coinCode` for example)
- makes intention clear: Send can only take a valid account, if there is no account there is no Send.
- makes Send cleaner/easier to understand by removing prop, helper function, null/undefined checks.
Small PR working towards **convert send.tsx to functional component**. I will open a few small PR's and try to reduce the size of `Send`/make it easier to understand, and then eventually open a bigger PR to convert it to its own functional …

frontend: only pass account to Send component

---

frontends/web/src/components/password.tsx
frontends/web/src/routes/device/bitbox01/restore.tsx
frontends/web/src/routes/device/bitbox01/setup/initialize.tsx
frontends/web/src/routes/device/bitbox01/unlock.jsx
frontends/web/src/routes/device/components/skipfortesting.tsx

Refactor the `password.jsx` file into typescript.
I had to cast to the concrete type a lot of times, I'm not sure if that makes sense since it can throw an error, but how _should_ an error be handled? e.g. `this.setState({ [stateKey]: value } as Pick<TState, keyof TState>, this.validate);`

frontend: refactor password.jsx into typescript

---

.github/workflows/ci.yml
scripts/github-ci.sh

Simplify nodejs setup, use GH actions instead of homebrew and nvm
https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs

ci: install nodejs with github actions

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/settings/components/device-settings/show-recovery-words-setting.tsx

frontend: add confirmation checkbox for "show mnemonic" dialog

---

frontends/web/src/routes/account/send/send.tsx

Remove unused state variable `btcUnit` from the Send component. Probably it was not noticed that it is not used anymore because the linter does not complain since we set it with `getConfig`.
Small PR in preparation for `send.tsx` refactor.

frontend: remove unused btcUnit from send.tsx

---

backend/accounts/account.go
backend/accounts/baseaccount.go
backend/accounts/baseaccount_test.go
backend/accounts/mocks/account.go
backend/coins/btc/handlers/handlers.go
backend/coins/btc/transaction.go
backend/coins/eth/account.go
frontends/web/src/api/account.ts
frontends/web/src/routes/account/send/send.tsx

Noticed this when planning the refactor of (frontend) `send.tsx`, this PR does not change anything and should be a pure refactor.
- the `propose-tx-note` handler did nothing but setting a field on `BaseAccount` it did not validate anything, thus removing it and just using the final tx note reduces the code size but changes nothing.
We initially separated the note from the txProposal because we did not want to perform any actions when (e.g calculate fee) when user types a note:
https://github.com/BitBoxSwiss/bitbox-wallet-app/commit/4eb692c84351dbd23ae391e99ffd5d8452db08f7
It would be good to validate the note though to match the constrains here, but that would not be a refactor so maybe in another PR:
https://github.com/BitBoxSwiss/bitbox-wallet-app/blob/87d6219ddb566a52aa410c54cd75d63669e …

frontend/backend: pass final tx. note to `sendtx` and remove `propose-tx-note` handler

---

backend/coins/btc/maketx/maketx.go
backend/coins/btc/sign.go
backend/devices/bitbox/keystore.go
backend/keystore/software/software.go

The SigHashes struct is a precomputation of hashes to speed up the computation of per-input sighashes. The idea is to compute it once, not per-input.
We made the instance after creating the tx, before signing it. This works fine, but with Silent Payments (BIP-352), the signer also modifies the transaction: it generates the silent payment output.
THe pre-computed sighashes are not valid in that case, as the transaction changes afterwards. We simply fix this by creating the instance after signing in the BitBox02 (which will support silent payments), and use it as before in the other keystores.

btc: refactor sighashes

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/exchange/guide.tsx

The text is different depending on what service you use, and if one buys or sells. Each service already has the security model text in its disclaimer.
Also changed from "Buy Guide" to "Exchange guide"

frontend: remove "Security Model" from exchange guide

---

Makefile

The line assumed it was running with `/tmp` as the working directory, but that is only true in the Dockerfile, but not generally.

Makefile: fix envinit path

---

CHANGELOG.md
backend/update.go
frontends/android/BitBoxApp/app/build.gradle
frontends/qt/Makefile
frontends/qt/resources/MacOS/Info.plist
frontends/qt/setup.nsi

Added missing CHANGELOG entry.
Reworded the Pocket sell CHANGELOG entry, the technical detail is unimportant for the release note. Also the BTC are not sold *to* Pocket, but Pocket sells it for the customer as a broker.

backend: update to version 4.44.0

---

.github/workflows/ci.yml

When a pull request is updated or a branch is being pushed to and a new job is created, cancel any currently running job.

ci: waste less cycles

---

.github/workflows/ci.yml
Makefile
frontends/ios/Makefile

For now we ignore signing the app, publishing it or even running it. This first step is to simply compile the iOS app to check for build errors.
In the future, we may want to consider using github secrets to automatically sign and push to testflight.
The macos runner image is bumped to 14, which defaults to XCode
15. The older version had some build errors with the iOS app.
I also tried porting the macOS Qt job to run on macos-14 which runs on ARM, using scripts/osx-brew.sh to install the x84_64 version of Qt, which is needed so the app can be built for x84_64. It works but we postpone this until necessary, as it slows down CI a lot (emulates all of compilation in x86_64 on ARM).

ci: build iOS app

---

frontends/web/src/components/rates/rates.module.css

The rotateable unit of the incoming fiat was rendered in a larger font-size than the rest of the incoming text.
Setting the font-size to inherit fixes this issue and renders the whole message with the same font-size.

frontend: fix styling for incoming unit

---

backend/devices/bitbox02/keystore.go

v9.19 had a version too, but we modified it in a breaking change (new payment request identifier for Pocket), so v9.19 would not actually work with the Pocket widget.

backend/bitbox02: payment requests only from v9.20

---

frontends/web/src/routes/account/send/components/confirm/confirm.tsx
frontends/web/src/routes/account/send/components/confirm/dialogs/confirm-wait-dialog.tsx
frontends/web/src/routes/account/send/components/confirm/types.ts
frontends/web/src/routes/account/send/send.tsx

Remove the `fiatUnit` state in Send because it is redundant since we can access `this.props.activeCurrency` since this commit: 373b7e89a2cbf6d4cf8f51ac69743b9a7b4efd61
Small PR preparation for `send.tsx` refactor.

frontend: remove redundant fiatUnit state in Send

---

frontends/web/src/routes/account/send/coin-control.tsx
frontends/web/src/routes/account/send/send.tsx

After: #2870 **and** #2866 
Create a sub-component for the coin control (toggle and utxo selection dialog) to make the `send.tsx` component smaller and easier to understand.

frontend: create coin control sub-component

---

frontends/web/src/routes/account/summary/chart.tsx

If the user is unplugging a wallet that is not remembered but still
has an empty rememebered wallet, the chart should be removed.

Frontend fix empty remembered chart

---

backend/exchanges/moonpay.go
backend/exchanges/pocket.go

The previous limit of 81,920 bytes caused issues due to increased response sizes, likely due to additional countries or fields in the JSON data. This change increases the limit to 100,000 bytes to accommodate current data and provide a buffer for future growth.

backend: increase API response size limit for available countries

---

backend/mobileserver/mobileserver.go

This fix is specific to Android, on iOS it probably simply errors and returns early.

backend/mobileserver: run timezone fix only on Android

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/exchange/components/buysell.tsx

These error messages should use context so that the whole message can be translated for each language.
Adding a placeholder does often not work in every langauge and the term 'buy' or 'sell' was not translatable in this case.
Removed the action placeholder for these messages, this needs to be updated in locize as well in all langauges.

frontend: remove i18n placeholder in error messages

---

frontends/web/src/routes/account/account.module.css

On small screens the Buy&sell button font size is larger than the other buttons, this is probably a regression that was introduced by some renaming.

frontend: fix button fontsize on mobile

---

frontends/web/src/routes/account/send/components/dialogs/message-wait-dialog.tsx
frontends/web/src/routes/account/send/send.tsx

Put the result from the send request into the `Send` components state and use it directly instead of `isSent` and `isAborted`. This simplifies the component and will make the refactor to a functional component easier because we'll be able to use a `useEffect` with a dependncy on the `sendResult` state that can `switch` over it and also reset the form.

frontend: put send request result in `Send` state

---

frontends/web/src/routes/account/send/components/inputs/receiver-address-input.tsx
frontends/web/src/routes/account/send/send.tsx

After #2870
In case #2870 is merged we can remove a lot of complexity from the open/closed state management of the scan QR dialog.

frontend: move `activeScanQR` into `ReceiverAddressInput` sub-component

---

frontends/web/src/components/groupedaccountselector/services.ts
frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/routes/account/summary/accountssummary.tsx
frontends/web/src/routes/account/utils.ts
frontends/web/src/routes/bitsurance/dashboard.tsx
frontends/web/src/routes/settings/manage-accounts.tsx

- rename function to correct typo
- update function parameter type from `TAccountsByKeystore[]` 
to new type `TKeystoreName[]` to  ease type requirements and 
prepare for integration with the lightning account

frontend: update isAmbiguousName function

---

frontends/web/src/api/account.ts
frontends/web/src/routes/account/summary/chart.tsx

Convert the Chart class component in chart.tsx to a functional component.
There some general improvements that could be made, but this PR aims to perform minimal changes to only transform the component from a class component to a functional one. I will open another PR with a general refactor when this one was merged.
note: I moved the `renderDate` function out of the component, but this improvement should've been in the next PR not this one, lmk if I should put it back.

frontend: convert chart.tsx component

---

frontends/web/src/api/devicessync.ts
frontends/web/src/routes/account/send/components/confirm/confirm.tsx
frontends/web/src/routes/account/send/components/confirm/dialogs/confirm-wait-dialog.tsx
frontends/web/src/routes/account/send/components/confirm/types.ts
frontends/web/src/routes/account/send/send.tsx

Move `signProgress` and `signConfirm` into the `ConfirmingWaitDialog`
and `BB02ConfirmSend` sub-components of the `ConfirmSend` sub-component
in `send.tsx`. This simplifies the `Send` component, makes it easier to
understand and is also better separation of bb01 and bb02 stuff.

frontend: move sign confirm and sign progress to sub component

---

go.mod
go.sum
vendor/modules.txt

The mentioned PR was merged and we can move back to upstream.

go.mod: remove temporary karalable/hid patch

---

CHANGELOG.md
go.mod
go.sum
vendor/github.com/BitBoxSwiss/bitbox02-api-go/api/firmware/query.go
vendor/github.com/BitBoxSwiss/bitbox02-api-go/util/sleep/sleep.go
vendor/github.com/BitBoxSwiss/bitbox02-api-go/util/sleep/sleep_macos.go
vendor/modules.txt

To prevent USB communication interruptions when e.g. recovering from 24 words.
See https://github.com/BitBoxSwiss/bitbox02-api-go/pull/111
```
go get github.com/BitBoxSwiss/bitbox02-api-go@88d5934
go mod tidy
go mod vendor
```

prevent sleep on macOS during long running queries

---

frontends/web/src/components/aopp/aopp.module.css
frontends/web/src/components/aopp/aopp.tsx

Tested by patching the `Start` function in `backend` like [this](https://github.com/benma/bitbox-wallet-app/commit/0529615c76c1cb6f2845ef6b9fe4a6aeee171269).
~~I actually forgot to remove the commit, but I guess it is good to leave it in there for reviewers to test the PR. I can remove it in the end. (note the delay is 15 seconds when testing).~~ removed it now.
I tested on `webdev` firefox with BB02B keystore and `servewallet-mainnet`. I tested the following `case` statements form the return: `error` `inactive` `user-approval` `awaiting-keystore`  `signing` 
I think `choosing-account` and `syncing` was tested too and looked fine but it was to fast to take a screenshot.
I think I did not test `success` because I don't know a callback to test aopp with.
Some pictures from testing:

frontend: transform aopp.tsx to funcitonal component

---

frontends/web/src/routes/lightning/send/send.tsx

to avoid displaying the Android keyboard by default on send screen.

frontend/lightning: remove autofocus from LN invoice input

---

frontends/web/src/components/progressRing/progressRing.module.css

Background of the progress ring was white in darkmode. Changed to be dark gray.
cherry picked commit from https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/2936

frontend: fix progress ring background in darkmode

---

frontends/web/src/components/spinner/Spinner.module.css

Some error messages are only partly centered and have no padding to the edge of the container.
Reason:
Spinner is used in account and other components to show loading but also unknown error messages. Each line of the message is rendered in its own paragraph element. Those paragraphs are centered by the parent element using flexbox. As soon as a paragraph contains text that spawns over multiple lines it will cause the paragraph to use the full available width with left aligned text.

frontend: fix layout on mobile for spinner with error message

---

CHANGELOG.md
backend/coins/btc/account.go
backend/coins/btc/account_test.go
backend/coins/btc/coin_test.go
backend/coins/btc/handlers/handlers.go
frontends/web/src/api/account.ts
frontends/web/src/components/badge/badge.module.css
frontends/web/src/components/badge/badge.tsx
frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/send/utxos.tsx

Label utxos that are to change addresses from our account (subaccounts
respectively) as change to give the user more information about the utxo
when selecting it in coin control.

frontend: label change

---

CHANGELOG.md
README.md
backend/accounts.go
backend/accounts_test.go
backend/backend.go
backend/backend_test.go
backend/coins/coin/codes.go
backend/coins/eth/account_test.go
backend/config/accounts_test.go
backend/config/config.go
backend/handlers/handlers.go
backend/rates/gecko.go
backend/rates/rates.go
frontends/web/src/api/account.ts
frontends/web/src/components/amount/amount.test.tsx
frontends/web/src/components/icon/logo.tsx
frontends/web/src/routes/account/utils.ts
frontends/web/src/routes/account/walletconnect/components/incoming-pairing/incoming-pairing.tsx
frontends/web/src/utils/walletconnect.ts

Goerli testnet shut down April 2020.
See also: https://github.com/BitBoxSwiss/bitbox02-firmware/pull/1317

ethereum: remove Goerli testnet

---

backend/handlers/handlers.go
frontends/web/src/api/account.ts
frontends/web/src/routes/account/summary/accountssummary.tsx
frontends/web/src/routes/account/summary/chart.module.css
frontends/web/src/routes/account/summary/chart.tsx
frontends/web/src/routes/account/summary/summarybalance.tsx

This commit adds functionality to display Lightning account
in 'My portfolio' in cases where it is active but not associated
with a connected or remembered wallet, or when all mainnet
accounts in the connected wallet are disabled.
The total coins table is updated to include the Lightning account
Hide chart, percentage change, and filters in my portfolio if
only the lightning account is displayed.

frontend: update 'My portfolio' with lightning account

---

frontends/web/src/components/hideamountsbutton/hideamountsbutton.module.css
frontends/web/src/components/hideamountsbutton/hideamountsbutton.tsx
frontends/web/src/components/layout/header.module.css
frontends/web/src/components/layout/header.tsx
frontends/web/src/routes/account/account.module.css
frontends/web/src/routes/account/account.tsx

Depending on translation, font-rendering on different platforms and
screensize the header buttons sometime break to a new line.
Changed to hide the button text on small screen and only use icons.

frontend: hide buttontext of header buttons on small screen 

---

CHANGELOG.md
frontends/web/src/hooks/qrcodescanner.ts

I.e. when resizing the window or rotating the screen it sometimes crashed.

frontend: make qrscanner more resilient to re-render

---

frontends/ios/BitBoxApp/BitBoxApp/BitBoxAppApp.swift
util/config/appdir.go

Similar to Android, we set `ExportsDir()` to `""` and let the backend environment `getSaveFilename()` construct the full path.
Mobile handling of the dirs/files is a big hack and works on implicit assumptions, e.g. that `getSaveFilename()` is always called with `filepath.Join(exportsDir, filename)`, which is only the filename on mobile as `ExportsDir()` returns `""`. This should be cleaned up, but for now iOS is made to behave like Android in this regard.

ios: fix exporting files (CSV exports, log export, notes export)

---

frontends/web/src/components/balance/balance.module.css
frontends/web/src/routes/account/account.module.css
frontends/web/src/routes/account/account.tsx

ETH can have long decimals (up to 18) and usually shows 4 action buttons: buy, send, receive and walletconnect.
Fixed that the balance is not covered by the action buttons.
Tested with `make servewallet-mainnet-prodservers` to see all action buttons including buy&sell

frontend: fix actionbuttons for eth

---

frontends/web/package.json

This is useful to test the production build of the web frontend locally in the browser.
First do a production build, either by:
- `make buildweb`
- `cd frontends/web && npm ci && npm run build`
Then run the frontend build with:
- `cd frontends/web && npm run preview`

frontends: add vite preview npm task

---

frontends/web/src/routes/account/account.module.css

The action buttons are not aligned with the right edge of the content area, but instead just follow the total balance.
This happens also in Qt6.2.

frontend: fix account action buttons alignment regression

---

.github/workflows/ci.yml

Post messages in channels for build successes and failures of `push` kind of events.
I decided to use two channels because I think different people care about successful and unsuccessful builds. So you can be in the artifacts channel without getting spammed with fail builds for example.
I also added "if-no-files-found: error", since I think it is an error if the final apps are not created.
I didn't wait for the "dry-run" to complete in my repo before opening this PR because pulling the docker images from GHCR takes forever.
https://github.com/NickeZ/bitbox-wallet-app/actions/runs/11650613418
edit: dry run finished, there was a bug. The bug is fixed.

CI: Send messages to mattermost with artifact links

---

frontends/web/src/routes/account/summary/chart.tsx

In some situation the percentage difference did not update.
Test:
- have 1 empty remembered wallet with no history
- unlock a wallet with a history so the chart loads
- remove the wallet
- expected result: total should be 0 with no percentage difference

frontend: reset percentage diff on chart

---

CHANGELOG.md
backend/chart.go
backend/coins/btc/handlers/handlers.go
backend/coins/coin/conversions.go
backend/rates/history.go
backend/rates/history_test.go
frontends/web/src/api/account.ts
frontends/web/src/components/amount/amount.tsx
frontends/web/src/components/balance/balance.test.tsx
frontends/web/src/components/transactions/components/details-dialog.tsx
frontends/web/src/components/transactions/transaction.tsx
frontends/web/src/routes/account/send/feetargets.test.tsx

In the account transaction list we used to show the fiat equivalent of each tx amount, using the latest fiat rates. We decided that it was not the best option, and could confuse users looking at past txs.
This changes the behavior showing the historical fiat amount instead. If the historical amount is not available (e.g. tx not confirmed yet or historical rates not updated), and the tx is recent enough, it will make an estimation using the latest rates.
In case of estimation, the fiat conversion will have a `≈` char prefix.
If the historical fiat rates are not available and the tx is older, a `---` will be shown, as in the tx details popup.
NOTE: 
While testing please consider that historical fee rates lags behind the latest ones for about 45mins and that testnet tx timestamps are …

frontend/transactions: show historical fiat value in txs list

---

backend/exchanges/btcdirect.go
backend/handlers/handlers.go
frontends/web/src/api/exchanges.ts
frontends/web/src/routes/exchange/components/buysell.tsx

3d1603c9b added frontend support for BtCDirect integration, but that was relying on pocket bitcoin regional availabilities to display the BtcDirect informative panel. This commit adds proper backend support.
The BtcDirect panel is now also shown in case of failure of the `getExchangeDeals` call or payment request errors.

backend/exchanges: add btcDirect support

---

frontends/web/src/app.tsx
frontends/web/src/hooks/drop.ts

The app currently accepts dropping files into the app window and tries to render those. This will error with a blocked error without any way to go back making the app unusable.
Added a hook to globally ignore dropped files.

frontend: ignore files dropped into the app window

---

frontends/web/src/components/amount/amount.tsx
frontends/web/src/components/transactions/transaction.module.css
frontends/web/src/components/transactions/transaction.tsx

The estimate (≈) symbol should be placed before the amount and sign separated by a white-space.
Example:
≈ +100.-

frontend: fix estimate symbol

---

CHANGELOG.md
frontends/web/src/contexts/BackButtonContext.tsx

The Android back button stopped working after the back button was used to close a dialog. The reason is that the backbutton pop handler did not remove the handler, as `slice(index, 1)` does not remove the element at `index`, it in fact keeps it. When properly removing the handler, back button behavior works as expected again.

frontend: fix back button with UseBackButton

---

CHANGELOG.md
frontends/web/src/components/auth/authrequired.tsx

The auth screen was sometimes showed for a very short time at startup even when it was disabled. This fixes the glitch, hiding the auth screen details while the backend checks if the auth config is enabled.

frontend/auth: fix auth screen glitch on startup

---

.github/workflows/ci.yml

Mantaining a json-blob is not as easy as maintaining a yaml multiline string. I don't think icon_emoji and props/card pull their weight for us to use the "PAYOLOAD" field instead of the "TEXT" field.

ci: More maintainable code

---

frontends/web/src/routes/account/summary/chart.module.css
frontends/web/src/routes/account/summary/chart.tsx

Before the chart on account-summary goes into mobile view below 640px causing the total balance and filters to have no spacing to the edge of the window if the window was between 640px and 678px.
Fixed by increasing the mobile style to be applied until 678px.

frontend: fix minor spacing issue on medium size screens

---

CHANGELOG.md
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java

Moonpay recently released a new widget update that requires the webview to access the DOM storage, causing our iframe integration to fail loading the widget on Android. This fixes the DOM access issue.

frontend/android: fix moonpay widget

---

backend/exchanges/btcdirect.go

BTC Direct supports buying and selling LTC through their private trading desk, so the link and info should also be shown to Litecoin accounts on exchange selection.

backend: add litecoin to btcdirect supported coins

---

frontends/web/src/utils/markup.test.tsx
frontends/web/src/utils/markup.tsx

The SimpleMarkup component allows translations to contian a strong element to emphasize parts of the text.
There is a bug that if the same translation contains newlines it renders the strong element as text.
Changed to that the regex takes multiline into account.

frontend: improve simple markup parsing

---

.golangci.yml
backend/accounts.go
backend/aopp_test.go
backend/coins/btc/account.go
backend/coins/btc/db/transactionsdb/transactionsdb_test.go
backend/coins/btc/electrum/electrum.go
backend/coins/btc/electrum/electrum_test.go
backend/coins/btc/maketx/maketx.go
backend/coins/btc/maketx/txsize_internal_test.go
backend/coins/coin/amount_test.go
backend/devices/bitbox/keystore.go
backend/devices/bitbox/pairing_test.go

Since Go 1.22, the issue of the loop variable being reused in closures has been fixed, so the `copyloopvar` workaround is no longer needed. This commit re-enables the `copyloopvar` linter, disables exportloopref linter (deprecated and replaced by copyloopvar) and refactors the code to remove redundant assignments. See also: https://go.dev/doc/go1.22

backend: re-enable copyloopvar linter and refactor code

---

CHANGELOG.md
backend/update.go
frontends/android/BitBoxApp/app/build.gradle
frontends/ios/BitBoxApp/Config.xcconfig
frontends/qt/Makefile
frontends/qt/main.cpp
frontends/qt/resources/MacOS/Info.plist
frontends/qt/setup.nsi

The only "problem" left is that the console logs
Please register the custom scheme 'bitboxapp' via QWebEngineUrlScheme::registerScheme() before installing the custom scheme handler.
But it seems to work anyway. I couldn't figure out how to get rid of this message.

Linux blank screen fix

---

CHANGELOG.md
frontends/web/src/components/transactions/transaction.module.css
frontends/web/src/components/transactions/transaction.tsx

Long transaction notes were only shown on one line and cut off by an ellipsis symbol.
Fixed by always showing the full transaction note and break onto multiple lines if necessary.
Transactions without notes show as a fallback a comment such as `received to <address>` which should only use one line and is cut off with an ellipsis...

frontend: show the full text of long transaction notes

---

CHANGELOG.md
backend/coins/btc/handlers/handlers.go
frontends/web/src/components/transactions/components/arrows.tsx
frontends/web/src/components/transactions/transaction.module.css
frontends/web/src/components/transactions/transaction.tsx
frontends/web/src/components/transactions/utils.ts

Until now a send-to-self transaction looked more like an outgoing transaction with the amount sent.
Changed to only show the fee paid as outgoing and the amount of coin as conversion amount.

frontend: change transaction info for send-to-self

---

CHANGELOG.md
frontends/web/src/app.tsx
frontends/web/src/components/guide/guide.module.css
frontends/web/src/components/layout/main.module.css
frontends/web/src/hooks/platform.ts
frontends/web/src/style/base.css

Changed to use native scrollbars on macOS, iOS and Android.
Only keep custom scrollbar CSS for Linux and Windows.

frontend use default scrollbars on macOS, iOS and Android

---

.github/workflows/ci.yml

This adds a GitHub Action job to build the Windows app and create the installer. Artifacts will be reported on Mattermost, like with other platforms.
Notable differences to our previous Appveyor CI:
* The GitHub windows-2019 image comes with Vistual Studio Enterprise instead of the Community edition. A directoy junction is created to point calls from the Community to the Enterprise path.
* NSIS, MinGW and Make are pre-installed already, not requiring any installations with choco anymore.
* Qt is not pre-installed anymore and now installed using an Action.
Because there are no changes to other files, the Appveyor build will continue to work and can be used in parallel.

ci: build windows app and report artifact

---

CHANGELOG.md
frontends/web/src/routes/bitsurance/widget.tsx
frontends/web/src/routes/exchange/pocket.tsx

Pocket and Bitsurance integrations both feature an address signing request in their widgets. With the previous implementation any re-rendering of the component (e.g. because of screen rotation on phone) caused the loss of the widget reference and the fail of the request. This commit fixes the bug.

frontend/widget: fix loosing iframe ref on screen rotation

---

frontends/web/.eslintrc.json
frontends/web/src/api/subscribe.ts
frontends/web/src/components/forms/select.tsx
frontends/web/src/components/icon/logo.module.css
frontends/web/src/components/icon/logo.tsx
frontends/web/src/contexts/WCWeb3WalletProvider.tsx
frontends/web/src/i18n/i18n.test.tsx
frontends/web/src/routes/account/info/buyReceiveCTA.tsx
frontends/web/src/routes/account/info/info.tsx
frontends/web/src/routes/account/send/feetargets.tsx
frontends/web/src/routes/account/walletconnect/components/incoming-pairing/incoming-pairing.tsx
frontends/web/src/routes/device/bitbox01/restore.tsx
frontends/web/src/routes/device/bitbox01/settings/components/mobile-pairing.tsx
frontends/web/src/routes/device/bitbox01/setup/goal.jsx
frontends/web/src/routes/device/bitbox01/setup/initialize.tsx
frontends/web/src/routes/device/bitbox01/setup/security-information.tsx
frontends/web/src/routes/device/bitbox01/setup/seed-create-new.jsx
frontends/web/src/routes/device/bitbox01/setup/seed-restore.jsx
frontends/web/src/routes/device/bitbox01/setup/success.jsx
frontends/web/src/routes/device/bitbox02/passphrase.tsx
frontends/web/src/routes/device/bitbox02/setup/name.tsx
frontends/web/src/routes/settings/components/appearance/defaultCurrencyDropdownSetting.tsx
frontends/web/src/routes/settings/components/appearance/languageDropdownSetting.tsx
frontends/web/src/routes/settings/components/device-settings/attestation-check-setting.tsx

So that we do not accidentally pass undefined, null, booleans or just any type in tempalte literals, see:
`all these should error ${false} ${undefined} ${[]} ${null}`
This is a eslint rule, so only make weblint will check.

frontend: add eslint rule restrict-template-expressions

---

CHANGELOG.md
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
frontends/web/src/routes/settings/components/appearance/notesImport.tsx

and add mime type handling in Android filepicker.
Before this, the file picker was allowing the user to select non-text files for notes import. Now this choice is restricted to *.txt files on Qt and text/plain files on Android and iOS (as it is not possible to filter single file extensions with the default file picker).

frontend/notes: filter text files on notes import

---

frontends/web/src/api/account.ts
frontends/web/src/routes/account/send/components/confirm/confirm.tsx
frontends/web/src/routes/account/send/components/confirm/dialogs/confirm-wait-dialog.tsx
frontends/web/src/routes/account/send/components/confirm/types.ts
frontends/web/src/routes/account/send/send-wrapper.tsx
frontends/web/src/routes/account/send/send.tsx
frontends/web/src/routes/account/utils.test.ts

replaces https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/2955

Frontend send refactor

---

frontends/web/src/routes/account/send/feetargets.tsx

The fees dropdown show useful information such as expected
time, or with config.frontend.expertFee current cost sat/vB.
This change enables opening the dropdown to see the current fees.
Added disabled to the 'custom' option so it is only selectable if
there is valid txinput data (such as address and amount).

frontend: keep fees dropdown always enabled

---

frontends/web/src/api/bitbox01.ts
frontends/web/src/hooks/sdcard.ts
frontends/web/src/routes/account/send/send-wrapper.tsx
frontends/web/src/routes/device/bitbox01/backups.tsx
frontends/web/src/routes/device/bitbox01/settings/settings.jsx
frontends/web/src/routes/device/bitbox01/setup/seed-create-new.jsx
frontends/web/src/routes/device/bitbox01/setup/seed-restore.jsx
frontends/web/src/routes/device/bitbox01/upgrade/require_upgrade.jsx

The device info endpoint can return null this can happen when a BB01 is plugged in but not yet unlocked.

frontend: fix bb01 device-info type

---

frontends/web/src/components/transactions/transaction.tsx

As the send-to-self amount is in coins there is no need to show an estimate symbol in front of the amount.

frontend: hide estimated symbol for send-to-self transactions

---

frontends/web/src/routes/account/summary/chart.tsx

On mobile the total changes when the user selects a point on the chart so that they can see exact amount at the time.
With scrolling or 2nd finger changing the currency it can happen that the amount does not update, ending up with a wrong amount/unit.
Fixed by resetting the tooltip value if the currency changes.

frontend: fix chart edgecase to properly update the total amount

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/lightning/activate.tsx

As the user needs to confirm on the device, the app UI should block and disallow going back.

frontend: use blocking view for create ln wallet step

---

frontends/qt/genassets.sh

The order of `find` results is non-deterministic, which breaks build reproducibility.

chore: sort web assets before generating RCC file

---

frontends/qt/server/Makefile.linux
frontends/qt/server/Makefile.windows

Fix Makefile.linux and Makefile.windows clean target so it does not error if files are absent. Add -f to the rm command in make clean to avoid failure when files do not exist.

build: fix clean error if file does not exist

---

scripts/dockerdev.sh

Recent commit ace02fe8aeb23c4ad2b49ec9c144397d32a6d383 introduced versioning for the app container. The commit introduced a bug that causes `make dockerdev` to fail when there is a stopped container that matches the current version. This fixes the bug.

container: fix bug in make dockerdev

---

frontends/web/src/components/transactions/transaction.tsx

Until a transaction has 6 confirmations we do show a estimation sign for the conversion amount as the exact time is still not final.
The user can optionally choose BTC or sat as conversion unit in these cases no estimation sign is needed.

frontend: hide estimate sign if conversion is btc or sat

---

backend/handlers/handlers.go
frontends/web/package.json
frontends/web/vite.config.mjs

This PR makes it possible to run the frontend on a port different from 8080.
There are 2 main changes:
1) Vite config is changed by adding `strictPort = true`
2) The port can be specified by an env var `VITE_PORT`. If not specified, it will default to 8080.
I feel 1 is the "mandatory" part of the PR. It makes no sense to allow the frontend to try different ports as it won't be able to connect to the backend anyway.
part 2 is optional, I think it's nice to allow to use another port. But if people object, I'd happily remove it and just leave 1.

frontend: allow frontend to run not on port 8080

---

CHANGELOG.md
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/ClipboardHandler.java
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
frontends/qt/main.cpp
frontends/web/src/components/copy/Copy.tsx
frontends/web/src/routes/exchange/pocket.tsx

This enables the use of the `navigator.clipboard` JS api to read/write the clipboard on both Qt and Android and in particular:
- fixes the copy buttons in the Pocket order confirmation page
- updates the api of the CopyableInput component

frontend: enable clipboard read/write for android/qt

---

frontends/web/package.json

This makes the webdev app running inside docker accessible from the host

config: add --host parameter to vite app npm start script

---

backend/coins/btc/electrum/client.go

The error message coming from electrum contains the serialized transaction and we do not want it in the logs, for privacy reasons, so we strip the entire error.
I opened a PR on their side to remove the raw tx from the error altogether: https://github.com/spesmilo/electrumx/pull/286/files

backend: do not log error containing serialized tx

---

backend/accounts/transaction.go
backend/accounts/transaction_test.go
backend/coins/btc/handlers/handlers.go
frontends/web/src/api/account.ts
frontends/web/src/components/amount/conversion-amount.tsx
frontends/web/src/components/transactions/transaction.tsx

Move the logic to compute the deducted amount out of the handlers exclude erc20 tokens from the computation.

backend: show deducted amount only for non-erc20.

---

backend/exchanges/btcdirect.go

This updates the list of countries where BTC Direct services are available.

backend/btcdirect: update countries

---

frontends/ios/BitBoxApp/BitBoxApp.xcodeproj/project.pbxproj
frontends/ios/BitBoxApp/BitBoxApp/BitBoxAppApp.swift
frontends/ios/BitBoxApp/BitBoxApp/Bluetooth.swift
frontends/ios/BitBoxApp/BitBoxApp/Info.plist

In this initial prototype, the app connects to the bluetooth dev-kit and wires up communication so the BitBoxApp can talk to it as if it was a BitBox02. In the future we want to enumerate BitBoxes in the UI,
but for now we simply connect to the devkit immediately.
The backend environment DeviceInfo function is used by the backend to recognize if a device is connected. We use it to recognize a bluetooth device. The interface is geared for USB HID devices, so for now we simply pretend to be a USB device. In a future PR we should change the DeviceInfo to be more generic, or have a separate method for Bluetooth devices.

ios: add initial bluetooth functionality

---

backend/exchanges/btcdirect.go
backend/exchanges/exchanges.go
backend/handlers/handlers.go
frontends/web/src/api/exchanges.ts
frontends/web/src/routes/exchange/components/buysell.tsx

Remove the hardcoded BtcDirect widget from the frontend code, ad instead add it to the returned list of exchange deals in the backend.

backend: add BtcDirect to exchange deals.

---

CHANGELOG.md
backend/backend.go
backend/bridgecommon/bridgecommon.go
backend/devices/usb/manager.go
backend/mobileserver/mobileserver.go
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/GoService.java
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java

The ACTION_USB_DEVICE_DETACHED intent in MainActivity was not handled by the app while it was in the background.
Resulting bug:
- when you disconnect an unlocked device while the app is in the background, and bring the app to the foreground again, the previous unlocked keystore is visible, as the backend didn't register the disconnet.
- same when the user disconnects the device while the app is in the background, and reconnects it before bringing it to the foreground. Ths is a special case, simply calling `updateDevice()` in `onResume()` would not handle this correctly, as a device would be connected, and an intermediate disconnect could not be detected.
To fix this, we detect the DETACH intent in the service, and trigger the backend to handle it.

android: handle device disconnect while the app is in the background

---

backend/arguments/arguments.go
backend/exchanges/btcdirect.go
backend/handlers/handlers.go
frontends/web/src/api/exchanges.ts
frontends/web/src/routes/exchange/btcdirect.tsx

Provide an endpoint to be called from the frontend. This endpoints returns the APIKey, the URL address and, if the action is "buy", the address.

   backend: provide getBtcDirectInfo API endpoint

---

backend/handlers/handlers.go
frontends/web/src/api/backend.ts
frontends/web/src/contexts/AppContext.tsx
frontends/web/src/contexts/AppProvider.tsx
frontends/web/src/routes/exchange/btcdirect.tsx

and use it in the frontend to correctly set the BTCDirect widget params.

backend: add /dev-servers endpoint

---

frontends/web/public/btcdirect/fiat-to-coin.html
frontends/web/public/btcdirect/polyfill.js
frontends/web/src/routes/exchange/btcdirect.tsx

The previous approach depended on the iframe having access to the parent context, but this wont work when the iframe is hosted on a different domain.
Instead of relaxing webengine restrictions this change simply uses postMessage api to pass data from and to the iframe.

frontend: use postmessage to communicate with the iframe

---

CHANGELOG.md
backend/accounts.go
backend/backend.go
backend/config/config.go
frontends/web/src/locales/en/app.json
frontends/web/src/routes/settings/advanced-settings.tsx
frontends/web/src/routes/settings/components/advanced-settings/restart-in-testnet-setting.tsx

Adds a button in the advanced settings that enables the app to start in testnet automatically on the next start. The setting is only valid for the next start, and it gets reset after that.
(note: the "enabled" text near the option has been removed, this is a slightly older screenshot)
Note that this PR does not automatically restart the application. This would require a lot more investigation on how to do it properly on all platforms.

backend/frontend: add option to restart in testnet

---

frontends/web/src/routes/exchange/btcdirect.tsx

Instead of deriving the coin/token unit from coinCode somehow,
the app can just pass account.coinUnit.
Fixes missing baseCurrency error when using ERC20 tokens, with the
drawback that in testnet the app now passes TBTC. BTC Direct does
not support testnet addresses nor testnet coins and will fallback
to just BTC.

frontend: fix missing base currency in btc-direct widget

---

frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java

Some payment providers such as iDEAL or SOFORT need to breakout the BitBoxApp and be continued in a native browser.
From https://checkout.btcdirect.eu/ the user fills in the bank they are using and will get redirected to their banking environment.
On mobile the bank may use intent links to automatically open and continue in the banking app.

backend: allow opening checkout.btcdirect.eu

---

frontends/web/public/btcdirect/fiat-to-coin.html

The feature below adds an additional tab to the Fiat to Coin widget, which includes the full Dollar Cost Averaging (DCA) widget.

frontend: enable btcdirect dca option

---

backend/accounts/transaction.go
backend/accounts/transaction_test.go

Default to show the amount of the tx for all transactions, and then add the fee for non-erc20 ones.

frontend: show correct amount for ERC20 tokens.

---

CHANGELOG.md
backend/accounts/baseaccount.go
backend/accounts/baseaccount_test.go

ERC20 tokens are now exported with the correct value for "unit" Added a new column "FeeUnit" as the fee is displayed in ETH/wei for ERC20 tokens.

frontend: fix export to CSV for ERC20 Tokens.

---

CHANGELOG.md
frontends/qt/setup.nsi

Currently, Windows users need to manually create a desktop shortcut. 
This PR creates a desktop shortcut during the installation process.

qt: create windows desktop shortcut during installation

---

backend/devices/bitbox02/handlers/handlers.go
backend/devices/bitbox02bootloader/firmware.go
backend/devices/usb/manager.go
frontends/web/src/api/bitbox02.ts
frontends/web/src/routes/settings/components/device-settings/firmware-setting.tsx
go.mod
go.sum
vendor/github.com/BitBoxSwiss/bitbox02-api-go/api/bootloader/device.go
vendor/github.com/BitBoxSwiss/bitbox02-api-go/api/common/common.go
vendor/github.com/BitBoxSwiss/bitbox02-api-go/api/firmware/device.go
vendor/github.com/BitBoxSwiss/bitbox02-api-go/api/firmware/pairing.go
vendor/github.com/BitBoxSwiss/bitbox02-api-go/api/firmware/query.go
vendor/github.com/BitBoxSwiss/bitbox02-api-go/util/semver/semver.go
vendor/modules.txt

```
go get github.com/BitBoxSwiss/bitbox02-api-go@2b90fad
go mod tidy
go mod vendor
```

vendor: update bitbox02-api-go

---

backend/exchanges/btcdirect.go
backend/exchanges/exchanges.go
frontends/web/src/api/exchanges.ts
frontends/web/src/routes/exchange/components/buysell.tsx
frontends/web/src/routes/exchange/components/exchange-providers.tsx

This allows to hide specific deals in the frontend deals list. e.g. when the exchange offers several payment methods with different fees. The deals are still used to show all the payments and fees in the info box.

backend: add isHidden property in exchange deals

---

frontends/web/public/btcdirect/back-to-app.html
frontends/web/src/routes/exchange/btcdirect.tsx

Added support to navigate back to the accounts view.
Added a 'back-to-app' message that routes to accounts, the widget will need to send this message once the user clicks 'Back to app'.

frontend: btcdirect allow to navigate back to accounts

---

backend/backend.go
frontends/web/src/routes/settings/advanced-settings.tsx
frontends/web/src/routes/settings/components/advanced-settings/restart-in-testnet-setting.tsx

Typo in config var, and the flag was never reset.

backend: fix restart in testnet

---

CHANGELOG.md
backend/coins/btc/account.go
backend/coins/btc/account_test.go

Run ensureAddresses in a separate goroutine.
This way the call is not blocking and the initializeLock can be released, which allows the device to be restarted in bootloader mode and the firmware upgrade process to start.
This way, `ensureAddresses` will keep running in the background and if connection is restored later, it will terminate correctly.
This has been tested on MacOS with Qt: note that if running this in webdev mode it won't work, as when the app is offline there is no way to reach the "manage device" option as it will hang forever.
The following in a screen recording that shows the correct behaviour.
https://github.com/user-attachments/assets/3818a8b1-2730-4e6e-a14f-b00632f720da
Before asking for reviews, here is a check list of the most common things you might need to …

backend: allow firmware upgrade when app is offline.

---

frontends/web/src/routes/exchange/btcdirect-otc.tsx
frontends/web/src/routes/exchange/components/buysell.tsx

Changes back to the correct link to the BTC Direct OTC desk.

frontend/btcdirect: use correct private trading desk link

---

cmd/servewallet/main.go
frontends/web/src/components/guide/entry.tsx
frontends/web/src/components/language/language.test.tsx
frontends/web/src/components/language/language.tsx
frontends/web/src/i18n/config.test.tsx
frontends/web/src/i18n/i18n.test.tsx
frontends/web/src/i18n/i18n.ts
frontends/web/src/routes/settings/components/appearance/languageDropdownSetting.tsx

This reverts commit 88f6a0c2e76430b715f5e96c2f93dd1fb11f4c5b, reversing changes made to eeef19ce961c109f1f7402fac6e8c2e64f061ab1.
This PR (lazy loading of languages) caused the app to have a whitescreen sometimes at launch.

Revert "Merge branch 'lazy-load-lang-defaults'"

---

frontends/web/src/app.tsx
frontends/web/src/locales/en/app.json
frontends/web/src/routes/device/no-device-connected.module.css
frontends/web/src/routes/device/no-device-connected.tsx
frontends/web/src/routes/router.tsx
frontends/web/src/routes/settings/components/tabs.tsx

Conditionally hiding navigation items is not ideal and can be confusing.
Another reason to always show 'Manage device' but with 'No device connected' is to have a place to add detect-bitbox button.
With this change the app will route into device settings if the user unlocks on no-connected-device route.
It does not cover showing no-connected-device again after the user unplugs, reason is that with rememeber-wallets this should go to account-summary and without go to waiting for device. There was no clean way to detect and route back to no-connected-device.
Ideally the 'Manage accounts' item is also always shown in settings navigation, which can be done in another commit.

frontend: always show manage-device in settings menu

---

backend/coins/btc/account_test.go

With ensureAddresses running in a separate goroutine, it might happen that after a call to account.Initialize() we perform checks that fail because the ensureAddresses goroutine hasn't completed yet.
By adding a call to require.Eventually we ensure that the account gets eventually synced (within a second) before proceeding with the rest of the test.

test: ensure that account is eventually synced.

---

scripts/check-locize-placeholders.py

If a translation is left empty, it falls back to English. In this case we should not check that the placeholders match, it would be a false positive.

ci: fix locize placeholder check on empty strings

---

frontends/qt/resources/MacOS/entitlements.plist

After updating to Qt 6.8.2, when signed, the app launched with a gray screen. Updating the entitlements according to
https://doc.qt.io/qt-6/qtwebengine-deploying.html#macos-specific-deployment-steps fixes that.

qt: update entitlements.plist for signing

---

backend/exchanges/btcdirect.go

BTC Direct has ceased supporting Tether (USDT)
- https://support.btcdirect.eu/hc/en-gb/articles/24592747089298-BTC-Direct-has-ceased-supporting-Tether-USDT

backend: remove usdt from btcdirect

---

backend/accounts/transaction_test.go
backend/coins/btc/handlers/handlers.go
frontends/web/src/components/amount/conversion-amount.tsx

Fixes the shown amount by allowing `formatJSONAmountAtTime` to work with a nil timestamp

frontend: fix shown amount for unconfirmed ETH txs

---

CHANGELOG.md
backend/update.go
frontends/qt/Makefile

Unfortunately the Comments before the `-extra-plugins` without line-break delimiter made it a separate command. The `-` in Makefile means `extra-plugins` is executed ignoring errors. This combination made CI pass without Wayland plugins actually being deployed.
Fixes #3229.

qt: fix support for Wayland on linux

---

backend/backend.go
frontends/web/src/routes/exchange/components/infocontent.tsx

BTC Direct updated their private trading desk links and asked us to change them.

btcdirect: update private trading desk links

---

backend/coins/btc/transactions/transactions.go
backend/devices/bitbox02/keystore.go
backend/rates/history_test.go

make function comment match function name

chore: make function comment match function name

---

frontends/web/.eslintrc.json
frontends/web/src/components/transactions/components/details-dialog.tsx
frontends/web/src/routes/account/send/components/confirm/dialogs/confirm-wait-dialog.tsx

It is considered good practice to use the type-safe equality operators === and !== instead of their regular counterparts
== and !=.
https://eslint.org/docs/latest/rules/eqeqeq

frontend: check for strict equal eslint rule

---

backend/coins/btc/handlers/handlers.go
frontends/web/src/components/amount/conversion-amount.tsx

ETH transactions do not have a "Created" timestamp we can't provide an estimated conversion based on that. We use real-time conversion instead. 
We also remove the skeleton for the cases in which a conversion is still not available: 

backend: show estimated conversions for unconfirmed ETH txs and remove skeleton when conversions are missing.

---

backend/devices/bitbox02/keystore.go

If downloading prevTx fails, it would be useful to see it in the logs.

backend/bitbox02: add some logging

---

frontends/web/src/routes/account/account.tsx

1260e54a628cfaca695a28d205fb21a96116a570 and
a3dee6b7f1a7781cb1c728e9f5f016b303eaeeb2 had a semantic merge conflict that only manifested after merge.

frontend: fix merge conflict

---

backend/devices/bitbox02/keystore_simulator_test.go

CI often fails in this step, this is an attempt to fix that.

backend/bitbox02: give simulator test more time to connect

---

frontends/web/src/components/layout/header.tsx
frontends/web/src/components/sidebar/sidebar.module.css
frontends/web/src/components/sidebar/sidebar.tsx
frontends/web/src/contexts/AppContext.tsx
frontends/web/src/contexts/AppProvider.tsx
frontends/web/src/routes/device/bitbox01/bitbox01.jsx

In the early versions of the BitBoxApp the sidebar had to be activelly hidden. This was needed for example during the setup to hide the sidebar.
https://github.com/BitBoxSwiss/bitbox-wallet-app/commit/737c7051af5e911cc267f48fec11da0f7571729c#diff-dfe1a46131ddaf4054e57c25f15a90037702158127d8959711cbcab68fac0418R161
In newer versions the setup view just covers everything so there is no need to actively hide the sidebar.
Most related code has already been removed, but there was still a case in BitBox01 setup and the code in the context, which can now be removed.

frontend: cleanup and remove unused sidebar related code

---

frontends/ios/BitBoxApp/BitBoxApp/BitBoxAppApp.swift
frontends/ios/BitBoxApp/BitBoxApp/Info.plist

@bznein fyi:
Cancelling an authentication normally should show the 'Authenticate' button to try again, but cancelling the auth when enabling the screen lock in the advanced settings should do nothing (just cancel the screen lock setup). Before this PR, cancelling the setup was buggy.

Ios screenlock

---

backend/accounts/account.go
backend/coins/btc/handlers/handlers.go
backend/coins/btc/transaction.go
frontends/web/src/api/account.ts
frontends/web/src/routes/account/send/send.tsx
frontends/web/src/routes/exchange/pocket.tsx

Previously, the highest fee rate was automatically applied to all transaction proposals with a SLIP-24 payment request. For selling and spending integrations that do not use SLIP-24 payment requests, there should also be an option to trigger this same behaviour.
This commit replaces the previous conditioning on payment requests with a general boolean field that is set independently and can be used for other integrations. This also allows setting a custom fee rate for transaction proposals with payment requests, if needed.

backend: add argument to force highest fee rate in tx proposal

---

backend/handlers/handlers.go

The frontend call that used it was removed in 4d30d09222eb35b248503ad4965b3ae70c40b151

backend/handlers: remove unused /rates

---

backend/accounts/baseaccount.go
backend/coins/btc/account.go
backend/coins/btc/account_test.go
backend/coins/btc/handlers/handlers.go
backend/coins/btc/synchronizer/synchronizer.go
backend/coins/btc/transaction.go
backend/coins/btc/transactions/transactions.go
backend/coins/eth/account.go
backend/coins/eth/account_test.go
backend/handlers/handlers.go
frontends/web/src/api/account.ts
frontends/web/src/components/groupedaccountselector/services.ts
frontends/web/src/routes/account/account.tsx
frontends/web/src/routes/account/send/send.tsx
frontends/web/src/routes/account/summary/accountssummary.tsx
frontends/web/src/routes/accounts/all-accounts.tsx
frontends/web/src/routes/bitsurance/dashboard.tsx

Note: this is still VERY MUCH Work In Progress. Feel free to take a look at the overall logic but be aware that it needs to be cleaned up and there are still TODOs
We don't want calls to Balance, Transactions,
GetUnusedReceiveAddressesses and SpendableOutputs to block as this can cause calls to pile up and consume resources; also, this calls can be made irrelevant if the user switches to a different page.
Instead, while the first sync is in progress, we return an appropriate error. After that, every call returns the latest known state.

backend: remove blocking API calls.

---

frontends/web/src/routes/account/send/components/confirm/confirm.tsx

When confirming transaction details on the device the app should block native Android back.

frontend: disable native back in confirm send step

---

frontends/web/src/components/sidebar/sidebar.tsx

In recent commit the hamburger navigation was replaced by bottom menu navigation on mobile. Note: we still use the hamburger on medium sized screens.
See a6d6af08191fc1b8c40c1352e62a6f5d1548df4c
The sidebar contained some code to listen for swipe events to open and close the sidebar on mobile. So when a user swipes from left to right in order to go back, it could happen that the swipe listener takes over and opens the sidebar instead of going back 1 step in history.
Removed the swipe listener in this commit.

frontend: remove code for swiping the sidebar

---

CHANGELOG.md
frontends/web/src/routes/account/utils.ts

The current GetCoinCode logic omits erc20 tokens, so we just use the "standard" text for confirmation time. 
With this change, we return "eth" for erc20 tokens so that we can show the correct confirmation time.

frontend: fix confirmation time for ERC20 tokens.

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/settings/advanced-settings.tsx
frontends/web/src/routes/settings/components/advanced-settings/restart-in-testnet-setting.tsx
frontends/web/src/routes/settings/components/advanced-settings/unlock-software-keystore.tsx

The testnet toggle was not active in testnet. Changing this settings require an app restart, this was only communicated by an inline message and could be easily missed.
This commit improves the UX by:
- changing the toggle to a normal settings item
- showing activate / deactivate instructions
- adding a blocking view that calls to restart the app

frontend: improve restart in testnet

---

frontends/web/src/routes/device/waiting.tsx

It's important to see the testnet warning early, otherwise it's very hard to see if one is in testnet mode.
It's also good to see the mobile data warning *before* one connects a device and all the data starts being used.

frontend: show global banners in the wait screen too

---

frontends/web/src/routes/settings/components/advanced-settings/restart-in-testnet-setting.tsx

There is no action to be performed on the BB02.

frontend: don't show the BB02 logo when switching testnet mode

---

frontends/web/src/routes/account/account.module.css
frontends/web/src/routes/account/actionButtons.tsx
frontends/web/src/routes/account/info/buy-receive-cta.tsx
frontends/web/src/routes/account/utils.ts

With the new bottom menu the app always prominently shows 'Buy & sell'
on mobile, so there is no need to show and clutter the send, recieve
buttons.
also added 3 small cleanup commits

frontend: hide exchange button on mobile

---

frontends/web/src/routes/exchange/btcdirect.tsx

This fixes the following error:
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('bitboxapp:') does not match the recipient window's origin ('https://bitboxapp.shiftcrypto.io')
Posting 'configuration' in handleConfiguration already works and was missing in the two new postMessage's that are used to 'confirm-transaction-id' and 'cancel-order'.

frontend: fix postmessage error

---

backend/accounts.go
backend/coins/eth/coin.go
backend/devices/bitbox02/device.go
backend/handlers/handlers.go

Inspired by https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/3298, I had ChatGPT come up with an ugly but working bash script that finds all duplicate imports. It looks like golangci doesn't have a linter for this specific.

chore: remove duplicate imports.

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/exchange/btcdirect.tsx

So far only PocketBitcoin has a sell option for Bitcoin only.
Added generic.sell with new translation for BTC Direct sell widget.

frontend: set view title to sell bitcoin/crypto for sell widget

---

backend/keystore/software/software.go

With this addition, we can use ETH accounts in a software keystore. As shown in the screenshot, accounts can be added, and they can correctly receive/send/send-to-self:

backend: add eth account to software keystore.

---

backend/backend_test.go
backend/coins/btc/account.go
backend/coins/btc/addresses/address.go
backend/coins/btc/addresses/address_test.go
backend/coins/btc/addresses/addresschain.go
backend/coins/btc/addresses/addresschain_test.go
backend/coins/btc/addresses/test/test.go
backend/coins/btc/types/types.go
backend/devices/bitbox02/keystore_simulator_test.go

The relative keypath always has two elements, the first element indicating change and the second indicating the address index.
A relative keypath of arbitrary length is harder to handle. E.g. it is not compatible with output descriptors with multipath indices (`xpub/<0;1>/*`), where also two elements are required to derive an address (the multipath index selecting between `<X;Y>` and the address index).
The unit tests change because the GetAddress test function used an empty relative path instead of a chainIndex and addressIndex, which now was forced to change with the stricter types.
I considered keeping `ChainIndex uint32` instead of `Change bool`,
because in multipaths, one could have more than two,
e.g. `xpub/<X;Y;Z>/*`, but I prefer the stricter type and it's not
likely we will ever …

backend/btc/address: be explicit about chainIndex/addressIndex

---

backend/signing/keypath.go

Optimize code using a more modern writing style.   Official support from Go, for more details visit https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.

refactor:replacing append([]T(nil), s...) by slices.Clone(s) added in go1.21

---

frontends/ios/BitBoxApp/BitBoxApp/Bluetooth.swift

Before https://github.com/BitBoxSwiss/bitbox02-firmware/pull/1447/, the product characteristic version string didn't include a 'v' prefix, but after it does.
The app backend requires it to parse the version.
We handle both cases for backwards compatibility.

ios: handle version with and without `v` prefix

---

frontends/web/package.json
frontends/web/vite.config.mjs

Qt was upgraded to 6.8.2 which includes a newer chromium version in 84a8a71ab80701f493602221e80464491f110a2d
Bumped build target in vite config, this saves a few bytes.
- https://github.com/BitBoxSwiss/bitbox-wallet-app/commit/84a8a71ab80701f493602221e80464491f110a2d
- https://wiki.qt.io/QtWebEngine/ChromiumVersions
- https://vite.dev/guide/build#browser-compatibility
- https://esbuild.github.io/api/#target
Browserlist in package.json seems to be only supported by vite plugin-legacy, see:
- https://github.com/vitejs/vite/tree/main/packages/plugin-legacy#targets
Removed Browserlist in package.json.

frontend: set vite/esbuild build target to chrome 122

---

frontends/web/public/btcdirect/coin-to-fiat.html

Using set-parameters was the recommended way for the buy widget but does not work for the sell widget (coin-to-fiat).
https://developer.btcdirect.eu/widget/sell-order-form.html

frontend: fix selecting altcoins in the btcdirect sell widget

---

CHANGELOG.md
frontends/qt/main.cpp

In Qt 5 this was on by default, but since our upgrade to Qt 6 this broke, as in Qt 6 one has to explicitly set the persistent storage path.

qt: persist local storage

---

frontends/web/src/locales/en/app.json
frontends/web/src/routes/exchange/components/buysell.tsx
frontends/web/src/routes/exchange/exchange.module.css
frontends/web/src/routes/exchange/exchange.tsx
frontends/web/src/routes/exchange/pocket.tsx
frontends/web/src/routes/router.tsx

Pocket Bitcoin was the only sell option before and requires a newer firmware. The sell tab in buy/sell just displayed a require-fw-update message instead of showing the sell option (Pocket).
Moved the required-firmware-update into pocket component so the app can shows all options.

frontend: move firmware required logic into pocket view

---

frontends/web/public/btcdirect/coin-to-fiat.html
frontends/web/src/locales/en/app.json
frontends/web/src/routes/exchange/btcdirect.tsx

Showing the order-id in the transaction note when selling to BTC Direct could help if there was an issue.

frontend: include order-id in transaction note when selling

---

frontends/web/public/btcdirect/coin-to-fiat.html
frontends/web/public/btcdirect/fiat-to-coin.html

This adds the missing return url to go back to the app, not this
was already on our subdomain on shiftcrypto.io but just missing
in the static file that is used for local testing.

frontend: add missing return url

---

frontends/android/BitBoxApp/app/build.gradle

I could not figure out how to install 3.31.6 in my Android Studio, but later versions also work fine.

android: make cmake version a minimum

---

frontends/web/src/routes/device/bitbox02/components/password-entry/password-entry.tsx

On iOS, the password entry video previously showed system media controls, and you were able to open it in fullscreen. Adding "playsInline" removes the option to interact with the video and hides these controls.
Tested on iOS and macOS.

frontend: hide media controls on password entry video

---

util/logging/logging-stack-hook.go

Optimize code using a more modern writing style.

refactor: use maps.Copy for cleaner map handling

---

CHANGELOG.md
backend/notes.go
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
frontends/web/src/routes/settings/components/appearance/notesImport.tsx

Changes the file type of notes exports to .jsonl (JSON Lines), which is a more common format used by compatible wallets as specified in BIP-329.
For example, exporting labels with Sparrow Wallet creates a .jsonl, which would previously have to be renamed manually in order to allow importing it in the BitBoxApp.
The supported import file types are updated accordingly, still allowing .txt imports for exports created prior to this change.

update notes import and export file type to jsonl

---

frontends/qt/main.cpp

In 00d7607 we switched from the default profile to a dedicated one, to store profile data on disk. This change didn't involve the WebEnginePage used to display external resources (e.g. links in 3rd party widgets) and caused external links not to be displayed because of incompatible profiles.
This fixes the issue sharing the same profile also for external pages.

fronted/qt: fix web engine profile for external links

---

CHANGELOG.md
frontends/web/src/components/amount/amount-with-unit.tsx
frontends/web/src/components/amount/amount.test.tsx
frontends/web/src/components/amount/amount.tsx
frontends/web/src/components/balance/balance.tsx
frontends/web/src/routes/account/summary/chart.tsx
frontends/web/src/routes/bitsurance/dashboard.tsx

In the transaction overview, the amounts are displayed with a space:
0.00 000 000, in the account balance without 0.00000000.
With a space, the amount is much easier to read consistent with other
amounts in the app.

Frontend format btcamounts

---

backend/backend.go
backend/banners/banners.go
backend/devices/bitbox/device.go
backend/devices/bitbox02/device.go
backend/devices/bitbox02bootloader/device.go
backend/devices/device/device.go
backend/handlers/handlers.go
frontends/web/src/api/devices.ts
frontends/web/src/app.tsx
frontends/web/src/components/banners/banner.tsx
frontends/web/src/components/banners/index.tsx
frontends/web/src/routes/settings/bb02-settings.tsx
frontends/web/src/routes/settings/components/tabs.tsx

We want to be able to show different banners to bb02 and bb02nova users. This adds a backend check to differentiate the product name and adds a new banner category for the nova.

backend/devices: split bb02 and nova product names

---

CHANGELOG.md
backend/mobileserver/mobileserver.go
frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
frontends/web/src/locales/en/app.json

NOTE: this is based on https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/3421 so that one needs to be reviewed before this one. 
Use ConnectivityManager to react to onLost (connection entirely lost, e.g. going into airplane mode), onAvailable (the opposite), and onCapabilitiesChanged (other scenarios, for example the network loses access to the internet, but it still works locally)

android: react to change in network capabilities.

---

frontends/web/src/components/dialog/dialog.module.css

Using height: 100% does not work as expected on iOS and is the
reason that transaction details cannot be scrolled properly.
Also adjusted dialog paddings on ios to maintain usability

frontend: fix scrolling long dialog content on ios

---

.github/workflows/ci.yml

ci: add ad-hoc app signature for macos target

---

CHANGELOG.md
frontends/web/src/locales/en/app.json
frontends/web/src/routes/settings/components/advanced-settings/enable-tor-proxy-setting.tsx

The Tor proxy can currently not be used on iOS. iOS restricts exposing local ports to other apps.

frontend: disable option to connect via tor proxy on ios

---

docs/BUILD.md

which was wrongly placed between Android related sections.

docs/BUILD.md: fix iOS section positioning

---

backend/accounts.go
backend/accounts_test.go
backend/aopp_test.go
backend/backend_test.go

With a BB02 BTC-only version, the log showed attempts to add LTC accounts, which were then skipped as unsupported. We can abort earlier in this case, which prevents the log from showing 'automatically created hidden account' for LTC accounts when LTC is not supported.

backend/accounts: skip unsupported coins when adding hidden accounts

---

CHANGELOG.md
frontends/ios/BitBoxApp/BitBoxApp/WebView.swift

As part of system memory and energy management, iOS may terminate the web view of the app at whim, e.g. after backgrounding the app for a long time, usually combined with many different apps open during active usage.
Whenever this happens, the "webViewWebContentProcessDidTerminate" hook is triggered and forces a reload of the web view, set to the root page. As this is only triggered if the web view was killed, it will not interfere with regular usage.
Users may experience the reload briefly when they foreground the app and the conditions for the reload are met. While this fixes the blank screen issue, this is still somewhat suboptimal, as the user would expect the last state from when they used the app to reload.
To test in the simulator, termination of the web content can be forced with: …

frontend/ios: fix blank screens when foregrounding after inactivity

---

frontends/web/public/btcdirect/coin-to-fiat.html
frontends/web/src/routes/exchange/btcdirect.tsx

This is a temporary workaround to force the coin type in the widget. Without this, the widget UI allows the user to pick a coin, potentially breaking the flow.

 frontend/btcdirect: share sell address to btcdirect widget

---

CHANGELOG.md
backend/accounts.go
backend/accounts_test.go
backend/handlers/handlers.go
backend/rates/mock.go
frontends/web/src/api/backupBanner.ts
frontends/web/src/components/amount/amount.tsx
frontends/web/src/components/banners/backup.tsx
frontends/web/src/locales/en/app.json
frontends/web/src/routes/account/summary/accountssummary.tsx

For each wallet, the first time it crosses 1000 USD/CHF/EUR, display a banner suggesting users to create a paper backup of their seed. If the default currency is different from these three, we use USD.
If the keystore is connected, the banner shows a link to the device setting where the user can see their recovery words.
If the keystore is not connected, the banner asks the user to connect it.
If amounts are hidden, we do not display the banner at all.
Video (where I manually changed the threshold from 1000 to 1, you'll need to do the same to test it if you don't have at least 1000 in a wallet) - note: the video is slightly outdated but still shows the overall flow
https://github.com/user-attachments/assets/83619e6f-d659-4bd0-bd41-41d4981370ba
A few comments are left inline.
Tested on …

frontend: add backup reminder banner.

---

CHANGELOG.md
backend/coins/eth/etherscan/etherscan.go

One ETH transaction can contain multiple deposits to a receive address. Because of the `seen` de-dup check, only the first one would be shown.
I checked if EtherScan really delivers two transactions instead of one for a self-transfer, but could not reproduce it.

backend/eth: show all internal transactions that share the same txID

---

frontends/qt/main.cpp

With Qt 5.15.2, dark mode was not working on Linux/Windows/MacOS We have since then updated to Qt 6 and the workaround is not needed anymore.
I have tested only on MacOS and dark mode works. Testing on other environments is welcome :) 

backend: remove QT workaround for dark mode.

---

frontends/qt/main.cpp

The sandbox was disabled for Linux on Qt 5.15.2 as it would cause the app to show a blank screen. This is not needed anymore as we upgraded to Qt 6.
Needs to be tested by someone with Linux as I currently only have a Macbook to work on.

backend: re-enable the sandbox for Qt.

---

frontends/web/src/components/banners/backup.tsx

Previously, a backup reminder was added but it was not possible to deep link directly into the workflow:
- 852f9c7c1f79537d0f660d07d2e14116ab7754b0
The recovery workflow has since been refactored to support deep linking:
- 747803a18255fd41153bfbf2907153aba635797c

frontend: deep link into backup workflow

---

backend/mobileserver/Makefile
frontends/qt/server/Makefile.linux
frontends/qt/server/Makefile.macosx
frontends/qt/server/Makefile.windows
scripts/ci.sh

As per official docs, `-trimpath `removes all file system paths from the resulting executable.
This way, stack traces in the logs won't show hardcoded paths that can confuse users.

chore: enable trimpath flag for go build.

---

CHANGELOG.md
frontends/web/src/routes/account/add/add.tsx

When there is only one coin supported, we want the back button on the choose name step to close the dialog. And we want the account name to be suggested.

frontend: remove currency selector and fix suggested account name for BTC-only.

---

backend/devices/bitbox02/keystore_simulator_test.go
go.mod

So refactorings related to BitBox02 keystore transactions are sure not to break payment requests.
This requires a simulator that is not yet released. Build it from latest bitbox02-firmware master and rename it to `simulator-v9.24.0` (version in filename is required so the tests can infer the version)
Then run using
```
SIMULATOR=/path/to/bitbox02-firmware/build-build-noasan/bin/simulator-v9.24.0 go test -mod=vendor -tags=bitbox02_simulator ./... -count=1 -v -run 'TestSimulatorSignBTCPaymentRequest'

backend/bitbox02: add integration test for payment requests

---

Makefile
frontends/web/Makefile
frontends/web/package.json

For testing purpose sometimes we want to test the actual prodution build instead of vite dev mode.
This first builds the frontend and serves without hot reloading.

frontend: add make webserve task for testing

---

frontends/android/BitBoxApp/app/build.gradle

We have NDK 28 installed by docker_install.sh. Still, `make android` gave this output:
```
Checking the license for package NDK (Side by side) 27.0.12077973 in /opt/android-sdk/licenses
License for package NDK (Side by side) 27.0.12077973 accepted.
Preparing "Install NDK (Side by side) 27.0.12077973 v.27.0.12077973".
```
It is unclear `gradlew assemble` chose this version, it's not in any cache/localprops.
Adding the version to build.gradle resolves this.

android: fix ndk version

---

frontends/web/src/routes/market/bitrefill.tsx

So the user can confirm the payment on the device.

frontend: show bitrefill address in a blocking dialog

---

frontends/web/src/routes/market/bitrefill.tsx
frontends/web/src/routes/market/market.tsx
frontends/web/src/routes/router.tsx

First merge https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/3552

Frontend add region info

---

backend/handlers/handlers.go
backend/market/bitrefill.go
frontends/web/public/bitrefill/bitrefill.css
frontends/web/public/bitrefill/bitrefill.html
frontends/web/src/routes/market/bitrefill.tsx

This adds a local copy of bitrefill.html, which handles the communication between the app and the bitrefill widget, to make future development easier. When the app runs in dev mode, the local file will be used instead of the remote one.

frontend/bitrefill: add local copy of bitrefill.html

---

frontends/web/tests/helpers/servewallet.ts

To avoid spurious failures when the servewallet takes more times to be ready, we increase the timeout but also we log how long a successful connection took, in order to help keep track of it.
Looking at one execution, we were very close to the timeout limit so it does make sense that we had intermittent failures.

chore: increase servewallet timeout.

---

frontends/web/src/routes/device/bitbox01/settings/settings.tsx

In a recent release BitBox01 support has been dropped, except for backup management. For this reason the app navigates directly into BitBox01-settings. This view was missing the banners, especially the BitBox01 EOL banner.
Added BitBox01 EOL banner to BitBox01-settings.

frontend: show banners on bitbox01 settings page

---

CHANGELOG.md
frontends/ios/BitBoxApp/BitBoxApp/WebView.swift

It calls window.open to launch user verification in the browser, but webview blocked it.

ios: fix Pocket user verification link

---

frontends/web/src/components/banners/offline.tsx
frontends/web/src/components/banners/sdcard.tsx
frontends/web/src/components/banners/testing.tsx
frontends/web/src/components/bluetooth/bluetooth.tsx
frontends/web/src/components/devices/bitbox02bootloader/bitbox02bootloader.tsx
frontends/web/src/components/message/message.tsx
frontends/web/src/components/status/status.tsx
frontends/web/src/routes/account/account.tsx
frontends/web/src/routes/account/info/info.tsx
frontends/web/src/routes/device/bitbox02/passphrase.tsx
frontends/web/src/routes/device/bitbox02/setup/name.tsx
frontends/web/src/routes/device/bitbox02/setup/pairing.tsx
frontends/web/src/routes/device/bitbox02/setup/password.tsx
frontends/web/src/routes/device/bitbox02/unlock.tsx

Status component is just a wrapper around Message component, with
some additional config checks for persistent dismissable messages.
Changed to make dismissable prop mandatory with that all occurrences
of Status that don't need this logic should error.
Note: Added clasaName prop to Message, as some instances use
className special text formatting or margins.
Instances that need new className prop on Message:
- account.tsx for offline error message & account.initializing/notSyncedText
- bitbox02/setup/name.tsx microsd warning message
- bitbox02/setup/pairing.tsx attestationFailed message
- routes/device/bitbox02/setup/password (video) errorText message

frontend: prefer message over status component

---

frontends/web/src/components/dialog/dialog.tsx
frontends/web/src/routes/settings/components/device-settings/factory-reset-setting.tsx

Fixed an issue with FactoryResetSetting where continuing to reset
the device should show a WaitDialog. But the simplified version in
a recent Dialog refactoring always called onClose as if the user
would aboard the workflow.
Regression introduced in:
- https://github.com/thisconnect/bitbox-wallet-app/commit/d5bb07888deac147a74b527c0251529f6ef0174f

Frontend fix factory reset

---

frontends/web/src/routes/market/components/countryselect.tsx

react-select requires object identity matching, not just value equality. (according to GPT)
to test this in webdev it also need https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/3587 
(and remove appfolder.dev/config.json)

frontend: fix country-selector default
