- Dockerfile
This makes sure we have exactly the `linuxdeployqt-continuous-x86_64.AppImage` file that we expect, since we fetch it remotely during build.
> Dockerfile: verify linuxqtdeploy checksum, break long lines

- scripts/dockerdev.sh
Without this change, `./scripts/dockerdev.sh` (and `make dockerdev`) fails
with `Unable to find image 'godbb:latest' locally` on clean checkout (tested at 5d8f347).
After this change, we check for the `godbb` image, and if it does not exist, we build the `Dockerfile`
in the root of the repo and tag it with this name.
> docker: Give hint in dockerdev.sh if godbb image is missing

- frontends/web/src/routes/device/settings/settings.jsx
This change simply prevents enabling 2FA from the web UI
if no phone is paired with the device, as reported by the backend.
It remains to be seen and verified whether the 2FA can be enabled
directy by sending "lock" command to the device
or backend which propagates the command to device.
R: @thisconnect @benma
> frontend: disable 2FA button unless paired

- backend/backend.go
- backend/devices/bitbox/device.go
- backend/devices/bitbox/device_test.go
- backend/devices/bitbox/pairing.go
- backend/devices/bitbox/pairing_test.go
- backend/devices/bitbox/relay/channel.go
- backend/devices/usb/manager.go
- util/config/file.go
- util/logging/instance.go
`devices/bitbox.Device`'s channel, onEvent and closed fields are accessed concurrently and need to be guarded with a mutex.
I consider this an intermediate solution, built on top of existing code structure. I believe a more elegant solution exists but would require substantial refactoring.
`bitbox.Device` now has a new unexported field which holds the channel config dir to aid automated testing. A couple nice side effects of this:
- your real channel.json config in the HOME dir is not touched during
tests, if present;
- tests shouldn't hammer prod relay endpoint anymore because
the channel config dir is a newly created temp dir for each run,
missing the channel.json file so dbb.listenForMobile isn't run.
Verified locally with `go test` and manually resetting a real bitbox device and going …
> backend: guard Device's internals against concurrent access

- scripts/coverage.sh
So that it's possible to run coverage for multiple packages.
For instance:
scripts/coverage.sh ./backend/...
This does not change the existing behaviour.
If no arguments are provided to the coverage.sh script,
the "go test" uses a package under the current directory.
R: @benma
> tools: pass all args to go test -coverprofile

- backend/backend.go
- backend/devices/bitbox/device.go
- backend/devices/bitbox/relay/channel.go
- frontends/qt/server/server.go
- util/config/appdir.go
- util/config/file.go
- util/logging/instance.go
Previously, there were two code paths which obtained the app's main config dir. They did it in roughly the same way but not identical on linux distributions.
This change attempts at unifying the two, sticking to the existing app dir, if present.
Unfortunately, github cannot recognize all commits are already in #16 except for the last one with the actual change.
> backend,frontends/qt: unify app config dir

- util/config/appdir.go
- util/config/appdir_test.go
There's no reason why AppDir should do filesystem stat calls every time it is called. It is enough to do it once at the startup and reuse the value for the entire lifetime of the app process.
One of the side effects of this is that app dir can now be replaced with a temp dir in tests.
Also added a test for AppDir but it has any value only on linux-based platforms.
R: @benma
> util/config: check the app config dir only once

- .travis.yml
- Makefile
- scripts/osx-build-check.sh
- scripts/travis-ci.sh
This adds MacOS to the Travis CI build process. It preps the Travis machine with a Makefile target and then builds the QT target for Mac OS.
> Add MacOS to Travis CI build

- README.md
- appveyor.yml
- frontends/qt/server/Makefile.windows
Currently this branch is building with Appveyor for CI on Windows. To make this work, @benma or @douglasbakkum will need to enable Appveyor for at least the bitbox-wallet-app repository.
This could be improved by removing the call to choco and using make from the system. It could also be improved by folding much of it back into Makefile targets. I think it is essentially functional at the moment. It currently uses the legacy cgo windows DLL build process, so it does not currently enable hardening as on other platforms.
Feedback welcome.
> Windows CI with Appveyor [wip]

- frontends/qt/main.cpp
The first two changes force the use of the 2d software rendering engine:
qputenv("QMLSCENE_DEVICE", "softwarecontext");
qputenv("QT_QUICK_BACKEND", "software");
Disable just-in-time regex engine:
qputenv("QT_ENABLE_REGEXP_JIT", "0");
Disable just-in-time javascript engine:
qputenv("QV4_FORCE_INTERPRETER", "1");
> reduce attack surface in QT desktop application

- appveyor.yml
- frontends/qt/server/Makefile.windows
- frontends/qt/windows_post.sh
qmake needs to be called in a different dir, it overwrites the
Makefile.
The `go get` packages are not needed to build the app.
> fixes to the windows build script

- Makefile
Update to use the correct Makefile target for the MacOS init target.
> make envinit rather than make init

- backend/devices/bitbox/pairing_test.go
The assumption that the '/' directory is non-writable turned out
to be incorrect under Docker environment.
This change uses a character in the dummy config dir name
which should fail dicrectory creation under all supported
environments.
R: @benma
> backend: fix pairing finish error test case

- scripts/ci.sh
When migrating to the `golangci-lint` tool the fast linting
was removed from the Makefile. However, in `ci.sh` there's
still some dead code dealing with the `--fast` flag.
Since `golangci-lint` does support a `--fast` flag I've
opted to resurrect the flag in your build scripts.
Also, the unnecessary `else` case has been removed.
> ci: fix --fast flag

- frontends/qt/Makefile
The .app bundle alone is enough, and has to be signed manually before
creating a zip or dmg.
> qt: don't produce macOS dmg

- Makefile
- README.md
It recreates the mockery mock files and the firmware asset file
everytime. Those are committed and don't need to be recreated when
building. One can call go generate manually when working on mocks or
changing the firmware asset.
> build: don't call go generate

- frontends/web/src/components/password.css
- frontends/web/src/components/password.jsx
- frontends/web/src/routes/device/waiting.jsx
for some reason event.getModifierState('CapsLock') does not work in Qt
I do not prefer this change if possible as the caps indication will be delayed to the next event instead of appearing immediately
> frontend: caps lock detection without event.getModifierState('CapsLock')

- backend/coins/btc/account.go
- backend/coins/btc/coin.go
- backend/coins/coin/coin.go
- backend/devices/bitbox/device.go
- backend/devices/bitbox/keystore.go
- backend/handlers/handlers.go
- It is used in the http layer and defines the http API, so the
definition should be local
- Other coins shouldn't reimplement the same function - reuse for
other coins using the account interface.
> account: move json business to handlers

- frontends/web/src/decorators/endpoint.ts
- frontends/web/src/decorators/load.tsx
- frontends/web/src/decorators/share.tsx
- frontends/web/src/decorators/store.ts
- frontends/web/src/decorators/subscribe.tsx
- frontends/web/src/decorators/translate.ts
- frontends/web/src/utils/types.ts
See the following caveat: https://github.com/Microsoft/TypeScript/issues/27278
> web: constrain the generic types for props to objects

- frontends/web/src/routes/account/send/send.jsx
Error message not cleared at the right time. Shows if you input an
amount fast and the callback is slow.
> frontend/send: fix race condition in error msgs

- frontends/qt/libserver.h
- frontends/qt/main.cpp
- frontends/qt/server/server.go
Before release, we used a live webserver in the qt app, and added the
auth headers on every request. We switched to a direct bridge instead,
leaving this code unused.
> qt: remove unused tcp listener, auth headers

- frontends/web/src/i18n/en.json
- frontends/web/src/routes/account/account.jsx
- frontends/web/src/routes/account/send/send.jsx
- frontends/web/src/routes/device/settings/components/changepin.jsx
- frontends/web/src/routes/device/setup/goal.jsx
- frontends/web/src/routes/device/setup/initialize.jsx
- frontends/web/src/routes/device/setup/seed-create-new.jsx
- frontends/web/src/routes/device/setup/seed-restore.jsx
- frontends/web/src/routes/device/waiting.jsx
When processing the i18n json files, the empty translation keys can be
dropped completely, resulting in the key being showed in the frontend.
Also, they are simply not needed.
> frontend/i18n: remove unused/empty keys

- backend/backend.go
- backend/coins/btc/account.go
- backend/coins/btc/coin.go
- backend/coins/eth/account.go
- backend/coins/eth/coin.go
All existing coins were initialized, regardless of whether activated
in the settings, or whether the account using it was
initialized. Initialized coins start syncing headers and creating
unused connections, which caused a noticable pause between unlocking
the device and the accounts showing up.
This fixes this regression.
> backend/coin: init only when account active and opened

- frontends/web/src/components/guide/guide.tsx
- frontends/web/src/routes/account/account.jsx
Account guide has no entries in "guide.account", only manual entries.
> frontend/guide: allow skipping screen key

- backend/coins/btc/coin.go
- backend/coins/eth/coin.go
The trimming formatted 0 as "" instead of as "0".
> coin: formatting of 0

- frontends/qt/main.cpp
Weird grid was drawn on macOS when either of the two flags was
enabled.
Looks like https://bugreports.qt.io/browse/QTBUG-60393, but also
present in 5.9.4.
Problem does not appear in 5.11.
> qt: software rendering bug in 5.9

- frontends/web/src/app.jsx
When accounts are uninitialized, the app redirected to /, regardless
of where it was before. Restrict to /account/.
> frontend/app: redirect only if in /account/

- frontends/web/src/routes/account/send/send.jsx
Enable on a coin-by-coin basis, as it does not apply to all of them.
> frontend/send: whitelist coin control for btc and ltc

- backend/coins/btc/feetarget.go
- backend/coins/eth/account.go
- frontends/web/src/routes/account/send/feetargets.jsx
- frontends/web/src/routes/account/send/send.jsx
Stop-gap solution to hide it in ETH. The proper step would be to move
FeeTargets and make it more generic.
> frontend/send: hide fee targets if there are none

- backend/coins/btc/account.go
- backend/devices/bitbox/keystore.go
- backend/keystore/keystore.go
- backend/keystore/keystores.go
- backend/keystore/software/software.go
- keypath and scripttype is both in Configuration
- relevant whether we are in singlesig or multisig, which is also in
the Configuration
- HasSecureOutput needs to have the same signature to be able to check
properly.
> backend/keystore: improve HasSecureOutput/OutputAddress

- Makefile
Say someone adds a key to English, and in the same go adds it to some
other languages they know. Locize push would lose the changes to other
languages (something that should be avoided, but if it happens, we
don't want the work to be lost). This flag fixes that.
> Makefile: locize push should also add/remove keys in every language

- backend/backend.go
- frontends/web/src/components/icon/logo.tsx
- frontends/web/src/components/sidebar/sidebar.jsx
Before, each account was converted into a multisig one, with the
signle-sig keypath. All used the same multisig type too, disregard the
account type.
> backend: fix multisig accounts

- Dockerfile
- Makefile
- scripts/go-get.sh
`go get ...` always gets master, which is not reliable/robust.
Start by fixing the linter version, so the CI does not break when that
updates in a backwards incompatible manner.
> deps: add tool to fix version of dev tools

- backend/handlers/handlers.go
The signing configuration alone can be ambiguous.
> backend/account/add: add coinCode to accountCode

- frontends/web/src/routes/device/settings/components/device-lock.jsx
Should not turn on lock if the operation was aborted.
> frontend/bitbox: fix 2fa ui bug

- appveyor.yml
- frontends/qt/setup.nsi
- frontends/qt/windows_post.sh
@benma @jvaltin  
This scripts currently expects the binaries/libs to be in build/windows. 
It can be run from either command line, or gui with nsis.
If it should accept any outside argument, or rather define a variable properly, instead of the hard baked names it currently uses, please let me know.
> Add Windows installer script

- frontends/web/src/routes/device/settings/components/changepin.jsx
Preact uses different event handlers than React. The state of the input field was not updating using `onChange`. Use `onInput` instead.
> frontend: handle preact input change to update state correctly

- .golangci.yml
- Makefile
- backend/backend.go
- backend/coins/btc/account.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/eth/account.go
- backend/coins/eth/etherscan/etherscan.go
- backend/devices/bitbox/device.go
- backend/devices/bitbox/error.go
- backend/keystore/software/software.go
- util/logging/logger.go
It enables by default gocritic, gochecknoinits, gochecknoglobals. We
select a few from gocritic (revisit if too invasive) and disable the
other two for now.
> ci: update golangci to v1.12

- frontends/web/src/components/language/language.jsx
I added a new translation key to the language button. As mentioned in the issue, this button will be 'Other languages' in English, and 'English' for other languages.
> frontend: add translation key to language switcher button

- Makefile
- scripts/travis-ci.sh
Easy to shoot oneself in the foot by force writing the other
files (e.g. accidentally pushing stale/uncommitted language files).
> Makefile: locize-push should only touch the reference language

- backend/devices/bitbox/device.go
- backend/devices/bitbox/handlers/handlers.go
- frontends/web/src/routes/account/account.tsx
The sd card check assumes the device is unlocked, but that is not the
case with for example watch only accounts.
> frontend/account: error with locked device

- backend/handlers/handlers.go
https://shiftcrypto.ch/start was missed and as a result was blocked.
> backend: whitelist all shiftcrypto.ch urls

- backend/coins/btc/addresses/address.go
- backend/coins/btc/addresses/addresschain.go
- backend/coins/btc/addresses/test/test.go
Useful information for keystores to know the relative keypath of the
address to the account.
> btc: hold onto account config and rel. keypath of an address

- backend/coins/eth/account.go
- backend/coins/eth/etherscan/etherscan.go
Increase etherscan rate limit (was 5req/s, not 1req/5s).
Transactions() should also wait until synced.
> eth: synchronization improvement

- backend/config/config.go
I have also prepared the functionality to whitelist the User
Agent for the http requests so we can restrict the API key usage if we
decide to implement this in the future.
> backend: change infura endpoint to use new API keys

- backend/coins/btc/account.go
EventStatusChanged fired twice, once on connect and once on sync. The
first one was too eager, as the status did not change most of the
time.
> btc/account: save an event

- backend/backend.go
- backend/coins/btc/account.go
- backend/devices/bitbox/keystore.go
- backend/devices/bitbox02/keystore.go
- backend/keystore/keystore.go
- backend/keystore/keystores.go
- backend/keystore/software/software.go
A keystore can indicate if it supports a specific coin/account.
> backend/keystore: SupportsAccount()

- backend/backend.go
- backend/devices/usb/manager.go
The UX is still too confusing when multiple devices are plugged in, as
only one keystore is actually loaded.
> backend: support only one device at a time

- .dockerignore
This reduces the context that needs to be copied with `make dockerinit`
from ~1.21GB to ~0.35GB on my machine, which improves performance
when building Docker images.
> .dockerignore: Initial commit

- .golangci.yml
- Makefile
- backend/coins/btc/account.go
- backend/coins/btc/blockchain/blockchain.go
- backend/coins/btc/blockchain/mocks/Interface.go
- backend/coins/btc/electrum/client/client.go
- scripts/ci.sh
Running out of memory since upgrading to v1.12
> ci: reduce memory consumption of golangci-lint

- Makefile
- backend/arguments/arguments.go
- backend/backend.go
- backend/handlers/handlers_test.go
- cmd/servewallet/main.go
- frontends/android/android.go
- frontends/qt/server/server.go
This pull request moves the devmode certificates from the backend to the config. They are reachable by passing the DevMode argument when creating a new Config.
> Move devmode electrum config from backend to config

- backend/backend.go
- backend/bitboxbase/bitboxbase.go
- backend/bitboxbase/handlers/handlers.go
- backend/bitboxbase/mdns/detector.go
- backend/bitboxbase/updater/updater.go
- backend/coins/btc/electrum/electrum.go
- backend/config/config.go
- frontends/web/src/components/bitboxbase/connectbase.tsx
This commit adds support to connect with electrs running testnet or mainnet on the BitBox Base. A new postConnectElectrumHandler was created for this purpose. It takes a bitboxBaseID, from that gets
the connected BitBox Bases'IP and initiates a connection with the base.
The electrs port and network type (mainnet/testnet) are fetched with the GetEnv get request.
Once connected, other active backends will be unset, such that only bitcoin accounts will be available.
> Allow connection to bitbox-base electrs

- frontends/android/BitBox/app/src/main/java/com/shiftcryptosecurity/bitbox/GoViewModel.java
- frontends/android/BitBox/app/src/main/java/com/shiftcryptosecurity/bitbox/MainActivity.java
According to
https://developer.android.com/training/data-storage/files.html#WriteInternalStorage
Also remove unused setDomStorageEnabled().
> android: use subfolder in internal storage

- backend/backend.go
- backend/coins/btc/coin.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/coin/coin.go
- backend/coins/eth/coin.go
- backend/handlers/handlers.go
Fees can be in a different unit, so this parameter is added so coin
implementations can treat fees differently if needed (example: ERC20
Token is the main unit, ETH is the fee unit).
> backend/coin: add isFee to unit, formatting amount

- backend/coins/btc/coin.go
- backend/coins/btc/db/headersdb/headersdb.go
- backend/coins/btc/headers/db.go
- backend/coins/btc/headers/headers.go
Storing headers directly in a file instead of bbolt reduces the
storage requirements by a factor of ~2.7
> btc/headers: more efficient storage

- backend/bitboxbase/bitboxbase.go
- backend/bitboxbase/handlers/handlers.go
- backend/bitboxbase/mdns/manager.go
- backend/bitboxbase/rpcclient/rpcclient.go
- backend/bitboxbase/rpcclient/websocket.go
The backend now passes a callback to properly unregister through the manager and bitboxbase package to the rpcclient. In case the websocket connection fails, the callback is called and both read and write websocket loops are closed.
Fix the ordering of the close channel to make sure that no double closing, or writing into a closed websocket connection occurs.
The rpc methods now return proper errors and need to get handled based
on their purpose. Also print the errors in their proper logging format.
> Handle Disconnects of the RPC Connection

- backend/backend.go
- backend/config/config.go
The connection to the regtest rpc server is now initialized in the same way as for testnet and mainnet and can be controlled from the electrum config file.
> Add regtest to electrum coin config

- frontends/web/package.json
- frontends/web/src/app.tsx
- frontends/web/src/components/guide/entry.tsx
- frontends/web/src/decorators/subscribe.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/yarn.lock
As far as I can judge, the preact update exposed problems that we already had before but which TypeScript didn't detect because it could pick the wrong method declaration and basically opt out of type checking. I fixed the issues but
- @originalblend337: Please review and test the change in `app.tsx` to the guide toggler (the behavior should have been broken before and I haven't tested the effect of my fix).
- @benma: Please check and test the change in `send.tsx`. The problem was more or less that `boolean | undefined` could not be assigned to `boolean` so I made `noMobileChannelError` optional as well.
> frontend: upgrade preact to 8.5.2, fix TypeScript

- scripts/go-get.sh
The newest checkout might not build, but it doesn't need to if we're
interested in an older version.
> scripts/go-get: do not build the fetched package immediately

- frontends/web/src/routes/account/receive/receive.jsx
The dialog is blocking and the copying should be done only there,
until we make it an inline dialog.
> frontend/receive: for now do not enable copy in background

- frontends/web/src/components/devices/bitbox02bootloader/bitbox02bootloader.tsx
- frontends/web/src/components/devices/bitbox02bootloader/toggleshowfirmwarehash.tsx
- frontends/web/src/locales/en/app.json
- Improves the update firmware screen with our new toggle button.
- Makes the content box fixed size so it doesn't jump with the added checkbox div (which also moved the Advanced Settings link, making the user unable to open/close without moving cursor)
- Center and add margin to "Device oriented the wrong way"
Before:
After:
> frontend: improve upgrade firmware screen UI

- backend/backend.go
- backend/erc20.go
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/receive/receive.jsx
- frontends/web/src/routes/account/utils.ts
In the receive tab, when verifying. Reason: we currently do not
support all erc-20 tokens. This guides the user to activate the token
they want in the settings.
> frontend/eth: warning to only receive only the current coin

- backend/bitboxbase/bitboxbase.go
- backend/bitboxbase/handlers/handlers.go
- backend/bitboxbase/rpcclient/rpcclient.go
- backend/bitboxbase/rpcmessages/rpcmessages.go
In preperation for adding JSON Web Tokens to the rpc message structs, move standalone values to a struct.
@0xB10C corresponding pull request to https://github.com/digitalbitbox/bitbox-base/pull/226
> BitBoxBase: Move ToggleSetting to a Struct

- backend/config/config.go
Until we have a better account discovery, this makes it easier for
upgraded users to find their legacy account funds.
Also enable bech32 by default, as exchange support now is pretty good.
> backend/config: enable bech32 and legacy accounts by default

- frontends/qt/main.cpp
It appears in unexpected places like in the context menu of
`Settings`, which copies an internal qrc:/ link.
> qt: remove CopyLinkToClipboard from context menu

- frontends/web/src/routes/bitboxbase/bitboxbase.tsx
When continuing from presynced state, wait dialog was not removed on success
> base-setup: fix presync bug

- backend/bitboxbase/bitboxbase.go
- backend/bitboxbase/handlers/handlers.go
- backend/bitboxbase/rpcclient/rpcclient.go
- backend/bitboxbase/rpcmessages/rpcmessages.go
- backend/bitboxbase/status/status.go
This commit adds the GetServiceInfo RPC and handler to the App.
The RPC provides the App with information about the services running on the BitBoxBase. The middleware notifies the App when the ServiceInfo change. The event is implement here as well, but not used yet.
> GetServiceInfo RPC

- backend/bitboxbase/bitboxbase.go
- backend/bitboxbase/handlers/handlers.go
- backend/bitboxbase/rpcclient/rpcclient.go
- backend/bitboxbase/rpcclient/websocket.go
- backend/bitboxbase/rpcmessages/rpcmessages.go
- backend/bitboxbase/status/status.go
- frontends/web/src/components/bitboxbase/unlockbitboxbase.tsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/bitboxbase/bitboxbase.tsx
All rpc calls now need to be authenticated with a token. A new token is received by calling the UserAuthenticate rpc method with the users's password and username.
This commit also re-works the setup wizzard for the BitBox Base to make sure that the authentication is run correctly and that the wizzard is not left in a state from which it cannot recover.
This PR needs to be tested against https://github.com/digitalbitbox/bitbox-base/pull/227
> BitBoxBase: Add Authentication with JWT

- frontends/web/tslint.json
It is nicer to have an `interface State { }` in a component than to
replace every `State` with `{}`, as it can be annoying / tricky to add
the State back in all the right places when you want to add a state
var.
> frontend/tslint: disable no-empty-interface rule

- frontends/web/src/components/fiat/fiat.tsx
- frontends/web/src/components/rates/rates.tsx
If you navigate to the settings page before the rates have been
fetched, or the rates could not be fetched, you'd have an error or an
empty screen.
> frontend: fix settings without rates

- backend/bitboxbase/bitboxbase.go
- backend/bitboxbase/handlers/handlers.go
- backend/bitboxbase/rpcclient/rpcclient.go
- backend/bitboxbase/rpcmessages/errorcodes.go
- backend/bitboxbase/rpcmessages/rpcmessages.go
- backend/bitboxbase/status/status.go
This PR adds the counterparts to the UpdateBase and GetBaseUpdateProgress RPCs added in https://github.com/digitalbitbox/bitbox-base/pull/228 to the App. Next to the RPCs a event for a BaseUpdateProgressChanged notification is added.
> base-rpc: add Base Update RPCs

- backend/backend.go
- backend/bridgecommon/bridgecommon.go
- backend/bridgecommon/bridgecommon_test.go
- backend/notifier.go
- scripts/ci.sh
Call it after bridgecommon.Shutdown(). Otherwise running Serve() again
can lead to undesired behavior, like opening a database twice and
hanging.
This commit is a partial solution, as we need to close all resources.
> backend: add Close()

- backend/bridgecommon/bridgecommon.go
- backend/bridgecommon/bridgecommon_test.go
backend.Close() in the goroutine happened at a non-deterministic time,
possibly after calling Serve() again.
> backend/bridgecommon: deterministic shutdown

- backend/coins/btc/account.go
For some users, BWS buried the change even deeper. Maybe they did not
always enforce the 20 gap limit on change addresses.
> backend/btc: increase change gap limit for legacy accounts

- backend/bitboxbase/bitboxbase.go
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/bitboxbase/basesettings.tsx
- frontends/web/src/routes/bitboxbase/bitboxbase.tsx
Calls the RebootBase RPC after user confirmation.
Currently there is no automatic reconnect as the base gets
deregistered once the websocket connection shuts down. Needs
additional backend functionality to keep trying to reconnect after restart.
> base-settings: add basic Reboot rpc to the dashboard frontend

- frontends/web/src/components/forms/input.css
In the PasswordSingleInput component, the checkbox for showing the
password was too large, running out of bounds of a dialog and being
clickable from a large area
> frontend: fix "show password" checkbox which was too large

- frontends/android/Makefile
This just makes it a little easier to watch adb's logcat logs
pertinent to the app.
The current filter does catch slightly more than just the app
yet the log output isn't cluttered and allows one to follow
the life of the app with enough comfort from command line.
> android: add a logcat "helper" make target

- .golangci.yml
- go.sum
This resolves the following error
+ golangci-lint run
level=error msg="Running error: context loading failed:
no go files to analyze"
Makefile:79: recipe for target 'ci' failed
I believe this is because of a recent golangci-lint upgrade.
It seems to be running with the default go modules support now,
which in turn tries downloading all the package dependencies.
Unfortunately, one package dep was added to go.sum at the time
where package checksums were computed incorrectly in certain conditions.
More on that can be found in golang/go issue 29278.
This went unnoticed for quite some time because vendored dir is used
instead of go.mod. Since the upgrade of golangci-lint, it started
using go.mod.
This change updates go.mod checksum, even though it isn't used,
and makes golangci-lint use …
> ci: make golangci-lint great again

- backend/backend.go
- backend/banners/banners.go
- backend/banners/banners_test.go
- backend/handlers/handlers.go
- frontends/web/src/app.tsx
- frontends/web/src/components/banner/banner.tsx
- frontends/web/src/decorators/translate.ts
- frontends/web/src/locales/en/app.json
Initial use-case: alert BitBox01 users of BitBox02's existence when
they plug in their BitBox01.
The banner information is fetched from shiftcrypto.ch.
> backend,frontend: add event-based banners

- backend/bitboxbase/bitboxbase.go
- backend/bitboxbase/rpcmessages/rpcmessages.go
- frontends/web/src/components/bitboxbase/changebasehostname.tsx
- frontends/web/src/components/bitboxbase/changebasepassword.tsx
- frontends/web/src/components/bitboxbase/confirmbaserpc.tsx
- frontends/web/src/components/bitboxbase/createbasebackup.tsx
- frontends/web/src/components/bitboxbase/enablesshlogin.tsx
- frontends/web/src/components/bitboxbase/setbasesystempassword.tsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/bitboxbase/basesettings.tsx
- frontends/web/src/routes/bitboxbase/bitboxbase.tsx
This PR implements functionality for these settings buttons:
- Enable/Disable Tor
- Change hostname
- Change password
- Shut down
- Create backup
- Enable ssh password authentication
- Set system password
Additionally:
- Add number of active lightning channels
> base-settings: add button functionality

- backend/bitboxbase/bitboxbase.go
- backend/bitboxbase/handlers/handlers.go
- backend/bitboxbase/mdns/manager.go
- backend/bitboxbase/rpcclient/rpcclient.go
- backend/handlers/handlers.go
- frontends/web/src/routes/bitboxbase/bitboxbase.css
- frontends/web/src/routes/bitboxbase/bitboxbase.tsx
- frontends/web/src/routes/bitboxbase/bitboxbaseconnect.tsx
Because:
Previously, the '/connectbase' endpoint would not succeed until after
the noise pairing hash was confirmed by the user. This means that when
connecting to the Base, the user would not be routed to the setup
wizard until after the pairing had succeeded (which happens
automatically now, but in final implementation would mean the user
would never be routed to the wizard)
This commit:
Refactors the intial rpc client ping and websocket dial to a separate
function which succeeds on initial connection. Only after this is the
noise pairing initialized.
> base-backend: refactor initial connection and noise pairing

- backend/banners/banners.go
> backend/banners: use reload instead of replace as event action

- backend/backend.go
- backend/bitboxbase/bitboxbase.go
- backend/bitboxbase/handlers/handlers.go
- backend/bitboxbase/mdns/manager.go
- backend/handlers/handlers.go
This was initially required to to hook up the events from the BitBoxBase struct to the backend. A direct reference to the BitBoxBase can be used though, since the BitBoxBase struct is defined then.
Should replace https://github.com/digitalbitbox/bitbox-wallet-app/pull/691
> Remove the BitBoxBase Interface

- backend/coins/btc/electrum/client/client.go
- util/rpc/rpc.go
Electrum always runs over json rpc in this app, the interface is not
used otherwise.
> util/rpc: remove useless Client interface

- backend/backend.go
- backend/bitboxbase/bitboxbase.go
- backend/bitboxbase/handlers/handlers.go
- backend/bitboxbase/mdns/manager.go
- backend/bitboxbase/rpcclient/websocket.go
- frontends/web/src/routes/bitboxbase/bitboxbase.tsx
- frontends/web/src/routes/bitboxbase/bitboxbaseconnect.tsx
@KasparEtter could you please take a look at this commit: https://github.com/digitalbitbox/bitbox-wallet-app/commit/76545637be7633cbade7e4698d427f679bfe120b
specifically: https://github.com/Tomasvrba/bitbox-wallet-app/blob/e4696353cbc1b4b4d23313d381593eb6b5abef4d/frontends/web/src/routes/bitboxbase/bitboxbase.tsx#L94
I had to type the `registeredBases[baseID]` as `any` because the `RegisteredBases` interface includes a boolean:
```
interface RegisteredBases {
[ID: string]: {
paired?: boolean;
status?: BaseStatus;
};
}
```
This is because:
```
type T1 = number & string;  // number & string
type T2 = string & boolean;  // never
```
If there is no boolean field in the `RegisteredBases` interface, then `newState.registeredBases[baseID][key] = value;` works fine. But with the boolean, it's a …
> Base pairing

- frontends/web/src/app.tsx
- frontends/web/src/routes/account/account.tsx
The Account component is invoked for `/account`, only for the routing
to happen. It's cleaner to invoke Account only for an actual account,
and do the routing in app.tsx closer to the other routing.
> frontend: account default routing refactor

- backend/devices/bitbox/events.go
- backend/devices/bitbox/pairing.go
- backend/devices/bitbox/relay/channel.go
- backend/devices/bitbox/relay/request.go
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/settings/components/mobile-pairing.tsx
When the relay server is not reachable, the frontend just displays a timeout message, while the backend logs an unrelated error. This commit attempts to improve this by displaying a separate message in the frontend when messages are not relayed correctly and improves the logging in the backend.
> Improve Mobile Pairing Error Messages

- frontends/web/src/components/backups/restore.tsx
- frontends/web/src/components/devices/bitbox02/checkbackup.tsx
- frontends/web/src/components/devices/bitbox02/createbackup.tsx
- frontends/web/src/components/devices/bitbox02/reset.tsx
- frontends/web/src/components/devices/bitbox02/showmnemonic.tsx
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/device/skipfortesting.tsx
Otherwise a non-state var could sneak in.
Readonly because the state is supposed to be set via setState().
> frontend: enforce state type

- backend/coins/eth/account.go
Regression of 5249d64c9e4dbff4cd0c94d1fc8b0588b188cdb4 -> /0 removed
in one place but not added in the other.
> backend/coins/eth: fix address level derivation

- frontends/qt/main.cpp
This makes the app scale well with the rest of the display
when the scaling factor is greater than 100%, especially font sizes.
Only Windows because there has been unexpected behavior on other
platforms in the past, at least on Qt versions before 5.14.
But we are currently stuck at 5.11 due to various dependencies and
older platforms support. Will reconsider and possibly upgrade to 5.14
in about a year.
See more about Qt HiDPI here:
https://doc.qt.io/qt-5/highdpi.html
> frontends/qt: enable HiDPI auto-scaling on Windows

- Makefile
- README.md
When building the BitBoxApp on macOS High Sierra with current software versions, there were a few issues. This pull request 
* installs 'homebrew' as recommended on brew.sh (the previous command recommends this as well in a warning)
* replaces 'pwd' with the var REPOROOT so that make can be called from outside the working directory
* moves necessary environment variables to the top of Makefile and removes the 'export' commands (that were not doing anything)
* removes 'brew install qt' as there is no reliable way to install the older version Qt 5.11 inside the script
* updates the README with more specific information about dependencies and versions
> macOS build: minor fixes

- frontends/web/src/components/rates/rates.css
- frontends/web/src/components/rates/rates.tsx
- frontends/web/src/components/transactions/transaction.css
- frontends/web/src/components/transactions/transaction.jsx
Few minor changes, this PR:
- removes space between sign and value (e.g `−1.234`)
- uses secondary grayish font color for the unit (CHF, BTC)
- uses green for incoming tx (not sure if that green is acceptable, but the red is very soft too)
- adds units (WU and b) to the tx detail view
> frontend/web: minor transaction styles improvements

- backend/coins/btc/headers/headers.go
We define our own checkpoints over using headers.net.Checkpoints,
because they are defined in the vendored btcd dep, and we want to
control it. Furthermore, the chaincfg.Params are evil globals
registered in the lib's `init()`, so we can't replicate the instances
ourselves.
> backend/coins: update checkpoints

- backend/coins/btc/headers/headers_test.go
Sometimes CI would run into the timeout.
> backend/coins/btc/headers: try to fix transient error

- backend/coins/eth/account.go
Which is 21000. This saves a network request to estimate the gas
limit. It is more robust as the gas estimation api call has been
unstable lately.
> backend/eth: hardcode gas limit for standard eth txs

- backend/coins/eth/account.go
The api calls recently stopped working when the gasPrice was set to a
non-zero value.
> backend/eth: fix etherscan gas estimation

- frontends/web/src/components/dialog/dialog.css
On linux, the address was still split on two lines by one char.
> frontend/dialog: increase width to fit bc1.. address

- Makefile
make buildweb on windows (mingw, gnu make 4.0) failed with:
```
$ make buildweb
rm -rf C:/Users/<user>/go/src/github.com/digitalbitbox/bitbox-wallet-app/frontends/web/build
yarn --cwd=C:/Users/<user>/go/src/github.com/digitalbitbox/bitbox-wallet-app/frontends/web install
yarn install v1.22.4
info No lockfile found.
```
Copy pasting the yarn install cmd into the shell worked. Hardcoding
the path in the `--cwd` flag in the Makefile also failed.
This is a fix by trial and error, the backtick env var is passed
unevaluated to yarn. Why this is works better then a passing the
absolute path directly is a mystery.
> Makefile: fix REPOROOT / make buildweb on windows

- backend/accounts/account.go
- backend/coins/btc/account.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/btc/transaction.go
- backend/coins/eth/account.go
- frontends/web/src/routes/account/send/send.tsx
When entering the tx details, on each form change, a /tx-proposal
backend call is made that creates the tx, including fee computation,
and returns the computed details to the frontend for display (fee,
total).
When clicking Review, the /sendtx backend call is called with the same
inputs, and the tx is re-created. With some bad timing, the fee rates
could have updated in the meantime, leading to a different fee than
the user sees in the app.
This commit fixes it in a general way: the tx proposal is persisted in
RAM, and /sendtx signs and sends that proposal instead of recreating
it.
> backend/account: fix fee mismatch between confirm dialog and device

- backend/coins/eth/etherscan/etherscan.go
Returning nil here led to an app crash if the etherscan http call
failed.
> backend/eth: fix typo when returning error

- backend/coins/eth/account.go
With a premature optimization, the gasLimit for the ETH account was
hardcoded to 21000. When sending regular ETH to a contract, the gas
limit can be higher, leading to rejected/cancelled transactions.
> backend/eth: query gasLimit also for the ETH account

- backend/accounts/account.go
- backend/coins/btc/account.go
- backend/coins/btc/account_test.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/eth/account.go
Because that's what it really means. This is to disambiguate with the
Initialize() function and the `alreadyInitialized` var used inside,
which are unrelated.
> backend/account: rename Initialized() -> Synced()

- backend/coins/btc/account.go
- backend/coins/eth/account.go
- backend/devices/bitbox/keystore.go
- backend/devices/bitbox02/keystore.go
- backend/keystore/keystore.go
- backend/keystore/keystores.go
- backend/keystore/software/software.go
Only the multisig flag is needed (and only in the bitbox01).
Multisig in the app is a simple demo of p2sh-multisig with multiple
bitbox01, so it is technical debt in a sense.
When combining accounts, it is currently simpler to assume that a
device can verify the addresses of all supported types (see
SupportsAccount()), which is true for all supported devices and
account types. Multisig is the only exception, where the bitbox01 can
sign it, but the app does not implement verifying the addresses on the
2fa app.
> backend/keystore: don't pass full signing config to CanVerifyAddress

- backend/coins/btc/maketx/maketx.go
- backend/coins/btc/maketx/maketx_test.go
- backend/coins/btc/maketx/txsize.go
- backend/coins/btc/maketx/txsize_export_test.go
- backend/coins/btc/maketx/txsize_internal_test.go
estimateTxSize assumed that all inputs in a tx are of the same
type (signing configuration in BitBoxApp terminology), e.g. version 0
native segwit.
It is extended to correctly handle transactions with mixed input
types. This will be needed when combining the different account
subtypes (e.g. Bitcoin Legacy, Segwit, Native Segwit) into one
account.
This is done by providing the input configuration for each input.
Testing this uncovered a bug:
signatureSize = 73 was wrong, signatureSize = 72 is correct (see
comments in the code). The unit test didn't catch it as it had too few
inputs, so by rounding the tx weight, the result was the same.
When mixing non segwit and segwit inputs, there is an empty witness
that has to be accounted for for each non-segwit input.
Tx construction, which uses …
> backend/btc/maketx: extend estimateTxSize to allow mixed inputs

- .github/workflows/ci.yml
- frontends/qt/Makefile
- scripts/travis-ci.sh
Alternative to Travis CI.
Runs the same scripts except SSH for nightly builds.
> ci: add github workflow

- backend/coins/btc/maketx/maketx.go
- backend/coins/btc/maketx/maketx_test.go
- backend/coins/btc/transaction.go
Can just pass the value directly instead.
> backend/btc/maketx: remove unnecessary callback

- backend/coins/btc/addresses/address.go
- backend/coins/btc/blockchain/blockchain.go
- backend/coins/btc/transactions/transactions.go
Code de-duplication, and it will be used from another package to get
the input configuration when creating a new tx.
> backend/btc: export function to create a pubkey script hash

- backend/devices/bitbox/device.go
Since f9118872, multisig was disabled on the bb01, so this check does
nothing.
> backend/bitbox01: remove singlesig check

- scripts/travis-ci.sh
The CI on macOS requires no tools installed in envinit make target.
This speeds it up a bit and avoids failures when upstream moves tools
source code around because we install with "go get".
Ideally, to fix the latter, we would install tools at specific release
versions in GO111MODULE=on mode. While this would probably work for
most, gomobile doesn't support "go build -mod=vendor" and regardless,
Go modules seem to make this more complicated and confusing. Also,
see https://github.com/golang/go/issues/25922.
> ci: don't run envinit on macOS

- backend/backend.go
- backend/config/config.go
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/settings/settings.tsx
Not the individual subaccount types.
For combined accounts ("Bitcoin", "Litecoin"), it just toggles the
account.
For split accounts, now either all account types are shown (Bitcoin:
bech32, Bitcoin, Bitcoin Legacy if supported), or none.
This is an acceptable trade-off, and only affects users with the
bitbox01 or users that will manually opt-in to split accounts.
The alternative would be a very hairy and granular settings screen,
which defeats the purpose of trying to simplify it.
> backend/config,frontend/settings: toggle Bitcoin, Litecoin

- frontends/web/src/components/transactions/transaction.jsx
- frontends/web/src/locales/en/app.json
The arrows were switched on the translated text, which only works in
English. Of course, the type should be used directly to figure out
what it is.
The translation has been deleted too, unused.
> frontend/transactions: fix buggy send/receive/self arrows

- backend/config/config.go
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/settings/settings.tsx
For the time being, we allow the user to go back to one account per
address/script type in the expert settings, like it was before unified
accounts.
> backend/config: option to force split accounts

- backend/coins/btc/account.go
- backend/coins/btc/maketx/maketx.go
- backend/coins/btc/maketx/maketx_test.go
- backend/coins/btc/sign.go
- backend/coins/btc/transaction.go
In preparation for unifying account types into one account.
I already make this a slice, but with only one element, so it behaves
the same as before.
When unifying e.g. Bitcoin Legacy, Segwit and Native Segwit accounts,
there would be one entry per such signing configuration.
Each accesss is marked with:
// TODO unified-accounts
with each following commit fixing one of those. This hopefully results
in smaller and easier to review commits.
> backend/btc: bundle address chains and signing config in one struct

- backend/signing/configuration.go
- backend/signing/configuration_test.go
Will be used as the new account db identifier when combining multiple
signing configs in one account (mixed inputs).
> backend/signing/configuration: hash over slice of configs

- backend/backend.go
- backend/coins/btc/account.go
- backend/coins/btc/account_test.go
- backend/coins/eth/account.go
- backend/handlers/handlers.go
Actual use in the following commit; but this allows the backend to
create multiple signingConfigs in a btc coin, to enable combining the
account types into one combined account.
> backend,backend/btc: pass signingConfigurations (plural)

- backend/coins/btc/account.go
- backend/coins/btc/transaction.go
For now we always use native segwit for change.
If it does not match the input types, it might even be a small privacy
benefit, as change is usually assumed to be the output that matches
the inputs type.
> unified-accounts: resolve TODO, pick change

- backend/coins/btc/sign.go
- backend/devices/bitbox02/keystore.go
- Pass all signing configs to the keystore
- Apply them in the bitbox02 keystore to correctly sign tx with mixed inputs.
> unified-accounts: resolve TODO, bb02 signing

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/settings/settings.tsx
No point in translating a constant name.
> frontend: remove t(settings.accounts.ethereum)

- backend/accounts/account.go
- backend/coins/btc/account.go
- backend/coins/btc/exchange.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/eth/account.go
- frontends/web/src/routes/account/receive/receive.tsx
The backend now sends unused addresses of each subaccount to the
frontend.
Frontend now only shows, as before, the addresses from the first
subaccount. Work needs to be done to allow the user to cycle through
the address types (see TODO).
> unified-accounts: resolve TODO, receive screen

- backend/backend.go
Before, the coin code was used for the database name, but it should
have been the account code all along, as the notifications work on an
account basis.
Changing this identifier now is good timing, as we just changed the
account db identifier as well (configurations hash).
> backend: fix transaction notifier db name

- backend/coins/btc/account.go
- backend/devices/bitbox/keystore.go
- backend/devices/bitbox02/keystore.go
- backend/keystore/keystore.go
- backend/keystore/software/software.go
keypath is directly derived from configuratio and redundant.
> backend/keystore: simplify VerifyExtendedPublicKey() signature

- frontends/web/src/routes/account/send/send.tsx
Addresses are now a multi-dimensional array with potentially multiple
address types. For the purpose of getting a quick address in dev mode,
always getting the first format works.
> frontend/send: fix devmode send to self

- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/info/signingconfiguration.tsx
- frontends/web/src/routes/settings/settings.tsx
Since unified accounts. there are no settings mentioning those words.
We ove it to the accounts guide, but only in split accounts, showing
the relevant part.
We might delete the entries soon altogether, as there is also the
accounts description banner that says more or less the same. Keeping
it for now though to not lose all the translations, in case we need
it.
Litecoin currently does not show them, as the text has 'Bitcoin' all
over. Not gonna fix this either.
> frontend/settings: move legacy, bech32, segwit guide entries

- frontends/web/src/components/dialog/dialog.css
- frontends/web/src/components/steps/steps.css
- frontends/web/src/utils/animation.ts
Popup animations prevent dialogs from showing up at all, at least on
Android devices where animations are disabled.
Being able to completely turn off animations is an accessibility
feature in most phones these days.
To reproduce the current issue on Android, go to Accessibility settings
and enable "Remove animations". Close the app completely and reopen.
Navigate to Settings, Connect your own full node, tap on "Check" for
any row in the Servers list. You'll see nothing and unable to scroll
up/down anymore. Expected: a dialog with the check status.
Trial and error has shown that Android WebView adheres to "Disable
Animations" accessibility setting and honors prefers-reduced-motion
@media CSS query, in which we suppress dialog animations.
See …
> frontend: suppress dialog animations when requested

- .github/workflows/ci.yml
AppImage, deb, rpm, macOS and Android.
They should be available for every new run at
https://github.com/digitalbitbox/bitbox-wallet-app/actions and in the Checks tab of PRs.
> ci: store build artifacts with github actions

- backend/coins/eth/account.go
- backend/coins/eth/etherscan/etherscan.go
When the transaction is invalid (e.g. a contract destination without
any data input), EstimateGas() returns an error.
Before, the error would be swallowed (only logged) and in the frontend
nothing would happen. Now we propagate it as is from EtherScan (it
does not provide any useful error code, just -32000 which stands for
server-error)
> backend/eth: propagate errors from EstimateGas()

- .github/workflows/ci.yml
- .travis.yml
- scripts/travis-ci.sh
- scripts/travis_ssh.sh
- scripts/travis_upload_nightlies.sh
This cuts overall run to about a half: 17min vs 9min on average.
And the test/lint job typically requires only ~5min.
Because Docker Hub may rate limit "docker pulls", use alternative image
stored in GitHub's docker.pkg.github.com registry.
https://docs.docker.com/docker-hub/download-rate-limit/ specifies that
> Docker will gradually impose download rate limits with an eventual
> limit of 300 downloads per six hours for anonymous users.
With the current CI image of 13 layers, it would limit us to 1 PR per
hour at the least. Add some typo corrections which trigger CI builds
and we may hit rate limiting quite fast.
Plus, it's always good to have a separate copy of the CI image for
times when DockerHub is inaccessible.
See ci.yml in .github/workflows for how to update this image in
the …
> ci: speed bump by running builds in parallel

- scripts/travis_upload_nightlies.sh
The bash installed on Travis CI VMs apparently requires spaces between
brackets in "if [ expression ]". If missing, it results in:
./scripts/travis_upload_nightlies.sh: line 6: [: missing `]'
Somehow I missed it when copying in 00227bb and the bash I have
installed locally accepts both. So, didn't catch it earlier.
> ci: add missing space in travis_upload_nightlies

- scripts/travis-ci.sh
- scripts/travis_upload_nightlies.sh
The script never actually worked. Pick any run like
https://travis-ci.org/github/digitalbitbox/bitbox-wallet-app/jobs/703697937
in which you'll see at the bottom:
./scripts/upload_nightlies.sh: line 33: cd: frontends/qt/build/osx:
No such file or directory
> ci: make upload nightlies actually work for macos on travis

- frontends/web/src/components/copy/Copy.css
- frontends/web/src/components/dialog/dialog.css
- frontends/web/src/routes/account/receive/receive.tsx
Long address can still break onto two lines, but this change
fixes the ugly tiny scrollbar by adding flexibleHeight prop.
The padding of the copy box is smaller and the width of the
dialog little wider so it should fit a few more letter in
one line.
> frontend: fix height in dialog for long addresses

- Makefile
Getting mockery failed:
$ GO111MODULE=off go get github.com/vektra/mockery/cmd/mockery
package github.com/vektra/mockery/cmd/mockery: cannot find package "github.com/vektra/mockery/cmd/mockery" in any of:
/usr/local/go/src/github.com/vektra/mockery/cmd/mockery (from $GOROOT)
/home/<user>/go/src/github.com/vektra/mockery/cmd/mockery (from $GOPATH)
> Makefile: fix make envinit

- frontends/web/src/app.tsx
The BitBoxLogo redirect to / was added so users can get back to the
device waiting screen if they for example go to the Settings.
When you click the BitBoxApp logo, we are routing to / and then with
maybeRoute() straight back to the first account, if there is one.
This seems to be broken with the current preact or
preact-router. Instead, the whole page reloads, with broken react
state (e.g. showing 'Connection lost' in the account...).
Inspired by https://github.com/preactjs/preact-router/issues/302, I
just randomly tried defering the routing via setTimeout (0 timeout),
which seems to fix the issue.
> frontend: fix double routing

- docs/BUILD.md
- frontends/qt/resources/MacOS/entitlements.plist
Notarization requires a hardened runtime. The app had two issues with
this:
- Gray screen at launch - fixed by whitelisting unsigned memory
execution in for QtWebEngine
- Couldn't open the HID device - fixed by
`allow-dyld-environment-variables`, by trial and error.
> qt/macOS: fix and document notarization

- scripts/travis_upload_nightlies.sh
The date command on macOS doesn't support the short -I or --iso flag:
$  ./scripts/travis_upload_nightlies.sh
date: illegal option -- I
usage: date [-jnRu] [-d dst] [-r seconds] [-t west]
[-v[+|-]val[ymwdHMS]] ...
[-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
So, use the longer +format argument.
> ci: use correct date arguments when uploading nightly on macos

- frontends/web/src/routes/account/send/send.tsx
If you first enter the amount, then scan an address from a QR code,
the amount would be deleted. Now it is preserved.
If the QR code encodes an amount as well, the amount is overwritten
with the amount from the QR code.
> frontend/send: don't overwrite amount when scanning a QR code

- .github/workflows/ci.yml
- scripts/travis_upload_nightlies.sh
See build docs https://github.com/digitalbitbox/bitbox-wallet-app/blob/673708a/docs/BUILD.md#signing--notarization and #903.
> ci: preserve symlinks while zipping macos app

- Makefile
The servewallet is used only during dev workflow and need not be
installed on PATH. It can be build and executed directly with "go run".
Especially relevant for docker-less setup.
For some hypothetical special cases, one can always
"go install ./cmd/servewallet" manually.
> cmd/servewallet: avoid install and just run

- frontends/web/src/routes/account/info/info.jsx
Removed classes that were previously used to vertically center
the address. Unfortunatelly this issue was not reproducible in
the macOS app. The addresses do not have to be vertically centered
anymore so removing the flex classes is fine.
> Frontend: fixes account info cropped on linux

- backend/handlers/handlers.go
There's no such thing as text/json. It may have used to be an
unofficial alternative a few years back but application/json is what's
set by IANA: https://www.iana.org/assignments/media-types/
This has no impact on the app except for maybe charset=utf8 when in
servewallet+webdev mode using an older browser, in which case it
actually makes them correctly interpret responses in UTF-8.
The reason I actually bothered is I started looking into the system language detection and one of the things I looked at was /api/config which is hard to read without correct mime-type. With it, beauty!
(on firefox)
> backend/handlers: set appropriate JSON mime type

- frontends/qt/genassets.sh
When doing incremental builds, I sometimes wipe web/build directory and
forget about it. This results in AppImage or Android completing the
build but their output's missing all web assets.
> scripts: make genassets.sh abort if web/build not found

- backend/rates/rates.go
- go.mod
- vendor/modules.txt
I find it very annoying, seeing nothing except "exchange rates changed"
messages in the logs. Hard to look for anything else.
Apart from the usual "no news is good news" reasoning, if exchange rate
update fails, it should be surfaced to the app UI in some way because
noone reads the logs except us. But it's beyond this simple commit.
Turns out spew package was used only in that one place.
Hence, vendor/modules.txt removes '## explicit' but the package is
still there because it's used by some others.
> backend/rates: avoid excessive logging and drop go-spew

- backend/backend.go
- util/socksproxy/socksproxy.go
The "using an unproxied ..." log line does not help in any way
but it keeps repeating every time something's using it, like the
exchange rate updates. It is actually any of these and more:
backend/update.go:
client, err := backend.socksProxy.GetHTTPClient()
backend/devices/bitbox/relay/request.go:
httpClient, err := request.channel.socksProxy.GetHTTPClient()
backend/coins/eth/etherscan/etherscan.go:
client, err := etherScan.socksProxy.GetHTTPClient()
backend/rates/rates.go:
client, err := updater.socksProxy.GetHTTPClient()
backend/backend.go:
httpClient, err := backend.socksProxy.GetHTTPClient()
When logged, it can't be attributed to the caller.
It's a separate line and logging is typically buffered; line ordering
should not be relied upon.
Similar reasoning with when the connection is …
> util/socksproxy: remove excessive logging

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/receive/receive.tsx
Only for unified accounts, where the user can actually choose the format.
> frontend: add guide entry to receive about address formats

- Makefile
Regression from 401bf795715738d5f47e95f4b060ac2a91a09ba9 where the
args were dropped.
> Makefile: fix servewallet commands

- backend/accounts/account.go
- backend/backend.go
- backend/coins/btc/account.go
- backend/coins/eth/account.go
- frontends/web/src/components/spinner/Spinner.tsx
- frontends/web/src/decorators/subscribe.tsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/account.tsx
On a slow network or on Tor, the initial sync can take a very long
time (minutes). After 10 or 20 seconds without any progress
indication, the user is left guessing if it will ever finish.
Unforuntately, the number of addresses that will be synced is not
known upfront, it could be 20 or 1000 addresses, and it is a rolling
window until there are 20 (or whatever the gap limit) unused addresses
in a row.
We could show `synced X out of Y` addresses, which both numbers
creeping up, but after some discussion decided that this does not help
more than just showing the number of addresses synced. The user still
does not know when it will finish, but at least sees that there is
progress.
The additional line is only shown for >1 synced
addresses. Single-address accounts like address-watchonly or …
> frontend/account: show number of synced addresses in the spinner

- frontends/web/src/components/backups/restore.tsx
- frontends/web/src/components/spinner/Spinner.css
- frontends/web/src/components/spinner/Spinner.tsx
- frontends/web/src/routes/device/setup/initialize.tsx
- frontends/web/src/routes/device/setup/seed-create-new.jsx
- frontends/web/src/routes/device/setup/seed-restore.jsx
- frontends/web/src/routes/device/unlock.jsx
Last use of showLogo was in 7f3f21b937e982d9c82e1967efbcf157f23a5ccf.
> frontend: remove unused property showLogo in Spinner

- cmd/servewallet/main.go
Some locale-involved formatting does not support charset appended
to a "code_territory" locale name and breaks the UI in
unpredictable ways when in servewallet dev mode.
In production, Qt ignores charset:
https://doc.qt.io/qt-5/qml-qtqml-qt.html#locale-method
Android doesn't seem to even mention charset:
https://developer.android.com/reference/java/util/Locale.html
> cmd/servewallet: strip charset from LANG in NativeLocale

- cmd/servewallet/main.go
I was too quick to push ef22a19f and forgot to update the comment.
> cmd/servewallet: correct comment about unsupported charset in LANG

- backend/devices/bitbox/pairing.go
Regression from 53466beec694c0bfdfdd80c5ba4ae10ddba6ff52.
Was accidentally reduced to 10s (maybe a debug leftover).
> backend/bitbox01: restore longer timeout when starting the pairing

- frontends/web/src/routes/settings/settings.tsx
@jadzeidan 
Add BB02-Multi to Ethereum and Litecoin.
Make it clearer that Separate account option is only for
BitBox02 Multi or Bitcoin-only.
> Frontend: update wording of multi and bitcoin-only

- frontends/web/src/components/sidebar/sidebar.css
This increases contrast of the sidebar label link for better
readability, as suggested by Thomas.
> frontend: increase readability of the sidebarlabel

- .github/workflows/ci.yml
- .travis.yml
- scripts/travis-ci.sh
Sometimes yarn install command fails with a network error.
Gradle and Homebrew do too but less often.
This will hopefully make the builds more stable.
Most recent run failed due to network: https://github.com/digitalbitbox/bitbox-wallet-app/runs/835012963, but there are more if you go back in build history, on both travis and github.
To invalidate the cache on GitHub, it is sufficient to change the cache key. Reference docs:
https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy.
Travis has an option in their UI: https://docs.travis-ci.com/user/caching/#clearing-caches
Both Travis and GitHub cache node modules, gradle and homebrew.
Some rough cache size numbers at the time of this commit:
- node …
> ci: enable caching to avoid intermittent build errors

- backend/accounts/baseaccount.go
- backend/coins/btc/account.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/btc/sign.go
- backend/coins/btc/transaction.go
- backend/coins/eth/account.go
btc and eth have a *lot* of copy/pasted fields and functions. This is
a start at putting them into a common helper struct.
> backend/coins: unify some common stuff in a BaseAccount

- backend/coins/btc/db/transactionsdb/transactionsdb.go
- backend/coins/btc/db/transactionsdb/transactionsdb_test.go
- backend/coins/btc/transactions/db.go
- backend/coins/btc/transactions/transactions.go
- backend/coins/btc/transactions/verification.go
Unconfirmed transactions would appear in an arbitrary order in the
app. This commit adds a time of first seen to each tx, and sorts by
that instead, so even unconfirmed transactions are ordered by age.
Same for transactions that confirmed in the same block, which are also
sorted in no particular order currently.
> backend/btc/transactions: store tx first seen time and sort by it

- frontends/web/src/components/devices/bitbox02/bitbox02.tsx
- frontends/web/src/locales/en/app.json
This PR adds a warning/checkbox to the create wallet & restore wallet wizard informing users that they should not plug their microSD card into a non-BitBox02 device.
> frontend: add micro_sd_card warning to create wallet & restore wallet wizard

- frontends/web/src/routes/account/send/feetargets.tsx
Regression of 8ff4909223d64362913fa1aea02a3174c4845b04. feeTargets is
empty in Ethereum, but the fee should still be shown.
> frontend/send: show fees for ETH

- backend/accounts/account.go
- backend/accounts/baseaccount.go
- backend/coins/btc/account.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/btc/transaction.go
- backend/coins/eth/account.go
- frontends/web/src/routes/account/send/send.tsx
When making a tx in the send screen, a tx proposal is created when
form fields are changed, to store the tx proposal to be signed and
sent, and also to compute the tx fees that the frontend should
display. This endpoint can have a long delay, e.g. in Ethereum it does
network requests.
The note was also part of the tx proposal, but that lead to a needless
delay and a display of "calculating fees..." when typing a note.
This commit makes a separate tx note proposal, as it can always be
processed instantly.
> backend/accounts: separate tx proposal from note proposal

- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/GoViewModel.java
- frontends/android/BitBoxApp/app/src/main/res/xml/device_filter.xml
Before this change, any device plugged into a USB-C would be accepted
as a BitBox02 device. This results in app crash if the the device isn't
actually a BitBox02 because Go's USB manager expects only valid devices
on the backend.
This commit simply ensures that the Android native code skips unknown
devices when looking for a BitBox02 in the list.
Closes https://github.com/digitalbitbox/bitbox-wallet-app/issues/938
> android: make sure device list is filtered by vendor/product ID

- frontends/web/src/components/transactions/transaction.tsx
When the user opens the tx detail and the note is empty
it renders in edit mode. When the user clicks save with
an empty note the input was still editable.
This change sets autofocus and readonly only based on
the editMode, so that the save behavior is consistent.
> Frontend: set focus on note input depending on editMode

- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/info/signingconfiguration.tsx
- hide account info for non bitcoin style accounts
- fix double back button in account info (eth)
> Frontend: ETH/ERC20 accountinfo

- backend/config/config.go
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/settings/settings.tsx
This will enable setting custom fees as well as seeing the sat/vB fee
rate estimations for the four fee targets.
> config: add option to enable expert fee settings

- backend/coins/btc/account.go
The db was closed before the Transactions instance was closed. This
could lead to a database access to a closed database in the
Transactions instance.
> backend/btc: close db last

- backend/rates/rates.go
The log is a debug leftover, and does not need to be logged every
minute.
> backend/rates: too much logging

- .github/workflows/ci.yml
TL;DIR: we're stuck with go1.14 + linter v1.27 for now. The longer explanation below is for potential gotchas when and if we'll ever upgrade to go1.15 or a more recent golangci-lint.
golangci-lint always uses the latest version of Go, which has recently released go1.15. Any linter version starting with the currently in use 1.27 and up to the latest 1.30 fails on go1.15 with panics. Any linter version past 1.27 with go1.14 panics, too.
Unfortunately, golangci-lint always overwrites the Go version when run in a github action in https://github.com/golangci/golangci-lint-action/blob/v1.2.2/src/install.ts#L26. I made a working PoC which allows to specify a Go version in https://github.com/x1ddos/golangci-lint-action/commit/6f8897f but wouldn't be able to send them a pull request because they …
> ci: delete troublesome golangci github action

- frontends/web/src/routes/account/send/feetargets.css
- frontends/web/src/routes/account/send/feetargets.tsx
- frontends/web/src/style/grid.css
With expert custom fee enabled the feetargets use now more space
as it displays sats per byte information. This change breaks the
proposed fee text onto a new line, but keeps the custom fee on
the same line on small screen.
> frontend: styling for fee targets and custom fee on small screen

- scripts/travis-ci.sh
Otherwise, it installs go1.15 which breaks the builds.
Also, removed HOMEBREW_NO_AUTO_UPDATE=1 line because otherwise homebrew
on Travis cannot find go@1.14.
> ci: pin to go1.14 on macOS

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/send/feetargets.css
- frontends/web/src/routes/account/send/feetargets.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/account/utils.ts
- frontends/web/src/style/grid.css
Addresses https://github.com/digitalbitbox/bitbox-wallet-app/pull/989#issuecomment-687723523
TODO: 
- locize rename and split the info in `send.feeTarget.description`
Screenshots:
> Frontend fee styling for largescreen

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/send/feetargets.tsx
c38dd0fc63704d290f1b552c67a1022f108ff8bd changed the translation keys,
which means all translations are lost.
Since it is only a text modification, it is best to keep the keys, so
the previous translations are marked for review instead of being
deleted.
The context field can be be translated with `_context` keys,
e.g. `_ltc`. If the translation is missing, it falls back to the key
without context.
> frontend/feeTargets: save the estimation translations

- backend/coins/btc/handlers/handlers.go
- frontends/web/src/routes/account/send/feetargets.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/test/routes/account/send/feetargets.test.tsx
The `Number()` conversion automatically cut off e.g. a zero, so it was
impossible to enter `1.01` without it being truncated back to `1` when
entering `1.0`.
Also, a default rate of `1` might not be good.
Solution: treat the fee rate as a string, like the amount, and let the
backend convert/validate.
> frontend/send: no autoformatting of custom fee rate

- appveyor.yml
Attempt to fix this CI error:
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
error compression-webpack-plugin@4.0.1: The engine "node" is incompatible with this module. Expected version ">= 10.13.0". Got "8.17.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make[1]: *** [Makefile:54: buildweb] Error 1
make[1]: Leaving directory 'C:/gopath/src/github.com/digitalbitbox/bitbox-wallet-app'
make: *** [Makefile:72: qt-windows] Error 2
> appveyor: use newer version of nodejs

- frontends/web/src/components/dialog/dialog.css
- frontends/web/src/components/forms/select.css
- frontends/web/src/routes/account/send/feetargets.tsx
- frontends/web/src/routes/account/send/send.tsx
The input focus stopped working after last rearrangement.
This fix delays calling input.focus as somewhat the input
is not ready at render to be focused.
This change also swaps network fee info and conditional
estimated confirmation time, as the fee is always displayed
and it is less flickering.
> frontend: focus custom fee input and rearange fee info

- .github/workflows/ci.yml
- scripts/travis-ci.sh
The auto-update seems to be erroring out which prevents the whole job to continue on GitHub CI.
Travis on the other hand already has Go preinstalled, as configured in .travis.yml.
> ci: skip macos homebrew auto-update on github runners

- appveyor.yml
We've been constantly exceeding our build artifacts storage because
every pull request generates and uploads a build artifact.
This should reduce the storage usage and make AppVeyor happy.
> ci: skip build artifacts for pull requests on appveyor

- frontends/android/BitBoxApp/app/build.gradle
- frontends/android/BitBoxApp/app/src/main/res/values/strings.xml
I don't want to uninstall my main app to test a new build. This will
install a separate app if build in debug mode.
> android: separate appID and app display name for debug builds

- backend/backend.go
- backend/rates/history.go
- backend/rates/history_test.go
- backend/rates/rates.go
This adds a new exported function PriceAt which returns a historical exchange rate at the given time.
Only BTC/USD pair is currently supported. All the others return flat 0.
Future commits will add all other coints and resolve pending TODOs.
> backend/rates: an MVP version of historical exchange rates updater

- frontends/web/.eslintrc.js
- frontends/web/tsconfig.eslint.json
Including .eslintrc fixed the following error:
Parsing error: parserOptions.project has been set for @typescript-eslint/parser.
The file does not match your project config: frontends/web/.eslintrc.js.
The file must be included in at least one of the projects provided.eslint
> Frontend: eslint inlucde .eslintrc

- frontends/web/.eslintrc.js
Tried with beforeBlockComment, allowBlockStart, allowObjectStart but
a comment between arugument destruction and another comment in a
commented out jsx block always errored, therefore completelly
disabled this rule.
> Frontend: disable eslint rule lines-around-comment

- backend/accounts/transaction.go
- backend/accounts/transaction_test.go
- backend/coins/eth/etherscan/etherscan.go
- backend/coins/eth/types/types.go
The fee is paid in Ether and is accounted for in the ETH account
already.
> backend/accounts: fix timeseries computation for erc20 tokens

- backend/backend.go
- backend/coins/eth/etherscan/etherscan.go
- util/ratelimit/ratelimit.go
We made one EtherScan instance per ETH and ERC20 token, all of them
firing at once. This was usually not a problem, except for in the
account summary / portfolio page, where all accounts are loaded in
quick succession.
This commit moves out the rate limiting to a new httpClient reused by
all instances.
> backend/eth: properly rate limit EtherScan

- backend/backend.go
- backend/config/config.go
- backend/erc20.go
- backend/rates/history.go
- backend/rates/history_test.go
- backend/rates/rates.go
- frontends/web/src/components/rates/rates.tsx
- frontends/web/src/routes/settings/settings.tsx
All active coin/fiat pairs are taken from the config on startup.
A follow up commit will make the updater enable/disable pairs
when the config is changed at runtime from the UI.
This migrates one bit of frontend's opaque config fiatList to the
backend side since both now need to be aware which fiat currencies
are active.
> backend/rates: support historical exchange rates for all coins

- backend/rates/rates.go
This is used in most recent exchange rates to show fiat value when
making a transaction.
Historical rates with CoinGecko already has it.
> backend/rates: add the missing SAI token to CryptoCompare

- backend/rates/history.go
- backend/rates/history_test.go
So that the handlers can identify whether the data is ready to plot a chart for a given range in the account portolio.
> backend/rates: expose history earliest/latest methods for handlers

- backend/backend.go
- backend/rates/history.go
Their docs at https://www.coingecko.com/en/api specify "up to 100 requests/minute" but let's use a slightly smaller value.
> backend/rates: rate-limit CoinGecko API client

- backend/backend.go
- backend/rates/history.go
- backend/rates/history_test.go
- backend/rates/rates.go
Turns out, they are lowercase everywhere in the backend.
The original CryptoCompare client uses uppercase.
This is left as a TODO for the future.
Note that frontend seem to use all uppercase, both coins and fiats.
> backend/rates: use lowercase coin symbols

- backend/backend.go
- backend/rates/history.go
- backend/rates/rates.go
- frontends/web/src/components/rates/rates.tsx
This is done in two places: at the backend startup and whenever active
coin accounts or selected fiats list changes. In both cases, all
historical rates goroutines are shut down and then started again
but only for the selected coin/fiat pairs.
Maybe a better way would've been to shut down only those goroutines
for which no coin or fiat is active anymore, but this complicates a
simple function and with an added jitter in a follow up commit will be
unnecessary.
> backend/rates: make historical rates settings configurable at runtime

- backend/backend.go
- backend/rates/history.go
- backend/rates/rates.go
This is useful for an upcoming commit where RateUpdater starts using a
persistent database for historical exchange rates which typically needs
to terminal all transactions.
It is also useful in testing where multiple instances of backends may
introduce lots of loose updater goroutines, if not shut down at the
end of the test.
Builds on top of https://github.com/digitalbitbox/bitbox-wallet-app/pull/1044.
> backend/rates: stop all RateUpdater's goroutines when Close'ing backend

- .github/workflows/ci.yml
Turns out homebrew kicks off its clean up process each 30 days.
However, this fails with strange errors like
"Error: Not a directory @ dir_s_rmdir - /usr/local/Cellar/openssl"
in https://github.com/digitalbitbox/bitbox-wallet-app/pull/1054/checks?check_run_id=1276415647
Wouldn't want to waste time on homebrew quirks and bugs.
So, I propose we disable its cleanup. It's a CI cache anyway.
https://github.com/Homebrew/brew/blob/master/docs/FAQ.md#how-can-i-keep-old-versions-of-a-formula-when-upgrading
> ci: prevent homebrew from running cleanup on github

- backend/backend.go
- backend/rates/bbolt_bench_test.go
- backend/rates/db.go
- backend/rates/history.go
- backend/rates/history_test.go
- backend/rates/rates.go
- util/ratelimit/ratelimit.go
RateUpdater loads the data on ReconfigureHistory for active coin/fiat
pairs and dumps new data on disk during each update loop iteration.
All PriceAt look ups use RateUpdater.history in-memory map as before.
In other words, the cache layer is transparent to RateUpdater users.
RateUpdater can still function without the cache but the app users
may be noticeably rate-limited, especially when connected over a VPN
or Tor.
> backend/rates: cache historical data in a persistent bolt DB

- backend/backend.go
- backend/coins/btc/account_test.go
- backend/coins/btc/coin.go
- backend/coins/btc/coin_test.go
- backend/coins/btc/maketx/maketx_test.go
- backend/coins/coin/coin.go
- backend/coins/coin/mocks/coin.go
- backend/coins/eth/coin.go
The "Bitcoin"/"Litecoin" etc. strings we define for accounts are in
fact coin names.
We mov this to the coin so it can be used to show the name of the coin
to the user, e.g. in the account summary page (table headers, which
currently just shows the coin code).
The accounts automatically added from a keystore just adopt the coin
name, so it behaves the same as before.
> backend/coin: add Coin.Name()

- backend/rates/history.go
- backend/rates/rates.go
The forward history update loop was iterating every 10min. This
interval was chosen after an approximate time of a new block on the
chain. However, it may be too slow in the worst case where RateUpdater
provides data stale up to 10min while already available from the API.
This commit reduces the potential staleness to only up to ~1.5min.
> backend/rates: add jitter to history loops and make them faster

- backend/handlers/handlers.go
- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/account/summary/balancestable.tsx
Since grouping accounts by coin currently happens in the frontend, we
fetch the coin names in the same way as we fetch the coin totals from
the backend: with a map. Maybe some day the backend can prepare all
the data in one go, which would make that part a bit nicer.
> frontend/accountSummary: show coin names instead of coin codes

- backend/handlers/handlers.go
- backend/rates/history.go
- backend/rates/history_test.go
If we try to chart until the current hour, often there are no rates
for the last hour, and the error 'gathering info' would be shown.
Now, the chart goes up until the latest datetime for which we can
compute a chart entry.
> backend/handlers: show chart until last available date

- Makefile
- scripts/dockerdev.sh
`make dockerdev` entered an image called `bitbox-wallet` made from
`make dockerinit`.
The official image on dockerhub is shiftcrypto/bitbox-wallet-app. Just
pulling that should be enough for someone to get started.
Fixes #1060.
> docker: unify docker image names

- backend/handlers/handlers.go
- frontends/web/src/routes/account/summary/accountssummary.tsx
We will use the fiat marked as starred in the settings for the
charts. This is a quick solution to a fiat cycle button that will take
more time.
> backend/handlers: use starred fiat for chart

- frontends/web/src/app.tsx
- frontends/web/src/components/sidebar/sidebar.tsx
Default route to account summary after unlock.
When there are no accounts, route to /, to not stay in the account summary.
> frontend/app: show account summary in production, fix routing

- frontends/web/package.json
Our desktop app is currently based on 5.11.2:
https://doc.qt.io/archives/qt-5.11/qtwebengine-overview.html
> This version of Qt WebEngine is based on Chromium version
65.0.3325.151, with additional security fixes from newer versions.
The previous value made our JS compilation toolchain output code that
led to a syntax error in the desktop app.
> frontend: fix browserlist

- frontends/web/src/routes/account/summary/accountssummary.tsx
The account summary screen can display the coin summary table,
even if not all chart data have been loaded.
> Frontend: fix no account to show loading

- frontends/web/src/routes/account/summary/accountssummary.tsx
We keep the code so we can bring it back easily if needed, but disable
in production.
It was accidentally enabled when we enabled the whole page in
production.
> frontend/accountsummary: remove export

- backend/handlers/handlers.go
- frontends/web/src/routes/account/summary/accountssummary.tsx
Was previously added to show the coin title when coin grouping was
still around. Not needed anymore.
> frontend/accountsummary: remove coin title

- frontends/qt/resources/Makefile
- frontends/qt/resources/linux/Makefile
The whole resources folder is packaged and installed, so the Makefile
was installed at `/Makefile` before.
Installing the new (fixed) package will remove the /Makefile.
Fixes #1081
> frontend/qt: move Makefile out of linux resources folder

- backend/accounts/account.go
- backend/coins/eth/account.go
An account should enforce Balance() can be safely called after
Initialize() and that the WaitSynchronized() call inside waits for it
to be actually synchronized. in BTC this is enforced as the first
counter increment happens in Initialize() (ensureAddresses()). In ETH
however, it did not. This fixes it, so that account.Balance() returns
the correct data after account.Initialize().
> backend/eth: initial sync fix

- backend/accounts/transaction.go
- backend/handlers/handlers.go
EarliestTime(), like Timeseries(), has to return an error if data is
missing. Before, if a btc/ltc account had only confirmed transactions
with no timestamps (headers not synced up yet, which give the
timestamp), it would have just been ignored in the chart, instead of
showing the error that we are still gathering data.
> backend/handlers/accountSummary: fix missing data issue

- frontends/web/src/routes/account/summary/chart.css
- frontends/web/src/routes/account/summary/chart.tsx
Disabled the standard crosshair price and time labels and added
a custom tooltip, displaying price and date (and time on weekly).
Also enabled entireTextOnly for the priceScale so text should
not be cut off anymore.
> Frontend: use custom chart tooltip

- frontends/web/src/routes/account/summary/chart.tsx
The summary differenece in percentage was sometimes off as
it did not update at all. Happend with all filter or with
shorter datasets, i.e. first tx less than a year old.
Fix is to simple remove the falsy visiblerange.barsBefore
check as it can be 0.
Also imported lightweight-chart types for LogicalRange and
BarsInfo and reformated the percentage debug tooltip.
> Frontend: fix summary percentage diff

- frontends/web/src/components/spinner/ascii.css
- frontends/web/src/components/spinner/ascii.tsx
- frontends/web/src/routes/account/summary/accountssummary.css
- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/account/summary/chart.css
- frontends/web/src/routes/account/summary/chart.tsx
- should flicker less during loading, due to fixed widths
- use animated text spinner
tested with:
- just `make servewallet`
- `rm -rf appfolder.dev && cp -r appfolder.dev.brokentxdate appfolder.dev && make servewallet` Note: required new pairing, best unplug BitBox02 first
- `rm -rf appfolder.dev/cache/exchangerates && make servewallet`
> Frontend portfolio loading

- backend/backend.go
- backend/rates/history.go
- backend/rates/rates.go
- util/ratelimit/ratelimit.go
When blocked by a rate limit during a network round trip, the request context keeps running. This causes such requests to abort before they even get a chance to fire due to the expired context.
What we want is to start a request context right before making an API call. This commit does exactly that by moving the rate limiting function at a "layer" above the HTTP round trip.
The commit also changes API requests timeout from 1min to 10sec - more than enough for CoinGecko to respond. If it doesn't, we better retry than wait another 50sec.
Alternatives which didn't work:
1. Make a new context in RateLimitedHTTPTransport once unblocked. This loses the cancel function, needed in ReconfigureHistory. It is still possible to make this work by select'ing on both old and new contexts but the code …
> backend/rates: do not let request context expire when rate-limited

- backend/rates/history.go
af5da49 introduced a new case in computing how long to backfill for in a loop iteration. Specifically, when fetched data is worth of less than 90 days.
My empirical testing here shows it may fall into many edge case traps and be stuck somewhere at 89.x days, never backfilling further in the past.
It may have already become too complicated and not worth it. I propose to simplify it back to what it was before: get daily 90days, hourly anything after. If an API response to the first call falls a bit short of 90 day, so be it. Forward history updates are hourly anyway.
> backend/rates: revert a buggy start/end computation bit in af5da49

- backend/rates/history.go
- backend/rates/history_test.go
Before this commit, forward history update loop has never had a chance
to catch up. It always calls an update with (start, now) but by the
time it gets to fetch the data, "now" is in the past.
This gets worse as the number of active coin/fiat pairs increases.
The bigger the number, the greater the lag behind "now" is due to rate
limiting.
The change resolves the issue by evaluating "now" at the time
RateUpdater requests data from the upstream and always returns the
latest available exchange rates.
> backend/rates: evaluate time.Now at the coingecko API call time

- backend/rates/history.go
In hindsight, exponential backoff would not help when many coin/fiat
pairs compete against the same rate-limited channel. The end result
reaches a constant QPS rate anyway.
When only few coin/fiat pairs are enabled, the random element may help
in spreading the load more evenly onto the upstream API.
> backend/rates: randomize back/forward cache fill loops

- frontends/web/src/routes/account/summary/chart.tsx
Before it was just an empty tooltip if the balance is 0.
> frontend: show 0 value in chart tooltip

- frontends/web/src/routes/account/summary/chart.css
- frontends/web/src/routes/account/summary/chart.tsx
On the weekly chart with many datapoints it should
now display date and time in the chart tooltip.
Did only display date before.
> frontend: render time in chart tooltip

- .golangci.yml
- backend/handlers/handlers.go
If the user gets started in the app for the first time and there are
no transactions, there is no need to wait for the headers and exchange
rates to sync. This avoids the 'gathering info' message as the first
impression.
> backend/handlers: chart data not missing if there are 0 transactions

- backend/accounts/transaction.go
- backend/accounts/transaction_test.go
- backend/coins/btc/blockchain/blockchain.go
Electrum servers return -1 for the tx height if the tx is unconfirmed
with an unconfirmed parent. The code in the Timeseries() incorrectly
assumed that unconfirmed means a height of 0, leading to an
false `ErrNotAvailable` error if such a transaction is present.
> backend/accounts: handle transactions with negative height

- backend/backend.go
- backend/coins/btc/electrum/client/client.go
- backend/coins/btc/electrum/electrum.go
- backend/config/config.go
- util/jsonrpc/jsonrpc.go
This is a breaking change. The app now requires a protocol at least v1.4 and won't be able to use an older electrum-compatible server which enforces protocol versioning during negotiation. Even then, the app won't be able to get a block height from older servers.
Also, some quick fixes to crashes due to util/jsonrpc that I saw while working on this.
The new servers are still synch'ing BTC mainnet so try testnets for now. LTC mainnet is ready. Should be all good by tomorrow.
Protocol changes: https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-changes.html
Updates https://github.com/digitalbitbox/bitbox-wallet-app/issues/499
Updates https://github.com/digitalbitbox/bitbox-wallet-app/issues/1123
> Compatibility with Electrum protocol 1.4 and Electrs v0.8.6

- frontends/web/src/routes/account/summary/chart.tsx
When leaving the chart on the weekly view after a while
it would be overwritten by the daily chart data.
It now checks the current source and updates the chart
accordingly.
> frontend: update chart depending on the current source

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/utils.ts
- frontends/web/src/routes/buy/info.tsx
The dropdown checks now each coin if buying is supported and
only shows those accounts.
> frontend: only show buyable coins in moonpay dropdown

- backend/chart.go
- backend/coins/btc/account.go
- backend/coins/btc/synchronizer/synchronizer.go
- backend/handlers/handlers.go
- util/jsonrpc/jsonrpc.go
- util/logging/instance.go
- util/logging/logger.go
- util/logging/logger_test.go
App log file is now rotated once its size exceeds a reasonably large
number. The rotated file is moved to a new name with ".1" suffix,
common for log rotations, replacing any existing file.
Once rotated a new empty file is created under the original name.
Thus, the app keeps at most double the threshold size.
Because previously the log file size was unlimited, we also truncate
the head of an existing log file if its size already exceeds the
threshold.
> logging: don't panic, truncate and rotate

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/buy/guide.tsx
The old key has Safello text in translated languages, and the key
'support' also does not fit.
> frontend/buy: change exchanges guide key

- frontends/web/src/i18n/config.js
- frontends/web/test/i18n/config.test.tsx
BitBoxApp currently does not support LANG=C.UTF-8 and errors with
`js: Uncaught RangeError: Invalid language tag: C`
Adding another fallback in case the proposed locale errors with Date.toLocaleString.
> frontend: catch language c and fallback to en

- backend/exchanges/moonpay.go
The app switches between test and live settings based on the coin code.
ERC20 tokens will come in a follow up commit.
They require some juggling between eth-erc20- prefix on the backend, no prefix on the frontend, and cross checking with what's enabled in the Moonpay dashboard.
> backend/moonpay: go live with BTC, LTC and ETH

- frontends/web/src/app.tsx
MoonPay needs an address to send to, therefore the device has
to be plugged in when using the service. Unplugging the device
should now route back to /.
> frontend: route back when unpluggin bb02 in buy view

- frontends/web/src/routes/buy/info.tsx
Before the check to find out which coins can be bought was only
executed when the user agreed to the disclaimer. With the 'do not
show the disclaimer again' option checked, the component shows
to the coin selection directly and needs to know which coins can
be bought rightaway.
> frontend: moonpay check for supported coins on mount

- backend/coins/btc/handlers/handlers.go
- backend/config/config.go
- backend/handlers/handlers.go
- frontends/web/src/i18n/config.js
- frontends/web/src/i18n/i18n.js
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/buy/info.tsx
- frontends/web/src/routes/buy/moonpay.tsx
- frontends/web/test/i18n/config.test.tsx
- frontends/web/test/i18n/i18n.test.tsx
Preferences are taken straight from the app config.
If a value is unsupported by Moonpay, they fall back to some default
values, according to their documentation. Worst case scenario, users
are still able to change both fiat and language directly in the widget.
> moonpay: propagate fiat and language to the widget 

- frontends/web/src/style/base.css
The pairing code font broke on macOS it used something with
serife like Times. We already use monospaced font in textareas
to display receive address or xpub.
Changed font for pre element to always use a monospace font.
> frontend: use monospaced font for pre element

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/buy/guide.tsx
- frontends/web/src/routes/buy/info.tsx
Updated links in disclaimer and guide pointing to 'supported countries' and MoonPay's privacy policy.
> frontend: update moonpay policy and support links

- frontends/web/src/routes/buy/moonpay.tsx
Did not cover the whole available area on larger screens.
Changed by just removing the content class that limits the
width of the content area.
> frontend: fix moonpay background on large screen

- frontends/web/src/routes/buy/moonpay.css
- frontends/web/src/routes/buy/moonpay.tsx
Added same check isBitcoin as in info.tsx and fixed a CSS
issue in combination with the spinner component. The spinner
is always in the background and covered later by the MoonPay
iframe as we just let it load and don't have the info if it
really loaded to hide the spinner again. The CSS issue was
that the spinner covered the title.
> frontend: add buy bitcoin or buy crypto in moonpay view

- backend/backend.go
- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
- frontends/qt/main.cpp
At the moment, we have only /buy/moonpay/ but the idea is we will
possibly add more in the future.
This commit also unifies Qt and Android frontend whitelists. They were
disaligned after switching routes back and forth.
There's no reason why keep two separate whitelists in the SystemOpen
function. They serve the same purpose and can be easily combined into
one.
So far, there doesn't seem to be a reason to use a more onerous regexp
compared to just a string prefix. This commit in fact does the latter
and all existing patters line up nicely.
If there's really a need in the future, can always switch to a regexp
based approach.
> frontend,backend: correct and unify/combine whitelists for opening external URLs

- frontends/web/src/components/devices/bitbox02/bitbox02.tsx
Unfortunatelly I could only reproduce it once and got the error
js: Uncaught TypeError: Cannot read property 'querySelectorAll' of null
on line
https://github.com/digitalbitbox/bitbox-wallet-app/blob/6ed4ff598ce0a352e13bb5bc3a42edcebc83d47f/frontends/web/src/components/devices/bitbox02/bitbox02.tsx#L357
This fix removes the dom reference and instead adds each checkbox
as a boolean to the state. That way we don't depend on the form
to be there or having to querySelect the input elements and check
if they are checked.
> frontend: fix continue button not clickable in wizard

- frontends/web/src/routes/account/account.css
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/style/layout.css
The new buy was miss-aligned, the buttons now have their own
line and are all equally spaced out and use the same width.
cc @jadzeidan
> frontend: better actions buttons layout on mobile

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/buy/info.tsx
Removing it for now, can be enabled later.
> frontend: remove apple and samsung pay from moonpay

- backend/handlers/handlers.go
- frontends/web/src/app.tsx
- frontends/web/src/routes/buy/info.tsx
- frontends/web/src/routes/buy/moonpay.tsx
Still could not find the 'undefined' issue though...
> Small moonpay fixes

- frontends/web/src/api/account.ts
- frontends/web/src/app.tsx
- frontends/web/src/components/alert/Alert.tsx
- frontends/web/src/components/balance/balance.tsx
- frontends/web/src/components/sidebar/sidebar.tsx
- frontends/web/src/components/transactions/transaction.tsx
- frontends/web/src/components/transactions/transactions.tsx
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/info/signingconfiguration.tsx
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/account/send/feetargets.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/account/utils.ts
- frontends/web/src/routes/buy/info.tsx
- frontends/web/src/routes/buy/moonpay.tsx
Some components contain api interfaces, that got wildly imported
all over and grew organically. This lead to incomplete and duplicate
interfaces and is hard to maintain.
Centralizing all api interfaces and promises into web/src/api helps
reducing duplicates and separates api from ui components.
Additionally promise return values from api all come typed.
This is the first step and collects all account interfaces and api
calls into api/account.ts. Next step is to refactor all components
to import the interfaces and api calls from api/account.
> frontend: refactor account into api/account

- frontends/qt/main.cpp
The expression `securityOrigin.toString() != "qrc://"` was always true
and so the video capture was never enabled when scanning QR code,
resulting in a blank page.
Also, `QUrl::toString()` uses `PrettyDecoded` formatting by default, but:
> The exact behavior of PrettyDecoded varies from component to
> component and may also change from Qt release to Qt release.
See https://doc.qt.io/qt-5.12/qurl.html.
So, comparing the scheme seems more appropriate here.
Unclear when things changed. It is possible the condition has
never worked before but the permission to use video capture was granted
implicitly due to local origin. The fact is Windows and macOS works
without this change. So, this must be a combination of Qt + Linux.
> frontend/qt: correct origin check when enabling video capture

- .github/workflows/ci.yml
- scripts/docker_install.sh
- scripts/travis-ci.sh
Nodejs LTS 14.x is required by newer preact-cli.
While there, also upgrade Go. Been meaning to do it for a while. Seemed
like a good opportunity.
> docker: upgrade nodejs to 14.x and go to 1.14.15

- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
- frontends/qt/main.cpp
- frontends/web/src/routes/buy/moonpay.tsx
- frontends/web/src/utils/custom.d.ts
They state that from March 31st, 2021, their in-app KYC process will
require camera access.
They said that
https://webrtc.github.io/samples/src/content/getusermedia/gum/ can be
used to test if it is working. This commit makes the camera at that
site work in the moonpay.tsx iframe.
In the Qt app, the security origin scheme check is dropped, as that is
easier than checking for the moonpay url. Note that all external
requests are blocked anyway, so only already whitelisted pages can
even be loaded, so the check was redundant.
> frontend: allow Moonpay to request camera access

- backend/handlers/handlers.go
We removed them to reduce logging volume, but the endpoints called are
very helpful output to trace what happened.
> handlers: log endpoints again

- CHANGELOG.md
- frontends/web/src/app.tsx
After creating a new wallet or restoring from backup, the app is
supposed to show a success screen. This has not happened due to a
regression.
The screen was skipped because the DeviceSwitch and the BitBox02
components were recreated completely, losing the internal state.
The components were recreated because the key attribute,
e.g. `key={['device-switch', devices]}`, "changed". The devices object
was the same, but in Javascript, one can't compare arrays like
this. `[] == []` or `['device-switch'] == [''device-switch']` is
always false, so the component was re-recreated.
We fix it by turning making the key a string derived from the devices,
so preact will correctly identify when the devices changed and when
they didn't change.
> frontend/app: fix bb02 success screen by fixing devices key attribute

- frontends/web/src/app.tsx
- frontends/web/src/components/devices/bitbox02/sdcardcheck.tsx
- frontends/web/src/components/devices/bitbox02/settings.tsx
- frontends/web/src/routes/device/manage-backups/manage-backups.jsx
The BackupsV2 component would be fed the sdCardInserted property via
the URL from the Settings component. This is fragile, e.g. if you
remove the sdcard while in the settings screen and then go to backups,
you will get an error.
The url part is also only used for the BitBox02, but the ManageBackups
component is for both BitBox01 and BitBox02, which makes this also
confusing.
For now we abstract away the microSD card check and use it when
loading the Backups component, so it should always work.
There is more refacoring that can be done later, e.g. cleaning up the
back button mess.
> frontend/bitbox02: fix sd card inserted state

- frontends/web/src/api/account.ts
- frontends/web/src/api/accountsync.ts
- frontends/web/src/api/subscribe-legacy.ts
- frontends/web/src/api/subscribe.ts
- frontends/web/src/app.tsx
- frontends/web/src/components/sidebar/sidebar.tsx
- frontends/web/src/connected.tsx
- frontends/web/src/index.js
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/buy/info.tsx
- frontends/web/src/routes/buy/moonpay.tsx
- frontends/web/src/utils/event-legacy.ts
- frontends/web/src/utils/subscriptions.ts
- util/observable/action/action.go
The subscribe decorator is currently used to push data from the go
backend to the frontend, using websocket in devmode and qt bridge
in the app. But it currently only works for the "newer" events,
containing "subject", "action" and "object", but not the "older"
events that have "data", "deviceID", "meta", "type" or "code"
keys. To support "older" events the pushed data needs to be handled
differently, this is done in utils/events-legacy.ts which is similar
to the existing utils/events.ts.
While the decorators are convinient to use and nicely abstract away
the data fetching they also have drawbacks:
- pushed data have no typed interfaces, so the interfaces have to
be defined on the component level as component props, which works
but is harder to share between different components and …
> frontend: refactor subscriptions and acountsync

- backend/coins/eth/account.go
- backend/coins/eth/etherscan/etherscan.go
- backend/coins/eth/rpcclient/rpcclient.go
- backend/coins/eth/types/types.go
- backend/coins/eth/types/types_test.go
By experience, it seems that at least with the Etherscan backend, a
transaction that is broadcast successfully (api endpoint returns 200
OK, no error message) still might be lost and never be mined. This
lead to the ETH account being unusable, especially because follow up
transactions get a new nonce, and it also can never be mined until the
previous nonce was mined.
This is an attempt to fix this: we simply rebroadcast when we see that
the backend does not know about the transaction. It happens the first
time immediately after broadcast, and then regularly with each account
update.
For now we simply log the broadcast attempts, so we can analyse the
problem further. In the future, we might use this to mark a tx as
failed (e.g. more than 10 failed attempts), or to give the user
certain …
> backend/eth: rebroadcast transactions that seem to be lost

- frontends/web/src/components/backups/backups.css
- frontends/web/src/components/devices/bitbox02/backups.tsx
- frontends/web/src/components/devices/bitbox02/checkbackup.tsx
- frontends/web/src/routes/device/manage-backups/manage-backups.jsx
- changed orange button to blue
- increase backup list width and heigth to make better use of the
screen and prevent a second scrollbar on the container
- rearanged buttons
> frontend: update manage backup layout

- frontends/web/src/components/backups/backups.css
- frontends/web/src/components/steps/steps.css
On the manage backups view the buttons have no space and on restore
from backup the buttons are too big. The gap CSS attribute only works
in newer webkit versions.
- changed from gap to margin to fix spacing issue
- removed button height on the restore backup from sd card, so that
the button uses the default button height
> frontend: fix manage backup buttons

- frontends/web/package.json
- frontends/web/src/components/qrcode/qrreader.ts
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/yarn.lock
This should make the JavaScript main bundle.js smaller and postpone loading the zxing library until you navigate to the Send route.
To create a chart use `cd frontends/web && yarn build --json` that will create a `stats.json`, you can drop that into https://chrisbateman.github.io/webpack-visualizer/
> frontend: lazy load qrreader

- frontends/web/src/api/account.ts
- frontends/web/src/components/rates/rates.tsx
- frontends/web/src/routes/account/send/feetargets.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/account/send/utxos.tsx
- frontends/web/src/routes/account/summary/chart.tsx
- frontends/web/src/routes/settings/components/fiat/fiat.tsx
Only app, accounts-summary, accounts tsx and some of the involved
modules have now migrated to api, but this ended up that we have
duplicate types for coin and fiat.
Moved fiat and coin type to api/account and import it from there,
so it shouldn't have anymore duplicate types.
> frontend: dedup coin and fiat types in rates

- backend/coins/btc/handlers/handlers.go
- frontends/web/src/api/account.ts
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/summary/accountssummary.tsx
It matches better what the getStatus call handling wants.
This will make it easier to add additional info such as error codes or
error messages to be displayed.
> frontend/account: bundle status data

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/account.tsx
Sometimes users activate the setting by mistake, or activate it but
don't have a Tor proxy running.
> frontend/account: if offline and tor proxy enabled, give user a hint

- frontends/web/src/assets/icons/copy-disabled.svg
- frontends/web/src/components/copy/Copy.tsx
There is no point if showing a disabled copy button, also the real
copy button is currently displayed in a different place (dialog).
Closes https://github.com/digitalbitbox/bitbox-wallet-app/issues/1001
> frontend: hide disabled copy button on receive view

- frontends/web/src/components/copy/Copy.tsx
- frontends/web/src/components/qrcode/qrcode.tsx
- frontends/web/src/routes/account/receive/receive.tsx
Moved state initialization out of constructor and use readonly
state initialization. We already do that in various places, reason
is less boilerplate and it tells TypeScript that the state key
shall not be mutated, example this.state.foo = 'bar'.
The linter should already know that this.state should be readonly
via eslint-plugin-react.
A while ago the copy component's input element has been changed
to textarea to support multiple lines, but the variable names and
types where still using input as name and type.
Changed variable names and types to use textarea, this should not
have a practical difference.
on top of https://github.com/digitalbitbox/bitbox-wallet-app/pull/1211
> Frontend: update copy component state init, var and type naming

- backend/backend.go
- backend/bitboxbase/bitboxbase.go
- backend/coins/btc/electrum/electrum.go
- backend/coins/btc/electrum/electrum_test.go
- util/test/tcp.go
The commit makes the electrum client provide SNI server name when
connecting to a node over TLS. It is very useful for a setup with
multiple nodes running on the same machine where a loadbalancer
dispatches connections to a specific node based on the SNI during a TLS
handshake. For example:
btc1.shiftcrypto.io:443  -> local port 50001
ltc1.shiftcrypto.io:443  -> same machine, local port 50002
tbtc1.shiftcrypto.io:443 -> same machine, local port 51001
I don't expect any breaking changes. The ServerName field merely
provides an indication to the server, typically for a certificate
selection in a multi cert setup. Our certificate validation remains
the same.
> backend/electrum: set ServerName to help SNI-capable loadbalancers

- backend/config/config.go
We've received a number of complaints about our nodes being
inaccessible on some systems. Most resolve by allowing an outbound
connection in a firewall or similar.
This commit tries to reduce this issue to a minimum by abusing HTTPS
and making the app connect via port 443 which these firewalls are
expected to be more lenient with.
These are the same nodes originally migrated to in commit 309ea92,
just behind port 443. On the infrastructure side, the routing is done
by matching the server name during TLS SNI handshake and
reverse-proxying TCP connection to the specific 5xxxx port on the same
host.
This of course requires client cooperation where it sends appropriate
server name in TLS SNI. Done in https://github.com/digitalbitbox/bitbox-wallet-app/pull/1209.
> backend/config: migrate node addresses from 5xxxx ports port 443

- frontends/qt/setup.nsi
The installer needs admin privileges for writing to `$PROGRAMFILES64`
and HKLM. The previously used value of "highest" escalates only to the
available permissions under that user. If the user can't escalate to
admin, the installer won't be able to write to `$PROGRAMFILES64`.
Setting `RequestExecutionLevel` to admin always escalates to admin or
fails the process.
Docs:
https://nsis.sourceforge.io/Reference/RequestExecutionLevel
---
Unfortunately, the setup.nsi script mixes system-wide and per-user
installation. For example, it writes files to the system-wide
$PROGRAMFILES64 and Start menu but then registers the uninstaller under
HKCU (Current User) for some unknown reason.
Neither the installer nor BitBox.exe need any special privileges.
Ideally, everything is run under current user and …
> windows: always run the installer as admin

- frontends/qt/setup.nsi
If a user already has BitBoxApp installed and it's currently running,
the new installation won't be able to proceed because the bitbox.exe is
not writable, assuming the same install directory is chosen.
This commit forces any running instance of bitbox.exe to quit before
doing anything else.
The taskkill command should be available on at least Windows 7 and on.
Docs: https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/taskkill
> windows: kill any running instance of bitbox.exe during the install

- frontends/web/src/app.tsx
Fixes a regresseion from
c9401c7cf18884287d743402b64e6a757e203127. Unlocking a device routes to
/account and is stuck there becaue maybeRoute() was not called anymore.
> frontend/app: restore routing

- backend/devices/bitbox02bootloader/device.go
Easier debugging when e.g. a firmware update goes wrong.
> backend/bitbox02bootloader: log firmware/signing key hashes

- frontends/web/src/components/backups/restore.tsx
- frontends/web/src/components/devices/bitbox02/bitbox02.tsx
- frontends/web/src/components/devices/bitbox02/createbackup.tsx
- frontends/web/src/components/devices/bitbox02/mnemonicpassphrase.tsx
- frontends/web/src/components/devices/bitbox02/reset.tsx
- frontends/web/src/components/devices/bitbox02/setdevicename.jsx
- frontends/web/src/components/devices/bitbox02/showmnemonic.tsx
- frontends/web/src/components/devices/bitbox02/upgradebutton.tsx
- frontends/web/src/components/wait-dialog/wait-dialog.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/bitboxbase/basesettings.tsx
- frontends/web/src/routes/device/settings/components/changepin.jsx
- frontends/web/src/routes/device/settings/components/device-lock.jsx
- frontends/web/src/routes/device/settings/components/hiddenwallet.jsx
- frontends/web/src/routes/device/settings/components/reset.jsx
- frontends/web/src/routes/device/settings/components/upgradefirmware.jsx
This potentially fixes TypeError: Cannot read property 'classList'
of null, in rare cases during wait-dialog's animation. The error
did not seem to have any other impact and app was fully functional.
> frontend: rewrite wait-dialog to typescript

- frontends/web/src/routes/account/account.tsx
The spinner takes up the whole screen. Afaik the status removed in
this commit is never visible.
> frontend/account: remove invisible offline status

- backend/backend.go
- backend/config/accounts.go
With the unified accoutns feature added some time ago, one
account (e.g. "Bitcoin") can combine multiple configurations,
e.g. p2wsh and p2wsh-psh, each at a separate keypath.
We will use persisted accounts to manage multiple accounts and
watchonly accounts, so they must also be able to store multiple
configs per account.
> backend/config: make persisted accounts compatible with unified accounts

- backend/devices/bitbox/keystore.go
- backend/devices/bitbox02/keystore.go
- backend/keystore/keystore.go
- backend/keystore/software/software.go
- backend/keystore/software/software_test.go
And implement it for all three keystore backends we have.
> backend/keystore: add RootFingerprint()

- backend/accounts/baseaccount.go
- backend/accounts/baseaccount_test.go
- backend/backend.go
- backend/coins/btc/account.go
- backend/coins/btc/account_test.go
- backend/coins/eth/account.go
The reason that the signing configurations were loaded lazily was that
it requires querying the xpubs from the device. With the BitBox01,
this is especially slow, but also the BitBox02 shows a small delay
when loading e.g. 3 xpubs.
Since we want to persist the accounts/configs anyway (to support
multiple accounts and watch-only), we need to get them
immediately. Since they will be persisted, this will only happens once
per keystore.
> backend/accounts: load signing configurations immediately

- backend/backend.go
- backend/config/accounts.go
The accounts are always stored in the unified format (multiple signign
configurations per account) in the accounts.json database. When
loading them, we split them into individual accounts if needed.
This previously happened when adding the BTC accounts when a keystore
is registered, but this will not work anymore as we will persist all
accounts and not load them dynamically after a keystore is registered
anymore. Instead, we will persist the default accounts when a new
keystore is registered.
createAndAddBTCAccount() and createAndAddETHAccount() will be changed
to persist the default accounts instead of loading them dynamically.
> backend: move split/unified accounts logic

- backend/backend.go
- backend/config/accounts.go
Before, we would load them dynamically whenever a keystore is
connected.
Now, we only load accounts from the accounts.json database, and
pre-populate the database with a default set of accounts to kick
things off.
We take into account the global settings for which coins are active,
so that users who already disabled some accounts have a smooth
migration. The global settings to activate/deactivate coins and tokens
will be removed and replaced with functionality to add and remove
accounts per keystore.
> backend: persist default set of accounts for a new keystore 

- backend/arguments/arguments.go
- backend/backend.go
- backend/devices/bitbox/device.go
- backend/devices/bitbox/keystore.go
- backend/devices/bitbox02/device.go
- backend/devices/bitbox02/keystore.go
- backend/devices/bitbox02bootloader/device.go
- backend/devices/device/device.go
- backend/devices/usb/manager.go
- backend/keystore/keystore.go
- backend/keystore/keystores.go
- backend/keystore/software/software.go
- backend/keystore/software/software_test.go
It was a "hacky" 2-of-2 multisig if two bitboxes are connected, which
was used to play with multisig in the past. The multisig argument to
enable this mode has been long removed. The cosigner index concept was
also wrong, as the cosigner index is not a property of the keystore,
but a property of the signing configuration (and could be infered
there from the xpubs that are present).
> backend: remove multisig

- backend/accounts.go
- backend/handlers/handlers.go
- frontends/web/src/api/backend.ts
Also show the display name and if an account can be added for this
coin, so the frontend can choose to disable the coin already upfront.
> backend/handlers: add more info to /supported-coins

- backend/accounts.go
- backend/backend.go
- backend/handlers/handlers.go
- frontends/web/src/locales/en/app.json
We re-purpose the existing /account-add endpoint, whose old behavior
will be retired.
> backend/handlers: expose CreateAndPersistAccountConfig

- backend/accounts.go
- backend/backend.go
- backend/coins/btc/account.go
- backend/coins/btc/account_test.go
- backend/coins/btc/addresses/addresschain_test.go
- backend/coins/btc/addresses/test/test.go
- backend/coins/eth/account.go
- backend/config/accounts.go
- backend/signing/configuration.go
- backend/signing/configuration_test.go
It belongs with the xpub and keypath, as each one can have a different
rootFingerprint in theory (e.g. multisig accounts).
> backend: move root fingerprint into the signing config

- backend/backend.go
When exchange rates updater is reconfigured, the backend needs to
collect all coins + ERC20 tokens.
It just so happens that an account.Coin().Code() already returns ERC20
tokens, meaning the second loop for collecting the tokens was
absolutely redundant.
> backend: drop usage of DeprecatedCoinActive in exchange rates updater

- backend/handlers/handlers.go
- frontends/web/src/api/account.ts
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/account/send/send.tsx
Account name is not good, especially with user-named accounts. "Get My
Savings" does not make sense.
> frontend: fix send/receie titles to use the coin name

- backend/backend.go
- backend/coins/btc/account.go
- backend/coins/eth/account.go
- backend/signing/configuration.go
- backend/signing/configuration_test.go
Also no need to use the config hash anymore, as the account code is
now unique, as it includes the keystore fingerprint.
> backend: make sure account code is unique

- backend/coins/btc/account.go
FatalError is called when getting the account status and blocked until
the accoutn was synced. The account component is not rendered until
the status endpoint returns, which would be after syncing. This
prevents the account component from showing the address scan progress
indication.
> backend/btc: don't block in FatalError()

- CHANGELOG.md
- backend/backend.go
- backend/config/accounts.go
- backend/config/config.go
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/settings/manage-accounts.tsx
- frontends/web/src/routes/settings/settings.tsx
Before, we would dynamically explode a unified account into multiple
individual accounts (one per signing config) if the keystore didn't
support unified accounts. This does not work well with account
management, where one wants to list all accounts, edit their names,
etc.
We kept a toggle in the settings to force-explode accounts, so that
users who (ab)used multiple signing configurations as multiple
accounts could get the behavior back. It was meant to be temporary,
but the above forces us to speed up its removal.
After this commit, users will find their split accounts to be unified,
and they can split the funds manually again by sendint the funds to a
new account (by using coin control).
> backend: remove dynamic split accounts

- backend/accounts.go
- backend/accounts_test.go
- backend/signing/configuration.go
- backend/signing/configuration_test.go
In lieu of a user-chosen order, we fix the order and group accounts by
coin, ordered by account number.
Tokens are unchanged, are listed after the parent ETH account, in an
arbitrary order.
> backend: sort accounts by coin, account number

- backend/backend.go
- backend/handlers/handlers.go
- frontends/web/src/api/account.ts
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/settings/manage-accounts.css
- frontends/web/src/routes/settings/manage-accounts.tsx
- frontends/web/src/style/layout.css
- added small lines to visualize their close relation to the
parent ethereum account
- commented out but kept the toggle favor account feature
- linked the coin accounts to their account-overview, but
have not id for tokens to correctly link to
> frontend: enabling tokens now use toggles on manage accounts

- frontends/web/src/components/message/message.tsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/settings/manage-accounts.css
- frontends/web/src/routes/settings/manage-accounts.tsx
- frontends/web/test/components/message/message.test.tsx
Added edit button to all accounts that are real coins and can
be named, edit input and save form displayed with a dialog
as inline is a bit trickier and we dont want the current
solution from edit notes.
> frontend: add rename account dialog to manage accounts

- backend/coins/eth/account.go
With newly up to 5 accounts per ETH and token, and conservatively 5
requests per update round, updating every 30s is too quick and 1min
should be ok.
> backend/eth: increase update interval to 1min

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/buy/guide.tsx
There is multiple issues:
- in some translations the url is missing or translated
- Entry component does not fallback to english if the
translated url is missing
- url should probably not be in translations (mostly)
Changed guide buy entry about exchanges to pass link-text,
title and text and hardcode the exchanges url.
Removed in app.json so we don't forget to update it.
> frontend: do not use guide entry link url

- frontends/web/src/components/sidebar/sidebar.tsx
Reasons are default accounts should be enough for average
users, also once the accounts are created the button does
not always have to be visible.
Add account in manage accounts should be sufficient.
> frontend: hide add-account button in sidebar

- backend/accounts.go
- backend/backend.go
- backend/handlers/handlers.go
- frontends/web/src/api/backend.ts
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/add/add.tsx
- frontends/web/src/routes/settings/manage-accounts.tsx
To avoid confusion, we disallow adding an account with a name that
another account already has.
We check all accounts, even ones that are not currently visible - we
might show them in the future in watch-only mode.
> backend: error on duplicate account name

- backend/accounts.go
- backend/backend.go
- backend/handlers/handlers.go
- frontends/web/src/api/backend.ts
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/add/add.tsx
- frontends/web/src/routes/account/add/components/coin-dropdown.tsx
Add it as a placeholder, use it as a default name if none was entered.
The suggested name is the coin name followed by the next account number.
> frontend/add-account: automatically suggest name

- frontends/web/src/routes/account/add/add.tsx
There can be error, i.e. account name already in use, the error
currently stays if the user progresses to the next step or is
going back.
Changed to hide the error when progressing with continue or back.
> frontend: remove error when continuing

- frontends/web/src/routes/account/add/add.tsx
If the user went with the suggested placeholder name, the success
message did not show the name.
> frontend/account/add: show name on success

- backend/accounts.go
- backend/backend.go
- frontends/web/src/locales/en/app.json
Doning a global name check did not work as expected. Adding default
accounts with default names can fail if there are already accounts of
the same name (e.g. from a different seed).
> backend: undo duplicate account name check

- CHANGELOG.md
- backend/coins/eth/etherscan/etherscan.go
There was a bogus unmarshal error before. Now:
unexpected response: {"status":"0","message":"NOTOK","result":"Max rate limit reached"}
> backend/etherscan: improve error message related to rate limiter

- CHANGELOG.md
- backend/accounts/account.go
- backend/accounts/baseaccount.go
- backend/accounts/baseaccount_test.go
- backend/coins/btc/handlers/handlers.go
- backend/signing/legacyconfiguration.go
Transaction notes are stored in json files named using the account
identifier. In v4.28.0, account identifiers changed as part of the
multi-accounts feature. It used to contain the hash of the signing
configurations. As a result, transaction notes set before were not
shown anymore, as the wrong file was loaded.
This patch restores the legacy transaction notes by loading the legacy
transaction note files.
In v4.27.0, you could have a unified account and split them into
individual accounts (one per signing configuration). Transaction notes
were not shared between these accounts even them. In v4.28.0, we
removed the split-account setting, so we consider notes from split
accounts as well - otherwise they would be lost for good.
> backend/account/notes: restore transaction notes lost in migration

- backend/rates/gecko.go
- backend/rates/history.go
The fetchGeckoMarketRange limits a single response to 1Mb or 1048576
bytes. It turns out a dataset for 2 years is about 1064916 bytes, as
observed in the logs of our coingecko mirror.
I believe the limits were ok at first but our mirror is now serving
rates at 5min interval data points for any range. Compared to
hourly/daily rates, this is a lot more data which doesn't fit into the
1Mb response limit.
Instead of increasing the response limit, I think it's best to reduce
initial backfill range. It doubles the backfill QPS but makes response
size smaller - faster network roundtrip, less room for failed requests
when internet connection is bad.
> backend/rates: reduce max range during initial backfill to 1 year

- frontends/web/src/app.tsx
The routing happened when the device was plugged in when the app was
running. It was not routed when the app was launched after the device
was plugged in.
> frontend/app: route to device bugfix

- frontends/qt/server/server.go
This resolves a CGO-related compile time errors:
_cgo_export.c: In function 'serve':
_cgo_export.c:48:3: error: expected specifier-qualifier-list before 'pushNotificationsCallback'
pushNotificationsCallback p0;
^~~~~~~~~~~~~~~~~~~~~~~~~
The reason is, when a CGO-exported Go function has args matching
the type, even if it's a C type, like so:
//export serve
func serve(pushNotificationsCallback C.pushNotificationsCallback)
the C code generated by CGO becomes invalid due to the arg and its type
taking identical name. Here's a snippet example:
CGO_NO_SANITIZE_THREAD
void serve(pushNotificationsCallback pushNotificationsCallback, ...)
{
__SIZE_TYPE__ _cgo_ctxt = _cgo_wait_runtime_init_done();
typedef struct {
pushNotificationsCallback p0;
responseCallback p1;
notifyUserCallback p2;
char* p3;
} …
> frontends/qt: make the libserver build work on go1.16

- frontends/qt/resources/linux/usr/share/applications/bitbox.desktop
See
https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#mime-types
Installing the .deb package automatically registers the scheme based
on this entry in the .desktop file. Manual changes to the desktop file
require calling `sudo update-desktop-database`.
> aopp: register URI scheme on linux

- backend/backend.go
shiftcrypto.support should be allowed so we can slowly move to
the new knowledge base, this will replace guides.shiftcrypto.ch.
Keeping guides as there are still some older links pointing to
it.
> backend: allow links to shiftcrypto.support and shiftcrypto.shop

- frontends/web/src/components/devices/bitbox02bootloader/bitbox02bootloader.tsx
- frontends/web/src/locales/en/app.json
When no firmware is installed, a "upgrade" messages may be confusing.
This commit makes the app display "install" in such cases.
This comes together with a bootloader change in which the same
messaging occurs now: installation vs upgrade.
@thisconnect, not sure if this is the right approach. You tell me.
FYI the bootloader changes are here:
https://github.com/digitalbitbox/bitbox02-firmware/pull/759
> frontends/web: more user-friendly messages for first firmware install

- backend/accounts.go
- backend/accounts/address.go
- backend/aopp.go
- backend/aopp_test.go
- backend/backend.go
- backend/coins/btc/addresses/address.go
- backend/coins/btc/headers/headers.go
- backend/coins/eth/account.go
- backend/coins/eth/address.go
- backend/errors.go
- backend/handlers/handlers.go
- frontends/web/src/api/aopp.ts
- frontends/web/src/api/backend.ts
- frontends/web/src/app.tsx
- frontends/web/src/components/aopp/aopp.tsx
- frontends/web/src/locales/en/app.json
More unit tests to follow. This is a start, but I tried to be as complete as possible. If the concept makes sense, ideally we merge this and iterate with improving the workflow, UI and edge cases.
One can test by going to https://testing.aopp.group/ and clicking the link after installing the app (on macOS: dragging the app to the Applications folder).
You can also copy the link and launch the app on the command line with the aopp URI as the argument, e.g.:
./BitBox 'aopp:?v=0&msg=I+confirm+that+this+Bitcoin+%28BTC%29+address+is+controlled+by+David+Lopez%2C+Poststrasse+22%2C+Zug%2C+Switzerland.+Unique+Identifier%3A+b83762dfbd8696a&asset=btc&format=any&callback=https%3A%2F%2Ftesting.21analytics.ch%2Fproofs%2F3730c437-4c4a-4364-8e7c-1b5a84b039f2'
@thisconnect to iteratively develop with …
> backend,frontend: implement AOPP workflow

- backend/aopp.go
- backend/devices/bitbox/keystore.go
- backend/devices/bitbox02/keystore.go
- backend/keystore/keystore.go
- backend/keystore/mocks/keystore.go
- backend/keystore/software/software.go
Can test with https://testing.aopp.group/?asset=eth, but only after the site is updated a little later today - ~currently it has a bug in ETH signature verification that will be fixed.~ currently we don't know if the recoverable id in Ethereum Signed messages should be offset by 27 or not (MEW [accepts both](https://github.com/MyEtherWallet/MyEtherWallet/blob/052f697f3b269db4378f331dbb89d24b406bb7c7/src/components/VerifyMessageInput/VerifyMessageInput.vue#L118)) the AOPP demo site expects it currently)
> backend/aopp: support ETH requests

- backend/devices/bitbox02/handlers/handlers.go
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/bitbox02/gotostartupsettings.tsx
- frontends/web/src/routes/device/bitbox02/settings.tsx
So users can toggle the startup firmware hash display.
The acutal bootloader page in the app needs to be improved to not show
the firmware upgrade if it is already up to date. This follows in
another commit.
> frontend/bitbox02: add button to go to startup settings

- frontends/web/src/components/aopp/aopp.tsx
Was a leftover from a previous version before putting the state into
the SubscribedProps.
> frontend/aopp: remove unused/wrong state

- backend/aopp.go
- backend/aopp_test.go
- backend/handlers/handlers.go
- frontends/web/src/api/aopp.ts
- frontends/web/src/components/aopp/aopp.tsx
If an AOPP link is clicked while no BitBox is connected, we do as
before and ask the user to insert and unlock.
However, if the BitBox is already inserted and unlocked, we don't want
a link click to immediately go to the account-chooser, but have an
intro dialog first asking the user if they want to proceed.
Builds on https://github.com/digitalbitbox/bitbox-wallet-app/pull/1365
> backend/aopp: add user-approval state 

- backend/devices/bitbox02bootloader/device.go
- backend/devices/bitbox02bootloader/handlers/handlers.go
- frontends/web/src/components/devices/bitbox02bootloader/bitbox02bootloader.tsx
- frontends/web/src/locales/en/app.json
If 'Go to startup settings' is clicked but there is no firmware upgrade to be done, the button to upgrade should not be shown.
> frontend/bitbox02/bootloader: don't show upgrade if there is no upgrade

- frontends/web/src/components/progressRing/progressRing.tsx
Some longer tx statusText translations pushed the progress
ring icon, so that it was rendered smaller than the specified width.
This only happens in a app size that sows the tx overview as table.
Added an inline style to set a min-width and prevent longer
texts shrinking the icon. Longer statusText will overlap slightly
on the right side.
> frontend: fix tx progress icon

- backend/aopp.go
- backend/aopp_test.go
We changed our minds and will always ask the user if they want to
continue. Before, we only asked if there was already an unlocked
BitBox02.
> backend/aopp: always start with aoppStateUserApproval

- frontends/web/src/components/forms/button.css
Before the secondary buttons were orange, this was used a long
time ago, but apparently still in use for example on the connect
your own node section as back button.
We never want orange buttons. Changed to white button with light
outline border.
> frontend: revamp secondary button style

- frontends/web/src/components/forms/field.tsx
- frontends/web/src/components/forms/index.tsx
- frontends/web/src/components/forms/label.css
- frontends/web/src/components/forms/label.tsx
- frontends/web/src/components/forms/radio.css
- frontends/web/src/components/forms/radio.tsx
- frontends/web/src/routes/device/bitbox01/backups.tsx
- frontends/web/src/routes/device/components/backup.tsx
- start using JSX.IntrinsicElements with 'div' or 'input' etc.
so that rest props are type checked
- removed textMedium radio prop, this was always used, so it is
now the default style
- fixed TypeScript recommendations in Backup component, the only
component that actually uses the radio component (sometimes)
> frontend: rewrite more form components to typescript

- CHANGELOG.md
- frontends/android/BitBoxApp/app/src/main/res/layout/activity_main.xml
This is a long requested feature to prevent the screen from turning off
which otherwise may happen often, for exapmle while inputting a
passphrase or confirming a transaction on the device.
The change uses no new app permissions such as WAKE_LOCK. It simply
tells the OS to keep the screen on as long as the app is visible in
the foreground. As soon as the app is gone off the screen, any
configured screen timeouts at the OS level resume normal operations.
The screen still locks normally using an regular action like pushing a
physical lock button on the phone.
See docs for more details:
https://developer.android.com/training/scheduling/wakelock#screen
> android: prevent screen from turning off while in foreground

- frontends/web/src/components/aopp/aopp.tsx
It does nothing. The user has to cancel on the device.
> frontend/aopp: remove cancel button during signing

- frontends/web/src/components/aopp/aopp.tsx
- frontends/web/src/components/forms/select.css
- frontends/web/src/components/fullscreen/fullscreen.css
- frontends/web/src/components/fullscreen/fullscreen.tsx
- always left align select dropdown labels
- rearrange forms that they do not interfere with fullscreen
components so that flexbox properly works
- position fullscreen buttons at the bottom of the screen
on smaller screens
- ensure bottons are pushed down by large content and that
scroll works properly
> Frontend aopp small screen styling

- frontends/web/src/components/aopp/aopp.css
- frontends/web/src/components/aopp/aopp.tsx
- frontends/web/src/components/fullscreen/fullscreen.css
- frontends/web/src/components/fullscreen/fullscreen.tsx
- show address and message on signing step
- fullscreen component: removed width prop and made it resposive
using a bigger content area on large screen
- display domain name in bold on the first step
- adjust device image and display it slightly smaller so it matches
the size of the real world device
- increase font sizes of labels, input fields, textareas, buttons
and select dropdowns in aopp fullscreen component
> frontend/aopp: ui update and stlying improvements for large screen

- backend/accounts.go
- backend/accounts/account.go
- backend/accounts/errors/errors.go
- backend/coins/btc/coin.go
- backend/coins/btc/feetarget_test.go
- backend/coins/eth/account.go
- backend/coins/eth/coin.go
- backend/coins/eth/coin_test.go
- backend/coins/eth/feetarget.go
- backend/coins/eth/feetarget_test.go
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/send/send.tsx
https://ethgasstation.info/ provides gas price estimates for different
priorities.
We use these to give the user fee options.
If the service is not available, we fall back to the previous gas
price estimation provided by the eth_gasPrice RPC call to the ETH
node (currently etherscan proxy).
FeeTargets() is currently doing all the work whenever it is called,
which should be once when the send screen is loaded and every time a
tx proposal is made (every time the user changes something in the send
screen). This could be optimized with a cache that is invalidated
regularly (or when a new block arrives).
Custom gas price option to be added later.
> backend/coins/eth: add fee targets based on EthGasStation

- frontends/qt/main.cpp
Commit a82a85020f164a705495bf21e689d93c7476e4cc forced Qt render in software mode, referring to some attack surface reduction. I could not find any existing vulnerabilities or advisory notes as to why and how exactly this helps in practical terms here.
OTOH, letting Qt use hardware acceleration, where available, improves user experience on Windows by far.
Until there's a reasonable and practical explanation why exactly software rendering yields more pro than cons in this context, I propose to switch back to Qt default backend rendering.
See Qt docs about backend renderers:
https://doc.qt.io/qt-5/qtquick-visualcanvas-adaptations.html
/cc @jadzeidan @thisconnect
> qt: let it use default rendering backend

- frontends/web/src/components/aopp/aopp.css
- frontends/web/src/components/aopp/aopp.tsx
Removed info text below the verify button on the AOPP success
screen, as we don't need it.
> frontend/aopp: remove reverify info text

- backend/accounts.go
In c6b816aa35bfdf855662df12e3b9cb43d31a1b96, the account.Close() was
accidentally dropped. When reinitializing the accounts (e.g. after an
account rename), the old ones were not closed, blocking the database
files, so the new ones could not properly load.
> backend: fix regression - close account

- frontends/web/src/routes/settings/manage-accounts.tsx
When clicking a deactivated account (Bitcoin, Litecoin, Ethereum)
the content area turns gray.
Added a check to test if the account is active before routing.
Tokens already had this check.
> frontend: fix deactivated account links to empty screen

- frontends/web/src/components/copy/Copy.css
- frontends/web/src/components/copy/Copy.tsx
- frontends/web/src/components/dialog/dialog.css
- frontends/web/src/components/transactions/transaction.css
- frontends/web/src/components/transactions/transaction.tsx
- increased width of tx detail dialog
- added options to style the copyinput component without border
and with right aligned text
> frontend: support copying tx address from tx details

- backend/accounts.go
- backend/accounts_test.go
When adding an account, the account config is created by getting the
xpubs. If this fails for one of the xpubs, no account should be added,
because:
- either the account is not "complete" (has a missing signing config
which it should have)
- or if all of them fail, the resulting account will have a
configurations entry that is `nil`, which means the account does not
load at all.
This was discovered by a user that had a `null` entry in the
configurations in accounts.json, and when they tried to add another
account, it would fail with the error that the account already
existed (based on the same account code).
> backend/accounts: abort on error instead of continue

- backend/devices/bitbox02/handlers/handlers.go
Some errors were not logged nor displayed in the app, making debugging
issues harder. The errors here could unexpected BitBox02 communication errors.
> backend/bitbox02: log communication errors

- frontends/qt/compile_windows.bat
A user reported that installation failed with errors that
msvcp140_1.dll and vcruntime140_1.dll was misisng.
We bundle all DLLs that exist with the msvcp140 and vcruntime140
prefix to solve this problem.
> frontend/qt: bundle more DLLs in Windows installer

- backend/config/config.go
- frontends/web/src/components/rates/rates.tsx
Currently the fiat currency default is Swiss Franc (CHF), but many
people don't know CHF or this default is not very useful for most.
Changed default to US Dollar (USD) as it is the most widely used
pair with Bitcoin and ohter crypto currencies. Kept Euro and CHF
as enabled secondary fiat currencies.
> config: change default fiat currency to usd

- backend/coins/eth/account.go
newTx() accesses account.balance to check if there are sufficient
funds, but that only works if the account is already synchronized.
The eth account unit test failed randomly due to this, as somtimes,
the tx proposal was made before the accoutn synced.
There is a separate issue to be addressed in a separate PR: the
account vars such as `balance` are written and read without a lock
from different goroutines.
> eth: sync account when making a tx proposal

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/account/send/send.tsx
There was some confusion that people are unsure if the BitBox has
to stay plugged in when receiving or sending.
Added guide entry that it is save to plugout the device after send
or creating a receive address.
> frontend/guide: add entry that plugout is ok after send and receive

- CHANGELOG.md
- frontends/qt/main.cpp
We attempted to use GPU accelerated rendering in a9823e9a3.
Some users had rendering artefacts on Windows, and at least one user
could not launch the app on Ubuntu 18.04 with:
```
ERROR:command_buffer_proxy_lmpl.cc Context Result::KTranslentFailure:Failed to send GpuChannelMsg_
CreateCommandBuffer.
Segmentation fault (core dumped)
```
To fix these issues, we revert the change and re-enable software rendering.
GPU acceleration was enabled to deal with a very laggy animation when
opening dialogs on Windows. We will deal with this by disabling such
animations in another commit.
> qt: go back to software rendering

- frontends/web/src/locales/en/app.json
Seems send.customFee.label is not used anywhere, also checked
all occurences of '.placeholder' and '.label'.
> frontend: remove unused translations

- CHANGELOG.md
- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/GoViewModel.java
- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/Util.java
There are these scenarios to cover:
- App is closed, user inserts device:
In this case, the user is prompted with all apps that register intent
filters for the device, including the BitBoxApp.
a) If the BitBoxApp is chosen, the app is launched with the
`ACTION_USB_DEVICE_ATTACHED` intent. Previously we would simply update
the device list in `onResume()` without checking the intent, which
included this case. Now we explicitly check the intent in
`onResume()` to avoid endlessly asking the user for permission (see below).
b) If the app is not chosen, permission is denied. If the user then
opens the app (without USB permission granted automatically like
above), previously the app would crash because of it. In this commit,
we request permission in `onCreate()` (by calling
`updateDevice()`). We …
> android: request USB permission if not automatically granted

- CHANGELOG.md
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/send/feetargets.tsx
- frontends/web/src/routes/account/send/send.tsx
Currently when selecting a custom fee, the label on top of the input
just says 'Network fee', but we use this label also for the total
amount of the estimated fee price below the selection.
Changed the custom fee label to display either 'Fee rate' or
'Gas price' depending on the coinCode of the selected account.
> frontend: use feerate or gas price for custom fee label

- backend/devices/bitbox02/handlers/handlers.go
- frontends/web/src/api/bitbox02.ts
- frontends/web/src/api/response.ts
- frontends/web/src/routes/device/bitbox02/mnemonicpassphrase.tsx
- frontends/web/src/routes/device/bitbox02/settings.tsx
- added api/response with success and fail union type
- added api/bitbox02 specifc for BitBox02
(is similar to api/devices)
- added getDeviceInfo and setMnemonicPassphraseEnabled
- changed device info response to always include the success field
- refactored mnemonicpassphrase component, so it doesn't need
to use callback function and works on its own
> frontend: start bitbox02 specific device api

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/bitbox02/mnemonicpassphrase.tsx
- cherry-picked https://github.com/digitalbitbox/bitbox-wallet-app/pull/1458/commits/af49d2b0b489bb71088382a5d64c8b5aeb1dd7ed
- add missing translations 
On the passphrase summary view:
Summary should mention that the coins cannot be accessed if the
passphrase is forgotten.
On enabled success view:
Success view now contains 2 tips to try and test with a small
amount and how to unlock the default wallet (by leaving the
passphrase empty).
> Frontend passphrase text

- frontends/web/src/components/aopp/aopp.tsx
Moving from fullscreen to view component in 4383f68 has
introduced a regression for AOPP workflow. Reason is that before
the fullscreen component was always centered, and now the view
component is by default left aligned.
Changed to add center prop to AOPP view.
> frontend: fix centered view regression

- frontends/web/src/routes/device/bitbox02/mnemonicpassphrase.tsx
The tips should only be shown on the succes enabled view, but
not on the success disabled view.
This has been fixed in 95d6f2dd0b43040ac72a8ee6d38332699fb3b301
but was forgotten to backport this to master.
> frontend: show tips on success enable only

- frontends/android/BitBoxApp/app/build.gradle
- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
Google Play now enforces a minimum level of 30.
The `setAllowFileAccess` change is because it defaulted to true before
and is defaulting to false now.
See also: https://developer.android.com/reference/android/webkit/WebSettings#setAllowFileAccess(boolean)
> android: target api level 30, enforced by Google Play

- frontends/web/src/app.tsx
- frontends/web/src/components/aopp/aopp.css
- frontends/web/src/components/aopp/aopp.tsx
- frontends/web/src/components/forms/checkbox.css
- frontends/web/src/components/forms/checkbox.tsx
- frontends/web/src/components/icon/combined.css
- frontends/web/src/components/icon/combined.tsx
- frontends/web/src/components/icon/index.jsx
- frontends/web/src/components/icon/index.tsx
- frontends/web/src/components/layout/main.css
- frontends/web/src/components/layout/main.tsx
- frontends/web/src/components/message/message.css
- frontends/web/src/components/status/status.css
- frontends/web/src/components/view/view.css
- frontends/web/src/components/view/view.tsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
- frontends/web/src/routes/device/bitbox02/passphrase.tsx
Continuation from https://github.com/digitalbitbox/bitbox-wallet-app/pull/1475#issuecomment-974635933
When enabling or disabling the passphrase setting users should
fully focus on the information shown and not be distracted by other
elements on the page, therefore the view in fullscreen is more
suitable than just a dialog.
Changed:
Introduced a new <Main> component for contents of the page, this
component should replace <div class="container">. Also left example
code of how <Header> and <Guide> components can be used.
- changed back button to go 1 step back in the passphrase infos
instead of going back to the settings view
- turned caret pointing to bb02 device into a shared component, so
it can be re-used in different places like AOPP.
- changed View component's default, fullscreen and …
> Frontend passphrase fullscreen styling

- frontends/web/src/components/password.jsx
- frontends/web/src/routes/device/bitbox01/bitbox01.jsx
- frontends/web/src/routes/device/bitbox01/check.jsx
- frontends/web/src/routes/device/bitbox01/components/upgradefirmware.jsx
- frontends/web/src/routes/device/bitbox01/create.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/blink.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/changepin.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/device-lock.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/hiddenwallet.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/legacyhiddenwallet.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/randomnumber.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/reset.jsx
- frontends/web/src/routes/device/bitbox01/settings/settings.jsx
- frontends/web/src/routes/device/bitbox01/setup/goal.jsx
- frontends/web/src/routes/device/bitbox01/setup/seed-create-new.jsx
- frontends/web/src/routes/device/bitbox01/setup/seed-restore.jsx
- frontends/web/src/routes/device/bitbox01/setup/success.jsx
- frontends/web/src/routes/device/bitbox01/unlock.jsx
- frontends/web/src/routes/device/bitbox01/upgrade/bootloader.jsx
- frontends/web/src/routes/device/bitbox01/upgrade/require_upgrade.jsx
- frontends/web/src/routes/device/bitbox02/setdevicename.jsx
- frontends/web/src/routes/device/manage-backups/manage-backups.jsx
- frontends/web/src/routes/settings/electrum.jsx
Decorators are intentionally not supported in RCA and is recommended to not use them, see [https://create-react-app.dev/docs/can-i-use-decorators/](https://create-react-app.dev/docs/can-i-use-decorators/)
closes #1490
> frontend: migrate decorators sugar-syntax to HOC

- appveyor.yml
Unfortunately the ci fails on windows when just using the latest
node version. Pinned to current LTS version.
> ci: pin nodejs to version 16 on windows (appveyor)

- frontends/web/src/api/subscribe.ts
- frontends/web/src/app.tsx
- frontends/web/src/components/alert/Alert.tsx
- frontends/web/src/components/anchor/anchor.tsx
Unfortunatelly TypeScript complains about files that are not
referenced, i.e. aopp.tsx
Took some changes from https://github.com/thisconnect/bitbox-wallet-app/pull/12
But it looks now as the next step is to just go through
all errors from TypeScript, when doing 'make buildweb' or
'make webdev'
> temporary changes to make typescript happier

- frontends/web/src/decorators/load.tsx
- frontends/web/src/routes/buy/moonpay.tsx
- frontends/web/src/routes/device/bitbox02/settings.tsx
why: on preact class components initialize with `{}`
but react initializes with `null`, so we must assing
the state to `{}` on the construction.
> frontend: initialize class components state with `{}`

- frontends/web/package-lock.json
- frontends/web/package.json
Save exact production dependencies as described in:
- https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/README.md#npm-dependencies
Dev dependencies are fine to use semver range, keeping as is.
> frontend: lock npm dependencies

- frontends/web/src/components/forms/button.jsx
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/send/send.tsx
Some parts of the code used `condition && something || else`, the
default create-react-app eslint rules have no-mixed-operators,
which improves readability of the code.
Added parentheses to group and make the code more logical to read.
> frontend: remove ignore eslint no-mixed-operators

- CHANGELOG.md
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/info/buyCTA.module.css
- frontends/web/src/routes/account/info/buyCTA.tsx
- frontends/web/src/routes/account/summary/accountssummary.tsx
Adds a buy CTA action for available to buy coins if the amount is 0
Closes #1473
> Add Buy CTA on Account Info #1473

- frontends/web/src/components/aopp/verifyaddress.tsx
- frontends/web/src/routes/device/bitbox02/upgradebutton.tsx
One difference to Preact 8 is that in React the state is null if
it was not properly initialized. This could lead to error:
Cannot descructure property ... of 'this.state' as it is null.
Checked all components that use setState and added missing state
initialization.
> frontend: add missing state initialization

- frontends/web/src/components/wait-dialog/wait-dialog.tsx
The wait-dialog component has an interesting logic that checks if
there are no children in which case it displays a graphic that
shows how to confirm on a BitBox01.
The component should also allow just strings as children and then
display that without the BitBox01 graphic. Changed to just check
for children and removed the is valid react component filter.
Tested:
- that graphic shows on BB01 facroty reset
- that graphic doesn't show on go to startup settings or factory reset
> frontend: wait-dialog should allow any children

- frontends/web/src/components/forms/select.tsx
- frontends/web/src/routes/account/send/feetargets.tsx
Unnescesary and duplicated prop, removed in favour of `defaultValue`
> Frontend: remove `selectedOption` from `Select`

- frontends/web/src/components/password.jsx
- frontends/web/src/components/qrcode/qrcode.tsx
- frontends/web/src/components/spinner/Spinner.tsx
- frontends/web/src/components/wait-dialog/wait-dialog.tsx
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/info/info.tsx
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/account/send/feetargets.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
- frontends/web/src/routes/device/bitbox02/components/steps/step.tsx
- frontends/web/src/routes/device/bitbox02/components/steps/steps.tsx
- frontends/web/src/routes/device/manage-backups/manage-backups.jsx
- frontends/web/src/routes/device/waiting.tsx
Due to the react migration, some Class Components methods
are beingg deprecated around 18.x, see
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html
This commit will ignore warnings, but components need
to be migrated if an react 18.x update is done
> Frontend: update unsafe class methods

- frontends/web/src/components/settingsButton/settingsButton.tsx
- frontends/web/src/routes/device/bitbox01/settings/settings.jsx
- frontends/web/src/routes/settings/settings.tsx
In the Qt app we shouldn't use normal anchors with href attributes
to link to different views. Reason this works in webdev, is that
react-scripts always serves the index.html with main JavaScript,
so after navigation and a full page reload occured the script can
pick up and continue. In the Qt app the index.html isn't served
and therefore something like a 404 happens.
Fixed by changing all remaining href on settings buttons to onClick
using the deprecated route method.
Refactored the settings component to a function components.
> frontend: fix settingsbutton linking

- frontends/web/src/routes/device/bitbox02/sdcardcheck.tsx
Currently the sdcardcheck component quickly flickers a dialog,
before the response of the check endpoint resolved.
Changed to not render at all until there is a response, once there
is a response if it is false, the dialog should show asking to
insert an sdcard and if true it should render its children
(the backup list fetched from the sdcard).
> frontend: sdcardcheck component should not render before check

- frontends/web/src/routes/account/account.tsx
A href links do not work in Qt app as a normal navigtion doesn't
find the index.html and will result in a 404.
This is different from webdev where every path returns the
index.html so that JavaScript can pick up and render.
cc @BrianCraig
> frontend: use link instead of anchor

- frontends/web/src/app.tsx
- reverted commit b239b0f
- added setStateWithDeviceList
- check if new device has accounts, then do maybeRoute instead of route to device settings
closes https://github.com/digitalbitbox/bitbox-wallet-app/issues/1546
Tested:
(just a screenshot of my doc)
> Frontend route unlocked

- frontends/web/src/routes/device/bitbox01/setup/security-information.tsx
On bb01 there is a bug where `SecurityInformation` doesn't render it's children because `children` works different in `preact` than `react`. 
This is involved in the `bb01` seed creation.
This bug was introduced on the `react` migration.
> frontend: fix bb01 seed creation

- frontends/web/src/components/update/update.tsx
This hides the download button because Android users usually auto-update their app through a store.
This should be added again with a download button that opens up the store where the app has been downloaded. #1571
> Android: hide download button

- frontends/web/src/routes/account/send/send.tsx
add space between coin amount and coin unit, this was a regression added on the react migration.
before: 
after:
> frontend: fix send transaction confirmation amount and unit spacing

- frontends/web/src/routes/device/bitbox02/backups.tsx
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
- frontends/web/src/routes/device/components/backup.tsx
After selecting a backup to restore and proceeding, the selected
backup is not visible anymore. We now show the selected backup during
restoring, so that the user knows they selected the right backup.
> frontend/bitbox02: show backup info while restoring

- CHANGELOG.md
- backend/rates/gecko.go
- backend/rates/rates.go
- frontends/web/src/api/account.ts
- frontends/web/src/components/rates/rates.tsx
- frontends/web/src/routes/account/send/feetargets.test.tsx
Closes #1564.
@x1ddos The changes I‘ve done are a replica of https://github.com/digitalbitbox/bitbox-wallet-app/pull/1335. However, I get some errors when running `make servewallet`:
ERRO[0000] updateLast                                    error="bad response code 400 > github.com/digitalbitbox/bitbox-wallet-app/backend/rates.(*RateUpdater).updateLast.func1 > /Users/schjonhaug/go/src/github.com/digitalbitbox/bitbox-wallet-app/backend/rates/rates.go:247 > github.com/digitalbitbox/bitbox-wallet-app/util/ratelimit.(*LimitedCall).Call > /Users/schjonhaug/go/src/github.com/digitalbitbox/bitbox-wallet-app/util/ratelimit/ratelimit.go:111 > github.com/digitalbitbox/bitbox-wallet-app/backend/rates.(*RateUpdater).updateLast > /Users/schjonhaug/go/src/github.com/digitalbitbox/bitbox-wallet-app/backen …
> Add support for NOK

- frontends/qt/server/server.go
According to the cgo docs (https://pkg.go.dev/cmd/cgo):
```
// Go string to C string
// The C string is allocated in the C heap using malloc.
// It is the caller's responsibility to arrange for it to be
// freed, such as by calling C.free (be sure to include stdlib.h
// if C.free is needed).
func C.CString(string) *C.char
```
> qt/server: free C strings again

- scripts/docker_install.sh
- scripts/travis-ci.sh
The package-lock.json file is at version 2, which requires a higher
npm version than previously installed. It was built and committed
outside of Docker, hence the mismatch.
> Dockerfile: update npm in the docker image

- frontends/web/src/locales/bg/app.json
- frontends/web/src/locales/de/app.json
- frontends/web/src/locales/en/app.json
- frontends/web/src/locales/es/app.json
- frontends/web/src/locales/fr/app.json
- frontends/web/src/locales/hi/app.json
- frontends/web/src/locales/it/app.json
- frontends/web/src/locales/nl/app.json
- frontends/web/src/locales/pt/app.json
- frontends/web/src/locales/tr/app.json
i18next had a breaking change introduce new v4 json format:
- https://github.com/i18next/i18next/blob/master/CHANGELOG.md#2100
So key: 'item', key_pluar: 'items' does not work anymore, new
syntax is: key_one: 'item', key_other: 'items'.
Made locize pull, renamed key and will need to be updated
with locize-push.
Part of https://github.com/digitalbitbox/bitbox-wallet-app/pull/1550
> frontend: renamed plural to v4

- frontends/web/package-lock.json
- frontends/web/package.json
- frontends/web/src/i18n/i18n.js
- frontends/web/src/i18n/i18n.test.tsx
Updated i18n library, removing unnescesary
i18next-react config in `src/i18n/i18n.js` implementation
because we already are using `I18nextProvider`.
Re-added `i18n.test.tsx`, removing `i18n` mock for a
more integral test.
closes #1543
> frontend: update i18next & activated tests

- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/account/send/utxos.tsx
This fixes a `this.utxos.current.getWrappedInstance is not a function` error thrown on the `Send.tsx`
Send Component has a Ref to UTXOs Class Component, this reference was being unwrapped using getWrappedInstance, due 
to using a translate HOC, which is not needed because the reference is already being forwarded by the HOC.
This difference may be because of using `withTranslation` from `i18n-react` after the React migration, which doesn't require the call to `getWrappedInstance()`, that the old `translate` HOC had.
> frontend: fix utxos reference unwrapping

- frontends/web/src/components/forms/input.test.tsx
- frontends/web/src/components/forms/input.tsx
- frontends/web/src/routes/account/send/feetargets.tsx
- frontends/web/src/routes/account/send/send.tsx
In React, changing the value of a controlled form input from undefined
to a defined value makes it uncontrolled. A warning popped up in the
console and the send tranasction form broke: it could no be cleared
after sending a transaction (setState() did not affect the form
anymore), disabling send all didn't remove the input value again, etc.
This commit removes `undefined` in the use of controlled form elements.
> frontend: disallow undefined value in controlled form inputs

- frontends/web/package.json
The dropdowns in the Qt app had 2 arrows, this is a regression
introduced when we changed to the new build.
BitBoxApp is using Qt 5.15.2 that is actually using Chromium 83
- https://wiki.qt.io/QtWebEngine/ChromiumVersions
Changing browserlist to build for 83 fixes the styling as the
reset has to be prefixed with -webkit, see:
- https://caniuse.com/css-appearance
> frontend: fix select dropdown styling

- frontends/web/src/routes/account/send/send.tsx
Regression from preact to React: setState() is async, so accessing
this.state.note after setState() can give an older non-updated value.
Entering e.g. 'test' in the note, the final tx can have 'tes' as the
actual note.
> frontend/send: fix setting note proposal

- frontends/web/src/components/aopp/aopp.tsx
- frontends/web/src/routes/account/add/components/coin-dropdown.tsx
- frontends/web/src/routes/buy/info.tsx
React has a defaultValue property on select dropdowns to set the
default value, but this is intendet to be used with uncontrolled
components. To control a select element React uses value.
Using both defaultValue and value triggers a warning: Select
elements must be either controlled or uncontrolled (specify
either the value prop, or the defaultValue prop, but not both).
AOPP, buy/choose-account and manage-accounts/select-coin all had
a defaultValue and a value props. As far as I can see they could
be all uncontrolled as there is no other form field or other
data that could change the select.
Decided to go with controlled component using value and removing
defaultValue, because I stlightly prefer controlled, i.e. if we
ever add another field that may change the value in the future.
> frontend: control select component

- CHANGELOG.md
Release date is in the future, so for now we just mention the tagged date.
> CHANGELOG: finalize 4.31.0

- frontends/web/src/routes/settings/manage-accounts.tsx
The code was supposed to keep a list of favorite accounts in the
frontend config to control which accounts are shown in the sidebar.
This was disabled and the plan was to use it later for tokens,
but tokens now use their own api endpoint and do not need to
be configurable in frontend config.
The unused code fetched favorites from frontend config with a
fallback to empty object. In various places there are checks for
if favorites is truthy, but favorites is not used anywhere else.
Removed favorite from manage-account component.
> frontend: remove unused dead code favorites in manage account

- frontends/web/src/api/coins.ts
- frontends/web/src/api/subscribe.ts
- frontends/web/src/components/headerssync/headerssync.tsx
- frontends/web/src/hooks/api.ts
- frontends/web/src/hooks/utils.ts
- added an example of `useAsync` and `useSubscription`
- removed unnescesary hiding logic on `HeadersSync`, due to logic of being displayed already hides component on load.
Partially fixes #1536
@thisconnect What do you think about this?
> frontend: add useLoad and useSubscribe hooks

- CHANGELOG.md
- backend/accounts.go
- backend/accounts/baseaccount.go
- backend/accounts/baseaccount_test.go
- backend/accounts_test.go
- backend/backend.go
- backend/bridgecommon/bridgecommon.go
- backend/bridgecommon/bridgecommon_test.go
- backend/coins/btc/account_test.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/eth/account_test.go
- backend/handlers/handlers.go
- backend/handlers/handlers_test.go
- cmd/servewallet/main.go
- frontends/android/goserver/goserver.go
- frontends/qt/BitBox.pro
- frontends/qt/filedialog.cpp
- frontends/qt/filedialog.h
- frontends/qt/libserver.h
- frontends/qt/main.cpp
- frontends/qt/server/server.go
- frontends/qt/setup.nsi
- frontends/web/src/api/account.ts
- frontends/web/src/routes/account/account.tsx
The default export path to the Downloads folder can fail if e.g. the
directory does not exist. It is also better UX to let the user choose
where to store the file.
> qt: use a file picker dialog to choose where to export a CSV to

- CHANGELOG.md
- frontends/web/src/routes/settings/electrum.jsx
There was a regression that the configured nodes only showed
TLS, but not what the actual address/domain is.
The problem was that the default state of the servers was
initialized based on props in the constructor. Using setState in
the constructor worked in Preact, but fails in React without an
error or warning.
Changed to intialize the state late in componentDidMount callback
so it shows now correct server settings.
Fixes https://github.com/digitalbitbox/bitbox-wallet-app/issues/1603
> frontend: fix electrum ui initialization

- CHANGELOG.md
- backend/rates/gecko.go
- backend/rates/rates.go
- frontends/web/src/api/account.ts
- frontends/web/src/components/rates/rates.tsx
- frontends/web/src/routes/account/send/feetargets.test.tsx
Add support for Swedish Krona (SEK), this is in the list of
currencies supported by CoinGecko:
- https://api.coingecko.com/api/v3/simple/supported_vs_currencies
Closes https://github.com/digitalbitbox/bitbox-wallet-app/issues/1600
> rates: add support for swedish krona (sek)

- frontends/qt/main.cpp
This change decreases the minimum width of the BBApp window to 360px, which allows a user to see the mobile version of the UI on desktop if they wish.
> qt: decrease minimum width for qt on desktop

- frontends/qt/libserver.h
- frontends/qt/main.cpp
- frontends/qt/server/server.go
This ensures the app doesn't crash after invoking getSaveFilename
dialog, for example when exporting transactions to CSV file, due to
memory release method incompatible with the one used during allocation.
Windows has different memory management models [1]. Relevant to this
case are: the C++ new/malloc which invokes HeapAlloc [2] and g++ mingw
malloc from portable C runtime. While malloc called from the Qt
frontend's main.cpp uses the former, Go's C.free uses the latter.
In fact, win32 docs state:
> Because the different heap allocators provide distinctive
> functionality by using different mechanisms, you must free memory
> with the correct function.
Before the filepicker dialog, we've always malloc'ed memory with cgo
functions like C.CString and released with the compatible C.free.
The …
> qt: release non-posix malloc'ed memory with a compatible free

- backend/accounts.go
- backend/accounts/baseaccount.go
- backend/backend.go
- backend/coins/btc/handlers/handlers.go
- frontends/web/src/components/transactions/transactions.tsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/account.tsx
SystemOpen() has a whitelist, but the whitelist does not cover
exported CSV files - only the Downloads folder, but the user can save
it somewhere else.
Instead of adding CSV export paths dynamically to the whitelist, it is
simpler to automatically open the CSV. This also avoids the clumsy
hack of converting the button from 'export' to 'open'.
> backend: open CSV automatically after export

- backend/coins/btc/addresses/address.go
- backend/coins/btc/addresses/address_test.go
- backend/signing/scripttype.go
Generate Taproot receive addresses according to BIP-86:
https://github.com/bitcoin/bips/blob/a3a397c82384220fc871852c809f73898a4d547c/bip-0086.mediawiki
> backend/btc: add P2TR script type and address generation

- frontends/web/src/components/dialog/dialog.tsx
Closing a confirm dialog with esc errors with:
> Cannot read properties of null (reading 'classList')
Seems that this is a regression from the Preact->React migration,
it looks like the setState callback is exectued earlier than in
Preact.
Moving updating the classList before setState fixes the error.
Test:
1) connect to own node
2) remove server
3) type esc
> frontend: fix close dialog with esc js error

- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
Regression from Reacht migration, the app currently shows a white
screen when password do not match. Reason setState callback fires
earlier it is unclear which setState sets createWalletStatus.
Test:
- factory reset
- create new wallet, enter name
- enter 2 different passwords
- expect password do not match error
Found in https://github.com/digitalbitbox/bitbox-wallet-app/pull/1601
> frontend: fix white screen if passwords do not match during setup

- backend/coins/btc/addresses/address.go
- backend/devices/bitbox/keystore.go
- backend/devices/bitbox02/keystore.go
- backend/devices/bitbox02/protobuf.go
- backend/keystore/software/software.go
This PR updates the bitbox02 keystore to enable taproot receive&sign. This PR does not add or enable any taproot accounts yet.
> Taproot receive/sign

- CHANGELOG.md
- backend/handlers/handlers.go
- frontends/web/src/api/account.ts
- frontends/web/src/components/rates/rates.module.css
- frontends/web/src/components/transactions/transaction.module.css
- frontends/web/src/components/transactions/transactions.module.css
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/summary/accountssummary.module.css
- frontends/web/src/routes/account/summary/accountssummary.tsx
- add subtotal row if there is more that one account of the same coin
- fix styling and labels
- as this also changes table headers of the account summary there is also changes to table headers of account overview
Everything can be squashed into 1 commit IMO.
TODO:
- review backend implementation
> Portfolio: support showing subtotals on account summary (portfolio)

- CHANGELOG.md
- frontends/web/src/components/copy/Copy.module.css
- frontends/web/src/components/transactions/transaction.tsx
And separate the link to the external block explorer. Users can then
more easily copy the txID without accidentally opening the explorer.
We add 5px of padding between the input and the copy button, otherwise
the input selection would overlap the button if there is a line break.
> frontend/transaction: make transaction ID copyable

- backend/accounts.go
- backend/accounts_test.go
- backend/backend.go
If the keystore supports it (e.g. after upgrading BitBox02 to
v9.10.0), the persisted accounts are updated with the taproot
subaccount, to make taproot addresses available also for existing
accounts.
The order of the script configs in the account config at the moment
matters only in that the first entry is used as the default address
type for Moonpay, AOPP and as the default change address. Future PRs
will remove this implicit assumption so that the order does not matter.
> backend/accounts: update existing accounts with taproot subaccount

- frontends/web/src/components/forms/radio.tsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/receive/receive.tsx
Toggling/cycling through 3 receive address script types is
confusing now that Taproot is supported, as it is unclear which
script type is currently selected and what the choices are.
Moving to a list of input radios gives a better overview. Using
radio inputs was anyway planed in an upcoming receive revamp.
Adding a addressDialog property to the receive view, that is
either false (do not show the dialog) or is a temporary object
containing the new addressType if the dialog is confirmed.
> frontend: use dialog to select receive address script type

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/receive/receive.tsx
Taproot is still new and not supported by all wallets, i.e. funds
might not show up in 3rd party watch-only wallets or not all
exchanges support it yet.
Adding a warning if taproot is selected.
> frontend: add warning if taproot is selected as receive address

- CHANGELOG.md
- backend/coins/btc/addresses/addresschain.go
- backend/coins/btc/addresses/addresschain_test.go
- backend/coins/btc/db/transactionsdb/transactionsdb.go
- backend/coins/btc/db/transactionsdb/transactionsdb_test.go
- backend/coins/btc/transactions/db.go
- backend/coins/btc/transactions/transactions.go
With lots of transactions in an account, loading them via the /transactions endpoint was very slow. The two main reasons (in order) were:
- many re-computations of the transaction hash (once for every input in each tx, plus a few times more per tx)
- slow lookup of addresses in the address chain to determine if an output is a change output
Fixing both reduces the time for calling the endpoint from ~20s to ~0s with around 700 transactions in the db.
> Improve speed of calling /transactions

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
Before the popup when restoring from mnemonic words repeated
itself:
- Title: Please follow the instructions on your BitBox02
- Text: Please follow the i… to restore from recovery words
Reason: the title used a generic follow-instrucitons
translation which is used in many places. Fixed by adding
a custom followInstructionsMnemonicTitle translation.
> frontend: reword restore-from-mnemonic instruction

- CHANGELOG.md
- frontends/qt/main.cpp
We switched to forced software rendering in
daaf2319afb3f5813a4bddd67e13b300590414e5 due to some users suffering
rendering artefacts and crashes with the default rendering backend.
The downside is that the app can be very slow on some machines,
especially when maximized with high resolution.
This env variable is a workaround to enable users to improve their
experience and try the default rendering, which is normally hardware
accelerated.
Closes https://github.com/digitalbitbox/bitbox-wallet-app/issues/1662
> qt: add BITBOXAPP_RENDER environment var to configure rendering

- frontends/web/src/routes/account/send/send.tsx
If the app does not have permissions to use the camera the library
returns 'Could not start video source' error.
This change shows the library error to the user in cases something
went wrong, but also if the scaning is aborted and no code has
been detected in that case the library returns 'Video stream has
ended before any code could be detected'.
> frontend: show errors from qr scanner

- frontends/web/src/components/guide/guide.tsx
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/device/waiting.tsx
- frontends/web/src/routes/settings/electrum.jsx
- frontends/web/src/routes/settings/settings.tsx
There is no need to maintain links to the support section and other
resources in the translation. The original idea was to use different
links for each language but it turns out that this was never used.
Moving all remaining links from translation file to the frontend.
tested:
- Waitscreen order and backup center
- Accountsummary coingecko link
- Connect to own node (en and de)
- Guide appendix
- BitBox01 guide in non-unified bech32 accounts
> Frontend remove links from locize

- CHANGELOG.md
- frontends/web/src/routes/account/send/send.tsx
It implements a subset of
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-681.md, not
looking at any parameters.
Same as in BTC/LTC, the QR code scanner result parser is forgiving and
accepts anything. The send form validation will catch it if the parsed
result is not a valid recipient address.
> frontend/send: enable QR code scanner for ETH-based accounts

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/send/send.tsx
Added guide entry to explain when the change output is a Taproot,
only shown in the guide of bitcoin accounts.
The rest was updated in locize and will need a locize-pull
> frontend: add guide entry about change output

- frontends/web/src/routes/account/receive/receive.tsx
This is a regression, the address index was set to the first
address when changing address type, introduced in:
- https://github.com/digitalbitbox/bitbox-wallet-app/commit/6622cfa8680d12ecd778075b61b8bb7f9650b9cb
Alternatively this is also fixed in https://github.com/digitalbitbox/bitbox-wallet-app/pull/1668
> frontend: change address type should change to first address

- frontends/web/src/api/account.ts
- frontends/web/src/api/devices.ts
- frontends/web/src/routes/account/receive/components/bb01paired.tsx
- frontends/web/src/routes/account/receive/components/verfiybutton.tsx
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/router.tsx
- removed HOC decorators and typed has-secure-output api
- changed receive-address api to work with useLoad
- moved PairedWarning to sub component to load it conditionally
- before: if warning.secureOutput was shown it removed the keydown
that is used to esc the receive view, and added again after the
alert callback. This is not necessary as handleKeyDown only
escapes if verifying is false.
> frontend: rewrite receive to functional component

- frontends/web/src/components/alert/Alert.tsx
- frontends/web/src/components/view/view.module.css
The alertUser component recently changed to use view component
internally, this didn't handle long text well, long text was
displayed overflowing the width of the dialog.
Changed styling of the view header and content to break-words
which fixes this issue.
Also changed, that multiline messages do not use div elements
as that is not allowed as child of H1 elements, which is what
ViewHeader uses.
Tested:
- long invalid addresses in electrum settings
- normal stupid simple message signing
- enable passphrase
> frontend: fix alert user ui text overflow

- frontends/android/BitBoxApp/app/src/main/java/ch/shiftcrypto/bitboxapp/MainActivity.java
The trailing slash is needed for the url replacement in
`shouldInterceptRequest()` to work properly.
> android: fix typo in BASE_URL

- frontends/web/src/components/sidebar/sidebar.tsx
- frontends/web/src/components/skeleton/skeleton.module.css
- frontends/web/src/components/skeleton/skeleton.tsx
- frontends/web/src/routes/account/info/buyCTA.tsx
- frontends/web/src/routes/account/summary/accountssummary.module.css
- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/account/summary/chart.module.css
- frontends/web/src/routes/account/summary/chart.tsx
Showing a placeholder (Skeleton) during loading improves the
user experience as there is less layout shifting and clear
indicators where content can be expected.
The skeleton component adds an invisible character so that the
CSS automatically inherits font-size from the parent in most
cases this sets the height correctly, if not there is a fontSize
prop to set the height. The component also has a minWidth prop
to indicate the desired width.
Changes:
- use skeleton for account summary view
- change chart on summary to always take a fixed height
- disable chart buttons until chart is loaded
- render sidebar asap even if subscribed keystores HOC is still
loading
- just pass data to chart component and let it handle it
- changed from setting accountsPerCoin once onmount to creating the
map on …
> frontend: improve visual loading of the account summary view

- frontends/web/src/routes/account/summary/chart.tsx
The chart filter buttons to change the chart to display
week, month, year and all is currently only checking
if the chart contains any data and the total is not 0.
But if the chart is updating the buttons are already active
even though the chart has not loaded and is displaying
updating data.
Changed to check for chartDataMissing and keep the buttons
disabled until everything is up to date.
> frontend: disable chart filter buttons if chartdatamissing

- Makefile
The current way with turning off the modules fails with:
```
gomobile: go install golang.org/x/mobile/cmd/gobind@latest failed: exit status 1
go: modules disabled by GO111MODULE=off; see 'go help modules'
```
According to the docs at
https://pkg.go.dev/golang.org/x/mobile/cmd/gomobile, `go install` is
to be used.
> Makefile: fix gomobile setup

- .github/workflows/ci.yml
- .golangci.yml
- Makefile
- README.md
- appveyor.yml
- backend/accounts/feetarget.go
- backend/accounts/transaction.go
- backend/coins/btc/maketx/txsize_internal_test.go
- backend/coins/coin/codes.go
- backend/devices/bitbox/error.go
- backend/rates/history_test.go
- docs/BUILD.md
- scripts/docker_install.sh
- scripts/travis-ci.sh
- util/errp/errp.go
Go 1.18 by default enables adding VCS info to the binary by querying
`git`. See https://tip.golang.org/doc/go1.18 ("VCS"). This fails in
the GitHub CI with the following error:
```
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```
It turns out that `git status` etc. on Github CI fails with:
```
fatal: unsafe repository ('/opt/go/src/github.com/digitalbitbox/bitbox-wallet-app' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /opt/go/src/github.com/digitalbitbox/bitbox-wallet-app
```
The issue is fixed by following this instruction.
See also: https://github.com/actions/checkout/issues/760#issuecomment-1097501613
golangci: remove newly added linters
Updated golangci-lint at the same …
> go: update Go to 1.18

- backend/coins/btc/transactions/verification.go
- backend/signing/configuration.go
xpubs and transaction hashes are sensitive informations and their logging
doesn't seem to be really useful. This update removes it.
> backend: remove sensitive data from the log file

- frontends/qt/setup.nsi
Currently, the windows installer uses "taskkill" to close any instances of the BitBoxApp that may be running during the installation.
This commit replaces "taskkill" with a user prompt to close the app if it detects a window with the title "BitBoxApp" is running.
> qt: update setup.nsis - replace "taskkill"

- frontends/web/src/components/aopp/aopp.tsx
- frontends/web/src/components/view/view.module.css
- frontends/web/src/components/view/view.tsx
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
If a View has a success icon by `<ViewContent withIcon="success"`
but not a lot of other content sometimes the ViewButtons are not
in the visible area on smaller screens.
Refactored the unused `top` option into `fitContent` to indicate
that the View should try to fit all content into the visible area.
With `fitContent` the big success icon will shrink if there is not
enough available space.
Note the footer could still be outside of the visible area and only
visible when scrolling down.
Also added some docstrings to the View component.
> frontend: add fitContent option to the view component

- frontends/web/src/components/centeredcontent/style.module.css
- frontends/web/src/components/devices/bitbox02bootloader/bitbox02bootloader.tsx
Currently the error is styled as plain text below the bootloader
dialog.
Changed styling to use status component as already used in various
other places and position before the bootloader dialog.
Before:
With this PR:
> frontend: update bootloader error styling

- frontends/web/src/routes/device/bitbox02/passphrase.tsx
The passphrase introduction explains what a passphrase is through
multiple steps. The second step is getting another line in a
different commit as that is pulled form locize.
This change increased the minimum height of the content area so
that all steps use the same height.
> frontend: increase minimum height of passphrase intro content

- frontends/web/src/api/bitbox01.ts
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/device/bitbox01/backups.tsx
- frontends/web/src/routes/device/bitbox01/settings/settings.jsx
- frontends/web/src/routes/device/bitbox01/setup/seed-create-new.jsx
- frontends/web/src/routes/device/bitbox01/setup/seed-restore.jsx
- frontends/web/src/routes/device/bitbox01/upgrade/require_upgrade.jsx
There is already api/devices.ts but this getDeviceInfo is specific
to BitBox01, so this change added api/bitbox01.ts.
Copied types from DeviceInfo struct in:
- [backend/devices/bitbox/device.go](https://github.com/digitalbitbox/bitbox-wallet-app/blob/197c8b7d4113d71bf717d391a70eda3b5f9b4cac/backend/devices/bitbox/device.go#L97-L112)
> frontend: type bitbox01 device info api

- CHANGELOG.md
- backend/coins/btc/handlers/handlers.go
- backend/coins/coin/conversions.go
- frontends/web/src/api/account.ts
- frontends/web/src/components/rates/rates.tsx
- frontends/web/src/components/transactions/transaction.tsx
- frontends/web/src/locales/en/app.json
/transactions endpoint modified to load only data displayed in transaction frontend list
A new /transaction endpoint created to load all available data for specific transaction in order to populate the detailed transaction view in frontend
FiatConversion component modified to use backend-calculated fiat amount conversions when available
Added code to show fiat value at time of transaction in detailed transaction view
> frontend/backend: modify transaction loading flow and add fiat value at time of transaction

- CHANGELOG.md
- frontends/web/src/components/headerssync/headerssync.module.css
- frontends/web/src/routes/account/summary/accountssummary.module.css
- frontends/web/src/routes/account/summary/accountssummary.tsx
When showing rapidly changing numbers like the number of blocks scanned, tabular numbers make the UI more stable. For example, a number like "11" is narrow while "12" is wider. By using tabular numbers, the width of the UI stays stable when it goes from rendering "11" to "12".
I added `font-variant: tabular-nums` to a few progress indicators. There is one indicator in account.tsx (`initializingSpinnerText`) that I didn't modify since it would require bigger changes to the Spinner component, such as allowing a parent to pass in JSX children instead of supporting only the `text` prop.
Block syncing progress:
https://user-images.githubusercontent.com/379606/179463028-19867286-09da-43d5-9b5e-39cacaec644c.mp4
Account summary scanning progress:
> frontend: kerning of progress numbers using tabular-nums

- frontends/web/src/components/headerssync/headerssync.tsx
Use the locale-specific formatting for currency numbers instead of
always using a singlequote as the thousandths separator. This is
done using Intl.NumberFormatter with the user's default locale.
> frontend: language-sensitive number formatting for blocks synced

- backend/devices/bitbox/keystore.go
- backend/devices/bitbox02/keystore.go
- backend/keystore/software/software.go
Not being able to reference the previous output of an input is a bug,
but at the moment one can run into it when making really fast
consecutive transactions: if a new tx is made before the previous one
is broadcast and received from the Electrum backend, it might reuse
UTXOs, which become spent the moment the previous tx is processed.
This commit simply removes the panic and turns it into an error that
the user sees in the frontend.
> backend/devices/keystore: don't panic if previous output missing

- frontends/web/src/routes/account/send/send.tsx
When BTC is the selected "fiat" currency, entering more than two
decimal places results in a red error border even though it is a legal
BTC amount.
The two decimal places where not correct before either e.g. for JPY,
where there are no decimals at all.
> frontend/send: allow more than 2 decimal places in the fiat field

- frontends/web/.eslintrc.json
- frontends/web/src/components/anchor/anchor.tsx
- frontends/web/src/routes/account/summary/chart.tsx
No space before type colon, space after type colon. Spaces around type arrows.
Spaces around funcion arrows.
Spaces around operators, e.g. `let a = b` instead of `let a=b`.
> frontend: more eslint spacing rules

- frontends/web/src/routes/account/receive/index.tsx
- frontends/web/src/routes/account/receive/receive-bb01.tsx
- frontends/web/src/routes/account/receive/receive.tsx
In e4f0d4e7 the receive view was split into BitBox01 and BitBox02
components so that the BitBox01 legacy version could remain as is.
This introduced an issue that no receive view is shown with the
software keystore used in webdev (dev mode).
Fixed receive view for software keystore and render the BitBox02
receive component.
> frontend: fix receive view with software keystore

- backend/chart.go
- backend/coins/btc/coin.go
- backend/coins/btc/coin_test.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/coin/coin.go
- backend/coins/coin/conversions.go
- backend/coins/coin/mocks/coin.go
- backend/coins/eth/coin.go
- backend/coins/eth/coin_test.go
- backend/handlers/handlers.go
- frontends/web/src/api/account.ts
- frontends/web/src/components/rates/rates.tsx
- frontends/web/src/components/transactions/transaction.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/account/summary/accountssummary.tsx
- frontends/web/src/routes/account/summary/chart.tsx
This PR (WIP):
- Fixes the BTC 2 digits backend formatting bug
- Proposes a draft solution to centralize formatting handling in the backend, exploiting higher precision when available
I still see room for some improvements in FromUnit implementation precision.
See commit messages for details.
Once agreed on this first draft, the next step is to refactor the frontend part, moving all the occasional formatting done there into the backend.
> Formatting refactor

- CHANGELOG.md
- frontends/android/BitBoxApp/app/src/main/res/values-v23/styles.xml
- frontends/android/BitBoxApp/app/src/main/res/values/colors.xml
- frontends/android/BitBoxApp/app/src/main/res/values/styles.xml
Before it was a dark green from Android project template that we never
changed.
```
<item name="android:windowLightStatusBar">true</item>
```
is added so that the text in the status bar turns black, otherwise it
would become invisible (white on white).
windowLightStatusBar is available only from API level 23 (even though
statusBarColor is available already from API level 21), so we enable
it for 23+.
> android: make status bar color the same white as the app background

- frontends/web/src/routes/account/info/signingconfiguration.tsx
The key accountInfo.scriptType was accidentally removed in:
9019690a0fe26a468e971632f348e775c66f05b5
This change replaces the hardcoded 'Type:' with the scriptType
translation.
> frontend: add missing scripttype translation

- frontends/web/src/routes/account/add/add.tsx
The ResponseData type in the frontend incorrectly assumed that
the errorCodes are 'alreadyExists' and 'limitReached', but the
codes are prefixed with 'account'. See the ErrorCode in errors.go.
Changed to accountAlreadyExists and accountLimitReached.
Also changed interface to type to not accidentally extend an
existin interface, should always use type.
> frontend: fix incorrect errorcode type

- frontends/web/src/routes/account/add/components/coin-dropdown.tsx
Select elements do not have placeholder prop. The selectPlaceholder
key is already added to the component via the first option.
TypeScript did not catch this as error because we use
JSX.IntrinsicElements['select'], which extends from HTMLAttributes:
interface SelectHTMLAttributes<T> extends HTMLAttributes<T>
where placeholder is an option.
Removed the placeholder prop.
> frontend: remove unused placeholder prop

- frontends/web/src/components/balance/balance.tsx
- frontends/web/src/components/rates/rates.module.css
- frontends/web/src/components/rates/rates.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/account/send/utxos.tsx
The use of fiat selection in send view was affecting only the balance,
but not the other parts of the page (i.e. the fiat amount to be transfered).
Since it is not easy to decide which should be the correct behavior if
the user change the fiat while compiling the form, we thought it was
better to disable the feature in this view.
> frontend/send: disable fiat selection for send view

- frontends/qt/main.cpp
The obsolete setRequestInterceptor causes the follwing warning:
'Use of deprecated not thread-safe setter, use setUrlRequestInterceptor instead.'
Use setUrlRequestInterceptor instead, see
https://doc.qt.io/qt-5/qwebengineprofile-obsolete.html#setRequestInterceptor
> qt: setRequestInterceptor is obsolete

- frontends/web/.eslintrc.json
- frontends/web/src/components/banner/banner.tsx
- frontends/web/src/components/guide/guide.tsx
- frontends/web/src/components/rates/rates.tsx
- frontends/web/src/components/view/view.tsx
- frontends/web/src/routes/account/add/components/steps.tsx
- frontends/web/src/routes/account/send/utxos.tsx
- frontends/web/src/routes/buy/info.tsx
- frontends/web/src/routes/buy/moonpay.tsx
- frontends/web/src/routes/device/bitbox01/backups.tsx
- frontends/web/src/routes/device/bitbox01/bitbox01.jsx
- frontends/web/src/routes/device/bitbox01/setup/initialize.tsx
- frontends/web/src/routes/device/bitbox01/setup/seed-restore.jsx
- frontends/web/src/routes/device/components/backups.module.css
- frontends/web/src/routes/router.tsx
Eslint rule react/no-unused-prop-types found a few issues, but also
false positives related to load decorator or custom store.
This change removes unused props, but does not permanently add the
rule to eslint.
> frontend: fix react/no-unused-prop-types

- backend/coins/coin/conversions.go
- backend/config/config.go
- backend/rates/rates.go
Added an enum with all the supported fiats and removed fiat strings
from around the code
> backend/rates: add supported fiat enum

- frontends/web/src/components/view/view.module.css
The contents of the success view was not aligned with the content width, this is a regression introduced in:
- 6fae0143e9e23dc3b3df8b4058fc45668a7341f9
> frontend: fix simple message signing success view

- frontends/web/src/routes/device/bitbox01/components/upgradefirmware.jsx
- frontends/web/src/routes/device/bitbox02/upgradebutton.tsx
Once the user is prompted to confirm upgrading the firmware on the
device, the dialog in the app should be blocking.
Changed to use DialogButtons to have nice alignment and do
not need to import the CSS file from another component.
> Frontend blocking firmware upgrade

- frontends/web/src/api/bitbox02.ts
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
Before this, `/attestation` endpoint was called in an untyped way from `bitbox02.tsx`. Now there is a dedicated typed funcion in `api/bitbox02.ts`.
> frontend/api: implement typed function to verify attestation on bb02

- frontends/web/src/routes/account/account.tsx
Cointracking asked us again to change their link. This time the ref  auto-applies a 10% discount code for an existing or new user.
> frontend: update cointracking link

- CHANGELOG.md
- backend/accounts/errors/errors.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/eth/etherscan/etherscan.go
- frontends/web/src/api/account.ts
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/send/send.tsx
If the user tries to send an erc20 transaction without having enough ETH to pay for the fee, etherscan returns a rough error message, which was previously displayed in the frontend as is.
Now the backend returns a dedicated error code and the frontend displays a comprehensible and localized error message.
> frontend: improved insufficient gas error for erc20 txs

- frontends/web/src/components/icon/assets/icons/star-inactive.svg
- frontends/web/src/components/icon/assets/icons/star.svg
- frontends/web/src/components/icon/icon.tsx
- frontends/web/src/routes/settings/components/fiat/fiat.module.css
- frontends/web/src/routes/settings/components/fiat/fiat.tsx
This is not about fixing the financial system but only about which
legacy currency should be set as the default unit of account. lol.
The current styling of the default fiat is star becomes orange
(outlined icon) and the toggle becomes inactive as it is disabled
so that the default cannot be turned off. The styling looks
confusing as it is not clear that this is the default.
To improve the visual styling this commit:
- added small '(default)' text after the currency
- made active star more prominent, changed from outline to filled
Also (additional commit)
- move inline svg to image to reduce the bundle size, JavaScript parse time and React dom diffing.
> frontend: refactor fiat default

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/guide.tsx
- frontends/web/src/routes/account/utils.ts
- move account guide to its own component
- remove old split account specific guide entries 
Moved isBTCScriptType to utils and the account guide to its own
component so that account.tsx is slightly simpler and easier to
refactor.
These were used in the settings page when we used to have separate
accounts per script type, with toggles for each one. this is also
all gone now with unified accounts and the multi-accounts feature.
Also: there is now a script type guide in the receive screen.
> frontend refactor account guide

- frontends/web/src/components/rates/rates.module.css
- frontends/web/src/components/rates/rates.tsx
- frontends/web/src/components/transactions/transaction.tsx
Fiat historical value is shown in tx detail. If the transaction is recent the value could be not available. The placeholder we used was '---' which led to poorly readable results for incoming/outgoing txs ('+---' or '----'). The new placeholer is 'N/A', which should be more readable.
> frontend: modify fiat historical value placeholder in tx

- frontends/web/src/api/backend.ts
- frontends/web/src/api/bitbox02.ts
- frontends/web/src/hooks/sdcard.ts
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
Ongoing effort to rewrite all class based components to functional components so we can use hooks.
- typed check-sdcard api
- typed buy-supported api
- remove load decorator and load config directly
also: remove old account type information
This was used before unified accounts were introduced. Removing.
> frontend: refactor account to functional component

- backend/coins/coin/conversions.go
- frontends/web/src/components/rates/rates.tsx
Unexpected errors from coingecko service were causing the backend to send amounts with nil conversions field, which caused runtime errors on the frontend. With this update, a != nil conversions field should always be available even when coingecko errors accour, allowing the frontend to handle the situation without blocks.
> backend/conversions: fix nil conversions when rates not available

- README.md
- backend/accounts.go
- backend/accounts_test.go
- backend/backend.go
- backend/coins/coin/codes.go
- backend/config/config.go
- backend/handlers/handlers.go
- backend/rates/gecko.go
- backend/rates/rates.go
- frontends/web/src/components/icon/logo.tsx
- go.mod
- go.sum
- vendor/github.com/digitalbitbox/bitbox02-api-go/api/firmware/device.go
- vendor/github.com/digitalbitbox/bitbox02-api-go/api/firmware/mnemonic.go
- vendor/modules.txt
ETH merge happened recently, and Ropsten and Rinkeby testnets will soon be deprecated from Etherscan. This add support for the new Goerli testnet.
> backend: add Goerli ETH testnet network

- CHANGELOG.md
- backend/coins/btc/coin.go
- backend/coins/btc/coin_test.go
- backend/coins/coin/conversions.go
- frontends/web/src/components/balance/balance.tsx
- frontends/web/src/components/rates/rates.tsx
- frontends/web/src/routes/account/summary/chart.tsx
- frontends/web/src/utils/trailing-zeroes.test.tsx
- frontends/web/src/utils/trailing-zeroes.ts
Added trailing zeroes when displaying BTC/LTC amounts in the frontend, with the exception of the balances displayed in the header of account and accountsummary views.
> frontend: adding trailing zeroes to BTC and LTC formatting

- frontends/android/BitBoxApp/app/build.gradle
- frontends/android/BitBoxApp/app/src/main/AndroidManifest.xml
According to
https://support.google.com/googleplay/android-developer/answer/11926878, the requirements as of now is that updating an app requires API level 31 (Android 12) by November 1st 2022.
The exported attribute is set according to
https://developer.android.com/about/versions/12/behavior-changes-12#exported:
> If your app targets Android 12 or higher and contains activities,
services, or broadcast receivers that use intent filters, you must explicitly declare the android:exported attribute for these app components.
> android: target api level 31, enforced by Google Play

- CHANGELOG.md
- frontends/android/goserver/goserver.go
On Android, due to a bug in
Go (https://github.com/golang/go/issues/20455), the local timezone is not correct. It is always UTC.
As a result, when restoring a backup on the BitBox02, the BitBox02 displays the current time in UTC instead of the local time.
This commit contains a workaround to fix the timezone on Android.
Alternative considered: getting the timezone offset in native Android code and sending it to Go-land via backend.Environment. I did not pursue this as a quick search didn't turn up an easy way to get the timezone offset on Android which takes into account daylight-savings etc.
> android: fix timezone so the BitBox02 shows the correct time

- CHANGELOG.md
- frontends/android/BitBoxApp/app/src/main/AndroidManifest.xml
- frontends/android/BitBoxApp/build.gradle
With Android 11 the visibility of the installed packages has been filtered to offer a higher privacy level to the user. This commit add to AndroidManifest.xml the `queries` elements needed to open external links for web pages and `mailto` urls.
Queries support is not granted in all Gradle versions. For this reason, the latter has been updated to v3.5.4.
Refs:
https://developer.android.com/training/package-visibility
https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9
https://android-developers.googleblog.com/2020/07/preparing-your-build-for-package-visibility-in-android-11.html
> android: add external link queries for Android 11 permissions

- frontends/qt/BitBox.pro
- frontends/qt/main.cpp
Introduced in 8a27bfe72793a86fdbdbc1384700861bdc84eb4c to enable the in-app lociz editor, which was removed again in 29a0764ea4a5d4f412ec928055439a083c47d99d.
> qt: remove unused QT_BITBOX_ALLOW_EXTERNAL_URLS

- frontends/web/src/components/guide/entry.tsx
- frontends/web/src/components/guide/guide.module.css
The entry property was also changed from `EntryProp | string` to
`EntryProp`, as the locize in-app editor (`cimode`) does not exist
anymore (removed in 29a0764e).
> frontend/guide/entry: convert to FunctionalComponent

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/bitbox01/setup/initialize.tsx
- frontends/web/src/routes/device/bitbox01/setup/security-information.tsx
- frontends/web/src/routes/device/bitbox01/setup/seed-restore.jsx
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
The same translation for 'Continue' is used in various components,
changed to use the same generic text everywhere instead of custom
translation key.
Note: I kept different commits so that it is easier to review, but I'll squash
into 1 commit once approved.
> frontend: use generic continue button translation

- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
Before there was a disabled grayed out continue button on the pairing step when the user should focus on the device and confirm the code.
Changed so that the is a point-to-device graphic without a disabled button. Once the pairing is confirmed it changes to a continue button.
> frontend: show point-to-device graphic on pairing step

- frontends/web/src/components/rates/rates.module.css
- frontends/web/src/components/transactions/transaction.module.css
- frontends/web/src/components/transactions/transaction.tsx
- frontends/web/src/components/transactions/transactions.module.css
Sometimes the unit breaks onto a separate line, this happens with
large amounts or coins with lots of decimal for example with ETH.
Changed styling so that very large amounts are cut off with "…",
but only visually so that copy/paste contains takes the whole
amount. This should also fix the issue with large amounts on
small screen, in extreme cases the fiat amount should squeeze
the coin amount together.
Also added "font-variant: tabular-nums" definition for the amount
so that all numbers take equal space, without using a monospace
font.
and small screen:
> frontend: fix coin and unit styling in tx overview

- frontends/web/src/api/bitbox02.ts
- frontends/web/src/routes/device/bitbox02/settings.tsx
The backend can in theory return nil/null in the attestation endpoint, if the endpoint is called before the device.Init() function has finished, where the attesation check is performed.
The bb02 init is a bit messy, in the above state probably most/all other bb02 calls would be broken too. For now, we simply adjust the return type of `verifyAttestation()` to match the backend.
> frontend/bitbox02/settings: handle attestation==null

- CHANGELOG.md
- backend/backend.go
- frontends/web/src/components/anchor/anchor.tsx
- frontends/web/src/components/guide/guide.tsx
As we are continuously adding and updating translations, we should
have a way to give feedback for the translations to help us catch
translation errors.
Added a mailto link at the bottom of the guide and allow mailto
links to be opened by the backend.
> frontend: add translation feedback link

- .golangci.yml
- backend/accounts/baseaccount.go
- backend/backend.go
- backend/chart.go
- backend/coins/btc/account_test.go
- backend/coins/btc/coin.go
- backend/coins/btc/coin_test.go
- backend/coins/btc/maketx/maketx_test.go
- backend/coins/btc/transaction.go
- backend/coins/btc/util/util.go
- backend/coins/coin/codes.go
- backend/coins/coin/coin.go
- backend/coins/eth/coin.go
- backend/coins/eth/coin_test.go
- backend/config/config.go
- backend/handlers/handlers.go
- frontends/web/src/api/account.ts
- frontends/web/src/api/coins.ts
- frontends/web/src/components/rates/rates.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/settings/settings.tsx
Instead of 'BTC' | 'sat', we use 'default' | 'sat', to avoid confusion with BTC coin units which also include 'TBTC' for testnet.
This helps with readability of the code, as the type and possible values are clear at every step.
> backend: add a BtcUnit type and use it everywhere to format sats

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/settings/settings.tsx
Added 'What is a Satoshi' guide entry on the settings page, as not all users might know what it is.
Also reordered settings entry and moved which exchange rates up as second entry.
> frontend: add guide entry for sats

- backend/coins/btc/handlers/handlers.go
- frontends/web/src/api/account.ts
- frontends/web/src/routes/account/account.tsx
- frontends/web/src/routes/account/info/buyCTA.tsx
Since recently, BTC amounts are returned with trailing zeroes, so the `'0'` string comparison stopped working to check if there is a balance.
Similar to `hasAvailable`, the backend should deliver the information.
> frontend/account: fix CanSend and Buy call to action

- frontends/web/src/routes/account/add/add.tsx
The add-account success view only has 1 button 'Done' to continue that goes directly to the newly created account. This makes adding multiple accounts a bit tedious becuase the user needs to navigate back to settings -> manage accounts -> add account.
- added a back button on select-currency (1st step of add-account) that goes back to the manage-accounts view
- added a 'Add another account' secondary button on the succeess step of add-account to easily add multiple accounts
> frontend: add options to navigate on add-account

- frontends/web/src/components/language/language.test.tsx
- frontends/web/src/components/language/language.tsx
- frontends/web/src/components/language/types.ts
As a part of our refactoring efforts and to follow the latest conventions in the frontend, class components need to be converted into functional ones whenever possible. 
Tests are updated so they work with the newly created functional component and its hooks. Also migrated the test away from enzyme to testing-library/react, as we plan to remove and not use enzyme anymore in the future.
> frontend: converted LanguageSwitch to a functional component and updated its test

- frontends/web/src/routes/account/account.tsx
Before this change, onAccountChanged was called immediately when the
account was switched and the code changed, as it depended on the code,
which changed the callback, which led to it being called due to this line:
`useEffect(onAccountChanged, [onAccountChanged, status]);`
Calling this callback before `accountApi.init()` is incorrect and
leads to an error.
Instead of depending on the code and status, we pass it as params
instead.
We also await the result of `init()`, as technically it is also async
and could finis after `onAccountChanged()` was called.
> frontend/account: call onAccountChanged after init/onStatusChanged

- frontends/web/package-lock.json
- frontends/web/package.json
- frontends/web/src/routes/account/send/__snapshots__/feetargets.test.tsx.snap
- frontends/web/src/routes/account/send/feetargets.test.tsx
- frontends/web/src/setupTests.js
- frontends/web/src/utils/markup.test.tsx
As enzyme doesn’t have support for the latest React versions, we would like to migrate our tests from enzyme to
react-testing-library (RTL).
> frontend: migrated tests from enzyme to RTL

- frontends/web/src/routes/settings/electrum-add-server.tsx
- frontends/web/src/routes/settings/electrum.module.css
The ‘download cert’ and ‘check’ buttons were not showing the loading animation when they were  supposed to. The problem
was due to the buttons' incorrect styling. It caused the animation to look invisible.
To fix the issue, their style has been altered to be the same as the buttons at the top of the page (the ‘Check’ and
‘Remove’ buttons). The `disabled` conditions for each button have also  been slightly refactored to increase its robustness
& readability which also fixed an existing bug.
Screen capture of the **now working (visible)** animation:
https://user-images.githubusercontent.com/28676406/199158463-05b41792-6aa4-4716-8fb0-d8fb920f41ab.mov
> frontend: fixed download cert, check, and add buttons

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/bitbox02/settings-guide.tsx
- frontends/web/src/routes/device/bitbox02/settings.tsx
Added a guide to manage device with entries about:
- BitBox02 name
- Secure chip
- Attestation / authenticity check
> frontend: add manage-device guide

- backend/backend.go
BitBoxApp used cryptocompare.com for exchange rates but uses coingecko now.
Removed cryptocompare.com so that links to it cannot be opened anymore.
Updated locize too.
> backend: do not allow links to cryptocompare.com anymore

- CHANGELOG.md
- frontends/web/src/api/bitbox02.ts
- frontends/web/src/routes/device/bitbox02/checkbackup.tsx
If the first checkBackup() call has a delay in the backend and the
second checkBackup() call starts before the first handles the
response, the dialog will be empty. I encountered this bug in the wild
recently.
Awaiting the first response before requesting the second fixes this.
> frontend/bitbox02/checkbackup: fix async bug

- backend/coins/btc/account.go
- backend/coins/btc/blockchain/blockchain.go
- backend/coins/btc/blockchain/mocks/Interface.go
- backend/coins/btc/blockchain/mocks/mock.go
- backend/coins/btc/electrum/client/client.go
- backend/coins/btc/transactions/verification.go
This will make it simpler to propagate and handle errors. It is also
easier to read.
There is no loss of performance, as this call already happens in a
goroutine as part of the callback to `ScriptHashSubscribe()`.
> backend/btc: make ScriptHashGetHistory synchronous

- Makefile
- backend/accounts.go
- backend/coins/btc/headers/headers.go
- scripts/run_regtest.sh
- Checkpoints not defined for regtest, make them optional
- Delete the headers-rbtc.bin file before running, otherwise an existing headers DB can conflict with a new regtest chain
- Fix loading regtest accounts
- Update benma2/electrs with a new image. Dockerfile inlined below:
```
FROM rust:1.64.0 as rust
RUN apt-get update
RUN apt-get install -y clang cmake
RUN git clone --depth 1 --branch v0.9.9 https://github.com/romanz/electrs.git /electrs-src
RUN cd /electrs-src && cargo build --release
WORKDIR /electrs
RUN cp /electrs-src/target/release/electrs /electrs/
STOPSIGNAL SIGKILL
ENTRYPOINT ["/electrs/electrs"]
```
> scripts/run_regtest: make regtest testing work again

- frontends/web/src/components/transactions/transaction.module.css
- frontends/web/src/components/transactions/transaction.tsx
In the last commit that improved support for large amounts or coins with lots of decimal, the space for the unit was fixed to 40px and the cause for some visual bug and inconsistent space between amount and unit. Sometimes too large or almost overlapping in case of GOETH.
This change creates a dynamic 'spacer' element with the correct width by passing the unit + 1 white-space to an invisible elemenet.
> frontend: fix space between amount and unit

- Makefile
Missing line break leads to following error while running `make osx-init`:
```console
➜  bitbox-wallet-app git:(master) make osx-init
/bin/bash -c ""
brew install go@1.18    brew install qt@5
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
Warning: No available formula with the name "brew". Did you mean brev?
==> Searching for similarly named formulae...
These similarly named formulae were found:
brew-cask-completion         brew-php-switcher            heroku/brew/heroku           nodebrew                     whalebrew
brew-gem                     brew-pip                     heroku/brew/heroku-node      phpbrew                      brev
To install one of them, run (for example):
brew install brew-cask-completion
==> …
```
> Fix line break in osx-init

- frontends/web/src/routes/account/summary/accountssummary.module.css
- frontends/web/src/style/base.css
The native progress element that shows the progress of upgrading the firmware has a visual regression and does not use the full available width anymore but is rendered at around 150px.
Looks like the default styling for the progress element changed in chrome and uses `display: inline-block;` and `width: 160px;`.
This is older but could be related:
- https://bugs.webkit.org/attachment.cgi?id=50959&action=diff#WebCore/css/html.css_sec1
> frontend: fix progress bar styling

- backend/coins/btc/coin.go
- backend/coins/btc/handlers/handlers.go
- backend/coins/coin/coin.go
- backend/coins/coin/mocks/coin.go
- backend/coins/eth/coin.go
- backend/coins/eth/coin_test.go
- backend/handlers/handlers.go
Merge of sat unit feature introduced a regression in the display of ERC20 token fee unit, caused by the absence of a boolean `isFee` argument for `GetFormatUnit` coin method.
> backend: fix unit error on ERC20 fees

- frontends/web/src/components/alert/Alert.tsx
- frontends/web/src/routes/device/bitbox02/bitbox02.tsx
- frontends/web/src/routes/device/bitbox02/passphrase.tsx
- frontends/web/src/utils/markup.test.tsx
- frontends/web/src/utils/markup.tsx
To follow the latest conventions in the frontend, we would like to convert `multilineMarkup()` into a "normal" JSX component, `<MultilineMarkup />`.
Previously, it's not possible to use the component as `<MultilineMarkup />` due to the usage of Preact 8 - which does not support document fragments.
> frontend: convert multilineMarkup to JSX

- CHANGELOG.md
- frontends/web/src/routes/account/summary/chart.module.css
- frontends/web/src/routes/account/summary/chart.tsx
- frontends/web/src/routes/account/summary/filters.tsx
- frontends/web/src/routes/account/summary/types.ts
portfolio chart on mobile looked like it had uneven spacings
and whitespaces which made it not centered. This is due to 
the vertical label (y-axis) drawn by the library.
This commit is inteded to fix that chart’s UI by partly re-styling
it for mobile, where the vertical label and side paddings are
removed.
To interact with the chart on mobile, long-press on the chart and
move around the chart. To stop interacting, users can simply lift
their fingers (stop touching the chart).
(Updated) screenshots of the chart:
> frontend: improved portfolio chart on mobile

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/summary/accountssummary.tsx
New entry guide to help users understand the action needed to be able to
explore (entering the tracking mode of) the portfolio graph.
This allows them to see the historical value of their
portfolio.
> frontend: new guide entry for entering tracking mode on mobile

- CHANGELOG.md
This change added a 0.5s-1s delay when launching the app, which should be addressed before releasing it. Moving out of the 4.35 release.
> CHANGELOG: move entry out of 4.35 to unreleased

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/settings/manage-accounts.tsx
It is translated as `$t(addAccount.title)` in all languages.
> frontend: remove the redundant manageAccounts.addAccount i18n key

- backend/coins/eth/account.go
Similar to 7a25ac8720989b2215806f802e42d5bf1ccc263a.
EtherScan returns this error during when estimating the gas if there are not enough funds to pay for the transaction.
This is likely a change in behavior in Etherscan, as the check below `// Check that the entered value and the estimated fee are not greater than the balance.` used to work. We keep that code in case we move away from Etherscan or Etherscan changes the behavior and returns a gas  anyway.
This is not a robust check as it compares strings, but it is the best we can do for now.
> backend/eth: return ErrInsufficientFunds if gas estimation failed

- frontends/web/src/routes/account/account.module.css
To improve the UI on mobile, we'd like to increase the size (height) of these buttons.
Before:
After:
> frontend: restyled buy/send/receive buttons on mobile

- frontends/web/src/components/confirm/Confirm.tsx
- frontends/web/src/components/dialog/dialog.module.css
- frontends/web/src/components/dialog/dialog.tsx
- frontends/web/src/components/language/language.tsx
- frontends/web/src/components/transactions/transaction.tsx
- frontends/web/src/hooks/matchmedia.ts
- frontends/web/src/routes/account/receive/receive-bb01.tsx
- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/account/send/utxos.tsx
- frontends/web/src/routes/device/bitbox01/check.jsx
- frontends/web/src/routes/device/bitbox01/components/upgradefirmware.jsx
- frontends/web/src/routes/device/bitbox01/create.jsx
- frontends/web/src/routes/device/bitbox01/restore.tsx
- frontends/web/src/routes/device/bitbox01/settings/components/changepin.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/device-lock.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/hiddenwallet.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/mobile-pairing.tsx
- frontends/web/src/routes/device/bitbox01/settings/components/randomnumber.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/reset.jsx
- frontends/web/src/routes/device/bitbox02/checkbackup.tsx
- frontends/web/src/routes/device/bitbox02/reset.tsx
- frontends/web/src/routes/device/bitbox02/sdcardcheck.tsx
- frontends/web/src/routes/device/bitbox02/setdevicename.tsx
- frontends/web/src/routes/device/bitbox02/upgradebutton.tsx
- frontends/web/src/routes/settings/manage-accounts.tsx
- frontends/web/src/routes/settings/settings.tsx
To maximise spacing and achieving a more modern look on mobile, we want to re-style the Dialog component to become a "modal bottom sheet" (or a bottom sheet).
Some screenshots and a screen recording:
https://user-images.githubusercontent.com/28676406/201877070-d82b3737-ed6d-4649-815c-bfd7c81afce1.mov
> frontend: improve dialog on mobile

- frontends/web/src/api/account.ts
- frontends/web/src/components/rates/rates.tsx
Conversions can sometimes be missing, as some of the logic in rates.tsx is executed before React, an error here seems to cause the app to fail resulting in a blank screen.
How to test:
1) unlock BB02, enable Tor and configure a inexistent port
2) quit and restart the app again
3) should show no blank screen
> frontend: conversions can be missing

- .github/workflows/ci.yml
The macOS 10.15 Actions runner image is beeing deprecated.
See https://github.com/actions/runner-images/issues/5583
> ci: use macos 11

- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/device/bitbox02/settings.tsx
- frontends/web/src/routes/device/bitbox02/upgradebutton.tsx
In 9107a09 we added a new Info section in the settings page, showing a green or a red icon, depending on the availability of new updates for the app.
This refactors the firmware version section of the device page, applying the same style and icons for firmware upgrades.
> frontend: add red/green icons to firmware version on device settings

- CHANGELOG.md
- frontends/web/src/components/sidebar/sidebar.css
- frontends/web/src/components/sidebar/sidebar.tsx
to improve our app's UI and achieving a more modern look, we'd like to make the sidebar menu / navigation to be of full screen size on mobile.
[Preview] Screen recording on mobile:
https://user-images.githubusercontent.com/28676406/204563461-d42905f8-3f87-4935-9160-481d918f20b6.mov
[Preview] Screenshot on desktop (no change):
> frontend: full screen menu on mobile

- frontends/web/src/routes/buy/moonpay.tsx
- frontends/web/src/style/layout.css
In f30df4f4a64f50789541fe153a24389b5fc1954d the iframe container accidentally contained 2 this.ref, which is wrong.
As the iframe scrolls anyway the header is always sticky. Removed scrollContainer classes, so that there is no double scroll.
> frontend: fix buy container

- frontends/web/src/components/sidebar/sidebar.module.css
- frontends/web/src/components/sidebar/sidebar.tsx
- frontends/web/src/style/index.css
- frontends/web/src/style/layout.css
As a part of our refactoring efforts in the FE, we'd like to use CSS modules whenever suitable.
**[Preview] Screenshot:**
exactly the same as our current sidebar, which should be the case since practically no styling was changed ✅
> frontend: migrate sidebar.css into a css module

- backend/coins/coin/conversions.go
The frontend types IAmount.Conversions to always be a map, never null. If null is returned, the frontend errors in rates.tsx when accessing `amount.conversions[active]`, crashing the whole frontend.
This fix has already been done before in
32387d1b9814eeeb44d69ff79dc8daaa1924f879, but accidentally undone again in f5a2a823cd406bde2a30f273a6e646606a38210f.
> backend/coin/conversions: never return nil for Conversions

- CHANGELOG.md
- backend/coins/btc/coin.go
- backend/coins/btc/db/headersdb/headersdb.go
- backend/coins/btc/db/headersdb/headersdb_test.go
- backend/coins/btc/headers/headers.go
A user reported a crash. A header was loaded (at a valid height) but nil was returned, so there was a crash:
```
github.com/btcsuite/btcd/wire.writeBlockHeader({0xd50a00, 0xc0003b0db0}, 0x5e2cc5?, 0x40?)
/home/marko/go/src/github.com/digitalbitbox/bitbox-wallet-app/vendor/github.com/btcsuite/btcd/wire/blockheader.go:125 +0x36
github.com/btcsuite/btcd/wire.(*BlockHeader).BlockHash(0xc0000af940?)
/home/marko/go/src/github.com/digitalbitbox/bitbox-wallet-app/vendor/github.com/btcsuite/btcd/wire/blockheader.go:54 +0x99
github.com/digitalbitbox/bitbox-wallet-app/backend/coins/btc/headers.(*Headers).canConnect(0xc00036f680, {0xd58318, 0xc00027fb20}, 0x54444, 0xc00032a000)
/home/marko/go/src/github.com/digitalbitbox/bitbox-wallet-app/backend/coins/btc/headers/headers.go:317 +0x1ee …
```
> backend/btc/headers: fix broken headers database

- backend/backend.go
- backend/exchanges/exchanges.go
- backend/exchanges/moonpay.go
- backend/exchanges/pocket.go
- backend/exchanges/util.go
- backend/handlers/handlers.go
- frontends/web/src/api/exchanges.ts
- frontends/web/src/i18n/config.js
- frontends/web/src/i18n/i18n.js
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/account/utils.ts
- frontends/web/src/routes/buy/exchange.module.css
- frontends/web/src/routes/buy/exchange.tsx
- frontends/web/src/routes/buy/info.tsx
- frontends/web/src/routes/buy/moonpay.tsx
- frontends/web/src/routes/router.tsx
This adds:
** Dynamic header
- header logic to display different coin names based on what the user wants to buy (as already implemented for other pages in /buy/ workflow).
** Region support for exchanges
- region list encoded following ISO 3166-1
- moonpay availability based on region (exploiting moonpay API REST call)
- localization of region names when displayed in `exchanges.tsx`
~~Please note that Pocket API REST service for supported regions is not ready yet. For this reason at the moment Pocket is displayed as available in every region.~~
** Deal details for exchanges
- Details of the deals offered by Pocket and Moonpay are available in `exchanges.tsx` with `FAST` and `BEST DEAL` tags.
** What is still missing: 
- `exchange.tsx` layout is just drafted to verify the logic. It still …
> buy/exchange: add logic for exchange selection

- frontends/web/src/components/sidebar/sidebar.tsx
to improve our UI, in the sidebar,  we'd like to have "Buy Bitcoin" instead of "Buy crypto" for wallets with only Bitcoin (and TBTC) account(s). 
Wallet with multiple of **only** bitcoin accounts:
Wallet with only 1 bitcoin account (preview in German):
Wallet with multiple accounts of various coins:
Small note: "Buy crypto" is translated.
> frontend: sidebar to use "Buy Bitcoin" for BTC only wallet

- backend/coins/btc/db/transactionsdb/transactionsdb.go
Begin() currently always opens a write-transaction, so we could init the buckets there. Most of the time we don't need write-transactions as read-only transactions suffice. This commit prepares using read-only transactions, which improve code clarity and performance.
> backend/btc/transactionsdb: don't create buckets on Begin()

- Makefile
- backend/backend.go
- backend/config/config.go
- scripts/run_regtest.sh
The kylemanna/bitcoind Dockerfile specifies `/bitcoin` as `$HOME`, making the btc data dir default to `/bitcoin/.bitcoin` (`-datadir` wasn't specified).
Also we define ports in variables for clarity.
> scripts/regtest.sh: fix datadir, define port vars

- frontends/web/src/components/view/view.module.css
- frontends/web/src/components/view/view.tsx
- frontends/web/src/routes/device/bitbox02/settings.tsx
Settings can use View, Grid and Column component for layout instead of plain div's. The View component is mostly used in fullscreen mode but an early version did support normal mode with sidebar and guide. Fixed some minor CSS issues (spacing etc.) so that normal mode should now be fully working.
This could also be used for normal settings and exchange integration in the future.
> frontend: use view component for device settings

- .gitignore
Was removed in b21fd73fa1b1fa87f684b76c1ce1a00a93bb0634 because in VS Code the content of the files could not be searched, probably because one rule ignores the locales directory, and other rules unignore the currently active languages that are supported in the BitBoxApp.
Searching in VS Code is still a bit buggy and content cannot be found unless one of the parent directories is specifically added in 'files to include'. This is good enough.
Added back the ignores that unfinished locales are not accidentally commited.
> git: ignore unfinished locales

- .github/workflows/ci.yml
- Makefile
- frontends/web/package-lock.json
- scripts/travis-ci.sh
This reduces the vulnerabilities reported by `npm audit`. Those are all npm dev dependencies and production modules should not be affected.
Deleted node_modules and package-lock.json and did a new clean
install running: `npm install --ignore-scripts`
opened so I don't forget but need to test this more.
> frontend: update package-lock.json

- frontends/web/src/routes/buy/pocket.tsx
To fix the UI bug where Guide icon on the header appears twice
[Preview] Before
[Preview] After
> frontend: conditionally renders Spinner in buy/pocket

- frontends/web/src/components/dialog/dialog.module.css
In 484c42f59207f12f428f588935cd3628e603d83b the device settings was refactored to use View component. This had a sideeffect that --size-default CSS variable was changed on large screens and the cause of a regression that paragraph text in dialogs are rendered with a larged font.
Fixed by adding some CSS to guard against View CSS.
> frontend: fix fontsize in dialogs regression

- frontends/web/src/routes/account/send/utxos.tsx
Fixes this error:
```
react_devtools_backend.js:4012 Warning: Each child in a list should have a unique "key" prop.
Check the render method of `UTXOsClass`. See https://reactjs.org/link/warning-keys for more information.
at div
at UTXOsClass (http://localhost:8080/static/js/bundle.js:23710:5)
```
> frontend/send: fix duplicate/no key in UTXOsClass

- backend/backend.go
to allow opening of their website from the BitBoxApp.
> backend: whitelist pocketbitcoin's website URL

- frontends/web/src/routes/account/receive/receive.tsx
- frontends/web/src/routes/account/send/send.tsx
to prevent page (send & receive screen) **also getting closed** when a user intends to close an opened dialog using "ESC" key.
[Preview] (actions: pressed "ESC" and then "ESC" once more):
_please ignore favicon,it's cached from a different app_
**Send Screen**
https://user-images.githubusercontent.com/28676406/211244484-f796c837-8740-41e2-805b-a4fa856c8770.mov
**Receive Screen**
https://user-images.githubusercontent.com/28676406/211244499-20605e1a-3e80-45da-8951-3806d9d9474a.mov
> frontend: add additional condition on closing pages using "ESC"

- backend/exchanges/util.go
Since the upgrade of Go to v1.19 in 257253c3a06862e755f9438afb76e52d2846395d import of ioutil is deprecated, causing the CI flow to fail. This fixes the import.
> backend: fix deprecated ioutil import in util.go

- backend/exchanges/pocket.go
- backend/handlers/handlers.go
- util/config/locale.go
- util/config/locale_test.go
This PR fixes a bug in the language param used to call the Moonpay widget and adds the language param in the URL used to call  Pocket widget. See commit messages for details
> Exchange widget language

- frontends/web/src/components/dialog/dialog.module.css
to centre the dialog's modal with respect to content when sidebar is opened, we needed to add an extra margin.
Extra margin's value is the width of the sidebar when it's opened.
> frontend: added extra margin for dialog modal

- frontends/web/src/routes/buy/iframe.module.css
- frontends/web/src/routes/buy/moonpay.tsx
- frontends/web/src/routes/buy/pocket.tsx
- frontends/web/src/routes/buy/terms.module.css
- frontends/web/src/style/layout.css
The iframe could not be scrolled all the way to the end, about exactly the height of the headers. Turns out JavaScript read the wrong height, as it included the height of the header.
Fixed the CSS height of the iframe container, so that the script reads the correct height.
Also removed unused CSS and fixed duplicated styling in MoonPay component. For some reason MoonPay was using styles from terms instead of iframe.module.css. Now both Pocket and MoonPay should use the same CSS.
> frontend: fix iframe scroll content

- frontends/web/src/components/guide/guide.tsx
Sometimes users made support requests to the translation feedback email, changed the order so that support is first.
> frontend: switch support and translation feedback links

- frontends/web/src/api/nativelocale.ts
- frontends/web/src/i18n/config.js
- frontends/web/src/i18n/i18n.js
- frontends/web/src/i18n/utils.test.ts
- frontends/web/src/i18n/utils.ts
- frontends/web/src/routes/buy/exchange.tsx
To improve our UX, it would be nice to have a pre-selected value for the region selector in the exchange / buy page.
This value is taken from user's config, which gets set the first time a user selects a region. If it's not available yet, the value (region) is taken from `native-locale` API.
If `native-locale` api doesn't provide a proper value, e.g `es-es419`, then there will be no pre-selected / default value for the selector.
[Preview] 
https://user-images.githubusercontent.com/28676406/214209426-ff63800a-2414-40f8-918c-a0e11037f1c7.mp4
explanation: The first time loading the exchange page, the region selected was France due to user's native locale as there's no saved region yet in the config. Then the user picks a region (Finland), and it gets saved in the config. `Finland` is then …
> frontend: pre-select region from user's native locale and config

- backend/backend.go
Same as btc/ltc/tltc, one dev node is sufficient for testing. This will reduce maintanence and load on the backend.
Regtest can be used to test failover behavior etc. when two servers are needed for testing.
> backend: remove one default btc testnet dev server

- frontends/web/src/components/appdownloadlink/appdownloadlink.tsx
- frontends/web/src/components/appupgraderequired.tsx
- frontends/web/src/components/update/update.tsx
- frontends/web/src/routes/settings/settings.tsx
- frontends/web/src/utils/url_constants.ts
To improve our UX, it would be better to have a "language-aware" download link. E.g German language app will use the german download page.
In the case where localised download page isn't available, will be fallbacking to the "international" / "default" downlaod page.
> frontend: created language-aware download link component 

- backend/aopp.go
- backend/exchanges/exchanges.go
- backend/exchanges/pocket.go
- backend/handlers/handlers.go
- frontends/web/package-lock.json
- frontends/web/package.json
- frontends/web/src/api/exchanges.ts
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/buy/pocket.tsx
A safe buy workflow requires a verification of the address that has been shared with the exchange. In this case pocket widget sends an email containing the address that has been shared by the user and requires a verification via `postMessage`. The address is displayed on the bb02 and should be ideally verified by the user opening the email con a second device (e.g. the phone) for better security.
> frontend/pocket: add address verification

- frontends/web/src/components/confirm/Confirm.tsx
- frontends/web/src/components/dialog/dialog-legacy.module.css
- frontends/web/src/components/dialog/dialog-legacy.tsx
- frontends/web/src/components/wait-dialog/wait-dialog.tsx
- frontends/web/src/routes/account/send/send.tsx
- frontends/web/src/routes/device/bitbox01/check.jsx
- frontends/web/src/routes/device/bitbox01/components/upgradefirmware.jsx
- frontends/web/src/routes/device/bitbox01/create.jsx
- frontends/web/src/routes/device/bitbox01/restore.tsx
- frontends/web/src/routes/device/bitbox01/settings/components/changepin.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/device-lock.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/hiddenwallet.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/mobile-pairing.tsx
- frontends/web/src/routes/device/bitbox01/settings/components/randomnumber.jsx
- frontends/web/src/routes/device/bitbox01/settings/components/reset.jsx
During the development of the new Dialog (improving dialog for mobile), we introduced a regression that affected several places such as the:
1. Factory reset device
2. send-QR
This PR fixes it.
We also will use the old dialog for all of the bb01 components and the Confirm component (which uses dialog internally).
This PR also fixes some other random bugs that are not exactly in the Dialog component but still related to it, such as:
1. WaitDialog style on mobile
2. Closing send-QR with ESC only toggles the dialog, not actually closing it.
[Preview] Factory Reset Device:
https://user-images.githubusercontent.com/28676406/215662356-0cf40823-430f-4994-9c08-a107622619a1.mov
(the WaitDialog isn't immediately closing anymore).
> frontend: fix regression on Dialog and created dialog-legacy

- frontends/web/src/i18n/utils.test.ts
- frontends/web/src/routes/buy/exchange.tsx
We have preivously used native-locale but we didn't take into account that native-locale may sometimes return nothing (empty).
Another PR then was created to fix this, using `i18n.language` - which is not exactly correct.
Thus, in this PR we used native-locale back. But, we are now handling empty native-locale gracefully so it won't crash the page whenever native-locale returns empty/nothing.
> frontend: use native-locale to pre-select region dropdown in exchange page.

- frontends/web/src/routes/device/bitbox02/settings.tsx
- frontends/web/src/routes/settings/settings.tsx
Added missing skeleton components so that the layout does not shift while the view is loading.
> frontend: reduce layout shift on settings and device settings

- backend/devices/bitbox02/handlers/handlers.go
The endpoint was returning an `error` instead of a struct with `success: false`.
> backend/bb02-handlers: fix `postBackupRestore` error handling

- frontends/web/src/routes/buy/exchange.module.css
- frontends/web/src/routes/buy/exchange.tsx
- frontends/web/src/routes/buy/moonpay.tsx
- frontends/web/src/routes/buy/pocket.tsx
1. Added min-height for radio buttons container in the
exchange page to prevent the layout shifting/jumping around
2. Set `guideExists` to be `false` for `<Spinner/>` to fix
"double guide" issue.
> frontend: fixed minor css issues in the exchange page(s).

- frontends/web/package-lock.json
- frontends/web/package.json
- frontends/web/src/locales/en/app.json
- frontends/web/src/routes/buy/pocket.tsx
This pushes the version of `request-address` js library to 0.0.6 and adds the handling of `RequestExtendedPublicKeyV0Message` requests, that allows sharing the account xpub with the Pocket widget.
NOTE: in order to test this PR, please force the staging environment for Pocket:
```
apiURL = pocketMainTestURL + "/" + locale + "/" + pocketWidgetTest
```
in https://github.com/Beerosagos/bitbox-wallet-app/blob/xpub-sharing/backend/exchanges/pocket.go#L73
I opened a separate PR to avoid needing this workaround in the future, see https://github.com/digitalbitbox/bitbox-wallet-app/pull/1946
> frontend/pocket: add xpub sharing logic

- frontends/web/src/components/banner/banner.tsx
As it has been 3 years since BitBox01 EOL and 3rd party services such as MEW silently dropped support, the banner in the BitBoxApp should be displayed in a more eye catchy warning style to encourage users moving their funds.
> frontend: change bb01 banner style to warning

- Makefile
- backend/arguments/arguments.go
- backend/backend.go
- backend/exchanges/pocket.go
- backend/handlers/handlers.go
- frontends/web/src/api/exchanges.ts
- frontends/web/src/routes/buy/pocket.tsx
This updates`PocketUrl`to return the address of the Pocket widget from staging or production environment depending on the `devservers` flag, instead of the net used, which was the previous approach.
It also adds a `servewallet-mainnet-prodservers` target in the Makefile, which runs the server on mainnet and with devservers flag disabled.
The reason for this PR is that address signing is currently disabled for the btc testnet at a firmware level, which forces using the mainnet when working on Pocket integration. This update allows choosing which Pocket environment should be used with a proper flag.
> backend/pocket: refactor `PocketUrl` to use devservers argument

- backend/accounts_test.go
- backend/arguments/arguments.go
- backend/bridgecommon/bridgecommon.go
- backend/handlers/handlers_test.go
- cmd/servewallet/main.go
`devmode` argument was not actively used in any part of the code. This removes that.
> backend/arguments: remove `devmode` argument
